ComputationalRadiationPhysics/picongpu

CHANGELOG.md, README.md, REFERENCE.md, src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/initialization/InitialiserController.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp
This releases fixes a potential deadlock encountered during checkpoints and initialization. Furthermore, we forgot to highlight that the 0.2.0 release also included a QED synchrotron emission scheme (based on the review in [A. Gonoskov et al., PRE 92, 2015](http://dx.doi.org/10.1103/PhysRevE.92.023305)).
Thank you to @psychocoderHPC  for spotting & fixing and @Heikman for the QED synchrotron photon emission implementation!
=> Release 0.2.1: QED synchrotron photon & fix potential deadlock in checkpoints

src/libPMacc/include/math/MapTuple.hpp
- refactor without any `BOOST_PP` usage
- remove constructor
- remove function `make_MapTuple()`
The constructor and `make_MapTuple` is never used and therefore the functionality is removed.
To create a constructor for MapTuple we need C++11 and need to rewrite `InheritLineary` to forward the constructor elements.
together with #1646 the issue #732 is solved.
=> `MapTuple`: fix broken compile with icc

src/picongpu/include/plugins/radiation/utilities.hpp
This is an alternative to #1644. Instead of template meta programming C++11 `constexpr` is used.
=> Add pow compile time using c++11

src/picongpu/submit/hypnos-hzdr/k80_profileRestart.tpl
This pull request adds a `*.tpl` file for `hypnos-hzdr` that requires in the `*.cfg` file the variable `TBG_restartPeriod` defining the periodicity of the checkpointing. The job will run till the first checkpoint, write the checkpoint, resubmit a followup job and finish. This happens till the final time step (defined via `-s` to allow compatibility with existing `*.cfg` files) is reached. 
This allows shorter walltimes while avoiding dependency lists on PBS.
=> add a tpl file for k80 hypnos that automatically restarts

test/hasCudaGlobalKeyword
The script search if the `__global__` keyword is used within one file in a folder.
Native CUDA kernel break the compatibility with [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka). Therefore @ax3l suggest to add a travis test with this little script to avoid the usage of `__global__` within PMacc and PIConGPU. 
usage:
```Bash
test/hasCudaGlobalKeyword src/libPMacc
test/hasCudaGlobalKeyword src/picongpu
test/hasCudaGlobalKeyword examples
```
=> checker script for `__global__` keyword

src/libPMacc/include/traits/GetNComponents.hpp
- improve error message for `GetNComponents` if not specialized for a given type
If the trait is not defined for a type the compiler fire a error message `incomplete type is not allow`. There is no information what does this mean. With this pull request the developer get useful information why the code is not compiling.
=> improve error message

buildsystem/CompileSuite/autoTests/config.sh, buildsystem/CompileSuite/autoTests/get_work.sh
Adding new dot files in the root of the repo, such as `.travis.yml` did not get cleaned up properly between tests. Following `git clone` commands in that tmp dir failed.
=> CompileSuite: Clean Up Dot Files

examples/SingleParticleCurrent/include/CheckCurrent.hpp, src/libPMacc/include/particles/ParticlesBase.kernel, src/picongpu/include/fields/MaxwellSolver/Lehe/LeheSolver.def, src/picongpu/include/particles/ionization/byField/Keldysh/Keldysh.def, src/picongpu/include/plugins/IsaacPlugin.hpp, thirdParty/cuda_memtest/.travis.yml, thirdParty/cuda_memtest/cuda_memtest.h, thirdParty/cuda_memtest/misc.cpp, thirdParty/cuda_memtest/ocl_memtest.cpp, thirdParty/cuda_memtest/tests.cu
We should not enforce UTF-8 locales on user systems.
CUDA memtest updated as in #1159, also contains an other minor fix from upstream: https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/7
For comparison, travis does not even handle UTF-8 grep-ing gracefully:
https://travis-ci.org/ComputationalRadiationPhysics/picongpu/builds/182302127#L209
=> Source Files: Remove non-ASCII Chars

buildsystem/CompileSuite/autoTests/new_commits.sh
Documents the updates in the compile suite using a GCC 4.9.4 [compile chain](https://github.com/ComputationalRadiationPhysics/compileNode/commit/f196064a911a01ae677930372c582182ce6125bd).
Also adds ISAAC compile-testing to it.
=> Compile Suite: GCC 4.9.4 Chain

.travis.yml, README.md, test/hasCudaGlobalKeyword, test/hasEOLwhiteSpace, test/hasNonASCII
We add travis to do tests on source files which are light-weight. This currently only includes #1672 but could also look for things like "careful, found a new external include", "found a new usage of a boost library", etc.
Let the scripts come!
- no `__global__` keyword
- no EOL white spaces
- non non-ASCII chars in source and script files
=> Travis: Simple Style Checks

src/libPMacc/include/communication/CommunicatorMPI.hpp, src/libPMacc/include/mappings/simulation/GridController.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Allows running a simulation with `-m`, writing a checkpoint and restarting that checkpoint *without* `-m`.
This does not break restarts that keep the moving window "-m" on.
Warning: *enabling* the moving window from a checkpoint that had no moving window does still not work nor from a sim was "paused" with that method will not work. This would require remembering "how many iterations did someone stop the moving window".
First build for @Heikman during his Master's thesis and requested again by [Bifeng](https://cg.hzdr.de/Lists/picongpu-users/Message/151.html) on the user mailing list. The patch was so small and quick that I forgot to write a PR for it.
=> Restart: Allow Disable of Moving Window

src/picongpu/include/plugins/radiation/vector.hpp
This pull request fixes a compile time bug in the radiation plugin's vector class that prevented using the `[ ]` operator on constant vectors.
This solves issue #1683
=> fix vector.operator[] const access in radiation plugin

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/radFormFactor.hpp, src/picongpu/include/simulation_defines/param/radiationConfig.param
This pull request extends the currently existing CIC particle shape (for radiation) for the TSC and PCS shape. 
**Requires:**
=> add TSC and PCS rad form factor shapes

src/libPMacc/include/Environment.hpp
device number outside valid range can be selected
The bug can be triggered if `CUDA_VISIBLE_DEVICES` is set to the number of GPUs in the node or if more MPI ranks as gpus per node are started.
The result is a run time crash. This bug is **not** critical and need no back port.
=> Device Selection: Guard Valid Range

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/SingleParticleCurrent/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleRadiationWithLaser/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleTest/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/libPMacc/include/eventSystem/events/kernelEvents.hpp, src/libPMacc/include/identifier/alias.hpp, src/libPMacc/include/identifier/identifier.hpp, src/libPMacc/include/lambda/Expression.hpp, src/libPMacc/include/lambda/make_Functor.hpp, src/libPMacc/include/math/ConstVector.hpp, src/libPMacc/test/memory/memoryUT.cu, src/picongpu/include/fields/FieldE.kernel, src/picongpu/include/fields/FieldManipulator.kernel, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/plugins/IsaacPlugin.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/visualization.param, src/picongpu/include/simulation_defines/unitless/visualization.unitless
Close #1687: Updated with sed script (see separate PR) and comitted via generic "tools" user.
~~Looks a bit odd for `pragma omp ...` and `pragma unroll ...` instructions. Not sure if we really want that for `#pragma`, too because in such a case it is not a `pre-compiler` instruction but a *non-standard, extended type description* (attributes, no-inline, etc.) or *non-standard, compiler-specific compile-time hint*.~~ script and style rule updated
=> Close #1687 Fix Pre-Compiler Spaces

.travis.yml, test/hasSpaceBeforePrecompiler
Tests and removes spaces before using pre-compiler commands. Was used to fix #1693.
~~Needs decision on `#pragma` lines https://github.com/ComputationalRadiationPhysics/contributing/issues/16 before merging.~~ ok
=> Test: Check & Remove Pre-Compiler Spaces

src/picongpu/submit/taurus-tud/picongpu.profile.example
This fixes #1704 by updating the Taurus (TUD) profile.
This addresses two issues:
- HDF5 1.8.15 (without patch-level) did undefine `__attribute__`
in C++ codes including it which breakes CUDA `__device__`, `__host__`
and similar annotations generally
- Boost 1.58.0 with GCC 5.1 and CUDA 7.5 was broken in `odeint`
Thanks to @psychocoderHPC for crawling through CUDA macros :)
@PrometheusPi tested at RT on taurus via KHI, even with HDF5 output.
=> Taurus (TUD): Update Profile to CUDA 8.0

src/libPMacc/include/compileTime/conversion/MakeSeq.hpp
- add a short hand definition for `typename MakeSeq<>::type`
- `MakeSeq`: allow a unspecified number of template arguments
This implementation follows the [contributing rule](https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md#20-short-access-to-member-typevalue-in-c11) for short access definitions.
=> define `MakeSeq_t`

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
This removes the complicated interface to define a species away from the PIConGPU user. Objects like `ParticleDesction` and `SuperCellSize` are hard to handle for the user.
- refactor `Particle<>` interface
- remove `SuperCellSize` and `ParticleDesciption<>` from PIConGPU user interface
- remove unused includes
=> simplify species definition

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/fileOutput.param, src/picongpu/include/simulation_defines/param/isaac.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/unitless/checkpoints.unitless
Use a more natural `using Sequence = MakeSeq_t< 1, 2, 3 >;` syntax for user input of type lists via `MakeSeq_t` and C++11 `using`.
Avoids boiler plate code without `=` and additional `::type` access:
`typedef Seq< 1, 2, 3 >::type List;`
Cleaned up syntax of `speciesDefinition` on the way.
=> Param: Type List Syntax

src/picongpu/include/plugins/adios/WriteMeta.hpp, src/picongpu/include/plugins/hdf5/WriteMeta.hpp
Close #1717 
This bug effects only simulations where no species is added to `VectorAllSpecies` in `speciesDefinitions.param`.
- write `openPMD` attributes `particleBoundary, particleBoundaryParameters`
only if PIConGPU defines at least one species
- HDF5:
- add namespace `writeMeta`
- add `writeMeta::OfAllSpecies<>`
- ADIOS:
- add namespace `writeMeta`
- add `writeMeta::OfAllSpecies<>`
**The last release 0.2.1 is affected. It is possible to workaround this bug in the old release:**
- add one species to `VectorAllSpecies` in `speciesDefinitions.param`
- remove all initialize functors from `InitPipeline` in `speciesInitialization.param`
=> fix: write openMPD meta data without species

src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.hpp, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.kernel
The interface change is transparent for the PIConGPU user.
- add curl instance to kernel parameter
- add `T_` to template names
- remove template keyword  `class` with `typename`
This change allow  to move constant curl calculations like `sin()` in the Lehe solver to the host side.
=> Maxwell solver, use curl instance

src/libPMacc/include/algorithms/ForEach.hpp
This change is backwards compatible (no interface change)
- use variadic templates to remove boost preprocessor
- reformat with new coding style
- cleanup includes
The documentation of the class `ForEach` is not touched.
=> ForEach: remove boost preprocessor

src/picongpu/include/fields/laserProfiles/laserWavepacket.hpp
This fixes issue #1720.
Since [December 2015](https://github.com/ComputationalRadiationPhysics/picongpu/commit/0acbd9050fdb4af40aa14434d3cdc11e8a862222) we fixed the implementation of the  transversely asymmetric envelope of the `laserWavepacket`. Due to this change a minus disappeared, which causes different (see issue) numerical artifacts.
=> add missing minus sign wavepacket laser transversal

src/picongpu/include/fields/MaxwellSolver/Lehe/LeheCurl.hpp
- move sinus calculation to host side
- use 64bit instead of `float_X` to calculate sinus 
- add `constexpr` to constant calculations
Dependencies:
--------------------
=> Lehe solver: optimize performance

doc/TBG_macros.cfg, examples/Empty/submit/1gpu.cfg
Fixes a small typo in `TBG_macros` and a spelling inconsistency, adds a bit further description on cells per GPU and supercells and adds a 1 GPU `.cfg` file to `Empty` so people cloning from that have an example to adjust instead of writing from scratch.
=> Documentation: Empty Example & TBG_macros.cfg

src/libPMacc/include/memory/Array.hpp
add C++11 STL like static array `Array<>`
Currently it is not possible to use `std::array<>` on the device side. We need the functionality for the up coming shared memory changes.
=> add `Array<>` with static size

src/libPMacc/include/memory/shared/Allocate.hpp
The user can allocate static sized shared memory without using the cuda prefix `__shared__`.
- add namespace `PMacc::memory::shared`
- add class `Allocate<>`
- add helper functions `allocate()`
- add macro to allocate shared memroy `PMACC_SMEM()`
This pull request allow an easier switch to `cupla` and minimize the up coming changes.
=> add shared memory allocator

src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/operations/CountParticles.hpp, src/libPMacc/include/particles/operations/splitIntoListOfFrames.kernel, src/picongpu/include/fields/FieldManipulator.kernel, src/picongpu/include/fields/FieldTmp.kernel, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/particles/access/Cell2Particle.tpp, src/picongpu/include/particles/creation/creation.kernel, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/plugins/IntensityPlugin.hpp, src/picongpu/include/plugins/PositionsParticles.hpp, src/picongpu/include/plugins/SumCurrents.hpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/plugins/makroParticleCounter/PerSuperCell.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.kernel, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel
- use PMacc macro `PMACC_SMEM` instead of CUDA native keyword `__shared__`
- remove usage of `GetEmptyDefaultConstructibleType<>` to workaround nvcc warnings
Commits from ~~#1726~~ and ~~#1725~~ are included in this pull request and would be deleted after the rebase.
The trait "GetEmptyDefaultConstructibleType<>" was introduced with #1045 to suppress nvcc warning if   a class with a non empty constructor is stored in shared memory. This is not longer the case if ~~#1726~~ is used to create variables in the shared memory. I removed the use of the trait because I need to touch all lines with the usage to use the new `PMACC_SMEM()` macro.
I will remove the trait `GetEmptyDefaultConstructibleType<>` in an separate pull request.
Not changed
-----------------
- The keyword `__shared__` in …
=> Topic use remove shared keyword

.travis.yml, test/correctBranchPR
Check that pull requests from forks are not accidentially opened to `master` (our default branch).
`master` is only updated with new stable releases. PRs to it will always be done by a maintainer that either merges `dev` from the mainline repo itself or a `release-...` branch, also from mainline.
If you want to see the help that is posted to the user that opened a PR falsely to `master`, check out https://travis-ci.org/ComputationalRadiationPhysics/picongpu/builds/188309672 that was triggered by #1730 . As always, we provide a one-click (or copy&paste) solution to fix the test, so developers can easily fix their problem and do not get annoyed.
```
Pull request opened to wrong branch!
New features need to go to our 'dev' branch but your
pull-request from 'ax3l/picongpu' was sent to …
```
=> Travis: Check PR Destination

examples/Bunch/include/simulation_defines/param/memory.param, examples/KelvinHelmholtz/include/simulation_defines/param/memory.param, examples/LaserWakefield/include/simulation_defines/param/memory.param, examples/ThermalTest/include/simulation_defines/param/memory.param, examples/WeibelTransverse/include/simulation_defines/param/memory.param, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/gasProfiles/FromHDF5Impl.hpp, src/picongpu/include/plugins/ChargeConservation.tpp, src/picongpu/include/plugins/IsaacPlugin.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/WriteFields.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/param/memory.param, src/picongpu/include/simulation_types.hpp
Allows to use multiple `GridBuffers` ("slots") in `FieldTmp` for all operations done with it so far.
Required for, e.g., T_e and n_e in Thomas-Fermi Ionization.
Current control: the number of scalar temporary fields can be set in `memory.param` via:
```C++
/** number of scalar fields that are reserved as temporary fields */
constexpr uint32_t fieldTmpNumSlots = 1;
```
~~Still throws dozens of `__host__ __device__` warnings but might compile already.~~
Thanks to @psychocoderHPC for pair programming support.
```C++
/* I want to access FieldTmp! */
DataConnector &dc = Environment<>::get().DataConnector();
/* And while we are defining this code, just saying: I will use two (2) slots of it,
*   <<So, do you copy?! - ... Brzzzz >> */
PMACC_CASSERT_MSG( …
```
=> FieldTmp: Multiple Slots

src/picongpu/include/fields/background/templates/TWTS/BField.tpp
- call function `math::tan()` instead of `tan()`
=> add missing `math::` namespace to `tan()`

src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/allocator/DeviceMemAllocator.tpp, src/libPMacc/include/cuSTL/container/allocator/HostMemAllocator.tpp
- add `HDINLINE` to method implementations
This changes are needed to support `clang++` as device compiler, see #1731
=> add missing `HDINLINE` prefix

src/libPMacc/include/nvidia/warp.hpp
assembler ptx command: add `%%` to use the laneid register
This changes is needed to compile with `clang++`, `nvcc` is relaxed and accept the special register also with one `%`.
Helpful [link](http://stackoverflow.com/a/40205665) with the explanation why we need to use `%%`
**There is no need to back port this change, because the current release only supports nvcc.**
=> fix missing '%%' to use ptx special register

src/libPMacc/include/cuSTL/algorithm/cudaBlock/Foreach.hpp, src/libPMacc/include/particles/IdProvider.hpp, src/libPMacc/include/random/RNGProvider.tpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.kernel
- add missing typename
- use static method to get runtime type from compile time vector
This is needed to support device side compile with `clang++`, see #1731
=> add missing typename's

src/libPMacc/include/cuSTL/algorithm/kernel/ForeachBlock.hpp, src/libPMacc/include/cuSTL/algorithm/kernel/detail/ForeachKernel.hpp
add excplicit cast to support clang structs for `threadIdx` and `blockIdx`
This is needed to support the `clang++` device compiler, see #1731 
Clang has it's own type for `threadIdx`,`blockIdx`,... to be compatible with our specializations for `dim3` we need to cast the magic CUDA variable explicit to `dim3`
=> explicit cast `blockIdx` and `threadIdx` to `dim3`

src/picongpu/include/algorithms/KinEnergy.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.hpp, src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/EnergyParticles.hpp
Computes the kinetic energy from momentum and mass. If the mass is zero, `E = cp` is used. Otherwise it is distinguished between non-relativistic momenta and the general relativistic case.
Tested with a small test script.
=> Add kinetic energy algorithm

src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/PngPlugin.hpp, src/picongpu/include/plugins/output/images/PngCreator.hpp, src/picongpu/include/plugins/output/images/PngCreator.tpp
If `pngwriter` is not available at compile time, the plugin `PngPlugin` register a help with information why the plugin can't use at runtime.
- PngCreator: add "tpp` file for `operator()`
- PngPlugin: add help message if `pngwriter` is not avail
This is the first plugin which full fill #1700
```bash
./picongpu --help
PositionsParticles: write position of one particle of a species to std::cout:
--i_position.period arg               enable analyser [for each n-th step]
PngPlugin: create pngs of a species and fields:
--i_png                               plugin disabled [compiled without 
dependency pngwriter]
PositionsParticles: write position of one particle of a species to std::cout:
--e_position.period arg               enable analyser [for each n-th step]
PngPlugin: create pngs of a …
```
=> PngPlugin: help message if dependency is not compiled

src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param
Fix energy density calculation. Prior to this the weighting factor was wrongly included in the energy density expression resulting in a quadratic dependency.
**Work-Around:** Use `CreateEnergyOperation` instead and divide by cell volume.
=> Fix energy density

src/picongpu/include/particles/startPosition/OnePositionImpl.def, src/picongpu/include/particles/startPosition/OnePositionImpl.hpp, src/picongpu/include/particles/startPosition/functors.hpp, src/picongpu/include/simulation_defines/param/particleConfig.param
Add a new starting position called `OnePosition` which is exactly one fixed position within a cell for all particles that will be initialized there.
Useful for particle pusher tests with single or few particles.
(Used and tested in #1716)
=> Particle StartPosition: OnePosition

src/libPMacc/include/mappings/simulation/Filesystem.hpp, src/picongpu/include/plugins/adios/WriteMeta.hpp, src/picongpu/include/plugins/hdf5/WriteMeta.hpp
The `iterationFormat` in `openPMD`'s base attributes in `/` should only contain the *basename*, not the path to the file in "fileBased" `iterationEncoding`.
This is not a minor bug since most post-processing tools I am aware of are currently not reading that attribute, but they might. Nevertheless, it violates the standard (I did not check it carefully when moving `.h5` and `.bp` files to their own dir in `simOutput`).
=> openPMD: iterationFormat only Basename

examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/picongpu/include/particles/manipulators/RatioWeightingImpl.def, src/picongpu/include/particles/manipulators/RatioWeightingImpl.hpp, src/picongpu/include/particles/traits/GetDensityRatio.hpp
This pull request fixes compile errors when using `RatioWeightingImpl` during species initialization as manipulator. 
Thanks @n01r for finding this bug and helping to fix it. 
This closes #1758 and also (the wrongly defined) #1757. 
***
@ax3l's notes:
- only the first two commits are relevant for a backport
=> Fix RatioWeighting (DensityWeighting) manipulator

examples/ThermalTest/include/simulation_defines/param/speciesInitialization.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/picongpu/include/particles/manipulators/DensityWeighting.def, src/picongpu/include/particles/manipulators/DensityWeighting.hpp, src/picongpu/include/particles/manipulators/ProtonTimesWeighting.def, src/picongpu/include/particles/manipulators/ProtonTimesWeighting.hpp, src/picongpu/include/particles/manipulators/manipulators.def, src/picongpu/include/particles/manipulators/manipulators.hpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
`RatioWeightingImpl` & `ProtonTimesWeightingImpl` are without parameters, so we need no `Impl` interface which clutters the user interface. (Reminder: Manipulators with parameters are first configured in `particleConfig.param` via their `Impl` interface and then used in `speciesInitialization.param`).
`RatioWeighting` is renamed to `DensityWeighting` since it changes the weighting depending on the `denistyRatio` of both species.
Use `ProtonTimesWeighting` to derive electrons from ions (protons) in `ThermalTest` so that manipulator is covered by the compile suite and users have an example for it.
Add the (constant) flags for `densityRatio` and `atomicNumbers` to the standard `speciesDefinition.param` so users know how to add them.
Adds no additional cost since those are constant per …
=> ManipulateDeriveSpecies: Refactor Functors & Tests

examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/simulation_defines/param/laserConfig.param
Hello y'all,
This pull request implements basic support of rotationally symmetric Gauss-Laguerre laser modes within the standard Gauss laser.
Literature on this can be found at numerous places, but you can start here:
[F. Pampaloni et al. (2004), Gaussian, Hermite-Gaussian, and Laguerre-Gaussian beams: A primer](https://arxiv.org/pdf/physics/0410021)
[Wikipedia on Gaussian laser beams](https://en.wikipedia.org/wiki/Gaussian_beam)
Although this implementation has passed basic testing, it is still work in progress. Especially, the implementation of evaluating Laguerre-Polynomials is very simple, but apparently good enough in performance for this purpose. Nevertheless a better library implementation for GPUs would be welcome. So far, I did not stumble across anything related to CUDA. On the …
=> Add transverse Laguerre-modes to standard Gauss laser.

src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/bremsstrahlung/Bremsstrahlung.hpp, src/picongpu/include/particles/bremsstrahlung/Bremsstrahlung.tpp, src/picongpu/include/particles/bremsstrahlung/PhotonEmissionAngle.hpp, src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.hpp, src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.tpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/_defaultUnitless.loader, src/picongpu/include/simulation_defines/param/bremsstrahlung.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/bremsstrahlung.unitless
Implementation of the Bremsstrahlung effect.
Here the screened Bethe-Heitler cross section is used. See e.g.:
> Salvat, F., et al. "Monte Carlo simulation of bremsstrahlung emission by electrons."
>    Radiation Physics and Chemistry 75.10 (2006): 1201-1219.
The numerics separates the energy spectrum into two parts. In the low-energy part
photon emission is neglected and a drag force is applied to the electrons. In the high-energy part
photons are created in addition to the drag force.
Electron deflection is treated as screened Rutherford scattering, see e.g. Jackson, chap. 13.5
The photon emission angle is taken from the Lorentz-boosted dipole radiation formula,
see e.g. Jackson, chap. 15.2
**Tests**
Energy loss without photons. 100MeV electrons should loose 10% of their energy during …
=> Add Bremsstrahlung

src/libPMacc/include/memory/shared/Allocate.hpp
fix #1766 I did not investigate the effect of this bug on other kernels than radiation.
- add type alignment to shared memory allocator
Tests:
This bug was introduced with #1726. The new method to create shard memory in #1726 removed the alignment information from the shared memory, this could result in unaligned memory access errors.
=> fix shared memory alignment

src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless
Adds a particle attribute which holds the offset from one particle to the next
in the same cell in units of frame position. This is a meta attribute used for
future particle-particle methods like collision.
=> Add particle attribute `inCellOffset`

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param
Makes the `inCellOffset` a default particle attribute.
=> Add inCellOffset to list of default attributes

.travis.yml, test/correctBranchPR
Follow-up to #1732 addressing a potential GitHub API rate limiting issue.
Thanks to @BanzaiMan, Travis CI now has a `$TRAVIS_PULL_REQUEST_SLUG` defined which we can use instead of querying the GitHub API.
=> Use Travis TRAVIS_PULL_REQUEST_SLUG

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, src/libPMacc/include/particles/Identifier.hpp, src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/libPMacc/include/particles/memory/dataTypes/SuperCell.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param
- move `inCellOffset` from `speciesAttributes.param` to `Identifier.hpp`
in PMacc
- replace 0xffffffff by `INV_IDX` from `frame_types.hpp`
- add `inCellOffset` to list of PMacc default particle attributes
- add documentation to `SuperCell.hpp`
=> Move attribute `inCellOffset` to PMacc 

src/libPMacc/include/particles/particleFilter/PositionFilter.hpp, src/libPMacc/include/particles/particleFilter/system/DefaultFilter.hpp, src/libPMacc/include/particles/particleFilter/system/TrueFilter.hpp
Removes the (virtual) default destructor in the fiter classes since they cause a nvlink warning during separable compilation:
```
nvlink warning : Function 'PMacc::TrueFilter::~TrueFilter()' has address taken but no possible call to it
nvlink warning : Function 'PMacc::privatePositionFilter::PositionFilter<3u, PMacc::TrueFilter>::~PositionFilter()' has address taken but no possible call to it
nvlink warning : Function 'PMacc::PositionFilter3D<PMacc::TrueFilter>::~PositionFilter3D()' has address taken but no possible call to it
nvlink warning : Function 'PMacc::PositionFilter3D<PMacc::TrueFilter>::~PositionFilter3D()' has address taken but no possible call to it
nvlink warning : Function 'PMacc::DefaultFilter<PMacc::PositionFilter3D<PMacc::TrueFilter> >::~DefaultFilter()' has address taken …
```
=> PositionFilter: Remove (virtual) Destructor

src/tools/bin/tbg
This PR fixes the check for end lines allowing windows new lines (Issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/1775)
Furthermore as tbg does only support unix new lines, the config files are check for this trait.
=> Fix #1775 tbg config newline check

src/picongpu/include/mallocMCconfig.hpp, src/picongpu/main.cu
Move the mallocMC settings to a clean, common header that can be used on top of `.cu` files.
=> mallocMC: Organize Setting

src/picongpu/include/simulationControl/MovingWindow.hpp
This pull request is based on #1780 and fixes the moving window for the edge case `slide_point = 0.0`. This makes it possible to activate the moving window directly at simulation initialization.
Happy merging :grinning:
=> Bugfix in MovingWindow.hpp, slide_point now can be set to zero.

src/picongpu/CMakeLists.txt, src/picongpu/include/ArgsParser.cpp, src/picongpu/include/plugins/common/particlePatches.cpp, src/picongpu/include/plugins/common/stringHelpers.cpp, src/picongpu/include/plugins/hdf5/openPMD/patchReader.cpp
- not the cleanest way to keep them in `include/` too, but better then accumulating all in the root path
- CMakeLists: Compile host code separately without nvcc "code splitting" and link it statically
=> Source Files: Move to Headers

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MacroCounter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MacroCounter.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param
Add a macro particle counter to the `FieldTmp` per cell particle to grid operations. Assumes all (macro) particles are point like in space and can be used to validate particle memory structures.
Removes Counter as a default used FieldTmp output since it is actually a debug quantity and wastes spaces.
=> fileOutput: MacroParticleCounter

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param
Removes a rendundant comma that was left over from a temporary change in the parameter file.
=> Fix: Remove rendundant comma in speciesDefinition.param

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/simulation_defines/param/fileOutput.param
Adds doxygen strings to the classes that users need to define `FieldTmp` operations in `fileOutput.param` or algorithms such as Thomas Fermi. This can help to understand how to use those and can be more detailed then the small examples we give in `fileOutput.param`.
=> FieldTmp Operations: Doxygen Strings

src/libPMacc/include/particles/ParticlesBase.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp
This change is transparent for the PIConGPU user.
PMacc user needs to remove the `ParticleBuffer` allocation inside its own particle class.
- `ParticlesBase`:
- allocate member `ParticleBuffer` inside the constructor
- destructor: delete all member
- `Particles`
- remove the allocation of member from the parent class
- remove destructor (now empty)
- remove unused member `m_gridLayout`
=> `ParticlesBase` allocate member memory

src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp
- remove `GridLayout<>` from the constructor interface
- ParticlesFunctors: remove `GridLayout` from constructor call
=> refactor `Particle` constructor interface 

examples/Bunch/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
Fix #1207 and allow to skip the current solver in `speciesDefinition.param` so neutral particles do not run this algorithm.
=> Fix #1207 Species can omit a Current Solver

src/libPMacc/include/memory/shared/Allocate.hpp
fix alignment definition of shared memory
This bug was introduced with #1767.
You can find more information about this issue in our similar [alpaka shared memory fix](https://github.com/ComputationalRadiationPhysics/alpaka/pull/318).
=> fix clang compile

examples/Bunch/include/simulation_defines/param/gridConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param, examples/LaserWakefield/include/simulation_defines/param/gridConfig.param, examples/SingleParticleTest/include/simulation_defines/param/gridConfig.param, examples/ThermalTest/include/simulation_defines/param/gridConfig.param, examples/WeibelTransverse/include/simulation_defines/param/gridConfig.param, src/picongpu/include/simulation_defines/param/gridConfig.param
This change allow to use the values of the array's inside static asserts.
define ABSORBER_CELLS and ABSORBER_STRENGTH as `constexpr`
=> use constexpr for arrays in  `gridConfig.param`

src/libPMacc/include/dimensions/DataSpaceOperations.hpp
This is a left-over from my 4D experiments last week: simplify and align the used formula for ND mapping.
Makes it straight forward to extent mapping to arbitrary dimensions whenever needed.
Yes, alignments are intentional, "because it's math" :)
@BenjaminW3 might be useful for alpaka, too.
=> DataSpaceOperations: Simplify Formula

src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless
The openPMD output and general description for a particle species' `boundElectrons` per ion is ill-described, mismatching that this attribute is, similar to our constant mass and charge attributes, not weighted for a macro particle but just for an underlying real particle.
Influence: post-processing tools, e.g. openPMD-viewer, did weight the number of bound electrons "twice".
Reference: https://github.com/openPMD/openPMD-standard/blob/1.0.0/EXT_ED-PIC.md#additional-attributes-for-each-particle-record
=> boundElectrons: non-weighted attribute

src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
Speedup the Esirkepov current deposition by optimizing the number of deposition points around the particles.
- work with a virtual coordinate system (depending of the particle position)
- remove variable with fixed length loop's
- guard loop bodies with if condition
- reduce the inner deposition loop by one
- remove if condition before the operation `atomicAdd`
=> improve Esirkepov speed

src/picongpu/include/simulation_defines/param/ionizationEnergies.param, src/picongpu/include/simulation_defines/param/ionizerConfig.param
Adds NIST tables for commonly used elements in our experiments, so users can use them directly. Covers: Dopants (He, N, also Ar could be relevant), Plastics & Surface Dirt (C, O, N), and commonly used benchmark materials (Al, Cu).
=> Ionization Configs: Add He, C, O, Al, Cu

src/picongpu/include/particles/traits/GetEffectiveAtomicNumbers.hpp, src/picongpu/include/particles/traits/GetIonizationEnergies.hpp
Adds a sanity check which verifies that the given number of ionization
energies / effective atomic numbers equals the proton number.
=> Verify number of ionization energy levels == proton number

src/libPMacc/include/math/ConstVector.hpp
fix the first part of #1802 
`ConstVector` allows that the number of given arguments is lesser than the dimentsion
of the vector it self. This results in unitialized values.
solution: add static assert to avoid wrong usage
=> ConstVector: Check Arguments Init Full Length

src/libPMacc/include/debug/PMaccVerbose.hpp, src/libPMacc/include/eventSystem/events/CudaEvent.hpp, src/libPMacc/include/eventSystem/events/EventPool.hpp
Moving event creation, handling and destruction in its own state since it is quite verbose in the already noisy memory level.
=> PMacc Log: Make Events Own Level

src/picongpu/include/simulation_defines/param/radiationObserver.param
This pull request fixes a wrongly set `delta_angle_theta` and `delta_angle_phi` calculation in the default `radiationObserver.param`. To avoid a miss-configuration if the default param file is used in a setup, this should be fixed.
=> fix wrong sign of delta_angle in radiation observer direction

src/picongpu/include/particles/ionization/ionizationMethods.hpp
fix #1810
`WriteElectronIntoFrame` creates NAN's for the electron momenta if the weighting of the ion
is less than one.
If the ion weighting is greater than one the electron momentum is not exact.
=> fix possible NAN momenta in ionization

src/picongpu/include/algorithms/KinEnergy.hpp, src/picongpu/include/particles/ionization/ionizationMethods.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param
C++98 backport of fixes to 0.2.3:
- Fix energy density #1750 #1744 (partial)
- fix possible NAN momenta in ionization #1817
C++98 compile with
```
1) mpfr/3.1.2                    8) openmpi/1.8.4.kepler.cuda70
2) mpc/1.0.1                     9) pngwriter/0.5.6
3) gmp/5.1.1                    10) hdf5-parallel/1.8.14
4) gcc/4.8.2                    11) libsplash/1.4.0
5) cmake/3.3.0                  12) libmxml/2.8
6) boost/1.62.0                 13) adios/1.9.0
7) cuda/7.0
```
Please take extra care if I missed C++11 features, `0.2.X` must be C++98 compatible.
=> Backport to 0.2.3: Energy Density, Ionization NaNs

src/libPMacc/include/math/ConstVector.hpp, src/libPMacc/include/ppFunctions.hpp
`PMACC_COUNT_ARGS` casts each value to `int` this creates warnings with `-Wconversion`
- fix implicit type cast in `PMACC_COUNT_ARGS` by passing the type of the arguments to the macro
- update usage of `PMACC_COUNT_ARGS` in `PMACC_CONST_VECTOR`
=> fix float to int cast warnings

src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
Since CMake 3.7 fixes -isystem includes with CUDA, let's recommend using that cmake version by default.
[1] https://gitlab.kitware.com/cmake/cmake/issues/14201
[2] https://cmake.org/cmake/help/v3.0/command/include_directories.html
=> Hypnos: Use CMake 3.7

CHANGELOG.md, src/libPMacc/include/math/ConstVector.hpp, src/libPMacc/include/ppFunctions.hpp
C++98 backport of fixes to 0.2.3:
- ConstVector: float to int cast warnings #1819
```
1) mpfr/3.1.2                    8) openmpi/1.8.4.kepler.cuda70
2) mpc/1.0.1                     9) pngwriter/0.5.6
3) gmp/5.1.1                    10) hdf5-parallel/1.8.14
4) gcc/4.8.2                    11) libsplash/1.4.0  # outdated!
5) cmake/3.3.0                  12) libmxml/2.8
6) boost/1.62.0                 13) adios/1.9.0
7) cuda/7.0
```
Please take extra care if I missed C++11 features, `0.2.X` must be C++98 compatible.
=> Backport to 0.2.3: ConstVector Casts Warnings

src/picongpu/include/particles/ionization/ionizationMethods.hpp
Use more `const` vars in ionization methods.
=> Ionization Methods: Const-Ness

src/libPMacc/include/cuSTL/container/CartBuffer.tpp
Compiling with clang is not possible if the prefix in the implementation is not equal to the prefix of the forward signature.
This fix is needed for #1731
=> add missing HDINLINE

src/picongpu/include/particles/manipulators/FreeImpl.hpp
- allow user constructor with and without current step
- allow user `operator()` with one or two particles
The changes allow to write user manipulators with different signatures:
```C++
// unary particle manipulator
struct DoubleWeightingFunctor
{
template< typename T_Particle >
DINLINE void operator()( T_Particle& particle )
{
particle[ weighting_ ] *= float_X( 2.0 );
}
};
using DoubleWeighting = FreeImpl<DoubleWeightingFunctor>;
// binary particle operator
struct CloneWeightingFunctor
{
template<
typename T_Particle1, 
typename T_Particle2
>
DINLINE void operator()( 
T_Particle2& particle1, 
T_Particle2& particle2 
)
{
particle1[ weighting_ ] = particle2[ weighting_ ];
}
};
using CloneWeighting = FreeImpl<CloneWeightingFunctor>;
// unary particle manipulator with constructor
struct …
```
=> refactor manipulator `FreeImpl`

CHANGELOG.md, src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpiexec.tpl, src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpirun.tpl, src/picongpu/submit/bash/bash_mpiexec.tpl, src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/keeneland-gt/parallel.tpl
Fix `bash` tbg templates as described in #1831 
This is a quick & dirty version of #1833 that goes to `dev`
=> Backport 0.2.3: Bash TBG templates

src/picongpu/include/particles/ionization/None/AlgorithmNone.hpp, src/picongpu/include/particles/ionization/byField/ADK/AlgorithmADK.hpp, src/picongpu/include/particles/ionization/byField/Keldysh/AlgorithmKeldysh.hpp
Fixes doxygen warnings and forgotten params in ionization routines.
=> Doxygen: Fix Warnings Ionization

src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpiexec.tpl, src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpirun.tpl, src/picongpu/submit/bash/bash_mpiexec.tpl, src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/keeneland-gt/parallel.tpl
Fix #1831: bash templates for `tbg` use an outdated syntax.
=> Fix #1831 Bash TBG Templates

src/libPMacc/include/eventSystem/events/CudaEvent.def, src/libPMacc/include/eventSystem/events/CudaEvent.hpp
Fix a cyclic include of itself instead of correctly including its forward declaration.
=> CudaEvent: Fix Cyclic Include

doc/TBG_macros.cfg, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/ResourceLog.hpp
This PR is a split of #1403 and needs to be merged after #1456 
The resource log is a user adaptable resource information log plugin which collects resource information and writes these information to a stream.
The user can choose which resource properties to write e.g.:
`--resourceLog.properties rank position currentStep particleCount cellCount`
which format to use e.g.:
`--resourceLog.format json` other options are `jsonpp`, `xml` and `xmlpp`
which stream the information should be written e.g.:
`--resourceLog.stream file` other options are `stdout` and `stderr`
and which prefix to use for filestreams:
`--resourceLog.prefix myprefix_`
Using the options `--resourceLog.period 1 --resourceLog.stream stdout --resourceLog.properties rank position currentStep particleCount cellCount …
=> Resource log plugin

src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteMeta.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/hdf5/WriteMeta.hpp
Compile errors fixed, mainly when ADIOS is used and HDF5 is not available.
- Fix ill-places string helper includes inside HDF5 and ADIOS.
- Adds missing openPMD trait include.
Might be responsible for failing compile in #1821.
=> HDF5/ADIOS: Fix ill-places helper incl

src/tools/bin/plotRadiation
This pull request fixes the matplotlib2.x incompatibility which occurs when `plt.imshow()` is used with `plt.xscale('log')`. See the following [matplotlib issue](https://github.com/matplotlib/matplotlib/issues/7661) for details. 
Furthermore 
- the `plt.contour()` option is removed because there is no equivalent for logarithmic axis
- The final `print`is now python3 compatible
- the `file`type is replaced 
- use `plt.tight_layout()`instead of `plt.subplot_adjust()`
The following pictures are the inital radiation of an LWFA - the spectral signatures should be at multiples of `omega_0`. 
**Prior to this fix:**
`matplotlib 1.3.1`
`matplotlib 2.0.0rc1`
**With the fix of this pull request:**
`matplotlib 1.3.1`
`matplotlib 2.0.0rc1`
=> Fix plot radiation matplotlib2.x

src/picongpu/include/simulation_defines/param/radiationObserver.param
This fixes a miss-definition in the default `radiationObserver.param` discovered by @BeyondEspresso in pull request #1811 .
=> fix comments and definition of radiationObserver default setup

src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSIEffectiveZ.hpp, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSIHydrogenLike.hpp, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSIStarkShifted.hpp
Fix falsly placed `@file` doxygen comments which spammed the namespace that came after it.
=> Doxygen: File Comments in Ionization

examples/ThermalTest/include/ThermalTestSimulation.hpp, src/libPMacc/include/lambda/CT/Eval.hpp
Fix #1848: Remove the general definition of `BOOST_BIND_NO_PLACEHOLDERS` which breaks all usages below this header of `boost::placeholders` which are in the context of `boost::bind` often assumed to be present. This is especially true for some boost internals, which due to that break for us from [time](https://svn.boost.org/trac/boost/ticket/10932) to [time](https://svn.boost.org/trac/boost/ticket/12841).
=> Remove BOOST_BIND_NO_PLACEHOLDERS

src/picongpu/include/plugins/hdf5/WriteSpecies.hpp, src/picongpu/include/traits/attribute/GetCharge.hpp
The charge of all but hydrogen ion species, as seen by the PIC algorithm, was wrong after ionizing an atom/ion.
Accidentially, the charge state inside our `GetCharge` trait was calculated as
```
proton number * ( proton number - bound electrons)
```
instead of
```
proton number - bound electrons
```
in case `chargeRatio` of the species in `speciesDefinition.param` was different from `1.0` (we usually set it to the fully ionized species' charge density).
**Affected Setups**
If all of the following criteria are true for at least one of your ion species, your simulation is affected:
- your species in `speciesDefinition.param` used an `ionizer`
- your species is not hydrogen
- your species moves and/or creates currents (pusher, current solver)
- you defined `chargeRatio` for that species …
=> Ionization: Fix Charge of Ionized Ions

src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/particles/manipulators/DriftImpl.hpp, src/picongpu/include/particles/manipulators/IManipulator.hpp, src/picongpu/include/particles/manipulators/IfRelativeGlobalPositionImpl.hpp, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/SetAttributeImpl.hpp, src/picongpu/include/particles/manipulators/TemperatureImpl.hpp
The first parameter for a particle manipulator is the offset to the origin of the local domain. IN the current dev it was not defined if it is the offset of the superCell or of a cell inside of a superCell. Some manipulators need the superCell offset (in cell) some a cell offset e.g. to create a global unique id.
This fix defined the offset as offset from the superCell to the origin of the local domain.
There will be a future full refactoring of the interfaces to support alpaka, therefore please ignore the new TODO within the code.
- rename `localCellIdx` to `localSuperCellOffset`
- add interface documentation
- Particles.kernel: give superCell offset to particle manipulators
tests:
=> Particle manipulators: Fix Position Offset

src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Density.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MacroCounter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MidCurrentDensityComponent.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MomentumComponent.def, src/picongpu/include/traits/attribute/GetMass.hpp
- `derivedAttributes` remove include `pmacc_types.hpp` with `simulation_defines.hpp`
`simulation_defines.hpp` is needed for `float_X`, `float_64`, ...
- `GetMass.hpp` remove unused include
=> fix missing/wrong includes

src/picongpu/include/particles/manipulators/CopyAttribute.def, src/picongpu/include/particles/manipulators/CopyAttribute.hpp, src/picongpu/include/particles/manipulators/manipulators.def, src/picongpu/include/particles/manipulators/manipulators.hpp
The manipulator copies one attribute of a particle to another one.
example usage:
```C++
using VectorSpeciesWithMementumPrev1 = PMacc::particles::traits::FilterByIdentifier<
VectorAllSpecies,
momentumPrev1
>::type;
/* copy attribute momentum to momentumPrev1 */
ForEach<
VectorSpeciesWithMementumPrev1,
particles::Manipulate<
particles::manipulators::CopyAttribute<
momentumPrev1,
momentum
>,
bmpl::_1
>
> copyMomentumPrev1;
copyMomentumPrev1(
forward( particleStorage ),
currentStep
);
```
=> Add Manipulator `CopyAttribute`

src/picongpu/include/particles/InitFunctors.hpp, src/picongpu/include/particles/Manipulate.hpp
- copy functor `Manipulate` from `InitFunctors.hpp` to `Manipulate.hpp`
- fix include order
- use new code style
Note: `InitFunctors.hpp` includes `Manipulate.hpp`, to keep the includes in the `speciesInitialization.param` small. All in all we should move all functors in `InitFunctors.hpp` in own files and use a collective include to include all once.
=> move functor `Manipulate` to separate file

src/picongpu/include/algorithms/Gamma.def, src/picongpu/include/algorithms/Gamma.hpp
- add a function `gamma<>()` to calculate the gamma of a particle
- add a forward declaration for the class `Gamma<>`
This change is needed to add filter functors for radiation in a follow up.
=> refactor gamma calculation

.readthedocs.yml, README.md, docs/source/conf.py, docs/source/doxyindex.rst, docs/source/index.rst, docs/source/param.rst, docs/source/param/core.rst, docs/source/param/extensions.rst, docs/source/param/memory.rst, docs/source/param/misc.rst, docs/source/param/plugins.rst, readthedocs.yml, src/libPMacc/include/cuSTL/algorithm/kernel/run-time/Foreach.hpp
This fixes the build on readthedocs:
- clean Up RTD Setup
- doxygen is provided
- include for markdown
- github extensions is not available on rtd
- doxygen: skip parsing three static asserts that are fasely interpreted as declarations
- sphinx: the full doxygen index currently takes ~2GB ram to build which is above the 1 GB limit on RTD, so we skip it for now
- update badges
- finish param file structure
- after merging, the build will be triggered and you can find the first doc (stubs) under http://picongpu.readthedocs.io
=> ReadTheDocs: Fix the Build

src/picongpu/include/simulation_defines/param/componentsConfig.param, src/picongpu/include/simulation_defines/param/densityConfig.param, src/picongpu/include/simulation_defines/param/dimension.param, src/picongpu/include/simulation_defines/param/fieldSolver.param, src/picongpu/include/simulation_defines/param/gridConfig.param, src/picongpu/include/simulation_defines/param/laserConfig.param, src/picongpu/include/simulation_defines/param/particleConfig.param, src/picongpu/include/simulation_defines/param/pusherConfig.param, src/picongpu/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/param/speciesConstants.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/speciesInitialization.param
Adds file descriptions and fixed doxygen strings to all `.param` input files that define the "core" particle-in-cell algorithm in PIConGPU. Fixed and added missing descriptions for our sphinx+breathe+doxygen [online docs](http://picongpu.readthedocs.io).
Since there have been questions resently between the scope of "default" files in `src/picongpu/include/simulation_defines/param/` and "specific" files in `examples/` here is a short summary.
`src/picongpu/include/simulation_defines/param/`:
- general point of reference for functionality
- must describe all available options
- define a basic EM PIC cycle without domain specific parts
(no lasers, no plugins, no fancy solvers, ...)
- do NOT need to explain complex combinations of the above
`examples/`:
- shall cover options and extensions …
=> Docs: Core Param Files

README.md
Link to `master` & `dev` instead of to `latest`.
=> RTD: Fix Badges

src/picongpu/include/particles/manipulators/FreeRngImpl.def, src/picongpu/include/particles/manipulators/FreeRngImpl.hpp, src/picongpu/include/particles/manipulators/manipulators.def, src/picongpu/include/particles/manipulators/manipulators.hpp, src/picongpu/include/simulation_defines/param/particleConfig.param, src/picongpu/include/simulation_defines/param/seed.param
The manipulator calls a user defined unary functor and provide a random number generator to it.
- add a new seed `FREERNG_SEED` in `seed.param`
- `particleConfig.param` add example to random enable of radiation
This pull request also close #1420 ( random electrons with radiation can be described with this functor)
```C++
struct RandomEnabledRadiationFunctor
{
template< typename T_Rng, typename T_Particle >
DINLINE void operator()( T_Rng& rng, T_Particle& particle )
{
// enable radiation for 10% of the particles
particle[ radiationFlag_ ] = rng() < ( 0.1 );
}
};
/* definition of RandomEnableRadiation */
using RandomEnabledRadiation = FreeRngImpl<
RandomEnabledRadiationFunctor,
nvidia::rng::distributions::Uniform_float
>;
```
=> Add Manipulator `FreeRngImpl`

src/picongpu/include/simulation_defines/param/ionizerConfig.param
Follow up to #1855: Fix typo in `atomicNumbers` of `Oxygen`. Thx to @n01r for the review!
=> Oxygen: Fix neutron number

src/picongpu/include/particles/manipulators/CopyAttribute.hpp
fix that a attribute of a constant(read only) particle is changed
Bug was introduced with #1861 and results in a compile time bug if `CopyAttribute` is used.
=> fix `CopyAttribute`

examples/WarmCopper/README.rst, examples/WarmCopper/cmakeFlags, examples/WarmCopper/include/simulation_defines/param/densityConfig.param, examples/WarmCopper/include/simulation_defines/param/gridConfig.param, examples/WarmCopper/include/simulation_defines/param/particleConfig.param, examples/WarmCopper/include/simulation_defines/param/speciesDefinition.param, examples/WarmCopper/include/simulation_defines/param/speciesInitialization.param, examples/WarmCopper/submit/1gpu.cfg
This setup initializes a homogenous, non-moving, copper block irradiated by a laser with 10^18 W/cm^3 as a benchmark for [SCFLY](https://dx.doi.org/10.1016/j.hedp.2007.02.001) (FLYlite) atomic population dynamics.
We follow the setup from [FLYCHK page 10, figure 4](https://dx.doi.org/10.1016/j.hedp.2005.07.001) assuming a quasi 0D setup with homogenous density of a 1+ ionized copper target. The laser (not modeled) already generated a thermal electron density at 10, 100 or 1000 eV and a delta-distribution like "hot" electron distribution with 200 keV (directed stream).
The observable of interest is <Z> over time of the copper ions. For low thermal energies, collisional excitation, de-excitation and recombinations should be sufficient to reach the LTE state after about 0.1-1 ps. For higher …
=> WarmCopper Example: FLYlite Benchmark

examples/Bremsstrahlung/README.rst, examples/Bremsstrahlung/cmakeFlags, examples/Bremsstrahlung/include/simulation_defines/param/bremsstrahlung.param, examples/Bremsstrahlung/include/simulation_defines/param/componentsConfig.param, examples/Bremsstrahlung/include/simulation_defines/param/densityConfig.param, examples/Bremsstrahlung/include/simulation_defines/param/dimension.param, examples/Bremsstrahlung/include/simulation_defines/param/gridConfig.param, examples/Bremsstrahlung/include/simulation_defines/param/laserConfig.param, examples/Bremsstrahlung/include/simulation_defines/param/particleConfig.param, examples/Bremsstrahlung/include/simulation_defines/param/speciesDefinition.param, examples/Bremsstrahlung/include/simulation_defines/param/speciesInitialization.param, examples/Bremsstrahlung/submit/0008gpus.cfg
This is a simulation of a flat solid density target hit head-on by a high-intensity laser pulse.  
In this process Bremsstrahlung is emitted via creation of macrophotons.
Macrophotons are travelling in every direction, yet they have a higher energy in laser direction.
=> add Bremsstrahlung example

INSTALL.md
Removes the gimli notes on INSTALL.md since that's not the way we render our markdown files.
=> INSTALL: Remove gimli

src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/particles/InitFunctors.hpp, src/picongpu/include/particles/Manipulate.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Remove the `particleStorage` member tuple from `MySimulation`. Access to singleton species memory can now be done via the the PMacc `DataConnector` in all places, reducing interface complexity dramatically.
`Particle` class: external DataConnector registration.
KHI RT test was successful.
=> MySimulation: Remove particleStorage

src/libPMacc/include/mpi/MPIReduce.hpp
Avoid side effects that the MPI context is not initialized but MPI functions were called.
- remove mpi function calls inside the constructor
- implicit initialize `MPIReduce` if any method is called
=> refactor `MPIReduce`

src/libPMacc/include/dataManagement/DataConnector.hpp
Add a `clean()` method to `DataConnector` to trigger unsharing (and potentially removing/destroying) all still shared `ISimulationData` objects.
@n01r also fixes the segfault on simulation shutdown if a RNG is used. RNG forgets to `unshare` itself from the DataConnector.
=> DataConnector: Add Clean() Method

src/tools/share/python/modules4picongpu/hdf5Radiation.py
The openPMD adjustments to the radiation hdf5 output introduced in pull request #1053 result in a different data structure than previously anticipated. Thus an adjustment of our python module to read the amplitude data was required but never implemented.
Now, this pull request adjusts the module to enable reading the new data structure. 
@ax3l Feel free to add the bug label if you think we should add it for bugs in modules as well.
=> adjust radAmplitude python module after openPMD changes

docs/source/dev/pmacc.rst
Document PMacc's `ForEach` and important identifier concepts.
Related to #842: `ForEach` could still need an in-doxygen code example.
=> Doc: `ForEach` & Identifier

docs/source/index.rst, docs/source/usage/REFERENCE.md, docs/source/usage/reference.rst
Close #1438 add a doc section explaining when and how to cite and acknowledge the PIConGPU community.
Independent of this elementary expectation of proper referencing, one could add a *separate page* on *reproducible science recommendations*:
- describe which files are recommended to publish for input/algorithm description
- document software versions of dependencies
- remind to cite the system, hardware & program that provided the computing resources
=> Doc: References & Citation

examples/ThermalTest/include/ThermalTestSimulation.hpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Remove fields and species from `MySimulation` member lists.
> *"We [open data activists] do not want to emancipate the [data], we want the [data] to emancipate themselves.”*
> -- Errico Malatesta
This simplifies the `MySimulation` interface to allow easier overloading and re-implementing of parts of it (like runOneStep) without the need to manage too many members. This becomes especially helpful if one tries to reimplement the `MySimulation` class in Python to *hack the PIC cycle*.
> *"[DataConnector] could never get a man to the moon, but it may the only mode that can allow us to survive on earth."*
> -- Sheldon B. Kopp
Global singleton classes like E, B, J, FieldTmp slots, species are only created via functors once and then shared with `DataConnector`. All algorithms accessing those can …
=> Freedom for Fields (& Species)

src/libPMacc/examples/gameOfLife2D/main.cu, src/libPMacc/include/Environment.def, src/libPMacc/include/Environment.hpp, src/libPMacc/include/dataManagement/DataConnector.hpp, src/libPMacc/include/eventSystem/Manager.hpp, src/libPMacc/include/eventSystem/events/EventPool.hpp, src/libPMacc/include/eventSystem/streams/StreamController.hpp, src/libPMacc/include/eventSystem/tasks/Factory.hpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp, src/libPMacc/include/mappings/simulation/EnvironmentController.hpp, src/libPMacc/include/nvidia/memory/MemoryInfo.hpp, src/libPMacc/include/particles/tasks/ParticleFactory.hpp, src/libPMacc/include/pluginSystem/PluginConnector.hpp, src/libPMacc/include/simulationControl/SimulationDescription.hpp, src/libPMacc/test/PMaccFixture.hpp, src/libPMacc/test/main.cpp, src/picongpu/include/simulation_classTypes.hpp, src/picongpu/main.cu
This change allows to execute `picongpu --help` also if MPI is not available (e.g. on the hypnos head nodes).
- create `detail::Environment` for all singletons without dimension
- add `detial::EnvironmentContext` to hold context information variables
for `Environment<>` independent of number of simulation dimensions
- change friend from `Environment<>` to `detail::Environment` (for all singletons without dependency to the simulation dimension)
- use clean environment finalize of PMacc
- remove gloable usage of `PMacc` and `picongpu` namespace
- update `gameOfLife`
- update PMacc test cases
=> PMacc environment refactoring

src/picongpu/include/particles/bremsstrahlung/Bremsstrahlung.tpp, src/picongpu/include/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/WriteFields.hpp
annotate template function calls with the keyword `template`
The fix is needed for #1731
This bug is also in the current release, but has **no effect** because we not support compiling with clang. Therefore I do not add the flag `effects latest release`
=> fix broken clang compile

src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/writer/Field.hpp
Fix #1899: our PIConGPU arrays describing cell sizes, offsets and sizes are in a rather inconsequent `{x, y, z}` order while the datasets they describe are *labeled* in `F[z][y][x]` order.
(note: this has nothing to do with slow or fast varying index aka C vs F order. This is just a inconsequent *labeling* of our `F[i][j][k]` indizes in PIConGPU, which arbitrarily did choose that `x` will always be the *fastest* varying "index"...)
This fixes the same issue as previously seen with `axisLabels` for openPMD in ADIOS and HDF5 output #1478.
Only affects if at least one of the following is true:
- moving window is used
- non-quadratic cells are used
the size / layout of the simulation box (`-g`) is independent of this issue and works quadratic and non-quadratic.
=> openPMD: Fix Grid Spacing, GlobalOffset

src/picongpu/submit/bash/bash_mpiexec.tpl, src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/davinci-rice/picongpu.tpl, src/picongpu/submit/hypnos-hzdr/fermi_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_vampir_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_wait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k80_profile.tpl, src/picongpu/submit/hypnos-hzdr/k80_profileRestart.tpl, src/picongpu/submit/joker-tud/fermi.tpl, src/picongpu/submit/joker-tud/fermi_vampir.tpl, src/picongpu/submit/joker-tud/tesla.tpl, src/picongpu/submit/joker-tud/tesla_vampir.tpl, src/picongpu/submit/judge-fzj/m2050.tpl, src/picongpu/submit/judge-fzj/m2050_profile.tpl, src/picongpu/submit/judge-fzj/m2070.tpl, src/picongpu/submit/judge-fzj/m2070_profile.tpl, src/picongpu/submit/keeneland-gt/parallel.tpl, src/picongpu/submit/lawrencium-lbnl/fermi_profile.tpl, src/picongpu/submit/lawrencium-lbnl/k20_profile.tpl, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/total_profile.tpl, src/picongpu/submit/taurus-tud/k20x_profile.tpl, src/picongpu/submit/taurus-tud/k80_profile.tpl
- skip GPU memory test if the binary `cuda_memtest` does not exists
- add `cuda_memtest` to  `bash` and `davinci` submit templates
We need this optional memory test for the case that it is not possible to build cuda_memtest ~~(e.g. on titan ORNL)~~ and if PIConGPU is compiled with clang as device compiler #1731.
[update] On titan ORN it is not possible to call a bash script with aprun, therefore it is not possible to activate `cuda_memtest`
=> check if binary `cuda_memtest` exists

REFERENCE.md
Change the short name (TeX alias) of our reference to be more readable.
=> BibTex: Change ShortHand

examples/ThermalTest/include/ThermalTestSimulation.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/eventSystem/events/CudaEvent.def, src/libPMacc/include/eventSystem/events/CudaEvent.hpp, src/libPMacc/include/lambda/CT/Eval.hpp, src/picongpu/include/plugins/SliceFieldPrinterMulti.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteMeta.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/hdf5/WriteMeta.hpp, src/picongpu/include/plugins/hdf5/writer/Field.hpp
C++98 backport of fixes to `0.2.4`:
- openPMD: Fix Grid Spacing, GlobalOffset #1900
- remove BOOST_BIND_NO_PLACEHOLDERS #1849
- std Include: Never inside Namespaces #1835
- HDF5/ADIOS: Fix ill-places helper incl #1846
- add missing HDINLINE #1825
- CudaEvent: Fix Cyclic Include #1836
```
1) mpfr/3.1.2                    8) openmpi/1.8.4.kepler.cuda70
2) mpc/1.0.1                     9) pngwriter/0.5.6
3) gmp/5.1.1                    10) hdf5-parallel/1.8.14
4) gcc/4.8.2                    11) libsplash/1.6.0 (build from source)
5) cmake/3.3.0                  12) libmxml/2.8
6) boost/1.62.0                 13) adios/1.9.0
7) cuda/7.0
```
Please take extra care if I missed C++11 features, `0.2.X` must be C++98 compatible.
=> Collection of Backports for 0.2.4

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
Fields `init()` shall not self-register themselves at the `DataConnector` anymore.
Follow-up that should have been in #1887 and fix to #1907.
Removes unnecessary interface params in their `init()` on the way, since it's the same methods and can be cleaned up with the new `DataConnector`.
=> Fields: No Self-Registration

src/picongpu/include/particles/manipulators/IfRelativeGlobalPositionImpl.hpp
the position for the second particle is only checked if the first particle is valid
This bug is only triggered if `IfRelativeGlobalPositionImpl` is used as binary operator. The example `KelvinHelmholtz` is only using the unary version of this manipulator.
=> fix manipulator `IfRelativeGlobalPositionImpl`

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp
It is not allowed to use `PMACC_VERIFY` in a device or host/device function ( because std::string is not available on device).
- remove `PMACC_VERIFY_MSG` from `laserTransversal`
Never the less the check is useless because it is already checked at compile time.
I added the compile time range check also to the method `laserLongitudinal` to be sure that
the value is valid before it is used inside the followed loop.
This bug was introduced with #1580 (currently not in the master branch). It is a non critical bug for `nvcc` but avoid to compile with `clang`.
=> remove useless `PMACC_VERIFY`

src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/particles/manipulators/DriftImpl.hpp, src/picongpu/include/particles/manipulators/IManipulator.hpp, src/picongpu/include/particles/manipulators/IfRelativeGlobalPositionImpl.hpp, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/SetAttributeImpl.hpp, src/picongpu/include/particles/manipulators/TemperatureImpl.hpp
C++98 backport of fixes to `0.2.4`:
- Particle manipulators: Fix Position Offset #1852 +  #1910
```
1) mpfr/3.1.2                    8) openmpi/1.8.4.kepler.cuda70
2) mpc/1.0.1                     9) pngwriter/0.5.6
3) gmp/5.1.1                    10) hdf5-parallel/1.8.14
4) gcc/4.8.2                    11) libsplash/1.6.0 (build from source)
5) cmake/3.3.0                  12) libmxml/2.8
6) boost/1.62.0                 13) adios/1.9.0
7) cuda/7.0
```
Please take extra care if I missed C++11 features, `0.2.X` must be C++98 compatible.
I also had to solve a few conflicts `src/picongpu/include/particles/Particles.kernel` which hopefully turned out well. Best to compare the diff of that file directly to the diff it got in #1852
=> Backport 0.2.4: Particle manipulators Position Offset

examples/Bremsstrahlung/include/simulation_defines/param/laserConfig.param, examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, src/picongpu/include/fields/FieldE.kernel, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldManipulator.hpp, src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPlaneWave.hpp, src/picongpu/include/fields/laserProfiles/laserPolynom.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp, src/picongpu/include/fields/laserProfiles/laserWavepacket.hpp, src/picongpu/include/simulation_defines/param/laserConfig.param
- `FieldE.kernel`: add laser scaling factor if `laser::initPlaneY != 0`
- `FieldE.tpp`:
- add asserts to check conditions for the laser initialization plane
- model: a change of initialization plane does not make a change in focus position or time-to-target necessary
- `FieldManipulation.hpp`: enable top absorber if `laser::initPlaneY != 0`
- `laserConfig.param`
- add namespace laser
- add parameter `initPlaneY`
- laser profiles (keep first top cell as origin for all laser parameters)
- manipulate focus depending of the `initPlaneY`
- shift the internal runtime based of `initPlaneY`
Todo:
scaling factor
--------------
The current implementation calculated a scaling factor for the amplitude to respect that we initialize only the electrical field and not magnetic field. The result of the …
=> allow to define the laser initialization plane

examples/Bremsstrahlung/include/simulation_defines/param/gridConfig.param, examples/Bunch/include/simulation_defines/param/gridConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param, examples/LaserWakefield/include/simulation_defines/param/gridConfig.param, examples/SingleParticleTest/include/simulation_defines/param/gridConfig.param, examples/ThermalTest/include/simulation_defines/param/gridConfig.param, examples/WarmCopper/include/simulation_defines/param/gridConfig.param, examples/WeibelTransverse/include/simulation_defines/param/gridConfig.param, src/picongpu/include/simulationControl/MovingWindow.hpp, src/picongpu/include/simulation_defines/param/gridConfig.param
This pull request closes issue #1915 by renaming `slide_point` to `movePoint` because it actually defines the start of the moving window.
=> rename slide_point to movePoint

docs/source/dev/pmacc.rst
Document the kernel start via a macro and which class is build behind it to explain the order of parameters.
=> Doc: PMacc Kernel Start

src/libPMacc/include/memory/shared/Allocate.hpp
add more documentation to avaoid wrong usage of the macro `PMACC_SMEM()`
=> shared memory allocator documenation

src/libPMacc/include/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp, src/libPMacc/include/memory/boxes/SharedBox.hpp
replace `__shared__ type varName` with `PMacc::memory::shared::allocate<...>()`
This is a follow up of #1727 and fix #1927 by flat all N dimensional arrays to 1D. 
There is a very small performance increase due to more 32Bit integer calculations (instead of 64Bit) during the address calculation for each shared memory access. 
Tests:
=> remove CUDA native static shared memory

src/libPMacc/include/compileTime/errorHandlerPolicies/ThrowValueNotFound.hpp, src/libPMacc/include/traits/GetNComponents.hpp, src/libPMacc/include/traits/HasIdentifier.hpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, src/picongpu/include/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, src/picongpu/include/traits/attribute/GetChargeState.hpp
An expression within a static assert those not depend on a template can be evaluated from the compiler even if the code is never instantiated.
This means that a context check inside the body of a class is not possible with some compiler e.g. clang.
A workaround is to extent the condition for the static assert with a template dependent expression those is always evaluated to `true`.
The expression `sizeof(AnyType)!=0` is always `true` and can be used as workaround.
This pull request is needed by the pull request to compile with clang #1731.
Tested with
=> clang compatible static assert usage

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/unitless/radiationConfig.unitless
This pull request removes the pre-compiler switch to exclude the Nyquist limit calculation and thus partially solves issue #667. 
Not calculating the Nyquist limit makes only sense if computing low frequency radiation - below `omega < pi / (2 * delta_t) ` (factor 2 due to propagation away from the detector at the speed of light). This is already resolved by the grid. In most cases, the Nyquist limit should be taken into account. Thus removing the option avoid misconfiguration by accidentally not activating this limit.
=> Remove nyquist limit switch

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/fileOutput.param, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.hpp, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/frequencies/radiation_lin_freq.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_list_freq.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_log_freq.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param, src/picongpu/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/unitless/radiationConfig.unitless
- Radiation: 
- disable help if dependencies for the solver are not fulfilled (announce the missing dependency to the user)
- add kernel dummy `KernelRadiationParticles<>` for missing dependencies
- `PluginController.hpp` always register the plugin `Radiation` (if HDF5 is available)
- remove usage of `ENABLE_RADIATION`
The plugin is now only available for species with the attribute  `momentumPrev1`. Before this pull request `momentumPrev1` must be added to all species to allow the usage of the radiation plugin.
Related to #667
=> remove define `ENABLE_RADIATION`

src/picongpu/include/algorithms/AssignedTrilinearInterpolation.hpp
This pull request remove the usage of floats for loop indices. The advantage is that the loop length is known at compile time and the compiler can optimize much more.
- use integer indices for the loops
- remove pragma unroll
Tests KHI positrons/electrons:
- clang [version 4.0.0 (trunk 290769)]
- nvcc [release 8.0, V8.0.44]
=> optimize `AssignedTrilinearInterpolation`

src/libPMacc/PMaccConfig.cmake, src/libPMacc/include/static_assert.hpp, src/picongpu/CMakeLists.txt
- use C++11 `static_assert` if clang is the device compiler
- `PMaccConfig.cmake`
- add compiler independent options: CUDA_FAST_MATH, CUDA_FTZ, CUDA_SHOW_REGISTER and CUDA_KEEP_FILES
- add clang compiler flag preperation section
- add option to select the device (CUDA) compiler
- PIConGPU `CmakeList.txt`
- add clang compiler section to create the device code
- add option `CUDAMEMTEST_ENABLE`
- set `CUDAMEMTEST_ENABLE=OFF` if clang is the device compiler
=> support for clang as host && device compiler

src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.hpp
close  #1934
The bug is that `decltype` returned a reference pointing to temporary memory and was introduced with #1798.
Use explicit `mallocMC::HeapInfo` instead of catching the type with `std::declval` and `decltype`.
This bug is not effecting the latest release!
Tests:
=> fix `PMacc::MallocMCBuffer`

examples/Bremsstrahlung/include/simulation_defines/param/speciesDefinition.param, examples/Bunch/include/simulation_defines/param/speciesDefinition.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesDefinition.param, examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WarmCopper/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/libPMacc/include/particles/traits/ResolveAliasFromSpecies.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
- change order of the template arguments `T_Flags` and `T_Attributes`
- update `speciesDefinition.param`
This refactoring would help to add species attributes in a future follow up automatically depending of the user selected solvers (species flags).
=> refactor `Particles<>` interface 

.gitignore
This pull request avoids that configuration files from [Visual Studio Code](https://github.com/Microsoft/vscode) are included into this git repository.
=> add visual studio code files to gitignore

src/picongpu/submit/taurus-tud/Slurm_Tutorial.rst
This adds some examples to the slurm documentation explaining how to control your job after submission to the scheduler.
=> add documentation on slurm job control

docs/source/conf.py, docs/source/dev/sphinx.rst, docs/source/index.rst, docs/source/usage/reference.rst
Fixes pdf chapter building on sphinx. Now looks great and table of contents is useful.
End of the HTML index page is still a bit messy, but ok.
```bash
cd docs
make pdflatex
okular build/latex/PIConGPU.pdf
```
=> Sphinx: Fix PDF Chapters

docs/source/install/path.rst
Fix a few typos in install docs, add classic modules as reference.
=> Docs: Typos, Modules

src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.tpp
make the `constexpr` from input available on device by storing it on a temporal `const`:
```
src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.tpp(42): error:
identifier "picongpu::particles::bremsstrahlung::electron::MIN_ENERGY" is undefined in device code
src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.tpp(43): error:
identifier "picongpu::particles::bremsstrahlung::electron::MAX_ENERGY" is undefined in device code
```
Add missing simulation_defines include.
Only showed up with `-g -G`, fixes #1774
=> Bremsstrahlung: Missing Include & Const

src/picongpu/submit/taurus-tud/Slurm_Tutorial.rst
This fixes a typo in the slurm documentation introduced with pull request #1945 
The command option fur u**n**hold is just ~~`uhold` - without `n`~~ `release`.
=> fix typo in slurm doc

docs/source/index.rst, docs/source/usage/param/core.rst, docs/source/usage/param/extensions.rst, docs/source/usage/param/memory.rst, docs/source/usage/param/misc.rst, docs/source/usage/param/plugins.rst, docs/source/usage/workflows.rst, docs/source/usage/workflows/numberOfCells.rst, docs/source/usage/workflows/resolution.rst
Starts a user workflows section in our docs with workflows to:
- set the number of cells of a simulation
- change the resolution of a simulation
=> Doc: Start a User Workflows Section

src/libPMacc/PMaccConfig.cmake
Embedded ptx code within the binary was accidentally removed with #1933.
If the code is compiled with `sm_20` and than performed on e.g. `sm_35` it can result in segfaults, see #1953, #1954
@PrometheusPi, @n01r could you please check if out issues are solved
=> fix missing ptx code within the binary

src/libPMacc/include/random/RNGProvider.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
Our RNGFactory should be shared with the `DataConnector` within `MySimulation` and should not share itself in its constructor.
This fixes #1953.
I will also change this behavior for `MallocMCBuffer` in a follow-up, although we have not issues from it.
=> Fix #1953 RNG Shutdown via DataConnector

src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
Follow-up to #1963: share the `MallocMCBuffer` from `MySimulation` explicitly instead of implicitly from its constructor.
RT tested with LWFA example, case 10 with ions and ionization (set to use lin. pol. ADK).
=> Refactor MallocMCBuffer Share

docs/source/install/profile.rst, docs/source/usage/tbg.rst
on literal file includes with line numbers in front the RTD style seems to mismatch the line numbers line height and the quoted text's line height.
We remove the line numbers for now in those includes.
=> RTD: Remove Linenumbers

src/libPMacc/include/memory/Array.hpp
This pull request is equal to #1767 and allows that elements stored within the Array are not default constructed.
The reason for this pull request is that we need to construct array of user defined object from PIConGPU param files. Without this change the user must always write/implement a default constructor, this would make the code more complex and would be complicated for a non computer scientist.
=> Array: store elements without a default constructor

src/libPMacc/include/memory/CtxArray.hpp
Add the class `CtxArray` to store varibles with context information for the lock step programming model.
```C++
// transform the thread index to a relative coordinate based on our exchange enumeration
// 1 == right, 2 == left, ...
memory::CtxArray< DataSpace<dim>, ExchangeDomCfg > relativeCtx(
threadIdx.x,
[&]( uint32_t const linearIdx, uint32_t const ) -> DataSpace<dim>{
return superCellIdx + Mask::getRelativeDirections<dim> ( linearIdx + 1u);
}
);
```
```C++
using ExchangeDomCfg = IdxConfig<
numExchanges, // e.g. 27
numWorker
>;
using ParticleDomCfg = IdxConfig<
frameSize, //e.g. 256
numWorker
>;
memory::CtxArray<
int,
ParticleDomCfg
> localGapIdxCtx( INV_LOC_IDX );
```
=> add array to hold context variables

src/libPMacc/include/mappings/threads/ForEachIdx.hpp, src/libPMacc/include/mappings/threads/IdxConfig.hpp
- add index domain decription class `IdxConfig`
- add for each functor to iterate over a index domain
`ForEachIdx` is the base algorithm to unroll loops for the upcoming lock step programming model for each kernel. This allows to declutch the *supercell* size and the number of worker (threads) to process a supercell or the particles within a *supercell*.
- old implementation only usable for functor with to parameter
```C++
for (int i = threadId; i < math::CT::volume<FullSuperCellSize>::type::value; i += maxThreads)
{
const DataSpace<Dim> pos(DataSpaceOperations<Dim>::template map<FullSuperCellSize > (i) - OffsetOrigin::toRT());
f(p1(pos), p2(pos));
}
```
- new implementation, usable for arbitrary number of functor parameter
```C++
mappings::threads::ForEachIdx< …
```
=> feature `ForEachIdx`

src/libPMacc/PMaccConfig.cmake, src/picongpu/CMakeLists.txt
The issue with the old implementation is that the variable `CMAKE_BUILD_TYPE` was always empty and therefore we build everything as `debug`. This should be avoided and is since #1662 not necessary.
- PMacc
- change default behavior from build in debug mode to build as release
- allow user to switch `CMAKE_BUILD_TYPE` between `Release` and `Debug`
- PIConGPU
- remove CMake option `PIC_RELEASE`
This changes the build type default to `Release`.
@ax3l Should we port this the the `0.3.0-rc`?
=> option for CMake build type

src/picongpu/include/simulation_defines/param/ionizationEnergies.param
The `\todo` section was outdated since there is currently no need for either
better storage of ionization energies or field strengths calculated from
them. (The latter is done by the BSI model itself.)
One of the remaining issues is that the ionization energy vectors take up
constant memory of the GPU even if they are not used. An improvement on that
should be requested in a GitHub issue, though.
This is a follow-up to #1983 .
=> Remove ToDo from ionizationEnergies.param

docs/source/usage/param/core.rst, docs/source/usage/plugin.rst
Updates the order in the usage chapter of our docs to be more intuitive.
Also adds a link to the wiki for plugins.
I would propose the following re-namings for our species files:
- `species.params`:
- just contains general defines, two ways to go:
- move `speciesDefinitions` headers like `DefaultAttributes` and
`DefaultFlags` to same file and rename to `speciesDefaults` or
- merge into header of `speciesDefinition.param`
- `particles.param`: rename to either `speciesFunctors.param` or
`speciesManipulation.param`/`speciesManipulators.param`
=>  Parameter Order in Manual

src/picongpu/include/simulation_defines/param/speciesDefinition.param
In the default density ratio of ions (aka "Empty example") the density ratio is accidentally defined negative. This fixes it (and did cost me some hours to figure out).
=> Fix Default Density Ratio Ions

src/libPMacc/include/compileTime/accessors/Type.hpp
The most ridiculous doxygen string I have ever written, enjoy:
```C++
/** Get ::type member of the given type
*
* @tparam T type from which we return the type held in ::type
*
* T must have defined ::type
*/
```
Can be used in conjunction with, e.g. `boost::mpl::transform` or `PMacc::OperateOnSeq`. Needed for multi-ionizer per species support.
=> CompileTime Accessor: Type (::type)

src/libPMacc/include/memory/IndexPool.hpp
Add a new container to libpmacc, that represents an index pool.
important, self-explaining methods:
- `get()` get a new index
- `release()` release an index
Tested with the particle merging plugin (future PR).
=> Feature: index pool

docs/TBG_macros.cfg
fix an outdated comment in the `docs/TBG_macros.cfg` examples for phase spaces
=> TBG Macros: Outdated Comment

INSTALL.rst, USAGE.rst, docs/source/conf.py, docs/source/dev/sphinx.rst, docs/source/install/compile.rst, docs/source/install/path.rst, docs/source/install/profile.rst, docs/source/models/LL_RR.rst, docs/source/models/ionization.rst, docs/source/models/photons.rst, docs/source/models/pic.rst, docs/source/postprocessing/openPMD.rst, docs/source/postprocessing/paraview.rst, docs/source/postprocessing/python.rst, docs/source/usage/reference.rst, docs/source/usage/tbg.rst, docs/source/usage/workflows/laserPeakOnTarget.rst, docs/source/usage/workflows/numberOfCells.rst, docs/source/usage/workflows/resolution.rst, examples/Bremsstrahlung/README.rst, examples/Bunch/README.rst, examples/Empty/README.rst, examples/KelvinHelmholtz/README.rst, examples/LaserWakefield/README.rst, examples/WarmCopper/README.rst, src/picongpu/submit/taurus-tud/Slurm_Tutorial.rst
Moves author macros to the right position and enables printing them.
- `sectionauthor`: author(s) of the doc
- `moduleauthor`: original author and maintainer(s) of the implementation (nor everyone that touched or formatted a file but relevant contributions to that section in modeling and implementing; scope: BA/MA/PhD thesis or sub-project lead)
=> Sphinx: Move Author Macros

examples/Bunch/include/simulation_defines/param/memory.param, examples/KelvinHelmholtz/include/simulation_defines/param/memory.param, examples/LaserWakefield/include/simulation_defines/param/memory.param, examples/ThermalTest/include/simulation_defines/param/memory.param, examples/WeibelTransverse/include/simulation_defines/param/memory.param, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/simulation_defines/param/memory.param
Add an explicit method to trigger that border data from the neighbor is gathered into the local guard of the GPU.
- add method `asyncCommunicationGather()` (gather neighbor's border data)
- add buffer for gather communication
- define `fieldTmpSupportGatherCommunication` variable in `memory.param` to activate gather support for `FieldTmp`
- remove method `getCommTag()`
Currently the new method `asyncCommunicationGather()` is only available in `FieldTmp` but should be later also be ported to all other buffers like `FieldE` and `FieldB`. The best way to do is is to extent the PMacc `GridBuffer` to support `asyncCommunicationScatter()` and `asyncCommunicationGather()`.
This is a bigger refactoring and should not be part of this pull request to allow a backport to the current release …
=> `FieldTmp` gather support

src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
This fixes issue #2012. 
For some reasons the `constexp` variable `TITLT_X` is not known on the device side in the `tan()` call. If defined before as `const`, the compile issue is solved. 
@psychocoderHPC Is there a better solution than the work around of this pull request?
=> Fix undefined device variable in tilted laser pulse

src/picongpu/include/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
Adds communication to the `FieldTmp` slots to cure an unholy domain-decomposition bug in Thomas-Fermi ionization. (Density and Energy in the a local GPU's border has contributions from the next GPU.) The full example shown below is given in #2008 but applies for all cases where Thomas-Fermi ionization is used.
**BSI+ADK+TF_dev**
**BSI+ADK**
Unfortunately, there seems an other bug (maybe wrongly shifted or some caching issue?). But at least it's already less severe:
**BSI+ADK+TF_PR**
=> ThomasFermi: Fix Domain Decomposition

src/libPMacc/include/math/vector/Vector.hpp
@psychocoderHPC and me added a little explicit cast to allow `float1_X` to be casted directly to `float_X`.
Only available for vectors with dimension one via `std::enable_if`.
This comes handy when working with FieldTmp, which is by default a `float1_X`.
=> Vector float1_X to float_X cast

docs/source/index.rst, docs/source/prgpatterns/lockstep.rst, src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.kernel
- refactor `KernelShiftParticles` (use lockstep description)
- add documentation `lockstep.rst`
- each variable which was previously the state of one thread is now a `CtxArray` and got the postfix `Ctx` for *the virtual worker's context* (this avoid side effects during the refactoring and helps to read the code)
- the number of worker per kernel is chosen at compile time and is currently fixed to the size of the supercell but will depend in the future on the alpaka accelerator restrictions.
- I tried not to change the logical flow of the algorithm or add optimizations.
- the changed code is formatted with the new code style
The *lockstep programming model* separates code those is evaluated by worker (threads) collectively and independently.
A problem is described by index domains. A index …
=> lock step kernel `KernelShiftParticles`

src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSI.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI.def, src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.def, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.hpp, src/picongpu/include/particles/ionization/byField/ionizers.def, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/simulation_defines/param/ionizer.param
The `BSIHydrogenLike` model was much too narrow since it was only applicable
to hydrogenlike states, i.e. states that have charge (Z-1)+.
The following replacement was done in
F_BSI = E_i^2 / (4*Z)
Z (nuclear charge) --> Z_i (ion residual charge)
That means that in a naive way the inner electrons shield the nuclear charge
from the electron that is to be ionized.
=> Rm BSIHydrogenLike, Add BSI with charge Z

docs/source/usage/workflows.rst, docs/source/usage/workflows/compositeMaterials.rst, docs/source/usage/workflows/quasiNeutrality.rst, examples/FoilLCT/README.rst, examples/FoilLCT/cmakeFlags, examples/FoilLCT/include/simulation_defines/param/components.param, examples/FoilLCT/include/simulation_defines/param/density.param, examples/FoilLCT/include/simulation_defines/param/dimension.param, examples/FoilLCT/include/simulation_defines/param/fileOutput.param, examples/FoilLCT/include/simulation_defines/param/grid.param, examples/FoilLCT/include/simulation_defines/param/laser.param, examples/FoilLCT/include/simulation_defines/param/memory.param, examples/FoilLCT/include/simulation_defines/param/particle.param, examples/FoilLCT/include/simulation_defines/param/speciesDefinition.param, examples/FoilLCT/include/simulation_defines/param/speciesInitialization.param, examples/FoilLCT/submit/0004gpus.cfg
This example models a laser-ion accelerator in the TNSA regime. An optically over-dense target n_max = 192 n_c consisting of a liquid-crystal material is used. Irradiated with a high-power laser pulse with a_0 = 5 the *8CB* ([4-octyl-4'-cyanobiphenyl](http://www.chemspider.com/Chemical-Structure.94149.html)) C_{21} H_{25} N target is assumed to be once pre-ionized due to realistic laser contrast and pre-pulses to C^+, H^+ and N^+ while being slightly expanded on its surfaces (modeled as exponential density slope).
The laser is assumed to be in-focus and approximated as a plane wave with temporally Gaussian intensity envelope of tau^{FWHM}_I = 25 fs.
This example is used to demonstrate:
* an ion acceleration setup with
* non-trivial initial conditions
* composite materials
* ionization …
=> Example: Foil (LCT) TNSA

.gitignore, docs/source/conf.py, docs/source/models/field_ionization.rst, docs/source/models/field_ionization_comparison_c_ii_ionization.py, docs/source/models/field_ionization_effective_potentials.py
Fix #2029 by using the official matplotlib (MPL) sphinx extension to embed plots on-the-fly.
Also fixed broken `make latexpdf` compile in usage of own align (use [nowrap](http://stackoverflow.com/questions/24867685/aligned-equations-with-mathjax-and-with-equation-numbers)).
Note:
- this might need regressions after merge, e.g. to set `agg` as backend by hand
=> Fix #2029 MPL Embedded Plots Sphinx

docs/source/models/field_ionization_comparison_c_ii_ionization.py
This is a follow up pull request to #2031 and #2011. It adds a missing `linestyle` in `field_ionization_comparison_c_ii_ionization.py`. 
(I missed this in the review of #2011.)
=> add missing linestyle to ionization plot for documentation

docs/source/models/field_ionization_comparison_c_ii_ionization.py
The unit of a (probability) rate is `1/s` not `Hz` (see [wikipedia article](https://en.wikipedia.org/wiki/Hertz#Definition)).
This pull request fixes the unit in the plot.
=> fix unit ionization rate plot

docs/TBG_macros.cfg, src/picongpu/include/plugins/SliceFieldPrinter.hpp, src/picongpu/include/plugins/SliceFieldPrinter.tpp, src/picongpu/include/plugins/SliceFieldPrinterMulti.hpp, src/picongpu/include/plugins/SliceFieldPrinterMulti.tpp
This pull request changes for all sliceField plugins the `.frequency` call to `.period` (as used in all other plugins). This makes the interface of the plugin more coherent.
Thanks @steindev for pointing out this issue *offline*.
=> SliceField Plugin: Option .frequency to .period

src/picongpu/include/fields/FieldManipulator.kernel
This fixes a bug introduces **3 years ago** with #212.
The typo `SDIMDIM` in the precompiler if-clause evaluates as false, thus causing **no absorber in z**. 
This effects all 3D simulations with absorbers. 
The field along z-are not absorbed, see here:
=> fix typo causing no absorber in 3D

src/picongpu/include/particles/traits/GetIonizerList.hpp
The alias `ionizers<>` is defined in `speciesAttributes.param` therefore `simulation_defines.hpp` must be
included.
No definition from `macc_types.hpp` is used.
Remove `#include "pmacc_types.hpp"` with `#include "simulation_defines.hpp"`.
The effect of the missing include should be a non compile able version of PIConGPU, This is not the case because the definition is included somewhere else in another file and therefore hides the error.
=> `GetIonizerList` fix missing include

docs/source/usage/param.rst
Migrated [a page I wrote](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Parameter-Files) recently in the wiki. Param files now have a good introduction about their meaning and the order of editing the files is explained.
=> Docs: Param Extended Description

src/picongpu/include/particles/InitFunctors.hpp
This pull request removes a not-needed template in `FillAllGaps` that prevents using `FillAllGaps` in the init pipeline. 
Thanks @psychocoderHPC for finding this bug.
=> fix FillAllGaps

examples/Bremsstrahlung/include/simulation_defines/param/speciesDefinition.param, examples/Bunch/include/simulation_defines/param/speciesDefinition.param, examples/FoilLCT/include/simulation_defines/param/speciesDefinition.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesDefinition.param, examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WarmCopper/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/ionizer.param
Adds the include in `speciesDefiniton.param` to examples where it was still missing. Otherwise Thomas-Fermi ionization could not be used in the `ionizers< ... >` sequence.
=> Examples: Collisional Ionization Include

examples/Bremsstrahlung/include/simulation_defines/param/speciesInitialization.param, examples/Bunch/include/simulation_defines/param/speciesInitialization.param, examples/FoilLCT/include/simulation_defines/param/speciesInitialization.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesInitialization.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/SingleParticleTest/include/simulation_defines/param/speciesInitialization.param, examples/ThermalTest/include/simulation_defines/param/speciesInitialization.param, examples/WarmCopper/include/simulation_defines/param/speciesInitialization.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/picongpu/include/simulation_defines/param/speciesInitialization.param
This pull request removes a wrong `typename` in the documentation of the particle manipulators. 
Adding this `typename` will lead to a compile time error.
=> remove extra typename in documentation of manipulators

src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp
Remove usage of local instead of the member variable.
The result of the bug is that more buffer than needed have stored the buffer size on the device.
This results in more memory copies from/to the device.
This could be negative for the strong scaling.
=> fix shadowed member variable

examples/Bremsstrahlung/README.rst, examples/Bremsstrahlung/include/simulation_defines/param/bremsstrahlung.param, examples/FoilLCT/include/simulation_defines/param/fileOutput.param, examples/SingleParticleTest/include/simulation_defines/param/fileOutput.param, src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.hpp, src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.tpp, src/picongpu/include/simulation_defines/param/bremsstrahlung.param, src/picongpu/include/simulation_defines/param/fileOutput.param, src/picongpu/include/simulation_defines/param/particle.param, src/picongpu/include/simulation_defines/param/synchrotronPhotons.param
This pull request fixes some typos discovered in param files during work with PIConGPU this week.  
It also fixes equivalent typos in associated files.
=> fix typos found in param files and associated files

INSTALL.rst, src/picongpu/CMakeLists.txt, src/picongpu/include/particles/bremsstrahlung/PhotonEmissionAngle.hpp, src/picongpu/include/particles/bremsstrahlung/ScaledSpectrum.hpp, src/picongpu/include/particles/synchrotronPhotons/SynchrotronFunctions.tpp
Fix error 
```boost/numeric/ublas/matrix.hpp(5977): error: namespace "boost::serialization" has no member "make_array"```
This bug is introduced with boost 1.64.0.
boost issue [12516](https://svn.boost.org/trac/boost/ticket/12516).
This fix allows to compile PIConGPU with boost 1.64.0 and cuda 7.5.
This fix is **not solving** #2048 for CUDA 8.0.
=> fix boost 1.64.0 odeint integrate bug

src/picongpu/include/fields/FieldE.kernel, src/picongpu/include/fields/FieldE.tpp
=> lockstep refactoring `KernelLaserE`

INSTALL.rst, src/libPMacc/PMaccConfig.cmake
Until we find a fix for Boost 1.64.0 and CUDA 8.0, we throw a clean abort at configure time to inform the user.
See #2048
=> Abort on CUDA8 + Boost 1.64.0

CHANGELOG.md, examples/Bunch/include/simulation_defines/param/speciesInitialization.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesInitialization.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/ThermalTest/include/simulation_defines/param/speciesInitialization.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp, src/picongpu/include/plugins/output/sockets/SocketConnector.hpp, src/picongpu/include/simulation_defines/param/speciesInitialization.param
Further backports for the 0.2.5 release (C++98):
**Bug Fixes:** (already in)
- ADK ionization: effective principal quantum number nEff #2011
- 3D3V: missing absorber in z #2042
**Misc:** (added in this PR)
- compile-time warning in 2D live plugin #2063
- DeviceBufferIntern: fix shadowed member variable #2051
- speciesInitialization: remove extra typename in doc #2044
=> Backports for 0.2.5-rc2

src/picongpu/include/fields/FieldE.kernel
remove usage of the undefined variable `cell`
This bug was introduced with #2056.
thx @n01r for the bug [report](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2056#pullrequestreview-40011823)
=> fix `KernelLaserE`

INSTALL.rst, src/libPMacc/PMaccConfig.cmake
fix #2048 follow-up to #2069
disable boost noexept if nvcc with (CUDA 8.0) is the device compiler and boost 1.64.0 is used
=> fix nvcc compile with boost 1.64.0

INSTALL.rst
rsync is quite an essential tool for our helper (bash) scripts and not yet documented. this adds it.
=> Install: Rsync Missing

src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
- remove method `createParticleBuffer()`
- call member method `reset()` within the constructor to have a valid object after creation
- `CallCreateParticleBuffer` 
- rename to `LogMemoryStatisticsForSpecies`
- remove call to `createParticleBuffer()`
- `MySimulation.hpp: call `LogMemoryStatisticsForSpecies` for each species
Note: This pull request contains two changes but a splitting it into two pull request make no sense.
=> remove `ParticlesBuffer::createParticleBuffer()`

docs/source/usage/param/extensions.rst, examples/WarmCopper/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/flylite/IFlyLite.hpp, src/picongpu/include/particles/flylite/NonLTE.def, src/picongpu/include/particles/flylite/NonLTE.hpp, src/picongpu/include/particles/flylite/NonLTE.tpp, src/picongpu/include/particles/flylite/helperFields/LocalDensity.hpp, src/picongpu/include/particles/flylite/helperFields/LocalDensity.kernel, src/picongpu/include/particles/flylite/helperFields/LocalDensityFunctors.hpp, src/picongpu/include/particles/flylite/helperFields/LocalEnergyHistogram.hpp, src/picongpu/include/particles/flylite/helperFields/LocalEnergyHistogram.kernel, src/picongpu/include/particles/flylite/helperFields/LocalEnergyHistogramFunctors.hpp, src/picongpu/include/particles/flylite/helperFields/LocalRateMatrix.hpp, src/picongpu/include/particles/flylite/types/Superconfig.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/param/flylite.param, src/picongpu/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless
This PR adds the interface for FLYlite non-LTE collisional-radiative modeling for ions.
Read it commit-wise. Implements:
- ion attribute `superconfig` (not used yet, but already initialized when used)
- ion alias/flag `populationKinetics` to enable non-LTE calculations for an ion species
- adds FLYlite API
- adds particle functors and implements all RT interfaces in `MySimulation`
- creates helper fields and fills them with proper values (histograms and densities)
- updates the WarmCopper example to use the `populationKinetics` algorithms (so the compile-suite catches it), RT tests on K80 were successful
The actual population kinetics is not part of this PR and still in development.
=> FLYlite: Interface & Helper Fields

src/libPMacc/include/fields/tasks/FieldFactory.hpp, src/libPMacc/include/fields/tasks/FieldFactory.tpp, src/libPMacc/include/fields/tasks/TaskFieldReceiveAndInsert.hpp, src/libPMacc/include/fields/tasks/TaskFieldReceiveAndInsertExchange.hpp, src/libPMacc/include/fields/tasks/TaskFieldSend.hpp, src/libPMacc/include/fields/tasks/TaskFieldSendExchange.hpp
- move `fields/tasks` to libPMacc
- change PIConGPU license to libPMacc license for the moved files
This is a cosmetic change to simplify a follow up change that the PIConGPU `FieldTmp` and `FieldJ` used the same kernel to `bash`(copy the border of the simulation area to a exchange buffer) and `insert`(copy exchange buffer to the simulation border).
Short: This will become a generic functionality for a N-dimensional GridBuffer.
- I have only moved the files
- there is no content/formation change beside the license
=> move folder `fields/tasks` to libPMacc

src/picongpu/include/simulation_defines/param/speciesAttributes.param
Follow up to last PR
formatting `speciesAttributes.param` properly as annotated in review.
Didn't want to do it halfway, but commited it as tools.
=> Format speciesAttributes.param

INSTALL.rst, docs/source/install/profile.rst
For the `picongpu.profile` files already listed, note which preparations are necessary to be installed. (See comment in #2093, report in #2092)
In the future #1969, PIConGPU's source will be a module on HPC systems, too. (Alternatively, a `spack install` command or similar.)
=> Profile Preparations

docs/source/models/field_ionization.rst
When I wanted to write the Euler number (*exp(1)*) I wrote `\exp` instead of `mathrm{e}`.
This PR fixes that.
=> Fix typo in ADK documentation

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/ParticlesBase.tpp, src/libPMacc/include/particles/tasks/TaskSendParticlesExchange.hpp
- rename `KernelBashParticles` to `KernelCopyGuardToExchange`
- rename `ParticlesBase::bashParticles` to `ParticlesBase::copyGuardToExchange`
=> lockstep refactoring of `KernelBashParticles`

src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp
- renaming of some variables and types
=> lockstep refactoring of `KernelDeriveParticles`

src/picongpu/include/particles/manipulators/AssignImpl.hpp
add missing check if source and destination particle is valid
- overhead because a non existent particle memory is copied
- particle ids are wasted
As I can see this bug is not producing any invalid memory access.
=> Assign: missing check for valid particles

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.kernel
- move the source code of the functor `KernelShiftParticles` under `KernelFillGaps` 
- remove host side call of `KernelFillGaps` and `KernelFillGapsLastFrame`
- call `KernelFillGaps` on device from `KernelShiftParticles`
- call `KernelFillGapsLastFrame` on device from `KernelFillGaps`
This PR dramatically  reduces the number of kernels called per time step and therefore improves the performance (~2%) and maybe the scaling.
The first commit changes no algorithms, only the source code of the functor `KernelShiftParticles` is moved after `KernelFillGaps`.
The second commit contains all important changes.
=> call `KernelFillGaps*` from device

src/libPMacc/examples/gameOfLife2D/include/Evolution.hpp, src/libPMacc/include/mappings/threads/ThreadCollective.hpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldTmp.kernel, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/bremsstrahlung/Bremsstrahlung.tpp, src/picongpu/include/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, src/picongpu/include/particles/ionization/byField/ADK/ADK_Impl.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp, src/picongpu/include/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, src/picongpu/include/particles/synchrotronPhotons/PhotonCreator.hpp
This pull request move the restriction out of PMacc that `ThreadCollective` must be called with the same number of worker than a supercell contains.
- remove the constructor with the N-dimensional worker index
- rename private type definitions
- update all call to the old constructor
Please check the changes commit wise
=> lockstep refactoring of `ThreadCollective`

src/libPMacc/include/eventSystem/tasks/TaskSetValue.hpp
- change hard coded chunk size to template parameter
The kernel is now longer and is fully rewritten, please take a deeper look to the kernel.
=> lockstep refactoring of `KernelSetValue`

src/picongpu/CMakeLists.txt
Depending on the the configured environment it could be that the linker
crashes. The reason for that is that the static library `picongpu-hostonly`
is not linked against the dependencies.
fix: link `picongpu-hostonly` with all dependencies.
=> fix possible linker error

src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp
=> lockstep refactoring of `KernelMoveAndMarkParticles`

examples/KelvinHelmholtz/include/simulation_defines/param/radiation.param
This pull request fixes a wrong documentation and implementation of the plasma frequency in the default KHI example `radiation.param`. It exists since the *alpha release*. 
This **does not influence** any publication related to the Gorden Bell competition.
It just avoids confusion if the default parameters are used without checking for consistency between `density.param` and `radiation.param`. Now, they are consistent.  
(I thought I fixed this in 2014 - how did it end up here again.)
=> fix plasma frequency and remove German comment

src/picongpu/include/plugins/EnergyFields.hpp
This pull request fixes a wrong MPI reduce in the field energy plugin.
It caused wrong field values (f.e. in TWTS runs)  because the mpi reduce reduces over two `float3_X[2]` instead of over just one `float3_X[2]` (which is equal two 2 `float3_X` - which was probably the intention of the developer).
**Thanks @psychocoderHPC for spotting this!**
Run time test show taht this solves the wrong output we see during TWTS runs. 
(This effects **all** heating tests)
**Effects so far:**
So far this caused mostly some massively increased `Ez` values. 
This **does not** effect the physics - just the output. 
CC-ing: @steindev, @BeyondEspresso
=> fix plugin energy field reduce

src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
This PR replace #2111 and solves the issue by removing dirty detection of a restart by checking the simulation time step.
- PIConGPU: remove magic time step increase to detect restarts
- PMacc (SimulationHelper): use class member `restartRequested` to  detect a restart
Cc-ing: @PrometheusPi, @steindev, @BeyondEspresso
=> fix restart with background fields enabled

src/libPMacc/include/cuSTL/algorithm/mpi/Reduce.hpp, src/libPMacc/include/mappings/threads/ForEachIdx.hpp, src/libPMacc/include/mappings/threads/IdxConfig.hpp, src/libPMacc/include/memory/CtxArray.hpp, src/libPMacc/include/traits/GetNumWorkers.hpp
Fix falsely placed doxygen comments in file headers which show up at unexpected places in the sphinx docs.
=> Doxygen: Fix Headers

examples/Bremsstrahlung/bin/plot_energy_histogram.py, examples/Bremsstrahlung/bin/plot_particle_calorimeter.py, examples/Bremsstrahlung/include/simulation_defines/param/bremsstrahlung.param, examples/Bremsstrahlung/submit/0008gpus.cfg
In the `Bremsstrahlung` example we have typically 100 macro electrons per cell.
Initially the photon weighting was 100 times less than the electron weighting.
This would lead to good photon statistics but created a memory overflow.
Therefore the photon weighting was increased 20 times.
Now the default example runs on k20 in 21 minutes and does not use too much
memory.
The influence of the parameter `WEIGHTING_RATIO` from `bremsstrahlung.param` is two-fold:   
From `Bremsstrahlung.tpp`:   
directly proportional to the **photon emission probability**
```
const float_X emissionProb = photon::WEIGHTING_RATIO * scalingFactor * ionDensity * c * DELTA_T * this->scaledSpectrumFunctor(Ekin, kappa);
```   
inversely proportional to the spawned **photons' weighting**
```
if(this->randomGen() < …
```
=> Reduce # photons in Bremsstrahlung example

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
- add method `setHandleInvalid()`
- add method `isHandleValid()`
- set internal point to non `const` to allow the state change to invalid
This is a pre work to support the new filter functors. The new functor concepts are needed to use the PIConGPU manipulator together with the lock step programming model and alpaka.
=> extend particle handle

src/libPMacc/include/mappings/threads/WorkerCfg.hpp
Add class to combine the compile-time number of workers and the runtime
worker index within one class.
This object allows to pass the number of workers and the worker index by value to a functor without any compile time apply calls. Nevertheless, the number of workers is still a compile time constant and can be used for lockstep programming within a class/functor.
```C++
// device kernel
struct Kernel
{
template< typename T_Functor >
void operator()( Functor & bobDevice )
{
auto bobReturn = bobDevice(
WorkerCfg< numWorker >{ threadIdx.x }
);
}
};
//Host code
HostFunctor bob{ };
PMACC_KERNEL( Kernel )( bob );
```
This class is a part of the new functor/filter concept.
=> add worker config class

src/picongpu/submit/submitAction.sh
Raise a warning in submitAction during `tbg` cfg file evaluation if compilable input files have been modified and seem to be newer then the picongpu binary.
Does not abort or do anything interactive but at least creates awareness. Related to #412
```bash
$ tbg -s qsub -c submit/0008gpus.cfg \
-t submit/hypnos-hzdr/k80_profile.tpl \
/bigdata/hplsim/scratch/huebl/lwfa-dev-017
WARNING: 1 input file(s) in include/
have been modified since the last compile!
Did you forget to recompile?
List of modified files:
/home/huebl/paramSets/lwfa-dev/include/simulation_defines/param/laser.param
1422697.hypnos3
```
=> TBG: Check Modified Input

pic-create
If libraries (or python modules) are present in a simulation's `picongpu/` directory (inside `lib/`), `pic-create` did fail to derive a new input parameter set.
This changes it (only a problem in `dev` since #2058).
Tested on both a creation from an example and a creation from a run simulation's `picongpu/` directory via:
```bash
$ pic-create $PICSRC/examples/LaserWakefield ~/paramSets/lwfa-dev1
$ pic-create /bigdata/hplsim/scratch/huebl/lwfa-dev-018/picongpu ~/paramSets/lwfa-dev2
```
=> pic-create: derived sim lib/

src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
This PR adds intermediate results to the core routines to reduce the computation. The optimizations are copied from the EmZ Esirkepov solver. Currently it is not possible to use a shared version of the Esirkepov core deposition algorithm to both solvers to reduce the code duplication's.
- use the EmZ Esirkepov implementation as base to reorder the Esirkepov code
- use helper variables to avoid multiple calculations of the some value
- add `S1()` helper method
This pull request increase the speed of PIConGPU in the KHI example with positron/ electrons 3D by a factor of 1.05.
I cherry picked this PR for the tests to the branch for the emz paper ( picongpu_0.3.0+#2112), because there I have already all results to validate the solver changes.
=> Esirkepov: reorder code order

src/libPMacc/include/filter/Interface.hpp, src/libPMacc/include/filter/operators/And.hpp, src/libPMacc/include/filter/operators/Or.hpp, src/libPMacc/include/functor/Filtered.hpp, src/libPMacc/include/functor/Interface.hpp
Introduce a generic implementation for a functor. The functor is instantiated on the host side then passed to the kernel and on the device/accelerator a device instance is created.
This workflow allows to pass a generic functor to the device without defining a fixed interface for the `operator()` but keeps the possibility that the user can embed container or other members into the functor even if there is a strong dependency to the accelerator. A example is the random number generator in alpaka, the generator depends on the accelerator but the accelerator is not known before the kernel is executed on the device.
At runtime, the following logic happens, for a binary filtered functor (`PMacc::functor::Filtered`):
- call filter for the two arguments (`PMacc::filter::Interface`)
- combine …
=> add interfaces for functor and filter

src/tools/splash2txt/splash2txt.cpp, src/tools/splash2txt/tools_adios_parallel.cpp, src/tools/splash2txt/tools_splash_parallel.cpp
Keep splash2txt in C++98 so we do not need to artificially push up it's CMakeLists.txt requirements to C++11.
**Or:** also make it require C++11 (the main project that ships it does so anyway). I might prefer the second option (patch below).
Fixes an issue reported in https://github.com/ComputationalRadiationPhysics/picongpu/issues/1984#issuecomment-313293471 (compile fail with, e.g. gcc 4.9 that still defaults to C++98 but supports C++11)
=> splash2txt: C++98

include/picongpu/simulationControl/MySimulation.hpp, include/pmacc/simulationControl/SimulationHelper.hpp
(Trying) to close #2137:
Restart of background fields could cause:
- artificial noise after restart from the outer regions with non-periodic boundary conditions
- if background fields are used (e.g. TWTS pulse)
Simplify the logic of restarting fields:
- do not add the already contained fields in `movingWindowCheck` again
- spares us the substraction we had before
- GUARDS are not part of the checkpoint data, which is cumbersome for the "outer" GUARDS of our global domain
- we need to add the background field ONLY in those to generate a valid restart field
=> Background Fields: Fix Restart GUARD

include/picongpu/simulation_defines/param/fieldBackground.param
This pull request fixes the mixed unit usage of wavelength `period_SI` (in meter) and position `y_SI` (in micro meters) to meter.
With the current setup this would be a period/wavelength of 0.02 nm - which is way below the grid resolution.
=> remove micro meters usage in default background field

README.md
Only show the "latest" (dev) badge for the docs. The latest stable would need to be bumped manually.
Renaming does not work properly, so we keep
- tags
- "latest" (for dev)
as to-be-build versions in RTD
=> Badge: Docs

include/picongpu/ArgsParser.cpp
`--help|-h` should write to stdout when explicitly requested, as it returns with a zero (success) state.
When triggered from invalid arguments, e.g. no arguments, the program-triggered help output stays with write to stderr
=> --help to stdout

.travis.yml, docs/propose_changelog.py, docs/source/models/field_ionization_comparison_c_ii_ionization.py, share/picongpu/examples/Bremsstrahlung/bin/plot_energy_histogram.py, share/picongpu/examples/Bremsstrahlung/bin/plot_particle_calorimeter.py, share/picongpu/examples/ThermalTest/tools/dispersion.py, src/tools/bin/pic2xdmf.py, src/tools/bin/plot_chargeConservation.py, src/tools/bin/plot_chargeConservation_overTime.py, src/tools/bin/printField.py, src/tools/bin/smooth.py, src/tools/share/python/sliceFieldReader.py
Add Python style checks to travis via flake8 tests.
=> Travis: Enforce PEP8

etc/picongpu/hypnos-hzdr/fermi_profile.tpl, etc/picongpu/hypnos-hzdr/k20_autoWait_profile.tpl, etc/picongpu/hypnos-hzdr/k20_profile.tpl, etc/picongpu/hypnos-hzdr/k20_vampir_profile.tpl, etc/picongpu/hypnos-hzdr/k20_wait_profile.tpl, etc/picongpu/hypnos-hzdr/k80_profile.tpl, etc/picongpu/hypnos-hzdr/k80_profileRestart.tpl
Remove the additional pass of `-x LD_LIBRARY_PATH` from the Hypnos `.tpl` files since they are not necessary anymore and caused an ugly:
```
vsetenv LD_LIBRARY_PATH failed
```
in stderr.
RT test was successful.
=> Hypnos: mpiexec LD_LIBRARY_PATH

include/pmacc/eventSystem/tasks/StreamTask.tpp
A pointer to a `EventStream` which is by default nullptr is accessed.
The bug is triggered by [TaskSetValue](https://github.com/ComputationalRadiationPhysics/picongpu/blob/05765f45534c0aa210be4a4f039d54051d6ba09c/include/pmacc/eventSystem/tasks/TaskSetValue.hpp#L233), a event task is created without using a stream. 
The bug is **CRITICAL** because unknown memory addresses are overwritten. I think the bug was only triggered during the initialization of the simulation, each time a species is created.
=> event system: fix illegal memory access

include/pmacc/memory/buffers/HostDeviceBuffer.hpp, include/pmacc/memory/buffers/HostDeviceBuffer.tpp
This pull request avoid type conflicts for the internal defined type `HostBuffer` and `DeviceBuffer` without templates with the corresponding PMacc type with templates. I have seen this issue on my upcoming cupla branch.
- rename internal type `HostBuffer` to `HBuffer`
- rename internal type `DeviceBuffer` to `DBuffer`
=> `HostDeviceBuffer` rename conflicting type defines

docs/TBG_macros.cfg, include/picongpu/ArgsParser.cpp, include/picongpu/CMakeLists.txt, include/picongpu/simulationControl/MySimulation.hpp, include/picongpu/versionFormat.cu, include/picongpu/versionFormat.hpp, share/picongpu/examples/Bremsstrahlung/etc/picongpu/0008gpus.cfg, share/picongpu/examples/Bunch/etc/picongpu/bunch_0032.cfg, share/picongpu/examples/Empty/etc/picongpu/1gpu.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0016gpus.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0001gpus.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0001gpus_isaac.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0008gpus.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0016gpus.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0032gpus.cfg, share/picongpu/examples/SingleParticleTest/etc/picongpu/0001gpu.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/0001gpu.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/0004gpus.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/0008gpus.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/0032gpus.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/0064gpus.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1gpu.cfg, share/picongpu/examples/WeibelTransverse/etc/picongpu/0004gpus.cfg
Supersedes PR #867, Output version information and exit with zero return state.
```bash
$ ./bin/picongpu --version
```
```
PIConGPU: 0.4.0-dev
Build-Type: Release
Third party:
OS:         Linux-4.4.0-38-generic
arch:       x86_64
CXX:        GNU (4.9.2)
CMake:      3.7.2 (Unix Makefiles)
CUDA:       8000
mallocMC:   2.2.0
Boost:      106200
MPI:        
standard: 3.0
flavor:   OpenMPI (1.8.6)
PNGwriter:  0.5.6
libSplash:  1.6.0 (Format 4.0)
ADIOS:      1.10.0
```
(returns with 0 exit status)
```bash
$ mpirun -n 2 ./bin/picongpu --versionOnce -g 64 32 32 --periodic 1 1 1 -d 2 1 1 -s 10
```
```
PIConGPU: 0.4.0-dev
Build-Type: Release
Third party:
OS:         Linux-4.4.0-38-generic
arch:       x86_64
CXX:        GNU (4.9.2)
CMake:      3.7.2 (Unix Makefiles)
CUDA:       8000
mallocMC: …
```
=> picongpu --version

include/picongpu/fields/FieldManipulator.hpp, include/picongpu/fields/FieldManipulator.kernel
- remove usage of the define `SIMDIM` to controll the algorithm
=> lockstep refactoring `KernelAbsorbBorder`

src/tools/png2gas/png2gas.cpp
Close #2159: Keep `png2gas` in C++98 so we do not need to artificially push up it's `CMakeLists.txt` requirements to C++11.
=> png2gas: C++98

etc/picongpu/hypnos-hzdr/picongpu.profile.example
PNGwriter 0.6.0 is now available on Hypnos (HZDR). Using it by default adds some performance improvements for PIConGPU and fulfills the requirement of the png2gas tool.
=> Hypnos: PNGwriter 0.6.0

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/taurus-tud/picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example, include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/pmacc/examples/gameOfLife2D/CMakeLists.txt
Prepares the Boost 1.62.0+ dependency pulled in by alpaka.
Taurus (ZIH) support was informed about our request for newer boost 1.62.0 version with gcc 5.3
=> Boost 1.62.0

docs/source/usage/plugins/radiation.rst, test/hasNonASCII
Remove latex unexpected character so sphinx pdf builds.
Also fix a typo in the nonACII test:
- fix typo in selection of .py files
=> Sphinx: PDF Radiation 

USAGE.rst, etc/picongpu/titan-ornl/picongpu.profile.example, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
`pic-configure [-a|--arch]` has the new syntax `backend:architecture`
Add instructions how to compile for CPU to our basic usage sections.
=> Doc: CPU Compile

buildsystem/CompileSuite/path.sh, pic-compile
fix an internal typo in the path helpers of our compile scripts.
=> pic-compile: fix internal typo

etc/picongpu/hypnos-hzdr/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/taurus-tud/Slurm_Tutorial.rst, etc/picongpu/taurus-tud/picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example, share/picongpu/dockerfiles/ubuntu-1604/picongpu.profile
Generally, prefer this style in call bash scripts.
It can be:
- nested,
- is a tiny bit more portable and
- is not prune to be [mismatched with '](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1984#issuecomment-321235872)
and has no difference in meaning.
For more information, see e.g.
https://github.com/azet/community_bash_style_guide#common-mistakes-and-useful-tricks
=> Bash Subshells: `cmd` to $(cmd)

include/picongpu/plugins/PluginController.hpp
Already runs on CPU, does not need to be disabled.
=> CPU Plugin: Enable Count Particles

include/pmacc/algorithms/math.hpp, include/pmacc/algorithms/math/defines/bessel.hpp, include/pmacc/algorithms/math/doubleMath/bessel.tpp, include/pmacc/algorithms/math/floatMath/bessel.tpp
This pull request adds Bessel-functions from the `CUDA` and `BOOST` libraries to the `PMACC` math implementation. Up to now, there have been no extensive tests, but it seems to compile fine so far.
This contribution does not have any special priority. So, please have a look at the code and give feedback at your leisure. :smiley:
=> Add Bessel functions to math library

INSTALL.rst, include/picongpu/CMakeLists.txt
The Boost.threads library pulls in `date_time` and `chrono` as additional dependencies that need a compile.
```bash
$ grep -iR "_Boost_THREAD_DEPENDENCIES" /usr/share/cmake-3.7/Modules/FindBoost.cmake
set(_Boost_THREAD_DEPENDENCIES date_time)
[...]
set(_Boost_THREAD_DEPENDENCIES chrono system date_time)
set(_Boost_THREAD_DEPENDENCIES chrono system date_time atomic)
[...]
```
Since the boost transient dependencies are updated via a manual list currently, we explicitly request all transient libraries for now (instead of letting the cmake script find and add them). This helps users with a newer boost version but an older CMake that does not know the latest boost releases (yet).
=> Boost Transient Deps: date_time, chrono, atomic

INSTALL.rst
With alpaka/cupla, CUDA is now an optional dependency.
Also includes minor clean-ups and puts OpenMPI 1.7+ as the requirement for support since it's the first OpenMPI with GPU awareness support.
=> Install Docs: CUDA is optional

include/pmacc/PMaccConfig.cmake
Forward additional third-party libraries. Alpaka might pull further libraries from `Boost.fiber` or any other backend, that are not used directly in the final (PIConGPU) target(s).
=> PMacc: Forward cupla/alpaka Libs

src/mpiInfo/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/png2gas/png2gas.cpp, src/tools/splash2txt/CMakeLists.txt, src/tools/splash2txt/splash2txt.cpp, src/tools/splash2txt/tools_adios_parallel.cpp, src/tools/splash2txt/tools_splash_parallel.cpp
Close #2188: for building against a common set of C++ dependencies, it is easier to always depend on the same language version (C++11 right now) to avoid requiring that all dependencies are build with C++98/C++11 ABI compatibility.
=> Tools: All C++11

docs/logo/pic_logo.svg
Adds more platforms to the PIConGPU logo.
If cone saves them as individual images and runs something like
```bash
convert -delay 8 pic_logo_{gpu,gpu,ppc,ppc,cpu,cpu,phi,phi,arm,arm,gpu}.png -morph 30 pic_logo.gif
```
one gets a beautiful gif such as 
(change commited as "tools" author)
=> PIConGPU Logo: More Platforms

CONTRIBUTING.md, INSTALL.rst, docs/source/install/compile.rst, docs/source/postprocessing/python.rst, docs/source/usage/plugins/radiation.rst, share/picongpu/examples/Bremsstrahlung/README.rst, share/picongpu/examples/Bunch/README.rst
Fix all broken links in the sphinx docs. Found via `make linkcheck` and fixed manually.
Upgraded to https where appropriate and redirected.
=> Docs: Fix broken links

include/pmacc/test/particles/IdProvider.hpp
Related to #2202
Add missing `HDINLINE` on CUDA backend.
```bash
cmake -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON /bigdata/hplsim/development/huebl/picsrc/include/pmacc/
```
=> PMacc: Fix IdProvider Test

include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, src/mpiInfo/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
Use imported targets for Zlib and Boost. This makes linking with existing libraries in system paths more robust, e.g. on centos, and spares the need to add include paths.
Do not add math on windows machines.
With our CMake requirement (version) we can rely on targets for all dependencies.
All dependencies, but Boost, where we need a fallback:
> Since the boost transient dependencies are updated via a manual list currently, we explicitly request all transient libraries for now (instead of letting the cmake script find and add them). This helps users with a newer boost version but an older CMake that does not know the latest boost releases (yet).
Since boost targets are not available in the same situation either, we add the `include_directories` + `${Boost_LIBRARIES}` fallbacks until boost …
=> CMake: Use Imported Targets Zlib, Boost

USAGE.rst, pic-build, pic-configure, pic-create
Just run `pic-build` inside a input directory.
This updates the binaries for a `tbg` call with the latest options in an input's param sets.
Just short-hand for
```bash
mkdir .build
cd .build
pic-configure ..
make -j install
cd -
```
Avoids confusion for users that are not used to out-of-source builds.
cc'ing @ComputationalRadiationPhysics/picls-developer @ComputationalRadiationPhysics/picls-maintainer please provide feedback and give this new tool in `dev` a try! You will never have to switch directories during input design again 💃
=> New Tool: pic-build

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/picongpu.profile
Updates the following points in our `Dockerfile`:
- `spack purge` was merged into `spack clean`
- instead of `module load` we can use `spack load` for easier selection syntax of specs
=> Docker Update: spack clean & load

.travis.yml
- install dependencies (CPU-only) via spack
- build tests with gcc 4.9.4
Besides a first build-up of the cache (~20min *once*! only 56MB cache!), the `make` of the PMacc unit tests runs quickly. This ensures the tests are not going to be outdated and will always build.
For a RT `make test`, the tests' footprint might be reduced a bit first (maybe to 1 GB mem consumption and <20sec per test).
Actually installing cupla can also save some double-builds.
=> Travis: Test PMacc Unit Tests

etc/picongpu/taurus-tud/picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example
Updates for `dev` for running on Titan and Taurus.
note: picongpu builds now officially *too long* to not be killed by the watchdog daemon of Taurus' head nodes.
=> Profiles for Titan & Taurus

src/tools/bin/tbg
`-h|--help` should exit with zero return code.
=> tbg: --help exit 0

include/picongpu/particles/densityProfiles/GaussianImpl.hpp
Fix wrong parameter usage in `Gaussian` density profile:
Instead of `gasSigmaRight` the `gasCenterRight` parameter was taken for the scale-length of the downramp.
Bug since the 0.2.x release series: 7b451c01304a228895d00fbe27507859c1e93569
=> Density: Param Gaussian Density

docs/source/dev/repostructure.rst, docs/source/index.rst
Documents the file structure in the repo as initially described in #1968.
=> Docs: Repo Structure

include/picongpu/particles/manipulators/generic/Free.hpp, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/startPosition/generic/Free.hpp, include/picongpu/particles/startPosition/generic/FreeRng.hpp, include/pmacc/functor/Filtered.hpp, include/pmacc/functor/Interface.hpp
fix #2215
`reinterpret_cast` is used to down cast a class. This is wrong and leads to wrong (not illegal) memory access within the class to the member's.
`static_cast` is used to solve the issue.
The bug was introduced with #2117, #2125 and #2168. 
The result of the bug is that the values within the member's of a class can be wrong, this can result in illegal memory access if the member is an offset within an array or in bad random number as in #2215.
=> fix class down cast

include/picongpu/particles/ParticlesInit.kernel
The position functor in `KernelFillGridWithParticles` is not correctly initialized therefore the random numbers between different cells within a supercell are correlated.
The bug is only triggered if the CPU backend `omp2b` is used. 
The bug was introduced with #2168.
- use virtual thread linear idx to initialize the position functor
=> fix random start for CPU back-end

include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/output/images/Visualisation.hpp
- activate PngPlugin for CPU accelerator `omp2b`
- remove some precompiler usage with runtime/compile time constructs
=> lockstep kernel refactoring `Visualisation.hpp`

include/pmacc/particles/memory/boxes/ParticlesBox.hpp
fix #2228
The function `setAsLAstFrame()` must be atomic between different grids.
With #2178 [this line](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2178/files#diff-82ce98f3d12c8577e81d5cc7c1a6245cR285) the function was wrongly changed to be atomic only between threads within a block.
- use `::alpaka::hierarchy::Threads{}` to `::alpaka::hierarchy::Grids{}`
=> fix `ParticlesBox::setAsLastFrame()`

include/picongpu/particles/ParticlesInit.kernel
use fast `atomicAllExch` instead of slow `atomicExch`
All threads within the kernel reducing it's value to the same pointer, tehrefore the faster version of `atomicExch` can be used.
=> use fast `atomicAllExch` in `KernelFillGridWithParticles`

include/picongpu/particles/flylite/helperFields/LocalEnergyHistogram.kernel
The shared memory histogram is reduced with the hierarchy `Threads`
to the global memory. This will produce raceconditions between blocks of a grid.
- use hierarchy `Blocks` instead of `Threads`
This bug was introduced with #2178.
=> fix wrong used hierarchy for atomic operation

include/pmacc/particles/ParticlesBase.kernel, include/pmacc/particles/memory/boxes/ExchangePushDataBox.hpp, include/pmacc/particles/memory/boxes/PushDataBox.hpp
- allow the user to control the hierarchy of the atomics for
- `PushDataBix`
- `ExchangePushDataBox`
- `KernelCopyGuardToExchange`: pass hierarchy to `pushN()` to controll the level for the atomic function.
This commit fix also the wrong used hierarchy in the method `push()` which was intruduced with #2178. This method is currently not used within PMacc therefore it not effects PIConGPU.
=> refactor `PushDataBox` and `ExchangePushDataBox`

include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/WriteSpecies.hpp
- disable usage of `MallocMCBuffer` if accelerator `omp2b` is used
- with `omp2b`: access the device memory directly without copying particles before to host
=> ADIOS: allow usage with accelerator `omp2b`

include/picongpu/plugins/PluginController.hpp
- move comma into the pre compiler guards
Bug was introduced with #2236 and is triggered if adios is not available.
=> fix comma in `PluginController`

include/pmacc/cuSTL/algorithm/kernel/Foreach.hpp, include/pmacc/cuSTL/algorithm/kernel/detail/ForeachKernel.hpp
- add functor `ForeachLockstep` to start a cuSTL functor which is lockstep ready
This functor is only a workaround up to all cuSTL functors are refactored and are lockstep ready.
=> cuSTL `Foreach` with lockstep support

pic-build, pic-configure, pic-create
This fixed the bug reported in issue #2221.
Allows to call the scripts `pic-create`, `pic-build`, `pic-configure` even with relative paths to the scripts instead of relying on the `$PATH` environment var.
=> Tools: Allow Call With Relative Path

INSTALL.rst, include/picongpu/CMakeLists.txt, include/picongpu/plugins/output/images/PngCreator.hpp
Close #2196
Remove the direct Boost.Thread dependency of PIConGPU. In its default configuration, we now require less transient non-headeronly libraries from Boost.
Note: the alpaka fiber backend pulls in context & thread and with them chrono, date_time and atomic again, if enabled.
=> Png Plugin: Boost to std Thread

docs/source/install/profile.rst, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example
Add a profile example per queue for Hypnos (HZDR) and Taurus (TU Dresden).
Allows to optimize the compile for the exact right architecture by default and cleans up confusion, e.g. for upcoming KNL profiles, and requires less user interaction.
=> Hypnos & Taurus: Profile Examples Per Queue

USAGE.rst
Document the `-march` for [GCC for the KNL](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html).
This is currently the only backend, but will probably be fine-tuned or replaced with an other backend soon (see #2210). Related to #2251.
=> Docs: Document KNL GCC -march

pic-configure
sets the default backend in `pic-configure` (and `pic-build`, `pic-compile`) to `cuda` with the currently selected default SM architecture from CMake (currently `sm_20`).
=> pic-configure: default backend CUDA

include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp, include/picongpu/particles/bremsstrahlung/Bremsstrahlung.tpp, include/picongpu/particles/creation/creation.hpp, include/picongpu/particles/creation/creation.kernel, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/AlgorithmADK.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSI.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSIEffectiveZ.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSIStarkShifted.hpp, include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp, include/picongpu/particles/ionization/byField/Keldysh/AlgorithmKeldysh.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/picongpu/simulation_defines/_defaultUnitless.loader, include/picongpu/simulation_defines/param/speciesDefinition.param, include/picongpu/simulation_defines/unitless/speciesDefinition.unitless
- remove define which disabled the ionization code on CPU
- use new functor interface with `collectiveInit`
- use a source frame for each worker (instead of all worker in the block)
- extend interface of all functors used together with `CreateParticlesKernel` (add method `collectiveInit()`)
Please check the changes commit wise!
=> enable ionization for CPU backend

docs/source/usage/param.rst, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example, etc/picongpu/titan-ornl/pythonOnRhea.profile.example, pic-create, pic-edit, share/picongpu/dockerfiles/ubuntu-1604/picongpu.profile
For easier forward-compatibility, we should not fill-up all default `.param` and `.unitless` files during pic-create. This also makes version control of input easier.
Our defaults are sane (basic PIC cycle without any density or lasers) for a PIC simulation and will only cause unnecessary conflicts when the defaults change.
Instead, we can clone only the files that are changed in input on `pic-create` and add the others automatically when needed.
The workflow possible with `pic-edit` editing `.param` files is:
```bash
pic-create $PICSRC/share/picongpu/LaserWakefield lwfa
cd lwfa
pic-edit grid laser isaac
pic-build
nano etc/picongpu/0001gpus.cfg
tbg ...
```
This also solves the issue of telling users "where to get additional files from" when they change inputs, because they do not need to …
=> New Tool: pic-edit

include/picongpu/CMakeLists.txt, include/picongpu/plugins/common/particlePatches.hpp, include/picongpu/plugins/hdf5/openPMD/patchReader.cpp
The PIConGPU CmakeLists.txt is separating host only and accelerator source files.
In the current implementation the host only and accelarator code is compiled twice (with host and device compiler).
The result of this bug is that compiling takes up to a factor of two longer than needed and all symboles are defined twice which can lead in linker issues.
This bug was introduced with #2178.
Fix: compile `main.cpp` with the device compiler and all other files with the host compiler
=> Inefficient CMake Compile

docs/source/index.rst, docs/source/install/instructions.rst, docs/source/install/instructions/docker.rst, docs/source/install/instructions/source.rst, docs/source/install/instructions/spack.rst, docs/source/install/path.rst
Streamlines the install instructions.
Organizes the install instructions to make them more clear.
Also adresses commonly seen user problems:
- only select *one* install path
- remove confusing recommendations for systems
- prefer [spack](https://github.com/LLNL/spack) over self-build in order of appearance
=> Docs: Streamline Install

src/tools/bin/tbg
quick fix for #2261: ignore the TERMCAP variable.
the underlying problem, which char in the variable is problematic with our processing, is not clear yet.
**update**:
replace the three special chars
- /
- \
- &
with proper escaping in environment vars before parsing.
Found from
https://stackoverflow.com/a/2705678/2719194
plus two extra `\\` for ... reasons. (Probably we strip the escapes by one level again in the `sed` processing below it)
=> tbg env variables escape \ and &

lib/python/picongpu/plugins/radiation.py, src/tools/bin/smooth.py
This pull request  solves issue #2264.
With #2028 there were several strings separated to make their length agree with PEP8. Due to this several formatting processes were broken. 
This pull request fixes these where it is necessary.
=> Radiation: fix wrong python formatting

include/picongpu/algorithms/FieldToParticleInterpolation.hpp, include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, include/picongpu/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp, include/picongpu/fields/currentDeposition/ZigZag/ZigZag.hpp, include/pmacc/math/vector/compile-time/Vector.hpp
- PIConGPU: add static assert to check if a stencil fits into a supercell
- PMacc: add specialization to get the minimum component of a compile time vector
=> check cells needed for stencils

share/picongpu/examples/FoilLCT/bin/plot_charge_density.py
Add a plot script to benchmark the ionization physics in the FoilLCT example.
Useful to compare various runs against each other, e.g.
- with different ionizers
- with different backends
We used a prototype of this script already in the last pull requests for verification.
Example usage:
```bash
plot_electron_density.py /bigdata/hplsim/scratch/widera/buildPIC/foil/runs/{012_k80_doubleFlush,013_laser_doubleFlush}
```
```bash
plot_electron_density.py /bigdata/hplsim/scratch/widera/buildPIC/foil/runs/{012_k80_doubleFlush,013_laser_doubleFlush} --step 1000 --sum
```
Tested with Python 2.7 and 3.5
=> FoilLCT: Plot Densities

etc/picongpu/cpuNumaStarter.sh
cpuNumaStarter always uses all hardware threads of a core, but depending on the
architecture this might not be what the user wants. Using more hardware threads
enables more independend register sets, but reduces the L1 cache per thread,
which might decrease performance.
The number of threads use from OpenMP is now calculated from the number of
cores per numa node and the number of hardware threads which shall be used.
If this number is not set, it is preset to the total amout of hardware threads
establishing the same behaviour as before.
I tested the script on the laser node of hypnos where it showed the same behaviour as before and on the KNLs of taurus where I were able to reduce the used hardware threads per core to achieve a better performance (factor 3!)
=> Improved the cpuNumaStarter.sh script to support not using all hw threads

src/tools/bin/tbg
This change provides the option to force tbg to accept an already existing directory for a new job. This is useful when tbg is used in other workflows, where tbg is only used to submit the job, but the working directory is prepared by the workflow prior to the invocation of tbg.
The changed code also produces a warning when the '-f' option causes tbg to actually use an existing folder.
=> tbg: Add -f | --force

USAGE.rst
Fix the moved example path for the `pic-create` introduction.
=> Docs: Fix Example Path

docs/source/postprocessing/python.rst
yt 3.4 has been released, adjust docs and some internal openPMD links.
@ComputationalRadiationPhysics/picongpu-developers let's give it a swing! :)
http://yt-project.org/doc/
https://gist.github.com/C0nsultant/5808d5f61b271b8f969d5c09f5ca91dc
[*Soon:*](https://github.com/LLNL/spack/pull/3498#issuecomment-330871973)
```bash
spack install py-yt
```
=> Docs: Python yt 3.4

include/picongpu/particles/creation/creation.kernel
Avoid that electrons are created within two independent steps.
This will increase the concurrency and increase the bandwidth utilization.
=> ionization: speedup particle creation

include/pmacc/memory/buffers/DeviceBuffer.hpp, include/pmacc/memory/buffers/HostBuffer.hpp
allow usage of cuSTL `container::CartBuffer` with CPU back-end
This feature was disabled for the CPU back-end with #2178 to avoid side effects during the porting.
=> enable cuSTL CartBuffer on CPU

etc/picongpu/cpuNumaStarter.sh
Intel MPI does not define $OMPI_COMM_WORLD_LOCAL_RANK, so we need
to check for $PMI_RANK instead.
=> Fixed cpuNumaStarter for Intel MPI

LICENSE.md, docs/source/conf.py
Update the documentation about used licenses to reflect recent changes in the code structure. Also adds infos on alpaka & cupla.
Also adds:
- PMacc: technically LGPLv3+ (which has a GPL fallback already)
- docs: from now on CC-BY 4.0 for images and texts
@ComputationalRadiationPhysics/picongpu-maintainers @ComputationalRadiationPhysics/picongpu-developers This PR proposes to make our manual/documentation/images in `docs/` licensed under a permissive open access license, the [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/), by default. The CC-BY license is the recommended license for open access publishing in Helmholtz and more suited to texts and images then the code licenses we have for the rest of the project. Do you agree to this change?
cc @PrometheusPi @n01r @psychocoderHPC …
=> License Docs: Update

include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/picongpu/simulation_defines/_defaultParam.loader, include/picongpu/simulation_defines/_defaultUnitless.loader
allow using synchrotron solver with the CPU back-end
I can't verify the solver because we have no useful preset to verify the correctness #2283
=> activate synchrotron for CPU back-end

include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, src/mpiInfo/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
It turns out, the `Boost::boost` target for the header only libraries is always available, even if the other targets are not, e.g. due to a newer boost version which leads to a `_Boost_IMPORTED_TARGETS FALSE`.
This fixes the detection properly in such a case by testing for the first (or any) of the oder requested targets instead.
=> CMake: Boost Target Check

include/picongpu/particles/shapes/CIC.hpp, include/picongpu/particles/shapes/P4S.hpp, include/picongpu/particles/shapes/PCS.hpp, include/picongpu/particles/shapes/TSC.hpp
Optimize the implementation of the particle shapes to help the compiler
to create optimized vector code.
Use easy if patterns to give the compiler the freedom to transform the if statements.
Currently we using something like arithmetic ifs to avoid branch differences during the particle shape evaluation. This will force the compiler to calculate all branches of the if. By refactoring the if conditions we can help the compiler to optimize the code much better. That allows the compiler to use masked assignments, to use branch differences or any other architecture specific optimizations.
thx to INTEL(R) for the [A Guide to
Vectorization with
Intel® C++ Compilers](https://d3f8ykwhia686p.cloudfront.net/1live/intel/CompilerAutovectorizationGuide.pdf)
=> optimize particle shape implementation

src/mpiInfo/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
Introduce the same minimal boost version as a requirement for tools as we use for the main project.
Helps a little to avoid picking up parallel installs of (system) boost versions, which are usually older.
=> CMake: Same Boost Min for Tools

include/picongpu/particles/startPosition/detail/WeightMacroParticles.hpp
Remove loop to calculate number of particles per cell with respect to `MIN_WEIGHTING`.
This improves the speed for the initialization of heterogeneous gas profiles e.g. laser wake field.
thx @wmles for pointing me to it
=> improve speed to calculate number of ppc

etc/picongpu/bash/mpiexec.tpl, etc/picongpu/bash/mpirun.tpl, etc/picongpu/hydra-hzdr/default.tpl, etc/picongpu/hypnos-hzdr/fermi.tpl, etc/picongpu/hypnos-hzdr/k20.tpl, etc/picongpu/hypnos-hzdr/k20_autoWait.tpl, etc/picongpu/hypnos-hzdr/k20_vampir.tpl, etc/picongpu/hypnos-hzdr/k20_wait.tpl, etc/picongpu/hypnos-hzdr/k80.tpl, etc/picongpu/hypnos-hzdr/k80_restart.tpl, etc/picongpu/hypnos-hzdr/laser.tpl
fixes the killall cleanup on HZDR queues so we do not get a verbose mpi message in case everything was ok (which leaves "killall" to fail).
on interactive "bash" execution, the killall is not necessary and removed. Also renamed the files to avoid duplication of "bash".
=> HZDR tpl: killall return

include/pmacc/PMaccConfig.cmake, pic-configure
Re-implementation of #2279 in pure CMake.
Easier to maintain a [list of compilers](https://cmake.org/cmake/help/v3.9/variable/CMAKE_LANG_COMPILER_ID.html) in one place and CXX+CXXFLAGS will always match.
Set the CPU architecture via `PMACC_CPU_ARCH`. Defaults to an environment variable of the same name. Only set if the (host) compiler is known, otherwise use CXXFLAGS if you experiment with more compilers.
Only set as a convinient setter for the user instead of going directly to CXXFLAGS as the user. Helpful in commands such as `pic-configure` to avoid building a compiler lookup list therein.
For a CUDA backend user, that still wants to set the CPU arch properly, this can be done with `-DPMACC_CPU_ARCH` (`pic-configure -c` or `ccmake`) or `export PMACC_CPU_ARCH`. For CPU backends, it is …
=> PMacc: Set CPU Architecture

etc/picongpu/taurus-tud/knl.tpl, etc/picongpu/taurus-tud/knl_picongpu.profile.example
The knl.tpl uses the new useHardwareThreadsPerCore feature of
PR https://github.com/ComputationalRadiationPhysics/picongpu/pull/2269
to set the number of used hardware threads per core to 1 at default.
Related to issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/2210
=> Added an example profile and tpl file for taurus' KNL

share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particle.param
Fix a missing constexpr in `particle.param`. Did fail to build on CPU builds (compile suite tests CUDA builds). Found last week with @psychocoderHPC 
Note: already exists in `0.3.0` but due to CUDA only, this is not problematic therein. Still, we can fix it there as well.
=> KHI: Fix Build

docs/source/install/profile.rst, etc/picongpu/pizdaint-cscs/picongpu.profile.example
Update to the latest modules and add libSplash for HDF5 support.
I drafted a very specific, quickly outdated, hands on install description in
https://gist.github.com/ax3l/68cb4caa597df3def9b01640959ea56b
which just summarizes what is already [in the manual](https://picongpu.readthedocs.io/en/latest/install/profile.html#piz-daint-cscs).
ccing @HighIander @BeyondEspresso
=> PizDaint (CSCS): Update Profiles

include/picongpu/fields/FieldE.tpp, include/picongpu/fields/laserProfiles/laserGaussianBeam.hpp, include/picongpu/simulationControl/MySimulation.hpp
Fix dead code and unused variables in scenarios such as:
- no laser or
- CPU only
found with clang-tidy, fixed manually.
=> Fix Dead Code

src/tools/bin/pic2xdmf.py
Fix the particle offset naming since the introduction of openPMD and fix missing `.format()` replacements with multi-line strings.
The latter issue was introduces with #2145, the former with release `0.2.0`.
=> XDMF Scripts: Fix Replacements & Offset

lib/python/picongpu/input/parameters.py, share/picongpu/examples/LaserWakefield/lib/python/picongpu/params.py
Just minor fixes of typos in documentation of parameter classes and the parameter range of Wave_Length_SI parameter of the LaserWakefield example.
=> Fixes for python parameters 

pic-compile, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/memory.param
Since #2243 the cmakeFlags file for examples without user params is removed.
`pic-compile` used the wrong default value and assumed that `cmakeFlags` is always setting the correct number of test cases within an example.
- fix pic-compile
- `WeibelTransverse` test: add `DefaultExchangeMemCfg` to `memory.param`
=> pic-compile: make cmakeFlags optional

include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.kernel, include/picongpu/particles/Particles.tpp, include/picongpu/particles/pusher/particlePusherAxel.hpp, include/picongpu/particles/pusher/particlePusherBoris.hpp, include/picongpu/particles/pusher/particlePusherFree.hpp, include/picongpu/particles/pusher/particlePusherPhoton.hpp, include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp, include/picongpu/particles/pusher/particlePusherVay.hpp
Forward the current step for the species update through `KernelMoveAndMarkParticles` and `PushParticlePerFrame` to the particle pushers.
- in most pushers, a useless parameter for the current time step will be moved to the device on kernel start (latency that can be hidden)
- according to k3diff, the unused parameter was optimized out by the compiler (tested with CUDA 8) and no additional registers or cmem is used compared to the current `dev`
[compile_dev.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/1402600/compile_dev.txt)
[compile_PR.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/1402601/compile_PR.txt)
cc @steindev @PrometheusPi
=> Push with currentStep

include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp
fix #2307
`CalorimeterFunctor`: set pitch size to zero to initilize the BufferCursor
I can't reproduce #2307 but this PR should fix it
=> fix usage of uninitialized variable

docs/source/install/profile.rst, etc/picongpu/draco-mpcdf/general.tpl, etc/picongpu/draco-mpcdf/picongpu.profile.example
Adds a `picongpu.profile.example` for the Draco cluster at MPCDF.
=> Profile: Draco (MPCDF)

include/picongpu/plugins/IsaacPlugin.hpp
On nodes with more than one GPU, the isaac plugin did always
use the first device, which resulted in "all CUDA-capable devices are
busy or unavailable" errors.
=> Isaac plugin using current device instead of the first device

share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/memory.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/fileOutput.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/memory.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/unitless/starter.unitless, share/picongpu/examples/WarmCopper/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/memory.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/speciesInitialization.param
replace `typedef` in examples with modern C++11 `using`. Commited as tools user.
Also added missing `typenames` where `::types` are taken from templated classes.
=> Examples: C++11 Using for Typedef

pic-configure
Cleanly abort if `cmakeFlags` exist but could not be successfully executed. Error will properly be forwarded to `pic-build`.
This can e.g. happen due to
- a wrongly selected case
- a newly created file with missing +x rights
Example (return-code 4):
```bash
$ pic-build
build directory: .build
/home/axel/src/picongpu/pic-configure: line 136: ../cmakeFlags: Permission denied
ERROR: Executing '../cmakeFlags' failed!
Is the file executable? (chmod u+x cmakeFlags)
```
first noted by @n01r
=> pic-configure: cmakeFlags return code

share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/laser.param
restore the default laser strength of 8.0 in the LWFA example. Follow-up to the unintentional change introduced in #2289.
ccing @codingS3b @theZiz
=> LWFA Example: Restore a0=8.0

INSTALL.rst, USAGE.rst, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example
Add a default installed `PIC_EXAMPLES` environment variable that eases to create new input from examples without struggling with long paths.
Also clean up header of profile examples on the way to be more intuitive:
- profile path first (sensitive to some system's module loads)
- name and mail notifications
- optional: computing project on some clusters
- optional: editor
- then all things that the user does not change in normal operation:
- modules
- required environment vars
- defaults in batch system of this file
Also added to [spack package](https://github.com/ComputationalRadiationPhysics/spack-repo) (https://github.com/ComputationalRadiationPhysics/spack-repo/commit/9c05bba8158a31f3f7f233be634345c4cb37fd54) and will be available to users also in simplified docker file #2286.
=> Doc: $PIC_EXAMPLES

include/pmacc/nvidia/atomic.hpp, include/pmacc/nvidia/warp.hpp
With CUDA9 the function `__shfl` should not be used anymore, instead function `__shfl_sync` should be used.
- use `__shfl_sync` with CUDA9
- add parameter `laneMask` to `warpBroadcast`
- add documentation to `warpBroadcastwarpBroadcast`
This PR removes the CUDA9 warning `cuda_9_0/include/sm_30_intrinsics.hpp(152): here was declared deprecated ("__shfl() is not valid on compute_70 and above, and should be replaced with __shfl_sync().To continue using __shfl(), specify virtual architecture compute_60 when targe`
=> add support for CUDA9 `__shfl_snyc`

include/picongpu/fields/background/cellwiseOperation.hpp, include/picongpu/simulationControl/MySimulation.hpp
fix #943
If field background is used than the border regions will be wrong.
The field background current is operationg on the local domain regions
`CORE + BORDER + GUARD`. The current is than scattered to the neighboring GPUs
and will create wrong border regions.
- operate background field current only on the region `CORE + BORDER`
- fix `cellwiseOperation` - index passed to the user functor was only correct if `CORE+GUARD + BORDER` was manipulated
With this fix current smoothing is still possible. **Attention** FieldJ is not part of the checkpointing #2325
~~do not merge, there is a wrong index calculation in `cellwiseOperation.hpp`~~
CC-ing: @steindev
=> Wrong border with current background field

include/picongpu/versionFormat.cpp
The version of CUDA is not printed.
- add CUDA9 support by removing the usage of `CUDA_VERSION`
- use `__CUDACC_VER_MAJOR__` to detect CUDA to avoid the usage of alpaka and/or picongpu includes
bug introduced with #2178
=> fix: CUDA verison not printed with `--version`

include/pmacc/PMaccConfig.cmake
Replace missing `PMACC_CUDA_COMPILER` with `ALPAKA_CUDA_COMPILER`.
The work-around was added in #2076 but the controlling var vanished during the marriage with alpaka in #2178 (https://github.com/ComputationalRadiationPhysics/picongpu/commit/0cc58f6443d15ed36aeb1a2fd9d9399ae0aed647#diff-d1fb8e3eeab4d2001da0932360713480).
Boost report: https://svn.boost.org/trac10/ticket/13049
Add missing work-around status' message to `PMaccConfig.cmake` when enabled.
=> CMake: Re-Enable Boost 1.64.0 + NVCC 8.0 Work-Around

include/picongpu/algorithms/DifferenceToLower.hpp, include/picongpu/algorithms/DifferenceToUpper.hpp, include/picongpu/fields/currentInterpolation/NoneDS/NoneDS.hpp, include/picongpu/fields/numericalCellTypes/EMFCenteredCell.hpp, include/picongpu/fields/numericalCellTypes/YeeCell.hpp
Fixes clang(-tidy) errors of the kind [clang-diagnostic-error]:
"default initialization of an object of const type '...' without a user-provided default constructor":
First approach before discussion:
```C++
const typename Difference::template GetDifference<0> Dx;
// to
const typename Difference::template GetDifference<0> Dx{};
```
Final approach: add explicit constructors to POD classes that are used as `const`:
```C++
struct GetDifference
{
static constexpr uint32_t direction = T_direction;
HDINLINE GetDifference()
{
}
// ...
};
```
=> Const POD Default Constructor

include/pmacc/math/Complex.hpp, include/pmacc/math/complex/Bessel.hpp, include/pmacc/math/complex/Bessel.tpp
Here we implement support of complex BesselJ0 and BesselJ1 functions. Runtime tests are still required, but feedback on the code is greatly appreciated.
=> Complex BesselJ0 and BesselJ1 functions

.travis.yml
Use [build stages](https://docs.travis-ci.com/user/build-stages/) for individual steps of the tests. Each stage is an independent job that does not share artifacts but will only run if the previous stages were successful.
- add clang-3.9 unit testing for PMacc.
- add flake8 test in both Python 2.7 & 3.6
- upcoming `clang-tidy` #2303, `clang-check` and `clang-format` tests
=> Travis: Stages

include/picongpu/fields/FieldE.tpp
Fix again the `warning: dynamic initialization in unreachable code` in FieldE laser init by restructuring the logic and adding an if instead of an early return. Also makes the criteria more self-describing. Follow-up to #2301.
=> FieldE: Fix Unreachable Code Warning

docs/source/install/profile.rst
Add notes on how to build ADIOS on Piz Daint (CSCS).
For both of your computing times, I also added a super-automated quick-start script here:
https://gist.github.com/ax3l/68cb4caa597df3def9b01640959ea56b
This is a temporary solution and will be quickly outdated. But that is ok due to the high importance of our current allocations.
Please make sure to adjust the right version/branch/url of PIConGPU accordingly.
ccing @BeyondEspresso @HighIander
=> Doc: Piz Daint ADIOS Build

lib/python/picongpu/input/parameters.py, share/picongpu/examples/LaserWakefield/etc/picongpu/0004gpus_gui.cfg, share/picongpu/examples/LaserWakefield/lib/python/picongpu/params.py
- dtype: data type of the PIConGPU value
- label: UI label instead of name
- formatter: UI value label instead of name
- make more easily modifiable with `tbg -o`:
- steps
- grid size
- devices
- expose TBG_steps properly as integers.
- all plugins dump in same interval: `TBG_plugin_period`
- add histogram, second cut in PNG and phase space
=> LWFA: GUI .cfg & Additional Parameters

include/pmacc/nvidia/atomic.hpp, include/pmacc/nvidia/warp.hpp
This is a follow up of #2333
- use `__shfl_sync` with CUDA9
- use `__ballot_sync` with CUDA9
=> add support for CUDA9 `__shfl_snyc, __ballot_sync`

include/pmacc/memory/Array.hpp, include/pmacc/memory/CtxArray.hpp
fix warning ` warning: __device__ annotation on a defaulted function("Array") is ignored`
- remove `HDINLINE` annotation
=> fix CUDA9 default constructor warnings

include/picongpu/plugins/PluginController.hpp
I somehow forgot to activate ISAAC for CPU builds if it is available although I tested it on CPU architectures...
=> Using ISAAC for CUDA and CPU build if available

include/pmacc/particles/operations/splitIntoListOfFrames.kernel
A racecondition triggered by a missing synchronization results in an illegal memory access.
- add missing `__syncthreads()`
Bug was introduced with #2163
=> restart: fix illegal memory access

.travis.yml, INSTALL.rst, docs/source/install/instructions/spack.rst, docs/source/install/path.rst, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Spack has its own GitHub organization now 🚀 ✨ 
This changes all links from LLNL to it.
=> Spack: Own GitHub Org

include/picongpu/particles/Particles.kernel, include/picongpu/particles/pusher/particlePusherAxel.hpp, include/picongpu/particles/pusher/particlePusherBoris.hpp, include/picongpu/particles/pusher/particlePusherFree.hpp, include/picongpu/particles/pusher/particlePusherPhoton.hpp, include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp, include/picongpu/particles/pusher/particlePusherVay.hpp
Clean up the particle pusher interface. Only passes the particle handle directly, making the overall API more clearly.
In the future, the main pusher will only manipulate the momentum and the particle change (usually linear step) will follow in a separate kernel together with the cell and memory management changes.
This is a preparation for particle probes.
=> Particle Pusher: Clean-Up Interface

docs/source/usage/plugins/phaseSpace.rst, share/picongpu/examples/LaserWakefield/etc/picongpu/0004gpus_gui.cfg
Improve ranges for LWFA GUI example and fix typos in example of phase space python analysis plot.
**Energy Histogram (step=4000)**
**Phase space: ypy (step=2000)**
(note: increased momentum range now even a bit more)
ccing @codingS3b
=> LWFA Example: Improve Ranges

docs/source/models/collisional_ionization.rst, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def, include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp, include/picongpu/particles/particleToGrid/derivedAttributes/EnergyDensityCutoff.def, include/picongpu/particles/particleToGrid/derivedAttributes/EnergyDensityCutoff.hpp, include/picongpu/simulation_defines/param/ionizer.param
Separate bulk from prompt electrons by defining an energy cut-off.
Above this threshold value electrons are classified as "prompt" electrons
and are therefore neglected in the calculation of electron temperature.
The actual cut-off value is highly debated, see [Kemp, Sentoku](http://link.aps.org/doi/10.1103/PhysRevLett.116.159501).
This is one of 4 planned improvements of the `ThomasFermi` implementation.
A test with a directed stream of electrons has shown that if the electrons have energies higher than the cut-off they will not be considered for the "temperature" calculation.
The test features a 2-dimensional 256 x 256 grid with period boundaries in every direction and about 6 copper ions distributed in every cell.
The ions are preionized once and electrons are derived from them.
There …
=> Add upper energy cut-off to ThomasFermi model

include/picongpu/initialization/InitialiserController.hpp
Allow to initialize unphysical particles in the `InitialiserController`. Unphysical in the sense, that those particles have mass and/or charge *undefined*. In such a case, it makes no sense to try to output a plasma frequency from it.
Note: we allow to define particles without such fundamental types in PIConGPU (instead of falling back to zero) since this allows us to differentiate between physical particles (such as photons or neutrals) and unphysical particles (test particles, probes, etc.).
=> InitController: Unphysical Particles

include/pmacc/traits/HasIdentifiers.hpp
New trait similar to `HasIdentifier` but accepts a sequence of identifiers to be checked at once.
Example usage in PIConGPU:
```C++
using RequiredIdentifiers = MakeSeq_t<
weighting,
position_pic,
momentum
>;
using SpeciesHasIdentifiers = typename pmacc::traits::HasIdentifiers<
PIC_Electrons::FrameType,
RequiredIdentifiers
>::type; // boost::mpl::bool_
```
=> New Trait: HasIdentifiers

include/picongpu/particles/traits/SpeciesEligibleForSolver.hpp
Allows to check if a defined `picongpu::Particles` class is eligible for computations with a specific solver.
Algorithms, Plugins and core methods can implement this trait to signal which identifiers (particle attributes), flags (particle frame attributes) or other requirements they have regarding particle species.
Use as follows:
```C++
using isEligible = traits::SpeciesEligibleForSolver<
PIC_Electrons,      // any picongpu::Particles species
ChargeConservation  // any solver class here
>::type; // this is a boost::mpl::bool_
// or if you need a bool
bool const okToUse = isEligible::value;
```
Of course you can also filter for the species from `VectorAllSpecies` for which a solver can be compiled:
```C++
using SeqEligibleSpecies = typename bmpl::copy_if<
VectorAllSpecies, …
```
=> New Trait: SpeciesEligibleForSolver

docs/TBG_macros.cfg, docs/source/usage/plugins.rst, docs/source/usage/plugins/checkpoint.rst, docs/source/usage/plugins/hdf5.rst, etc/picongpu/hypnos-hzdr/k80_restart.tpl, include/picongpu/plugins/Checkpoint.hpp, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/output/IIOBackend.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/pmacc/simulationControl/SimulationHelper.hpp, share/picongpu/examples/LaserWakefield/etc/picongpu/0001gpus_isaac.cfg
This pull request adds a plugin which controls the checkpoint creation and restart which was before a part of the hdf5 and adios plugin.
This is the first step to refactor our IO plugins to allow the usage as multi plugin.
It is now possible to restart from adios and create new checkpoints with hdf5.
**This plugin renames all command line options to control the checkpoint creation and restart.**
- add checkpoint plugin 
- add interface to unify usage of IO-backends (adios or hdf5)
- add Checkpoint plugin
- register `Checkpoint` as plugin
-  refactor adios and hdf writer interfaces 
- Refactor interfaces that both plugins can be used as stand allown plugin and controlled checkpoint plugin.
- **rename command line parameter**
- `--checkpoints` to `--checkpoint.period`
- `--softRestarts` to …
=> create separate plugin for checkpointing

include/picongpu/particles/pusher/particlePusherProbe.hpp, include/picongpu/simulation_defines/param/pusher.param, include/picongpu/simulation_defines/param/speciesAttributes.param, include/picongpu/simulation_defines/unitless/pusher.unitless, include/picongpu/simulation_defines/unitless/speciesAttributes.unitless
Add a new particle pusher (probe).
Interpolates the electro-magnetic fields as a usual pusher but instead of pushing the particle (changing the momentum) it saves the result on particle attributes.
As an additional feature, this allows to add an additional pusher attribute. This allows to *probe* the fields and at the same time move the particle (free streaming with a moving window) or even to create a tracer particle (which fully interacts with the simulation).
Also adds two species attributes that can be used to store a particle's E and B field as seen after fieldToParticle interpolation with respect to shape.
More details on the usage will follow in the main PR.
=> Particle Pusher: Probe

include/picongpu/plugins/BinEnergyParticles.hpp, include/picongpu/plugins/ChargeConservation.hpp, include/picongpu/plugins/ChargeConservation.tpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpaceMulti.hpp, include/picongpu/plugins/PngPlugin.hpp, include/picongpu/plugins/PositionsParticles.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Implement the `SpeciesEligibleForSolver` trait for all plugins working on particles.
This allows to query each plugin and check if it is possible to compile it for a specific particle species before specializing the class for it.
Note: as soon as the interface in #2364 does not change during review, this PR can be merged independently / in parallel and does not need to be rebased.
Note: radiation is not yet set up with the same trait (defaults to: assume it will work with each species) since it already checks manually for `momentumPrev1`; we should refactor this check to the new trait in a follow-up PR.
=> Plugins: SpeciesEligibleForSolver Traits

docs/source/models/collisional_ionization.rst, include/picongpu/particles/ionization/byCollision/ThomasFermi/AlgorithmThomasFermi.hpp, include/picongpu/simulation_defines/param/ionizer.param
In tests that I did a while back, I found an unphysical prediction of ionization states that the Thomas-Fermi fitted formula by More, 1985 delivered. 
This applies to typical ion densities for gases but also pre-plasmas and can, depending on electron temperature, predict the ionization of a charge state that is much more deeply bound than the average energy of a free electron that would be responsible for the collision process.
A simple man's approach to this issue is to set a cut-off value for low densities.
It is advisable to strongly motivate the exact value of this cut-off parameter with independent calculations done for instance with FLYCHK.
**update 2017-11-08** This is how the average charge state at liquid argon density looks like for electron temperatures from 0 to 450 electron …
=> Add lower ion density cut-off to ThomasFermi model

docs/source/usage/plugins/checkpoint.rst
=> fix spelling mistake

include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/multi/IHelp.hpp, include/picongpu/plugins/multi/ISlave.hpp, include/picongpu/plugins/multi/Master.hpp
- add class to create a generic multi plugin `multi:::Master`
- add interfaces
- `IHelp` allow to expose the command line requirements of a plugin
- `ISlave` interface that a plugin can be used from the multi plugin `multi::Master`
- make `EnergyParticles` multi plugin ready
it is currently not allowed to call this plugin multiple time (we need particle filter support)
- `PluginController`: register `EnergyParticles` as multi plugin
related to #1288
=> generic multi plugin

include/picongpu/particles/ParticlesInit.kernel, include/picongpu/particles/startPosition/OnePositionImpl.def, include/picongpu/particles/startPosition/OnePositionImpl.hpp, include/picongpu/particles/startPosition/QuietImpl.hpp, include/picongpu/particles/startPosition/RandomImpl.hpp, include/picongpu/particles/startPosition/generic/Free.hpp, include/picongpu/particles/startPosition/generic/FreeRng.hpp
Allows to transparently use the `OnePosition` particle initialization `startPosition` with particles without weighting (such as probe particles).
This will straight initialize the number of particles per cell (ppc). It is recommended to only use one ppc with this start position.
=> Start Pos: OnePosition w/o Weighting

include/picongpu/particles/traits/GenerateSolversIfSpeciesEligible.hpp
Solvers can define the trait `SpeciesEligibleForSolver` to check a particle species if it fulfills requirements of the solver.
The compile-time factory here returns a list of particle solvers (of the same solver), but fully specialized with matching particle species from a sequence of species.
=> CT Factory: GenerateSolversIfSpeciesEligible

include/pmacc/particles/memory/dataTypes/Particle.hpp
Allow that a particle handle with the same template signature can be overwritten.
This change is necessary to allow that we can store a handle in a `CtxArray` for the lockstep programming model.
=> allow update of a particle handle

docs/source/usage/particles.rst, include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/Manipulate.hpp, include/picongpu/particles/filter/All.def, include/picongpu/particles/filter/All.hpp, include/picongpu/particles/filter/filter.def, include/picongpu/particles/filter/filter.hpp, include/picongpu/particles/manipulators/IBinary.def, include/picongpu/particles/manipulators/IUnary.def
This pull request changed the name for the particle filter which is necessary to allow the usage later in our plugin e.g. `--e_energy.filter All`
- rename particle filter
- add static `getName()` method to the filter
- update usage
related to #1288
=> rename filter: `IsHandleValid` -> `All`

include/picongpu/particles/filter/RelativeGlobalDomainPosition.def, include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp, include/picongpu/simulation_defines/_defaultParam.loader, include/picongpu/simulation_defines/param/particle.param, include/picongpu/simulation_defines/param/particleFilters.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particleFilters.param
`RelativeGlobalDomainPosition`: add static method `getName()`
- move particle filter from `particles.paramm` to `particleFilters.param`
- add a name to each filter configuration
related to #1288
=> add new param file `particleFilters.param`

docs/TBG_macros.cfg, docs/source/usage/plugins/checkpoint.rst
Adds additional details on the IO backends in docs and tbg macros.
=> Docs: Checkpoints Backends

docs/TBG_macros.cfg, docs/source/usage/plugins/energyFields.rst, docs/source/usage/plugins/energyParticles.rst, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/misc/AppendName.hpp, include/picongpu/plugins/misc/ExecuteIfNameIsEqual.hpp, include/picongpu/plugins/misc/concatenateToString.hpp, include/picongpu/plugins/misc/misc.hpp, share/picongpu/examples/FoilLCT/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0016gpus.cfg, share/picongpu/examples/WeibelTransverse/etc/picongpu/0004gpus.cfg, src/tools/bin/plotNumericalHeating
refactor `EnergyParticles` to allow
- usage as multiplugin
- filter particles
- add command line parameter `.filter`
- tool `plotNumericalHeating`: update uased filename of particle energies
- plugins: add miscellaneous helpers 
- `misc::AppendName<>` adds the name of a filter to a vector of strings
- `ExecuteIfNameIsEqual` execute a unary functor
- `concatenateToString()` concatenate all values of an string container
Please only review the three latest commits.
=> add particle filter to `EnergyParticles`

include/picongpu/plugins/BinEnergyParticles.hpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpaceMulti.hpp, include/picongpu/plugins/PositionsParticles.hpp, include/picongpu/plugins/multi/Master.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Fix traits for `SpeciesEligibleForSolver` for species plugins (introduced in #2367). This worked previously when applied in the right way but now it is properly implemented without accidentally specializing non-eligible combinations of species & plugins.
Also adds the new trait to the new Master class for Multi-Plugins.
=> Plugins: Fix SpeciesEligibleForSolver

include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp
The used types `SpeciesEligibleForSolver` and `HasIdentifiers` are not included.
=> add missing includes

include/picongpu/particles/filter/All.hpp, include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp, include/picongpu/particles/manipulators/binary/Assign.def, include/picongpu/particles/manipulators/binary/DensityWeighting.def, include/picongpu/particles/manipulators/binary/ProtonTimesWeighting.def, include/picongpu/particles/manipulators/generic/Free.hpp, include/picongpu/particles/manipulators/generic/FreeRng.def, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/manipulators/generic/None.def, include/picongpu/particles/manipulators/generic/detail/Rng.hpp, include/picongpu/particles/manipulators/unary/CopyAttribute.def, include/picongpu/particles/manipulators/unary/Drift.hpp, include/picongpu/particles/manipulators/unary/RandomPosition.def, include/picongpu/particles/manipulators/unary/Temperature.hpp, include/picongpu/particles/startPosition/OnePositionImpl.hpp, include/picongpu/particles/startPosition/QuietImpl.hpp, include/picongpu/particles/startPosition/RandomImpl.hpp, include/picongpu/particles/startPosition/detail/WeightMacroParticles.hpp, include/picongpu/particles/startPosition/generic/Free.hpp, include/picongpu/particles/startPosition/generic/FreeRng.hpp, include/picongpu/simulation_defines/param/radiation.param, include/pmacc/filter/operators/And.hpp, include/pmacc/filter/operators/Or.hpp, include/pmacc/functor/Filtered.hpp, include/pmacc/functor/Interface.hpp, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/radiation.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/radiation.param
Refactor functor operator to `HDINLINE` to allow that functors and filter can be used on the host too.
This PR is required for the upcoming particle filters for PIConGPU, related to #1288.
=> refactor PMacc functor interface

include/picongpu/plugins/CountParticles.hpp, include/picongpu/plugins/ResourceLog.hpp, include/picongpu/plugins/adios/ADIOSCountParticles.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/WriteSpecies.hpp, include/picongpu/plugins/adios/restart/LoadSpecies.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/plugins/hdf5/restart/LoadSpecies.hpp, include/picongpu/plugins/kernel/CopySpecies.kernel, include/picongpu/plugins/misc/SpeciesFilter.hpp, include/pmacc/mappings/simulation/ResourceMonitor.hpp, include/pmacc/mappings/simulation/ResourceMonitor.tpp, include/pmacc/particles/operations/ConcatListOfFrames.hpp, include/pmacc/particles/operations/CountParticles.hpp
- PMacc: use particle filters in `ResourceMonitor`, `ConcatListOfFrames` and `CountParticles`
- PIConGPU:
- add helper class `SpeciesFilter`
- Prepare all plugins which uses PMacc particle methods to be particle filter ready.
Note: `ConcatListOfFrames` is currently hacky. All usages of alpaka accelerators are filled with fake values. This means that is it currently not possible to use accelerator dependent functions (RNG, ...) with the filter. We need to rewrite `ConcatListOfFrames` as proper alpaka kernel. This is **not** possible currently until we fully switch to alpaka (currently we are running in a mixed mode with native CUDA).
**WARNING** the species names in the output files from HDF5 and ADIOS will be change after this PR. New name are `<speciesName>_<filternName>`. The current …
=> add support for particle filters

share/picongpu/examples/FoilLCT/etc/picongpu/0004gpus.cfg, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/grid.param
Avoid getting too close to the CFL for the foil example in order to keep numerical stability.
Previous:
Courant c*dt <= 1.00006 ? 1
Now:
Courant c*dt <= 1.00056 ? 1
See issue #2391 
Also increases the runtime to 5k steps (~5min on K80) by default to provide more dynamics
=> Foil Example: Fix CFL

.travis.yml, include/picongpu/particles/flylite/helperFields/LocalDensity.kernel, include/pmacc/particles/memory/buffers/MallocMCBuffer.hpp, test/hasExtLibIncludeBrackets
- add test check if external libraries are included with `<>` brackets
- add `hasExtLibIncludeBrackets` to travis code style checks
- fix wrong include brackets in `LocalDensity.kernel` and `MallocMCBuffer.hpp`
=> bracket test for external libraries includes

docs/source/usage/workflows.rst, docs/source/usage/workflows/probeParticles.rst, docs/source/usage/workflows/tracerParticles.rst, include/picongpu/particles/densityProfiles/EveryNthCellImpl.def, include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp, include/picongpu/particles/densityProfiles/profiles.def, include/picongpu/particles/densityProfiles/profiles.hpp, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/density.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/fileOutput.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/speciesDefinition.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/speciesInitialization.param
Documentation on how to use probe particles ("probes") in PIConGPU. Adds probe particles to the `FoilLCT` ion acceleration example.
Probe particles (“probes”) can be used to record field quantities at selected positions over time.
As a geometric data-reduction technique, analyzing the discrete, regular field of a particle-in-cell simulation only at selected points over time can greatly reduce the need for I/O. Such particles are often arranged at isolated points, regularly as along lines, in planes or in any other user-defined manner.
Probe particles are usually neutral, non-interacting test particles that are statically placed in the simulation or co-moving with along pre-defined path. Self-consistently interacting particles are usually called tracer particles. …
=> Probe Particle Usage

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, thirdParty/cuda_memtest/cuda_memtest.h
Updates cuda_memtest:
- remove cuBLAS include [#14](https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/14)
From
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/8a0e21bea7be98a1d0f0f9fc48ae90f87c3ecb81) to
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/7a585d504831431d0e95ff00d0217181201dbb12)
```bash
git subtree pull --prefix thirdParty/cuda_memtest \
```
=> Update cuda_memtest: no cuBLAS

include/pmacc/cuSTL/algorithm/kernel/detail/ForeachKernel.hpp
Add a missing include to Boost.Preprocessor in cuSTL's ForeachKernel.
=> cuSTL: Missing Include in ForEach

docs/source/models/collisional_ionization.rst, docs/source/models/collisional_ionization_thomas-fermi_cutoffs.py, include/picongpu/particles/ionization/byCollision/ThomasFermi/AlgorithmThomasFermi.hpp, include/picongpu/simulation_defines/param/ionizer.param
Depending on the material the Thomas-Fermi prediction for the average charge state can be unphysically high. For some materials it predicts non-zero charge states at 0 temperature. That can be a reasonable approximation for metals and their electrons in the conduction band. In the general case there should be no free electrons at 0 temperature, though.
Therefore this commit implements a lower temperature cutoff.
The `detailedBalanceThomasFermi` function now accepts the parameters
- `temperature` in eV
- `massDensity` in g/cm^3
just as the fitting model described by More (1985).
See the Thomas-Fermi prediction of the charge state of the constituents of polystyrene, carbon and hydrogen.
- once run with 0 eV electron temperature - TF prediction: <Z> = 4.40
- one run with 5 eV: TF prediction …
=> Add lower electron temperature cut-off to ThomasFermi model

docs/source/dev/clangtools.rst, docs/source/index.rst, include/picongpu/CMakeLists.txt
Add a CMake target for clang-tidy. Can be used to check (or fix) code with e.g.:
```bash
cmake -DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE=ON ~/src/picongpu/include/picongpu/
make VERBOSE=true clang-tidy
```
or just any other PIConGPU example in the usual `pic-configure` and `make [install]` workflow.
Needs at least [clang-tidy 3.9](http://releases.llvm.org/3.9.0/tools/clang/tools/extra/docs/clang-tidy/index.html), otherwise it segfaults.
also allows to set an explicit newer version in ubuntu/debian via
```bash
cmake -DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE=ON  \
-DCLANG_TIDY_BIN=$(which clang-tidy-3.9) \
~/src/picongpu/include/picongpu/
```
- include in-source files but exclude external headers
- add `.clang-tidy` config file with set of checks we want to add on top of the defaults (see …
=> Clang-Tidy

include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/pmacc/random/distributions/normal/Normal_float.hpp, include/pmacc/random/methods/AlpakaRand.hpp, include/pmacc/random/methods/MRG32k3aMin.hpp, include/pmacc/random/methods/XorMin.hpp
- re-add `RNG` XorMin and `MRG32k3aMin` (was emoved with #2226)
- on CPU: the RNG has a fallback to the default alpaka RNG
- PIConGPU: use XorMin by default
CC-ing: @n01r
=> RNG with reduced state

include/picongpu/CMakeLists.txt
The check should prevent in-source-builds. If your source directory is picongpu and the build directory is picongpu_build, this check throws an error. But this isn't an error. To prevent this, I add a /. This should be correct because SOURCE_DIR_ROOT is a file (It is the result of get_filename_component(...) ). I checked it and get no error with the directory names picongpu and picongpu_build. The directory picongpu/build throws an error message.
=> [Hotfix] CMake is too accurate

etc/picongpu/submitAction.sh
During the submit with `tbg`'s `--force` (overwrite) option, our `submitAction.sh` creates directories. If they exist, this throws and unnecessary warning. `mkdir -p` (for create "parent" directories) does not throw in such a situation and fixes this.
=> tbg -f: mkdir -p submitAction

include/picongpu/particles/filter/IUnary.def, include/picongpu/particles/filter/filter.def, include/picongpu/particles/filter/filter.hpp, include/picongpu/particles/functor/User.def, include/picongpu/particles/functor/User.hpp, include/picongpu/particles/functor/functor.def, include/picongpu/particles/functor/functor.hpp, include/picongpu/particles/functor/misc/Rng.def, include/picongpu/particles/functor/misc/Rng.hpp, include/picongpu/particles/manipulators/generic/Free.def, include/picongpu/particles/manipulators/generic/Free.hpp, include/picongpu/particles/manipulators/generic/FreeRng.def, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/manipulators/generic/None.def, include/picongpu/particles/manipulators/manipulators.hpp, include/picongpu/particles/startPosition/generic/FreeRng.def, include/picongpu/particles/startPosition/generic/FreeRng.hpp, include/picongpu/plugins/CountParticles.hpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/ResourceLog.hpp, include/picongpu/plugins/adios/ADIOSCountParticles.hpp, include/picongpu/plugins/adios/WriteSpecies.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/plugins/misc/ExecuteIfNameIsEqual.hpp, include/pmacc/functor/Interface.hpp
- create functor folder
- move `manipulators/generic/detail/Rng.*` to `functor/misc`
- add functor `User` to reduce code duplication for the optional current step within the constructor
- filter: add `IUnary` interface for filter to secure the interfaces
- plugin: enforce in all plugins which uses filter that the interface is fulfilled
- manipulator:
- update used dependency `Rng`
- set `getName()` static
- use `misc::User` to initialize the user functor
- make `getName()` static to allow working with the name withou creating a instance
- remove return type detection (simplefy the code)
**Note:** There is no change in the algorithmic part of the methods.
=> refactor particle manipulators/filter/startPosition

include/pmacc/random/distributions/misc/MullerBox.hpp, include/pmacc/random/distributions/normal/Normal_float.hpp, include/pmacc/random/methods/AlpakaRand.hpp, include/pmacc/random/methods/MRG32k3aMin.hpp, include/pmacc/random/methods/XorMin.hpp
- revert interface change from #2410 (remove fmethod `getNormal` from the method)
- add helper class `MullerBox` to generate normal distributed random numbers from uniform distributed
- add specialization to create uniform random number with `MRG32k3aMin` and `XorMin`
=> RNG: Normal distribution

INSTALL.rst, docs/source/install/profile.rst, etc/picongpu/pizdaint-cscs/picongpu.profile.example
This updates the profiles for Piz Daint (CSCS):
- ADIOS 1.11.1 -> 1.13.0
- enables transforms:
- zlib (serial) (`--adios.compression zlib`)
- [blosc](https://github.com/ornladios/ADIOS/pull/135) (with zlib and more; parallel) (e.g. `--adios.compression blosc:threshold=2048,shuffle=bit,lvl=1,threads=10,compressor=zstd`)
- own zlib
- own libpng
The install scripts under https://gist.github.com/ax3l/68cb4caa597df3def9b01640959ea56b are updated accordingly.
Note: blosc with 10 theads and zstd was the [fastest & best-compressing option](https://arxiv.org/abs/1706.00522) of the three tested above
ccing @n01r @PrometheusPi @BeyondEspresso @HighIander
=> Piz Daint: ADIOS 1.13.0

lib/python/picongpu/input/parameters.py, share/picongpu/examples/LaserWakefield/lib/python/picongpu/params.py
Changes the structure of the params.py parameter definition to a dictionary containing group names as keys and a list of parameters as the value for each group.
This will be used to better represent the adjustable parameters in the jupyter notebook UI.
Besides, a wrapper function for the set_value function of the UiParameter is introduced. This becomes necessary since we refactored the callback functions for the sliders in the notebook UI.
=> Group parameters in LWFA example

src/tools/bin/tbg
fix #2414
A single `'` is quoted with `'\''` which creates an error in combination with slurm.
The issue is solved by removing `\''` from the environment variables.
=> fix wrong quoting of `'`

share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/WarmCopper/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/WarmCopper/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/speciesInitialization.param
This refactors the `particle.param` and `speciesInitialization.param` files for the examples to transport the particles-per-cell (ppc) parameters more transparently for the user into the density profile to discrete particle mapping step of the initialization.
See the related question in issue #2411.
=> Examples: Init of Particles per Cell

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh
This documents the changes to CUDA 8.0+ on the CI and our dependencies.
We do not remove the CUDA 7.5 work-arounds (e.g. for boost) yet since it can in principle still be needed and work, e.g. if we replace Boost::mpl with something more modern #1997
=> CI/Deps: CUDA 8.0

docs/source/usage/particles.rst, include/picongpu/particles/filter/filter.def, include/picongpu/particles/filter/filter.hpp, include/picongpu/particles/filter/generic/Free.def, include/picongpu/particles/filter/generic/Free.hpp, include/picongpu/particles/filter/generic/FreeRng.def, include/picongpu/particles/filter/generic/FreeRng.hpp, include/picongpu/particles/filter/generic/FreeTotalCellOffset.def, include/picongpu/particles/filter/generic/FreeTotalCellOffset.hpp, include/picongpu/particles/functor/functor.def, include/picongpu/particles/functor/misc/TotalCellOffset.def, include/picongpu/particles/functor/misc/TotalCellOffset.hpp
- add helper to provide the cell offset to the total domain origin of a supercell
- add generic filter:
- `Free` - calls a user defined filter
- `FreeRng` - calls a user defined filter and provide a random number generator
- `FreeTotalCellOffset` - calls a user defined filter and provide the offset of the particle (in cells)
- update `particles.rst`
=> new particle filters

docs/source/usage/workflows/quasiNeutrality.rst, include/picongpu/particles/manipulators/binary/UnboundElectronsTimesWeighting.def, include/picongpu/particles/manipulators/manipulators.def, share/picongpu/examples/FoilLCT/README.rst, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/speciesInitialization.param
Add a new binary manipulator suitable for partially pre-ionized targets (more than once pre-ionized).
`speciesInitialization.param`:
```C++
using InitPipeline = mpl::vector<
// ... ,
// partial pre-ionization: set bound electrons for C & N
Manipulate<
manipulators::TwiceIonized,
Carbon
>,
ManipulateDeriveSpecies<
manipulators::binary::UnboundElectronsTimesWeighting,
Carbon,
Electrons
>,
>;
```
`particle.param`:
```C++
// ...
namespace manipulators
{
//! ionize ions 2x
struct TwiceIonizedImpl
{
template< typename T_Particle >
DINLINE void operator()(
T_Particle& particle
)
{
constexpr float_X protonNumber = GetAtomicNumbers< T_Particle >::type::numberOfProtons;
particle[ boundElectrons_ ] = protonNumber - 2.;
}
};
//! definition of TwiceIonizedImpl manipulator
using TwiceIonized = …
```
=> Manipulators: UnboundElectronsTimesWeighting

include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp, include/picongpu/plugins/PhaseSpace/PhaseSpaceFunctors.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpaceMulti.tpp
Fix for weighted particles with a weighting off the "typical" (nominal) weighting. The plugin calculated, since its introduction in #347 (releases: `beta-rc5`-`0.3.1`), the momentum bin of particles with non-typical weighting wrong: particles with lower weighting were put in proportionally lower momentum bins and with higher weighting than "typical weighting" were put in proportionally higher bins.
Entries to phase space bins originating from
- up/downramp particles
- material dopings with non-"typical" weighting
- below-1.0 areas of the normalized density profile
are ill-placed in the phase space image. Momenta of lower-weighting (macro) particles were underestimated, momenta of higher-weighting (macro) particles were overestimated.
This *only* affects a plugin, deriving a 2D phase space …
=> Phase Space Plugin: Fix Weighted Particles

share/picongpu/examples/Bremsstrahlung/etc/picongpu/0008gpus.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0016gpus.cfg, share/picongpu/examples/SingleParticleTest/etc/picongpu/0001gpu.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1gpu.cfg
follow up of #2403 (thx @ax3l for the hint that I missed it in the original PR)
add missing required option `hdf5.file` to example cfg's
=> add `hdf5.file` to cfg's with IO

include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.kernel, include/picongpu/particles/Particles.tpp, include/picongpu/particles/filter/generic/Free.def, include/picongpu/particles/filter/generic/Free.hpp, include/picongpu/particles/filter/generic/FreeRng.def, include/picongpu/particles/filter/generic/FreeRng.hpp, include/picongpu/particles/filter/generic/FreeTotalCellOffset.def, include/picongpu/particles/filter/generic/FreeTotalCellOffset.hpp, include/picongpu/particles/manipulators/generic/Free.def, include/picongpu/particles/manipulators/generic/FreeRng.def, include/picongpu/simulation_defines/param/particleFilters.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particleFilters.param
The filters on `ManipulateDerive`- and `Derive`-Species should be filtering the particles to derive (in the source species). Before, this was accidentally filtering the destination species to manipulate and derived all particles from the source species. This is not necessary, lacks the filter in the source species and is confusing, also since a manipulator can simply filter with a simple if where needed.
In order to guarantee this works, the "Free" manipulators needed a fix to check for `isValid()` before applying a user-filter.
Also, the comments have been improved to be more accurate and the examples for input files have been fixed for little typos and are more clear now.
The default of the `particleFilters.param` should only be `All` as well (compile-time). The KHI example shows a more …
=> (Manipulate)DeriveSpecies: Fix Filters

.travis.yml
Updated to
- clang 5.0
- CMake 3.9.2
References:
- https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
- https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/
=> Travis: Image Updates

include/pmacc/random/distributions/misc/MullerBox.hpp
The flag to mark a valid second generated random number was not initialized.
The result of this bug are wrong normal distributed normal numbers (not used in PIConGPU yet).
bug was introduced with #2415
=> fix muller box

lib/python/picongpu/input/parameters.py
This pull request adds functions to the `UiParameter` and derived classes for proper (and clearer) conversion of values adjusted by the user in the UI via e.g. sliders and their possibly transformed (linear scaled, or log scaled) 'internal' values which will be passed to PIConGPU.
In the docs, we will from now on refer to the `self.value` of each Parameter object as being on the 'internal scale' and possible slider widgets values (that might be used to change the `self.value` attribute)
that the user is allowed to adjust as being on the 'ui scale'.
Each class deriving from `UiParameter` now needs to override the following functions:
- convert_value_to_internal_scale
- convert_value_from_internal_scale
Besides, the `get_value()` function was renamed into the hopefully clearer …
=> Clearer conversion functions for Parameter values between UI scale and internal scale

docs/source/install/profile.rst, etc/picongpu/pizdaint-cscs/picongpu.profile.example
Update the [install shortcut](https://gist.github.com/ax3l/68cb4caa597df3def9b01640959ea56b) for Piz Daint.
Build own CMake 3.10.1 (FindHDF5 fixed in 3.10.0-rc5+).
ccing @HighIander @BeyondEspresso @steindev @psychocoderHPC
=> Docs: Piz Daint Update CMake

include/picongpu/plugins/adios/ADIOSWriter.hpp
This removes an old work-around for ADIOS in which we handled scalar writes differently than normal variables.
This should not be necessary anymore and caused problems on Piz Daint when writing a species with exactly one particle in it together with blosc compression.
thx to @n01r for spotting it and testing the patch on Piz Daint, thx to @psychocoderHPC for investigating the issue with me.
Note: an alternative work-around would have been to set `canCompress = false;` in the first part of the `if` branch, but this code section looks overall fishy and should not be necessary.
=> ADIOS: Fix 1 Particle Dumps

docs/source/usage/plugins/adios.rst, docs/source/usage/plugins/chargeConservation.rst, docs/source/usage/plugins/checkpoint.rst, docs/source/usage/plugins/countParticles.rst, docs/source/usage/plugins/countPerSupercell.rst, docs/source/usage/plugins/energyFields.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/energyParticles.rst, docs/source/usage/plugins/hdf5.rst, docs/source/usage/plugins/intensity.rst, docs/source/usage/plugins/isaac.rst, docs/source/usage/plugins/particleCalorimeter.rst, docs/source/usage/plugins/particleMerger.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/png.rst, docs/source/usage/plugins/positionsParticles.rst, docs/source/usage/plugins/radiation.rst, docs/source/usage/plugins/resourceLog.rst, docs/source/usage/plugins/sliceFieldPrinter.rst, docs/source/usage/plugins/sumCurrents.rst
Start a sub-paragraph in each plugin explaining the memory complexity it adds (e.g. memory costs at RT) as soon as a plugin is compiled in or activated.
Wording:
- no extra allocations: no (global) memory is allocated at all
- negligible: the extra allocations are too small to be relevant (e.g. a few scalar values)
For people added as reviewers: please take a look at the sections of your plugins and add comments as necessary :)
=> Plugin Docs: Memory Complexity

docs/source/usage/plugins/particleCalorimeter.rst, include/picongpu/particles/Particles.hpp, include/picongpu/simulationControl/GuardHandlerCallPlugins.hpp, include/picongpu/simulation_defines/param/speciesAttributes.param
- add species attribute `boundaryCondition<>`
- extent particle description with the in flag defined boundary condition
- call method `onParticleLeave` for all plugins by default if `boundaryCondition` is not defined
- remove section that the user needs to activate monitoring of leaving particles via extenting of the species flags
**attention** This PR change the default behavior, now all plugins will be notified if particles leave the global simulation box.
Fixes #2433
I run the LWFA example 3000 steps once with calorimeter which monitors the leaving particles and one without. I compared a few samples in the hdf5 (plain) and saw that the energies in the file where the leaving particles are monitored are higher than within the other run. I also checked that the function to monitors the …
=> particle boundary conditions

include/pmacc/random/RNGHandle.hpp, include/pmacc/random/RNGProvider.hpp, include/pmacc/random/distributions/Uniform.hpp, include/pmacc/random/methods/RngPlaceholder.hpp
By using non generic place holder to substitude the random number
generation method it is possible to avoid substitution failer
if a unspecified random number is embedded into other template signatures
with boost mpl placeholder.
This change is needed to allow the usage of random number generator where the state is stored between kernel calls.
=> RNG: use non generic place holder

docs/source/usage/param/core.rst, docs/source/usage/particles.rst, include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/Manipulate.hpp, include/picongpu/particles/manipulators/IBinary.def, include/picongpu/particles/manipulators/binary/DensityWeighting.def, include/picongpu/particles/manipulators/binary/ProtonTimesWeighting.def, include/picongpu/particles/manipulators/binary/UnboundElectronsTimesWeighting.def, include/picongpu/particles/startPosition/detail/WeightMacroParticles.hpp, include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/WarmCopper/include/picongpu/simulation_defines/param/speciesInitialization.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/speciesInitialization.param
Updates particle initialization methods for consistency.
`speciesInitialization.param`: `DeriveSpecies` & `ManipulateDeriveSpecies` without the ~Species~ suffix now
Moves more docs to the manual section (by putting them in the user-facing API doxygen strings instead).
=> Particle Init Methods: Unify API & Docs

README.md, docs/source/usage/reference.rst
Add [reference](https://github.com/ComputationalRadiationPhysics/picongpu-communitymap) in README to our [community map](https://computationalradiationphysics.github.io/picongpu-communitymap/) :)
=> Docs: Community Map

include/pmacc/random/RNGHandle.hpp, include/pmacc/random/RNGProvider.hpp
The current dev is not compiling with the accelerator `omp2b`.
- fix `GetRandomType` trait (add missing `template` keyword)
=> fix RNG cpu compile

include/pmacc/random/distributions/Normal.hpp, include/pmacc/random/distributions/Uniform.hpp, include/pmacc/random/distributions/misc/MullerBox.hpp, include/pmacc/random/distributions/normal/Normal_double.hpp, include/pmacc/random/distributions/normal/Normal_generic.hpp, include/pmacc/random/distributions/uniform/Range.hpp, include/pmacc/random/distributions/uniform/Uniform_Integral64Bit.hpp, include/pmacc/random/distributions/uniform/Uniform_double.hpp, include/pmacc/random/distributions/uniform/Uniform_float.hpp, include/pmacc/random/distributions/uniform/Uniform_generic.hpp, include/pmacc/random/methods/AlpakaRand.hpp, include/pmacc/random/methods/MRG32k3aMin.hpp, include/pmacc/random/methods/XorMin.hpp
- fix minor documentation bugs
- add support for 64Bit floating point
- normal distributed numbers
- uniform distributed numbers
- add 64bit integer support to generate uniform distributed random numbers
- fix usage of `float` in the generic `MullerBox`
- RNG methods: extent interface with to generate a 64bit integer random number
- rename the range `ExcludeOne<...>::Use24Bit` to `ExcludeOne<...>::Reduced`
I fixed a documentation to the normal distributes number ranges and some hard coded usages of `float`. I have not added the label **BUG** because both are very tiny and has no real effect to the users.
=> PMacc RNG 64bit support

include/pmacc/cuSTL/algorithm/kernel/detail/ForeachKernel.hpp, include/pmacc/cuSTL/algorithm/kernel/detail/SphericMapper.hpp, include/pmacc/cuSTL/algorithm/kernel/run-time/Foreach.hpp
- add `algorithm::detail::KernelForeachLockstep`
- change the interface of `algorithm::kernel::detail`
- update `algorithm::kernel::RT::ForEach` to run with a lockstep kernel
This PR is currently a workaround and must be refactored as soon as cuSTl is fully supported on the host side.
This PR is marked also as **BUG** because it solves that the assign function of a host cuSTL buffer was broken on CPU side due to the missing lockstep support. As I know only the `ParticleCalorimeter` was affected.
=> cuSTL kernel::ForEach: add lockstep support

include/picongpu/particles/particleToGrid/derivedAttributes/BoundElectronDensity.def, include/picongpu/particles/particleToGrid/derivedAttributes/BoundElectronDensity.hpp, include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp, include/picongpu/simulation_defines/param/fileOutput.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/fileOutput.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/fileOutput.param
Adds a new attribute to derive the density of bound electrons of an ion species.
=> Derived Attribute: Bound Electron Density

include/picongpu/particles/filter/generic/FreeRng.def, include/picongpu/particles/filter/generic/FreeRng.hpp, include/picongpu/particles/functor/misc/Rng.def, include/picongpu/particles/functor/misc/Rng.hpp, include/picongpu/particles/functor/misc/RngWrapper.hpp, include/picongpu/particles/manipulators/generic/FreeRng.def, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/manipulators/unary/RandomPosition.def, include/picongpu/particles/manipulators/unary/Temperature.def, include/picongpu/particles/startPosition/RandomImpl.def, include/picongpu/particles/startPosition/generic/FreeRng.def, include/picongpu/particles/startPosition/generic/FreeRng.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/picongpu/simulation_defines/param/particle.param
- add class `RngWrapper`
- refactor template signature for particle functors/manipulator/filter with RNG
- MySimulation: enable always the RNG which holds the states over the full simulation
- update default param files
- LWFA is running two times faster due to faster initialization during the slide
=> PIConGPU use tiny RNG

include/picongpu/plugins/IsaacPlugin.hpp
follow up of #2452
Unify the meaning of `isaac.period` with other plugins.
- define `notifyPeriod` as `std::string`
- map the command line option `.period` to `notifyPeriod` instead of `render_interval`
=> ISAAC: unify the usage of period

include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.kernel, include/picongpu/particles/access/Cell2Particle.tpp, include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpaceFunctors.hpp, include/picongpu/plugins/PluginController.hpp, include/pmacc/cuSTL/algorithm/cudaBlock/Foreach.hpp
- PMacc: Remove default constructor to avoid the usage of of `threadIdx,...` without an accelerator.
The second reasin is that the implicit index calculation break the usage of the lockstep model.
- PIConGPU:
- DirSplitting: remove the usage of `cudaBlock::ForEach` default constructor
- PhaseSpace: add full lockstep support to allow the usage together with an host accelerator
The first two commits are dependent changes for the PhaseSpace. IMO it make no sense to provide the change in an separate PR because this mean that I need to provide the change also for the PhaseSpace plugin. This would require tests for a intermediate stage those is not necessary.
=> PhaseSpace: add lockstep support

include/picongpu/simulation_defines/_defaultParam.loader, include/picongpu/simulation_defines/param/unit.param, include/picongpu/simulation_defines/unitless/physicalConstants.unitless
Move conversion units from `physicalConstants.unitless` to `unit.param` to allow the usage within particle filters.
=> move conversion units to `unit.param`

include/picongpu/particles/ParticlesInit.kernel, include/picongpu/particles/flylite/IFlyLite.hpp, include/picongpu/particles/startPosition/generic/Free.hpp, include/pmacc/functor/Filtered.hpp, include/pmacc/functor/Interface.hpp, include/pmacc/nvidia/rng/distributions/Normal_float.hpp, include/pmacc/nvidia/rng/distributions/Uniform_float.hpp, include/pmacc/nvidia/rng/distributions/Uniform_int32.hpp, include/pmacc/nvidia/rng/methods/Xor.hpp, include/pmacc/random/RNGHandle.hpp, include/pmacc/random/methods/AlpakaRand.hpp, include/pmacc/static_assert.hpp
- remove `std::declval` with `alpaka::core::declval`
- use C++ static assert for clang
- defer assert if the compiler is allowed to evaluate the expression even if it is never used
=> fix clang device compile

docs/source/install/instructions/spack.rst
Fix the spack instructions on how to install a compiler. In case the compiler is already present as a system compiler, @berceanu reported problems.
Closes #2456 with a work-around for now.
Related upstream issue: https://github.com/spack/spack/issues/6902
=> Spack: Compiler Already There

include/picongpu/fields/Fields.def, include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def, include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp, include/picongpu/particles/particleToGrid/derivedAttributes/BoundElectronDensity.def, include/picongpu/particles/particleToGrid/derivedAttributes/ChargeDensity.def, include/picongpu/particles/particleToGrid/derivedAttributes/Counter.def, include/picongpu/particles/particleToGrid/derivedAttributes/Density.def, include/picongpu/particles/particleToGrid/derivedAttributes/Energy.def, include/picongpu/particles/particleToGrid/derivedAttributes/EnergyDensity.def, include/picongpu/particles/particleToGrid/derivedAttributes/EnergyDensityCutoff.def, include/picongpu/particles/particleToGrid/derivedAttributes/LarmorPower.def, include/picongpu/particles/particleToGrid/derivedAttributes/MacroCounter.def, include/picongpu/particles/particleToGrid/derivedAttributes/MidCurrentDensityComponent.def, include/picongpu/particles/particleToGrid/derivedAttributes/MomentumComponent.def, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/hdf5/WriteFields.hpp
- derived attributes
- set method `getName()` static
- add method `getName()` to class `FieldTmpOperation`
- IO plugins ADIOS/HDF5
- use method `getName()` to get the name of `FieldTmpOperation`
- ADIOS/HDF5 plugin: add support for command line parameter `.source` to select fields
**this PR fixes a bug that the name of the derived fields in combination with ADIOS used the wrong naming schema.**
- wrong: `<solver name>_<species name>`
- correct: `<species name> _<solver name>`
CC-ing: @n01r, @HighIander, @PrometheusPi
=> Topic io fields as source

share/picongpu/dockerfiles/README.rst
Nvidia GPU Support is now integrated into docker if [nvidia-docker2](https://github.com/NVIDIA/nvidia-docker) is installed.
This makes the runs more standard and straight forward, just append to `docker run` calls a `--runtime=nvidia` if a CUDA GPU pass-through is needed.
=> Docker: Nvidia-Docker 2.0

docs/source/_static/hide_chapter_titles.css
In the section that introduces the usage of .param files, only the titles of the files shall be shown. This is currently not possible, see https://github.com/michaeljones/breathe/issues/318
This PR applies a work-around for HTML to hide additional doxygen information (does not fix the underlying issue and is issue still exists in pdf & epub).
=> Param Docs: Title Only

docs/source/usage/plugins/energyHistogram.rst, include/picongpu/plugins/BinEnergyParticles.hpp
The filter for energy histograms can now be implemented with the more generic particle filter concept.
This removes the old "distance to detector" and opening angle implementation and adds an example how to limit the detector acceptance.
=> EnergyHistogram: Remove Detector Filter

docs/source/usage/param/core.rst, include/picongpu/simulation_defines/param/unit.param
Add doxygen file description and linkage in manual for the new `unit.param` input file.
Follow-up to: #2457
=> Docs: unit.param

docs/source/usage/plugins.rst
Moves the inclusion of the toctree for plugins up in the document. Otherwise the heading "Period Syntax" takes precedence in the menu / sections.
Follow-up to #2452
=> Docs: Fix Headline Plugins

include/picongpu/CMakeLists.txt
Add missing defines from last commit. Folllow-up to #2468
=> PNGwriter 0.7.0: Defines

include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/Manipulate.hpp, include/picongpu/particles/Particles.hpp, include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp, include/picongpu/particles/traits/GetPhotonCreator.hpp, include/picongpu/plugins/ChargeConservation.tpp, include/picongpu/simulationControl/MySimulation.hpp, include/picongpu/simulation_defines/param/species.param, include/pmacc/particles/compileTime/FindByNameOrType.hpp, include/pmacc/traits/GetCTName.hpp
solve #2393
Instead of passing the particle species type to a functor like `CreateDensity` it is possible to use the name of the species. This solve an issue if two species cyclical reference to each other.
- PMacc: new traits ￼…
- add generic `GetCTName` trait to get a compile time name of a class
- add compile time method to find a species type by name or by the type
it self within a sequence of species types
- PIConGPU:
- remove the usage of `MakeIdentifier` to pass species to functors
- use `particles::compileTime::FindByNameOrType_t` to search for a species within `VectorAllSpecies`
- remove include from `species.param` which is useless and break the compile
```C++
using InitPipeline = mpl::vector<
CreateDensity<
densityProfiles::Foil,
startPosition::Quiet1ppc,
PIC_Ions
>, …
```
=> Topic get species by name

include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
This is a fix for #2464 which now fully solves #2393.
The `FindByNameOrType` functionality was missing from the
<IonizationModel>_Impl.hpp files.
Now it's possible to just give a predefined particle species name in the
`speciesDefinition.param` for the electrons as destination species for ionization.
I used the standard Bremsstrahlung example, kicked the electrons out of the initialization pipeline and let the gold atoms be ionized be the laser. I then looked for the electrons and photons to appear in the `<species>_macroParticlesCount.dat`.
Just to illustrate usage now:
```c++
// name for the electron species that will be created through ionization
using Electrons = bmpl::string< 'e' >;
using ParticleFlagsIons = bmpl::vector<
...
ionizers<
MakeSeq_t<
particles::ionization::BSIEffectiveZ< …
```
=> Patch get-by-name functionality for ionization

pic-build
CMake multi-args to `pic-build -c "... ..."` were not forwarded properly to `pic-configure` and `cmake`.
The example `pic-build -c "-DPIC_VERBOSE=21 -DCMAKE_BUILD_TYPE=Debug"` did not work, the same way passing a non-standard generator with `-c "-G Ninja -D..."` failed.
@sbastrakov you were right, this is actually a problem in the script forwarding multi-args for cmake with spaces in general. This also affects linux systems and should fix your generator issue on Visual Studio as well. Thanks for the report!
=> pic-build: CMake multi-args

include/picongpu/fields/laserProfiles/laserExpRampWithPrepulse.hpp, include/picongpu/simulation_defines/param/components.param, include/picongpu/simulation_defines/param/laser.param, include/picongpu/simulation_defines/unitless/laser.unitless, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/laser.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/laser.param, share/picongpu/examples/FoilLCT/cmakeFlags, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/FoilLCT/include/picongpu/simulation_defines/param/laser.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/laser.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/ThermalTest/include/picongpu/simulation_defines/param/components.param, share/picongpu/examples/WeibelTransverse/include/picongpu/simulation_defines/param/components.param
This PR introduces enhancements to the laser-time-profile.
Based on the laserWavepacket-profile, the intensity before the main pulse is modified. 
Like in the following picture: 
the user can specify three (time-intensity)-points, according to which the laser is initialized. Additionally, a gaussian prepulse can be added.
- additionally to the parameters of the laserWavepacket-profile:
float_64 WAVE_LENGTH_SI = 0.8e-6;
float_64 AMPLITUDE_SI = 1.738e13;
float_64 LASER_NOFOCUS_CONSTANT_SI = 0.0
float_64 PULSE_LENGTH_SI = 10.615e-15 / 4.0;
float_64 W0_X_SI = 4.246e-6;
float_64 W0_Z_SI = W0_X_SI;
float_64 RAMP_INIT = 20.0;
float_X LASER_PHASE = 0.0;
PolarisationType Polarisation = LINEAR_X;
- the following new parameters are introduced:
float_X INT_RATIO_PREPULSE = 0.;
float_X …
=> New Laser Profile: Exp. Ramps with Prepulse

pic-build
follow up of #2475 and fix the [reported issue](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2475#issuecomment-360741057)
Allow to use white spaces in arguments. e.g. `./pic-build -c "..." -b omp2b`
This issue with the fix from #2475 was that all arguments of `pic-build` are forwarded as one single argument to `pic-configure`
CC-ing: @sbastrakov
=> pic-build: CMake multi-args with white spaces

share/picongpu/examples/LaserWakefield/etc/picongpu/0008gpus.cfg
This pull request resolves issue #2477 by extending the number of cells in y direction by 50% (+256 cells), pushing the slide point a bit farther, adjusting the GPU distribution and shortening the laser init without changing the laser duration. 
Now, moving window simulations with 8 GPUs produce meaningful result.
=> fix #2477: adjust LWFA setup for 8GPUs

include/pmacc/dataManagement/DataConnector.hpp, include/pmacc/eventSystem/Manager.hpp, include/pmacc/eventSystem/events/EventPool.hpp, include/pmacc/eventSystem/streams/StreamController.hpp, include/pmacc/eventSystem/tasks/Factory.hpp, include/pmacc/eventSystem/transactions/TransactionManager.hpp, include/pmacc/mappings/simulation/EnvironmentController.hpp, include/pmacc/nvidia/memory/MemoryInfo.hpp, include/pmacc/particles/tasks/ParticleFactory.hpp, include/pmacc/pluginSystem/PluginConnector.hpp, include/pmacc/simulationControl/SimulationDescription.hpp
This is a structure, but in several places forward declared as a class, which caused a warning. Replace `class `with `struct `in forward declarations.
Of course, it would be easier to just make `pmacc::detail::Environment` a class. However, it does not store any internal state, so to me structure feels better fitting. Btw, there is a similar type `pmacc::Environment`, which is a class. Maybe it would make sense to make it a structure too (or make both a class for uniformity).
=> Fix warning concerning forward declarations of pmacc::detail::Environment

include/pmacc/cuSTL/cursor/BufferCursor.hpp
There has been a problem with `dim `used both as a template parameter of `BufferCursor `and a member of a privately inherited base class. So the code does not compile in Visual Studio, as the member overshadowed the template parameter (ofc it might be a bug in VS, but my understanding of how name lookup works in this case agrees with VS here). Renamed parameter `dim `to the guidelines-conforming `T_dim` and also fix formatting in this file.
=> Fix buffer cursor dim

include/pmacc/algorithms/math.hpp, include/pmacc/algorithms/math/defines/pi.hpp, include/pmacc/math/complex/Bessel.tpp, include/pmacc/math/complex/Complex.tpp
This is part of #2485. As discussed with @psychocoderHPC , fist I only made changes to PMacc: added a new file with Pi constants and some derivatives (only those currently used, not for all M_... cases), replace usage of M_PI with the new values.
=> Eliminate M_PI from PMacc

include/pmacc/random/distributions/normal/Normal_double.hpp, include/pmacc/random/distributions/normal/Normal_float.hpp
Disable specializations for the normal distribution for the RNG methods
`XorMin`and `MRG32k3aMin`.
=> PMacc: fix CPU compile

include/pmacc/simulationControl/TimeInterval.hpp
It is not portable and only used for the `TimeIntervall `class. I've replaced it with features of C++11 std::chrono.
=> Get rid of <sys/time.h>

include/picongpu/fields/currentInterpolation/Binomial/Binomial.def, include/picongpu/fields/currentInterpolation/Binomial/Binomial.hpp, include/picongpu/fields/currentInterpolation/None/None.def, include/picongpu/fields/currentInterpolation/None/None.hpp, include/picongpu/fields/currentInterpolation/NoneDS/NoneDS.def, include/picongpu/fields/currentInterpolation/NoneDS/NoneDS.hpp, include/picongpu/simulation_defines/param/fieldSolver.param
- remove the template parameter for the simulation dimension from all current interpolation classes
- move trait specialization to hpp file to avoid usage of a incomplete type
- update code style following [this](https://github.com/ComputationalRadiationPhysics/contributing/blob/dc58d36e537248329fdd780dc0e8b852dca40d2f/codingGuideLines/cpp.md) style guides
Please check the last commit independent of each other, this commit contains only the style updates.
=> remove template dimension from current interpolator's

src/tools/bin/tbg
This is to allow for all variables used in the *.tpl file to be set through the -o option, instead of only being able to override variables which have otherwise been defined in either the *.tpl or *.cfg.
=> tbg: Add content of -o arg to env

include/pmacc/memory/buffers/HostBufferIntern.hpp
A tiny fix of unsigned index into signed - OpenMP officially allows only signed. (And VS of all compilers complains about it).
=> Fix type of index in OpenMP-parallelized loop

include/picongpu/main.cpp
There is ERROR macro defined in wingdi.h file. I assume it is somehow included from VS's implementation of the standard library. So there is a collision with ArgsParser::ArgsErrorCode::ERROR. Since the problem is only in main.cpp, I decided just to undef it manually there.
=> Visual Studio: ERROR macro defined in wingdi.h

docs/source/usage/particles.rst, include/picongpu/particles/manipulators/manipulators.def, include/picongpu/particles/manipulators/manipulators.hpp, include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.def, include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.hpp
Add a new unary manipulator that also passes the current total cell index of a particle.
Potential usage in `particle.param`:
```C++
namespace manipulators
{
struct FunctorSaveYcell
{
template< typename T_Particle >
HDINLINE void operator()(
DataSpace< simDim > const & particleOffsetToTotalOrigin,
T_Particle & particle
)
{
particle[ y0_ ] = particleOffsetToTotalOrigin.y();
}
static constexpr char const * name = "saveYcell";
};
using SaveYcell = unary::FreeTotalCellOffset<
FunctorSaveYcell
>;
}
```
(`y0` is a user-defined `speciesAttribute` of type `uint32_t` to store an initial particle position as of the cell index in y.)
=> Manipulator: unary::FreeTotalCellOffset

include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Validate the input of `minEnergy` in the particle calorimeter plugin.
Avoids both negative energies as minimum and zero-energies for log scale energy ranges.
Fix #2511
=> Calorimeter: Validate minEnergy

include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.tpp
Some (relatively) global names were hidden by inaccessible base class members. Explicitly put namespace for such names.
=> Fix issues with name hiding in Particles

include/pmacc/memory/buffers/HostBufferIntern.hpp
The issue was introduced in my earlier pull request #2505 (sorry, did not check it back then) and results in a very long compile warning on Linux.
=> Fix signed and unsigned comparison

include/pmacc/math/vector/Vector.hpp
This solves issue #2507
After some discussion offline @psychocoderHPC proposed a solution, which I implemented.
The error was caused by pmacc::container::DeviceBuffer with T_dim = DIM1. The DeviceBuffer class template has a constructor with a default value for pitch, involving pmacc::math::Size_t<0>::create(). This constructor is not actually used, but VS tries to compile the default value anyway. As a workaround add a fake method create() for Vector<T, 0> partial specialization. The new method will always fail to compile due to static assert.
So it should not matter for other compilers, since they did not try to compile that create() anyway, and is enough for Visual Studio to work. And nobody could actually call the new method by mistake as it won't compile.
=> Fix build error concerning pmacc::math::Size_t<0>::create() in Visual Studio

include/pmacc/ppFunctions.hpp, include/pmacc/preprocessor/size.hpp
As pointed out in #2476 compound literals are not standard C++ and ideally should be fully replaced to provide better portability. However, there seems to be no easy and portable way to fully get rid of them in the current code which counts the number of macro arguments. Boost.Preprocessor provides a macro exactly for that, but it is enabled only for some compilers (comment there says others are not tested), notably, enabled for Visual Studio, but disabled for nvcc. So I've decided to use a macro from Boost if it is enabled and keep the previous implementation as a fallback. Currently it works on my Windows system with Boost implementation and for nvcc the previous implementation is used.
=> Partially replace compound literals in PMacc

include/pmacc/eventSystem/events/kernelEvents.hpp
The previous implementation casted *this to const KernelStarter instead of const reference to it, thus creating a copy for no apparent reason. A cast to reference seems more fitting here, not only because of a copy but for readability (the code in question just calls const version of `operator()`).
Additionally the original version does not compile correctly in Visual Studio, however it seems to be a bug in VS.
=> Fix type cast in pmacc::exec::KernelStarter::operator()

include/pmacc/fields/operations/AddExchangeToBorder.hpp, include/pmacc/fields/operations/CopyGuardToExchange.hpp, include/pmacc/particles/ParticlesBase.kernel, include/pmacc/types.hpp
At long last it seems to be the final modification required to build PIConGPU with MSVC.
Due to a bug, MSVC captures constexpr in lambdas as non-constexpr variables, which breaks compilation e.g., if it is used as a template argument in a lambda.
As discussed with @psychocoderHPC and @ax3l I added a macro to be used for such variables instead of constexpr and replace the (very few) problematic cases with it. Also in some cases the only usage was an unnecessary typecast, which I removed.
After some more consideration I chose the name `PMACC_CONSTEXPR_CAPTURE `instead of what we discussed: did not like having `CONSTEXPR_LAMBDA `as it is potentially confusing with a lambda being a constexpr (in C++17), and did not like having MSVC in the name, since the code where it is used is general. …
=> Add a workaround for MSVC bug with capturing constexpr

etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example
follow up of #2521
Change module name `openmpi/2.1.2.kepler.cuda80` to `openmpi/2.1.2.cuda80`
=> Hypnos (HZDR): fix openmpi module name

pic-configure
Fix the check for old param file structure in `pic-configure`
follow-up to #2331
=> pic-configure: fix old structure check

docs/source/usage/workflows/probeParticles.rst, include/picongpu/param/speciesDefinition.param, include/pmacc/compileTime/String.hpp, include/pmacc/particles/memory/frames/Frame.hpp, include/pmacc/particles/traits/ResolveAliasFromSpecies.hpp, include/pmacc/traits/GetCTName.hpp, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/WarmCopper/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesDefinition.param
- add function to get the n-th character of an compile time C-string
- add compile time string without runtime size (encoded in template signature)
- remove usage of `boost::mpl::string<>` with `PMACC_CSTRING()`
=> compile time string

README.md
URLencode `(` with `%28` and `)` with `%29`.
Causes trouble in Markdown where `[alt](uri)` is the syntax for links: https://github.com/jupyterlab/jupyterlab/issues/3937
=> DOIs with (): URLencode

etc/picongpu/pizdaint-cscs/picongpu.profile.example
Use the proper general environments to load GPU nodes and CUDA toolkit.
With that, we can also use the new CMake 3.10+ module now :)
Boost module request is currently pending.
Note: if you are using an older `dev` version of PIConGPU or a 0.3.X release, replace the [quick start](https://gist.github.com/ax3l/68cb4caa597df3def9b01640959ea56b) gist's installs of:
- libSplash 1.7.0 with 1.6.0
- PNGwriter 0.7.0 with 0.6.0
We also learned about this Cray-CMake manual today:
http://docs.cray.com/books/S-2801-1608/S-2801-1608.pdf
=> Piz Daint: Module Update

include/pmacc/dimensions/DataSpaceOperations.hpp
remove expensive modulo operation
With this PR the expression `X % Y` cannot be changed by  the compiler into a bit shift if Y is not a power of two. Nevertheless, on my Laptop with back-end `omp2b` we get a very small (<1.02) speedup.
For CUDA, I can see that the register usage decreases for most kernels of PIConGPU.
=> remove modulo in 1D to ND index transformation

docs/TBG_macros.cfg, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa.sh, share/picongpu/examples/Bremsstrahlung/etc/picongpu/8.cfg, share/picongpu/examples/Bunch/etc/picongpu/32.cfg, share/picongpu/examples/Empty/etc/picongpu/1.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/16.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/16.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/1_isaac.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/32.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4_gui.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg, share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/1.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/32.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/4.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/64.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/8.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg, share/picongpu/examples/WeibelTransverse/etc/picongpu/4.cfg, share/pmacc/examples/gameOfLife2D/submit/1.cfg, share/pmacc/examples/gameOfLife2D/submit/2.cfg, share/pmacc/examples/gameOfLife2D/submit/4.cfg
Removes the naming of "GPUs" from `.cfg` file names and variables and uses (as `-d|--devices`) the more general *device* naming.
Changes the composition of required parameters `-d`, `-g` and `-s` in order to allow easier editing with the python bindings.
=> Refactor .cfg files: devices

etc/picongpu/bash/mpiexec.tpl, etc/picongpu/bash/mpirun.tpl, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Contains two bug fixes for running a container smoothly on DGX-1.
- TBG bash template: support up to 8 GPUs per node
Usually, one would do one-node runs with those anyway or would need to adjust it by hand of multi-node is desired. With this setting, using a full 8-GPU DGX-1 node is possible without hacks.
- OpenMPI root execution fix and mpiexec as well
Make the root work-around more robust via an export (`export -f mpi...`) and include mpiexec as well.
Also does not not build cuda_memtest on containers anymore since it wastes time on startup for demos.
=> DGX Docker

INSTALL.rst
Fix the download link of HDF5 since it changed to a new structure. Choose latest version 1.8 patch release as the example.
=> Doc: Fix HDF5 Release Link

thirdParty/cupla/.gitmodules
Remove the .gitmodules file from cupla.  We ship alpaka ourselves and it can confuse git clone steps to have it in there.
First seen as an issue with ReadTheDocs builds (activated by default [since November last year](https://github.com/rtfd/readthedocs-build/issues/30)).
=> cupla: no .gitmodules

USAGE.rst, docs/source/usage/param.rst, docs/source/usage/tbg.rst
Fix calls to `--help` in commands auto-build into the manual.
Follow-up to #2537 #2539
=> Docs: Fix Cmd Help

include/picongpu/param/ionizer.param
`ionizer.param`:
* the effective Z array contained too many 5p orbital entries   
--> fix: delete 1 value and go to 6
* changed the configuration of Cu and Au to their real-life   
ground state configuration which slightly differs from the   
Madelung rule prediction
* updated documentation on shell occupation
=> Fixed excess 5p shell entry in gold effective Z

include/picongpu/param/density.param
Properly stay with float_X for the normalized density profile (usually between 0. and 1.)
=> Free Density: Fix float_X

include/picongpu/plugins/adios/ADIOSWriter.hpp
Fix that particles dumped with adios (tranform layer enabled, MPI aggregate enabled) causing reading errors.
Solved by enable compression for all MPI ranks even if the size of data which must be written is zero.
issue: https://github.com/ornladios/ADIOS/issues/170
requires a post-1.13.0 ADIOS for the following fixes:
- reads:
- https://github.com/ornladios/ADIOS/pull/162
- https://github.com/ornladios/ADIOS/pull/163
- writes:
- zlib https://github.com/ornladios/ADIOS/pull/165
- bzip2, isobar and zfp https://github.com/ornladios/ADIOS/issues/174
Cc-ing: @n01r
=> fix zero size transform writes

lib/python/picongpu/input/parameters.py, lib/python/picongpu/input/requirements.txt, share/picongpu/examples/LaserWakefield/lib/python/picongpu/params.py
This PR gets rid of `UiParameter`, `LinearScaledParameter` and `LogScaledParameter` and instead introduces a single `Parameter` class which has the option to pass in arbitrary conversion functions to handle different scales on the UI and on the internal PIC scale of each parameter.
It also makes use of the `pint` package for easier unit conversion.
=> Simpler Python Parameter class

share/picongpu/dockerfiles/ubuntu-1604/start_lwfa.sh
Add a new sub-domain for serving the ISAAC HTML client. The main domain is now redirected to HTTPS by default which can interfere with the unencrypted ws:// sockets in ISAAC (mixed content warnings).
=> Docker: Update ISAAC Client URL

include/picongpu/versionFormat.cpp
Properly convert the running number into a dotted version, following the official formatting rules:
https://www.boost.org/doc/libs/1_66_0/boost/version.hpp
Improves the version output and makes it consisten with other outputs. Related to #2146
=> Boost: Format String Version

docs/source/dev/picongpu.rst
Fix the namespace of `ComputeGridValuePerFrame` in the docs.
Follow-up to #2377
=> Docs: Namespace ComputeGridValuePerFrame

etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example
Hypnos did not yet properly build zlib in the dependency chain.
This led to several severe instabilities and several bug reports in the past months, mainly with unpredictible crashes & segfaults during I/O (e.g. #2504) but also with compile errors in CPUs #2549.
While modules are getting rebuild, a lack of auto-loading the dependency means we have to load zlib manually for now. Loading zlib explicitly is also useful if you build some dependencies by hand as a developer.
=> Hypnos: Zlib

README.md, docs/Doxyfile, docs/source/dev/doxygen.rst, docs/source/index.rst, include/picongpu/main.cpp
Let's publish our doxygen builds on [`gh-pages`](http://computationalradiationphysics.github.io/picongpu).
This adds the instructions on how to update it. Doxygen docs are not versioned as sphinx docs are, so we should decide when we update the docs to keep possible confusion small.
=> Doxygen: Publish As Well 

docs/source/usage/particles.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/workflows.rst, docs/source/usage/workflows/particleFilters.rst, include/picongpu/param/particleFilters.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/particleFilters.param
Document how to limit generic "free" filters to eligible particle species as asked in #2573.
Add to `particleFilters.param` files:
* docstring
* includes commonly needed for eligible traits
* section with prepared namespace for traits
=> Docs: Limit Filters to Eligible Species

include/picongpu/plugins/radiation/ExecuteParticleFilter.hpp, include/picongpu/plugins/radiation/Radiation.kernel, include/picongpu/plugins/radiation/amplitude.hpp, include/picongpu/plugins/radiation/calc_amplitude.hpp, include/picongpu/plugins/radiation/nyquist_low_pass.hpp, include/picongpu/plugins/radiation/parameters.hpp, include/picongpu/plugins/radiation/particle.hpp, include/picongpu/plugins/radiation/radFormFactor.hpp, include/picongpu/plugins/radiation/taylor.hpp, include/picongpu/plugins/radiation/utilities.hpp, include/picongpu/plugins/radiation/vector.hpp
Add at least the basic picongpu namespace.
Later on, needs proper namespace per directory.
Seen as [polluted scope in Doxygen docs](https://computationalradiationphysics.github.io/picongpu/annotated.html).
=> Radiation Plugin: Namespace

include/pmacc/eventSystem/events/kernelEvents.hpp, include/pmacc/test/PMaccFixture.hpp, include/pmacc/test/memory/HostBufferIntern/copyFrom.hpp, include/pmacc/test/memory/HostBufferIntern/reset.hpp, include/pmacc/test/memory/HostBufferIntern/setValue.hpp, include/pmacc/test/memory/memoryUT.cpp, include/pmacc/test/particles/IdProvider.hpp, include/pmacc/test/particles/particlesUT.cpp, include/pmacc/test/random/2DDistribution.cpp
Add missing namespace to PMacc tests. Related to #2577
=> PMacc Tests: Add Missing Namespaces

etc/picongpu/pizdaint-cscs/normal.tpl
On Piz Daint I received strange warnings in `stderr` after their maintenance and after
we changed the worlkflow to use some of their modules (`cmake` and the `daint-gpu` module) instead of building the code ourselves.
Example:
```Shell
Mon Apr  9 19:34:23 2018: [unset]:_pmi_alps_get_apid:alps response not OKAY
Mon Apr  9 19:34:23 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
Mon Apr  9 19:35:49 2018: [unset]:_pmi_alps_get_apid:alps response not OKAY
Mon Apr  9 19:35:49 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
```
I reported these warnings which at least didn't seem to have any malicious
consequence and the CSCS support reached out to Cray.
After setting three different environment variables the warnings disappeared.
They apparently appeared once for each call of `srun`.
I …
=> Piz Daint: avoid pmi_alps warnings

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/titan-ornl/picongpu.profile.example, etc/picongpu/titan-ornl/pythonOnRhea.profile.example, include/picongpu/CMakeLists.txt, include/picongpu/plugins/adios/ADIOSWriter.hpp, src/tools/splash2txt/CMakeLists.txt
ADIOS 1.13.1 fixes several issues with zero-sized block reading and writing when compression transports are used.
This mostly shows up in PIConGPU with simulations on which some GPUs hold zero particles, e.g. in ion acceleration.
Close #2562
=> ADIOS: 1.13.1

include/picongpu/simulationControl/MySimulation.hpp
The old parameter `--restart.step` is shown in the error message if the master
checkpoint file is not available.
- add correct parameter `--checkpoint.restart.step` to the error message
- fix in code documentation string
=> fix error message:  missing restart step

thirdParty/alpaka/README.md, thirdParty/alpaka/appveyor.yml, thirdParty/alpaka/include/alpaka/version.hpp
Update alpaka from 
- dev alpaka@develop (ComputationalRadiationPhysics/alpaka@9e3d274)
to
- release  alpaka@master (ComputationalRadiationPhysics/alpaka@c0e1b3c56 == [`0.3.0`](https://github.com/ComputationalRadiationPhysics/alpaka/tree/0.3.0) )
Bugs Fixed:
* fixed multiple bugs where CPU streams/events could deadlock or behaved different than the native CUDA events
* fixed a bug where the block synchronization of the Boost.Fiber backend crashed due to uninitialized variables
New Features / Enhancements:
* added support for stream callbacks allowing to enqueue arbitrary host code using `alpaka::stream::enqueue(stream, [&](){...});`
* added support for compiling for multiple architectures using e.g. `ALPAKA_CUDA_ARCH="20;35"`
* added support for using `__host__ constexpr` code within …
=> updata alpaka to release 0.3.0

include/picongpu/param/precision.param, include/picongpu/unitless/precision.unitless, share/picongpu/examples/LaserWakefield/include/picongpu/param/precision.param
Add a file doxygen comment for the precision input file. Will be automatically be shown in the manual.
Also fixes a typo in `trigonometric`.
Related to #1982.
=> precision.param: file doxygen

docs/requirements.txt, docs/source/conf.py
The syntax highlighting with pygments was broken in the readthedocs theme.
Also changes the pygments style to `default` since the `"sphinx"` style has a weird green background that does not go well with the rtd theme.
Fixed in sphinx_rtd_theme 0.3.0+, so we just install a newer version of it in the rtd instance: https://github.com/rtfd/sphinx_rtd_theme/pull/448
=> Syntax Highlighting: Fix RTD Theme

include/picongpu/param/mallocMC.param
Add a file doxygen string to the mallocMC input file. Will show up automatically in the manual.
Related to #1982.
=> mallocMC.param: file doxygen

include/picongpu/param/memory.param, share/picongpu/examples/FoilLCT/include/picongpu/param/memory.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/memory.param, share/picongpu/examples/ThermalTest/include/picongpu/param/memory.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/memory.param
Add a doxygen string explaining the `GUARD_SIZE` parameter. The runtime error from PMACC_VERIFY we throw in `MySimulation.hpp` did otherwise not make sense to users.
Other resources: *Docs » Workflows » Setting the Number of Cells* in the [manual](https://picongpu.readthedocs.io/en/latest/usage/workflows/numberOfCells.html).
Thx to @HighIander for the hint docs were missing.
Related to #1982.
=> memory.param: GUARD_SIZE docs

buildsystem/CompileSuite/autoTests/new_commits.sh
Update the following plugins to their minimum version for the compile suite:
- libSplash 1.7.0
- ISAAC 1.3.0
Remove rivlib (used in our first 3D in situ render plugin before ISAAC).
=> CompileSuite: Update Plugins

include/picongpu/particles/filter/All.hpp, include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp, include/picongpu/particles/filter/generic/Free.hpp, include/picongpu/particles/filter/generic/FreeRng.hpp, include/picongpu/particles/filter/generic/FreeTotalCellOffset.hpp, include/picongpu/particles/functor/misc/Rng.hpp, include/picongpu/particles/functor/misc/TotalCellOffset.hpp, include/picongpu/particles/manipulators/generic/Free.hpp, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.hpp, include/picongpu/particles/startPosition/generic/Free.hpp, include/picongpu/particles/startPosition/generic/FreeRng.hpp, include/pmacc/functor/Filtered.hpp, include/pmacc/functor/Interface.hpp
fix: RNG segfault first seen in #2554 
We call the `rng` init several times with virtual workers.
The `rngHandle` generates a table of states on which is one selected on `RngHandle::init()`.
By copying the handle first, we make sure that each virtual worker starts from the same initial `rngHandle`, which avoids double-shifts which result in out-of-memory access.
Set functor interface to create the on device functor of an host functor to `const` to avoid side effects if an worker in lockstep programming is deriving the device functor multiple times from the same base host functor.
- PMacc functor interface change: const on device functor factory
- PIConGPU: const functor on device factory
- `Rng.hpp`: create a copy of the RNG handle before calling `init()`
- const-ify the factory method to …
=>  PMAcc functor: const on device functor factory

include/pmacc/nvidia/atomic.hpp, include/pmacc/nvidia/warp.hpp
fix #2514
If NVIDIA TESLA V100 is used with a CUDA9.X the gpu is deadlocking.
The reason for the deadlock is the wrong usage `__ballot_sync`.
Solved by using `__activemask()` to call for active lanes in the warp.
- change interface of `warpBroadcast`: remove `laneMask`
=> fix V100 deadlock

bin/pic-configure, include/pmacc/traits/GetNumWorkers.hpp
This PR allows to use more cpu accelerators. To simplify debugging it often helps to run the program serial, which is now supported.
- add accelerator `serial` == `ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE`
- add accelerator  `tbb` == `ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE`
- update `pic-configure`
=> add support for more cpu alpaka accelerators

include/pmacc/random/distributions/distributions.hpp, include/pmacc/random/methods/AlpakaRand.hpp, include/pmacc/random/methods/MRG32k3aMin.hpp, include/pmacc/random/methods/XorMin.hpp, include/pmacc/random/methods/methods.hpp
- add `cupla::Acc` as default accelerator (template interface)
- add a accumulative include for random `methods` and `distributions`
Because of the reason that PMacc is depending on `cupla` and mostly used with one accelerator the interface for defining a random number method from the user side looks much more easier if the method is by default specialized for the accelerator activated in cupla.
This change is a requirement to expose the used random number generator method in PIConGPU to the user.
=> PMacc: refactor RNG method interface

include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp
Within PIConGPU the random numbers generated are set hard to `float`. The user is allowed to change the precision in `precision.param` thus also the random numbers should have the user defined precision.
- remove the usage of `float` with `float_X`
**Note:** The latest release is also effected by this bug but due to the missing `double` precision implementation for the used random number generator in `0.3.X`  it is not easy fixable.
=> remove usage of pure `float` with `float_X`

include/pmacc/mappings/simulation/EnvironmentController.hpp
`friend struct detail::Environment;` can  not be used if the namespace `detail` is not known in the file.
- include `pmacc/Environment.def`
- remove forward declaration
=> fix missing include

docs/source/usage/param/misc.rst, include/picongpu/_defaultParam.loader, include/picongpu/param/random.param, include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp, include/picongpu/particles/functor/misc/Rng.hpp, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp, include/picongpu/simulationControl/MySimulation.hpp
Remove the hard coded `XorMin` method with the user changeable `RandomGenerator` from `random.param`
- rename `seed.param` into `random.param`
- remove unused seeds for particles, temperatures, ...
- add type definition `RandomGenerator` (can be changed by the user)
=> expose random number method to the user

include/picongpu/param/random.param, include/picongpu/random/seed/ISeed.hpp, include/picongpu/random/seed/Seed.cpp, include/picongpu/random/seed/Seed.hpp, include/picongpu/simulationControl/MySimulation.hpp
In some cases it is useful to initialize the random number generator
always with the same value to increase the reproducibility of different
simulation runs. IN some cases the opposit is required.
- re-enable the possibility to choose the seed
- add different seed generators:
- seed::Value<...>
- seed::FromEnvironment
- seed::FromTime
**The seed generators can be moved into `PMacc` as soon as we remove the requirement that PMacc must be header only.**
=> seed generator for RNG

include/picongpu/random/seed/Seed.cpp
It is currently not possible to compile PIConGPU due to a compiler error (Tested with gcc 5.3.0):
```
include/picongpu/random/seed/Seed.cpp:60:20: error: ‘stoi’ is not a member of ‘std’
seed = std::stoi( seedStr );
```
- add missing include `<string>`
This bug was introduced with #2607
=> (compile issue) fix random seed

include/picongpu/fields/FieldManipulator.kernel, include/picongpu/plugins/IntensityPlugin.hpp, include/picongpu/simulationControl/MySimulation.hpp, include/pmacc/fields/operations/AddExchangeToBorder.hpp, include/pmacc/fields/operations/CopyGuardToExchange.hpp, include/pmacc/particles/ParticlesBase.hpp
A few algorithms in PMacc and PIConGPU was not able to handle more than one guard supercell.
This algorithm assumes always one supercell as guard.
Fix:
- take in account the number of used guarding super cells
- `MySimulation.hpp`: fix grid layout initialization.
- `ParticlesBase.hpp`: fix that guarding cells are passed as parameter into `ParticlesBuffer` instead of the supercell size
**Note** The latest release is also effected by this issue that the guard size must be always one. Since the change of the number guard supercells is more than less a feature we should not back port this fix.
Other bugfixes those are needed to solve the ssumtion that the guard size is always one: #2613
=> fix that guard size must be one

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, include/picongpu/CMakeLists.txt
Since ISAAC 1.3.0 forgot to bump the version define, CMake will not find it with required minimum versions.
1.3.1 fixed that.
Update: there seem to be more issues with ISAAC... hard to figure out after a year without a changelog and PRs. We will go for the latest release 1.3.3+.
ISSAC `${ISAAC_INCLUDE_DIRS}` is even in 1.3.3 broken and points to CMake dir instead of include dir: https://github.com/ComputationalRadiationPhysics/isaac/issues/68
Update: work-arounded both in spack recipe of PIConGPU and compile suite ISAAC module by explicitly setting `CPATH` to ISAAC include dir...
Going for ISAAC 1.3.3 since we fixed some boost and CUDA 9 issues AFAIR.
=> ISAAC 1.3.3+

docs/source/usage/plugins/particleCalorimeter.rst, docs/source/usage/plugins/phaseSpace.rst
Fix outdated and missing filter flags in examples of the phase space and particle calorimeter plugin.
Discovered by @kossag14, thx!
=> PS & Calorimeter Plugins: Filter Docs

include/picongpu/fields/LaserPhysics.hpp, include/picongpu/fields/laserProfiles/ExpRampWithPrepulse.hpp, include/picongpu/fields/laserProfiles/GaussianBeam.hpp, include/picongpu/fields/laserProfiles/None.hpp, include/picongpu/fields/laserProfiles/PlaneWave.hpp, include/picongpu/fields/laserProfiles/Polynom.hpp, include/picongpu/fields/laserProfiles/PulseFrontTilt.hpp, include/picongpu/fields/laserProfiles/Wavepacket.hpp
Increase readability of laser profile implementations by using C++11 literals for constant numbers with suffix `_X` instead of `float_X( ... )`.
=> Lasers: float_X Constants to Literals

include/picongpu/param/density.param, include/picongpu/param/particle.param, include/picongpu/param/particleCalorimeter.param, include/picongpu/param/png.param, include/picongpu/param/pngColorScales.param, include/picongpu/param/speciesAttributes.param, include/picongpu/param/speciesConstants.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/density.param, share/picongpu/examples/Bunch/include/picongpu/param/png.param, share/picongpu/examples/FoilLCT/include/picongpu/param/particle.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/png.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/density.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/png.param, share/picongpu/examples/WarmCopper/include/picongpu/param/particle.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/png.param
Increase readability of input `.param` files by using C++11 literals for constant numbers with suffix `_X` instead of `float_X( ... )`.
=> Params: float_X Constants to Literals

INSTALL.rst, include/pmacc/PMaccConfig.cmake
Sadly, the truly working GCC range is smaller than the official CUDA support. This is caused by missing support of `std::tuple` which is pulled easily in dependencies such as boost.
The latest NVCC 9.2 is supposedly good as it adds official `std::tuple` support and even support for GCC 7.
Close #2388
=> Limit Supported GCC with nvcc 8.0-9.1

INSTALL.rst, include/picongpu/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, thirdParty/mallocMC/CHANGELOG.md, thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/version.hpp
Updates mallocMC:
- Fix V100 Active Lanes in Warp [#145](https://github.com/ComputationalRadiationPhysics/mallocMC/pull/145)
From
- `mallocMC@dev` (https://github.com/ComputationalRadiationPhysics/mallocMC/commit/3531c29c0d2a88be45508a789eab624cb0dd4fc5)
to
- `mallocMC@2.3.0crp` (https://github.com/ComputationalRadiationPhysics/mallocMC/tree/4b779a34cd8ba073b24f69435d71022f3988d42e == [2.3.0crp](https://github.com/ComputationalRadiationPhysics/mallocMC/tree/2.3.0crp))
```bash
git subtree pull --prefix thirdParty/mallocMC \
git@github.com:ComputationalRadiationPhysics/mallocMC.git 2.3.0crp --squash
```
=> Update mallocMC to 2.3.0crp

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, include/picongpu/CMakeLists.txt
Require the latest ISAAC release for PIConGPU.
This release fixes a CMake install issue and several rendering artifacts in border regions.
For details please refer to:
https://github.com/ComputationalRadiationPhysics/isaac/releases/tag/v1.4.0
I updated the compile suite with the new release.
=> ISAAC: 1.4.0+

INSTALL.rst, include/pmacc/PMaccConfig.cmake
CUDA 9.2 will not yet run as alpaka first has to support it.
Know alpaka 0.3.1 issue:
- https://github.com/ComputationalRadiationPhysics/alpaka/issues/525
Tested alpaka 0.3.1 CUDA releases are 7.0 - 9.1:
- https://github.com/ComputationalRadiationPhysics/alpaka/blob/0.3.1/.travis.yml#L54
PIConGPU currently works with CUDA 8.0+ (and 7.5 in some limited cases, we removed official support).
=> Doc: CUDA 9.2 not yet supported

INSTALL.rst, include/pmacc/PMaccConfig.cmake
Allow to use CUDA 8.0 together with gcc 5.0 to 5.3.
The support for this compiler combination was removed with #2628.
Note: I used `gcc/5.3.0` and `cuda/8.0` together since over a year and have no issues.
=> re-enable CUDA 8.0 and gcc 5.0 - 5.3 support

docs/TBG_macros.cfg, docs/source/usage/plugins/adios.rst
Add missing `transport-params` option to ADIOS manual (was only present in `docs/TBG_macros.cfg`).
Also add blosc usage example for compression.
=> ADIOS: More Transport & Compression Doc

INSTALL.rst, include/pmacc/PMaccConfig.cmake
Specify maximum supported GCC due to std::tuple issues in nvcc <= 9.1
This just adds GCC 5.5 explicitly to the docs.
Follow-up to #2636
=> NVCC 8.0 GCC <= 5.3 && 9.0/9.1: GCC <= 5.5

include/picongpu/fields/laserProfiles/GaussianBeam.def
With the refactoring of the laser code (#2587), a bug was introduced that only appears when using a CPU back-end. (According the @psychocoderHPC, the `nvcc` does not check this not-used code, thus the error is not thrown.) 
This pull request fixes this issue by adding the `default::` namespace to the Laguerre mode attributes set before.  
The error occurs when compiling the `LaserWakefield` example using the `etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example`.
Thanks @psychocoderHPC for all your explanations on that issue.
=> fix namespace issue in default GaussLaguerre  laser

include/pmacc/particles/ParticlesBase.kernel
By definition our last frame is allowed to not be fully filled with particles.
To reduce the memory foot print the last frame, it should never be empty after all gaps are filled.
This is currently not always the case.
Remove the last frame in the a supercell in `KernelFillGapsLastFrame` if it is empty.
@theZiz thx for helping me to find this issue with your graphical debugging tool [ISAAC](https://github.com/ComputationalRadiationPhysics/isaac) :-)
=> remove empty last frame

include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
In `PhaseSpace.tpp` both the `axis_p_range` as well as the `pRange_unit` contain the factor m_species (species mass in electron masses). That resulted in the momentum range being too large for all ions when later momentum values are multiplied by this `pRange_unit`.
This commit fixes that issue.
Now the momentum range in the plots created e.g. with the [script from the plugin documentation](https://picongpu.readthedocs.io/en/latest/usage/plugins/phaseSpace.html?highlight=phase%20space#analysis) are correct as well and correspond to the momentum limits from the `cfg` file.
**FoilLCT example: `4.cfg`**
```Shell
TBG_e_PSypy="... --e_phaseSpace.min -2.0 --e_phaseSpace.max 2.0"
TBG_H_PSypy="... --H_phaseSpace.min -0.04 --H_phaseSpace.max 0.04"
TBG_C_PSypy="... --C_phaseSpace.min -0.02 …
```
=> Plugin PhaseSpace: fix momentum meta information

docs/source/install/profile.rst, etc/picongpu/pizdaint-cscs/picongpu.profile.example
Marco's script takes into account the limited quota on $HOME and builds the libraries in `/dev/shm`. I just tested it and it runs fine.
=> Update Piz-Daint installation script

include/picongpu/initialization/InitialiserController.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp
Change the "GPU" naming to "device" naming. A device can be a multi-core CPU, a GPU or similar.
=> Log: per device instead of GPU

include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/Manipulate.hpp
The algorithm `Manipulate` and `ManipulateDerive` allows to set a particle.
This filter was not provided with the species information.
- apply corresponding species to the filter functor
=> fix `Manipulate*`

include/picongpu/particles/filter/generic/FreeRng.def, include/picongpu/particles/filter/generic/FreeRng.hpp, include/picongpu/particles/functor/misc/Rng.def, include/picongpu/particles/functor/misc/Rng.hpp, include/picongpu/particles/manipulators/generic/FreeRng.def, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/startPosition/generic/FreeRng.def, include/picongpu/particles/startPosition/generic/FreeRng.hpp
PIConGPU RNG functors, filters and startPosition functors have the species type in the tempate signature. This type is not needed. 
The species was a left over from the old random number generator.
- remove unused template species signature from RNG functors
=> remove unused species template signature

include/picongpu/param/physicalConstants.param, include/picongpu/param/unit.param, include/picongpu/unitless/physicalConstants.unitless
We need the speed of light and its normalization very
early in other `.param` files, e.g. to define energy filters.
This work-arounds this by defining it earlier than `unit.param`
Close #2585
=> Early Normalized Speed of Light

lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
Fix the python module plotting the energy histogram plugin on several issues:
- data order: order of x-y arguments mismatched
- update image: rescale properly in log axes
- labels: typo fixed, iteration removed
=> Python: EnergyHistogram MPL Plot

include/picongpu/main.cpp, include/pmacc/types.hpp
Newer versions of GCC, such as gcc 7.1, throw a warning in `-Wextra` on fallthrough.
So let's explicitly try to annotate it.
=> fix fallthrough warning

include/pmacc/types.hpp
Missed that this attribute is unknown prior to GCC 7 and causes a warning.
Replace with NOP in that case.
In clang it's in all supported versions (e.g. in [clang 3.7+](https://releases.llvm.org/3.7.0/tools/clang/docs/AttributeReference.html#fallthrough-clang-fallthrough))
Follow-up to #2665
=> gnu::fallthough is GCC 7+

include/picongpu/fields/FieldTmp.hpp, include/picongpu/fields/FieldTmp.tpp, include/pmacc/memory/buffers/ExchangeIntern.hpp
Fix a memory leak found with valgrind in:
- `ExchangeIntern.hpp`
- `FieldTmp`
Use `std::unique_ptr` instead of native pointers to avoid memory leaks.
=> fix memory leaks PMacc/PIConGPU

include/picongpu/plugins/adios/ADIOSWriter.hpp
There is no need to set `adios_set_max_buffer_size`. It sets the maximum ADIOS is allowed to allocate in its buffers (but this call does not pre-allocate things).
But the actual buffer is since ADIOS 1.10.0 already dynamically allocated (#1639) and the default for maximum allocation is a large default. If we later on want to control host-side memory, we can just set a ratio of free host mem, but ADIOS will only allocate what it actually needs until then.
See
https://github.com/ornladios/ADIOS/commit/9fae0d12fea535a4366e81c0c04d7a3be54c3179
Fix #2656 (Crashes reported in some cases since our buffer estimate was not precise enough.)
=> ADIOS: No adios_set_max_buffer_size

include/picongpu/unitless/png.unitless
Fix #2674: PNG laser-selection & field scaling static asserts: did not work with clang.
=> PNG Unitless: Fix Static Asserts

include/picongpu/simulationControl/MySimulation.hpp
Use consequent "device" instead of "GPU" naming in program option help and memory error messages.
=> MySimulation: GPU => Device
