include/pmacc/PMaccConfig.cmake
Exclude old, definitely unsupported, buggy and not-worth-the-workaround compilers in CMake.
Throws early and fatal, so users know directly their software environment is too old.
Clang 3.8 exclusion (and [Xcode < 8.0](https://en.wikipedia.org/wiki/Xcode)) related to #2300
=> PMacc: Min GCC & Clang

include/picongpu/particles/filter/generic/FreeTotalCellOffset.hpp, include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.hpp
Functor and filter `FreeTotalCellOffset` can not be used (code is not compiling) because the factory method is missing the const quallifier.
=> fix missing const quallifier

include/picongpu/plugins/IsaacPlugin.hpp
With gcc 5.4 PIConGPU combined with ISACC is not compiling.
The reason is that the compile needs a hint that a method it templated.
Bug found by @FelixTUD
=> fix gcc compile of IsaacPlugin

thirdParty/alpaka/alpakaConfig.cmake, thirdParty/alpaka/appveyor.yml, thirdParty/alpaka/include/alpaka/core/Unused.hpp, thirdParty/alpaka/include/alpaka/rand/RandStl.hpp, thirdParty/alpaka/include/alpaka/rand/TinyMT/Engine.hpp, thirdParty/alpaka/include/alpaka/rand/TinyMT/LICENSE.txt, thirdParty/alpaka/include/alpaka/rand/TinyMT/tinymt32.h, thirdParty/alpaka/script/travis/install_clang.sh, thirdParty/alpaka/test/unit/rand/src/RandTest.cpp, thirdParty/alpaka/test/unit/stream/src/StreamTest.cpp
Improved Alpaka CPU RNG state. Fix #2653
Update alpaka from 
- release  alpaka@0.3.2 (ComputationalRadiationPhysics/alpaka@847aed6 == [`0.3.2`](https://github.com/ComputationalRadiationPhysics/alpaka/tree/0.3.2) )
to
- release  alpaka@0.3.3 (ComputationalRadiationPhysics/alpaka@172b9e2a4974a86e312cc4fb170556438e2dcc8e == [`0.3.3`](https://github.com/ComputationalRadiationPhysics/alpaka/tree/0.3.3) )
- add CPU random number generators based on `std::random_device` and TinyMT32
- made TinyMT32 the default random number generator
- add `alpaka::ignore_unused`
```
git subtree pull --prefix thirdParty/alpaka \
git@github.com:ComputationalRadiationPhysics/alpaka.git 0.3.3 --squash
```
=> Alpaka 0.3.3

include/picongpu/initialization/InitialiserController.hpp, include/picongpu/plugins/IntensityPlugin.hpp, include/picongpu/plugins/IsaacPlugin.hpp, include/picongpu/plugins/PhaseSpace/DumpHBufferSplashP.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp, include/picongpu/plugins/adios/ADIOSCountParticles.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/NDScalars.hpp, include/picongpu/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, include/picongpu/plugins/adios/restart/LoadSpecies.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/NDScalars.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, include/picongpu/plugins/hdf5/restart/LoadSpecies.hpp, include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/writer/Field.hpp, include/picongpu/plugins/hdf5/writer/ParticleAttribute.hpp, include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp, include/picongpu/plugins/output/GatherSlice.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp, include/pmacc/cuSTL/algorithm/mpi/Gather.tpp, include/pmacc/cuSTL/algorithm/mpi/Reduce.tpp, include/pmacc/mpi/MPIReduce.hpp, include/pmacc/mpi/reduceMethods/AllReduce.hpp, include/pmacc/mpi/reduceMethods/Reduce.hpp, include/pmacc/simulationControl/SimulationHelper.hpp, share/pmacc/examples/gameOfLife2D/include/GatherSlice.hpp
Our event system in PMacc is not running in a separate threads. If we call a blocking operation e.g. MPI_Barrier or MPI collective operations and there are open tasks in the event system queue it could be that the full simulation is freezing. The reason is that it is possible that a MPI process `1` is waiting for a MPI operation which is never opened from the peer rank `2` because the peer is hanging in an other blocking operation those can not be finsihed until the rank `1` starting the corresponding counter part operation.
Parts of the bugs was already fixed in #1659 but we missed that this is a behavior with all blocking operations e.g. MPI blocking operations, MPI blocking collectives and parallel file system operations those mostly also use MPI blocking collectives.
=> fix possible deadlock in blocking MPI ops

etc/picongpu/hypnos-hzdr/k20_restart.tpl, etc/picongpu/hypnos-hzdr/k80_restart.tpl, src/tools/bin/nextstep_from_period.sh
Write a script for computing next step from the new-style period syntax.
Necessary for restart.tpl, which has to extract the parameters for the next restart.
=> Restart TPLs: new checkpoints.period syntax

include/pmacc/particles/ParticlesBase.hpp, include/pmacc/particles/ParticlesBase.kernel, include/pmacc/particles/memory/dataTypes/SuperCell.hpp, include/pmacc/test/particles/memory/SuperCell.hpp, include/pmacc/test/particles/particlesUT.cpp
Extent the supercell to be aware about the number current number of particles.
- SuperCell:
- add method `getNumParticles()`
- remove method `setSizeLastFrame()`
- add method `setNumParticles()`
- re-format SuperCell to the new code style
- add const to read only methods
- ParticleBase
- count number of particles during `KernelShiftParticles` and fill gaps kernel
- add unit test to test the supercell method `getSizeLastFrame()`
The second commit contains only the code style changes and add const to read only methods  of the supercell.
I am not sure if we should put this PR into 0.4.0 or wait until we opened the release branch.
=> supercell particle counter

include/picongpu/fields/LaserPhysics.hpp
This fixes the wrong laser initialization on CPUs due to a reuse of the laser functor in the `ForEachIdx` loop (issue #2688).
co-authored by @psychocoderHPC.
=> fix laser init on cpu

INSTALL.rst, USAGE.rst, docs/source/install/instructions/docker.rst, docs/source/install/instructions/source.rst, docs/source/install/instructions/spack.rst, docs/source/usage/param.rst, docs/source/usage/tbg.rst, include/pmacc/PMaccConfig.cmake
- add `tbg` section
- update "basic usage" section:
- fix outdated .cfg file names
- improve clarity and structure
- update install instructions:
- refresh version ranges
- update min. alpaka
- add notes, e.g. to spack and use nvidia docker 2+
- replace wget with more widespread curl command (linux/osx)
- remove untar verbosity
Greetings from Toronto Airport!
=> Manual: Updates for 0.4.0

include/picongpu/plugins/output/WriteSpeciesCommon.hpp, include/pmacc/memory/buffers/MappedBufferIntern.hpp
For HDF5 checkpoints and normal dumps we use CUDA mapped memory to transfere the particles to the host memory. Due to the usage of cupla and the reason that mapped memory is not supported by cupla and alpaka we fall back to native CUDA functions. To free mapped memory the function `cudaFreeHost`. This function is also used to free normal host memory allocated with `cudaMallocHost` which is supported by cupla.
The cupla internal macros rename `cudaFreeHost` to `cuplaFreeHost` and fall back to alpaka functionallity to free the memory. In the case where we allocated the memory without the knowledge of cupla, cupla is trowing an error and `cudaFreeHost` will never be called.
The result in PIConGPU is that with each particle dump the host memory footprint grows until we run out of memory.
- …
=> fix out of host memory during HDF5 dumping

src/tools/bin/plotNumericalHeating
fix: #2687
The field energy is ignored/not used in the tool `plotNumericalHeating`.
This results into a wrong heating plot.
- add usage of `fields_energy.dat`
- fix documentation
=> fix plotting tool for numerical heating

bin/pic-configure
fix #2694
Allow the PIConGPU user to select the alpaka accelerator `ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE`.
This accelerator is called in PIConGPU `threads`.
- add `threads` to the `-b` option of `pic-configure`
- update help of `pic-configure`
=> accelerator `threads`

include/pmacc/mappings/kernel/MappingDescription.hpp, share/pmacc/examples/gameOfLife2D/include/Evolution.hpp, share/pmacc/examples/gameOfLife2D/include/Simulation.hpp
The game of life example has a runtime issue that the mapping description verification
to check the number of supercells is always twrowing an error. The reason it that the
not existing default constructor is `MappingDescription` is used.
Please do not ask me why the code before is compiling. The class `MappingDescription` has no default constructor but is a not initialized member of the class `Evolution<>` which means by definition the default constructor should be called. Due to the fact that there is a user defined constructor there should be no default constructor available. 
Error message:
```
./gameOfLife -d  1 1  -g 128 128 -p 1 1 -r 23/3 -s 100
newborn if=3 stay alive if=23 mask=4108
terminate called after throwing an instance of 'std::runtime_error'
what():  expression (( …
```
=> fix gameOfLife

include/pmacc/cuSTL/algorithm/kernel/run-time/Foreach.hpp, include/pmacc/cuSTL/container/assigner/DeviceMemAssigner.hpp
Deprecation warning in Boost 1.67+
```
include/boost/math/common_factor_rt.hpp:13:93:
note: #pragma message: This header is deprecated.
Use <boost/integer/common_factor_rt.hpp> instead.
BOOST_HEADER_DEPRECATED("<boost/integer/common_factor_rt.hpp>");
```
https://github.com/boostorg/math/blob/boost-1.67.0/include/boost/math/common_factor_rt.hpp
=> Boost: Deprecated Math Header

docs/source/usage/plugins/countParticles.rst, docs/source/usage/plugins/countPerSupercell.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/hdf5.rst, docs/source/usage/plugins/intensity.rst, docs/source/usage/plugins/particleCalorimeter.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/png.rst, docs/source/usage/plugins/radiation.rst, share/picongpu/examples/Bunch/include/picongpu/param/radiation.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiation.param
This pull request fixes various misspelled words in the read-the-docs plugin documentation.
Some errors pointed to further mistakes in the radiation plugin, which have been fixed too.
=> fix misspelled words in plugin documentation

bin/tbg
If the path to `egetopt` is not in the environment variable `PATH` tbg falls back to use the `egetopt` in the same location as `tbg` itself. In that case the command `which` is throwing a long error message that egetopt can not be found.
This PR hide the error message and create an own error message if needed.
=> fix tbg error message

lib/python/picongpu/utils/param_parser.py
This PR adds a python script that can be used from the command line.
It allows to read and filter JSON files as generated by the jupyter notebook UI  based on their status (either compile-time or runtime parameter).
It returns CMAKE define strings that can be further processed by pic-configure to define the given parameter values in the picongpu simulation.
The JSON file structure is assumed to be like here:
```
{
"_A0": {
"type": "compile",
"values": [
41.69166666666667
]
},
"WAVE_LENGTH_SI": {
"type": "compile",
"values": [
8.000000000000001e-07
]
},
"PULSE_LENGTH_SI": {
"type": "compile",
"values": [
5.000000000000001e-15
]
},
"BASE_DENSITY_SI": {
"type": "compile",
"values": [
9.99539589003089e+24
]
},
"TBG_STEPS": {
"type": "run",
"values": [
7841
]
}
}
```
At the moment we use this …
=> Python: param_parser for JSON parameter files

lib/python/picongpu/plugins/sliceFieldReader.py
Use of `map()` changed from Python 2 to 3 which results in an error when using the function now. This PR avoids the map function but uses a (more pythonic) list comprehension which is also version independent.
A grammar error in a comment is corrected as well.
=> Fix sliceFieldReader

docs/source/install/instructions/spack.rst
Document more modern compilers for Spack install method.
By default, spack takes the latest supported (CUDA) version which supports GCC 7.
Document older releases with according older GCC as alternatives. Close #2693
=> Docs: Spack GCC Compiler CUDA

docs/requirements.txt
Fix readthedocs sphinx to version 1.7 since the latest
1.8 release line has a bug rendering overloaded C++ code with breathe.
Upstream issue: https://github.com/sphinx-doc/sphinx/issues/5496
=> RTD: Sphinx 1.7

etc/picongpu/hypnos-hzdr/fermi.tpl, etc/picongpu/hypnos-hzdr/k20.tpl, etc/picongpu/hypnos-hzdr/k20_autoWait.tpl, etc/picongpu/hypnos-hzdr/k20_restart.tpl, etc/picongpu/hypnos-hzdr/k20_vampir.tpl, etc/picongpu/hypnos-hzdr/k20_wait.tpl, etc/picongpu/hypnos-hzdr/k80.tpl, etc/picongpu/hypnos-hzdr/k80_restart.tpl, etc/picongpu/hypnos-hzdr/laser.tpl
`cuda_memtest` can currently only be used if the node is exclusive allocated by the user and no other job is running on it.
All hypnos template files for hypnos supports that the user can allocate only a subset of a node. In this case `cuda_memtest` will crash if an other user/job is already using gpu zero.
This PR will disable the GPU memory test if the job has not alloacted all GPUs.
- remove PBS option `-n` (exclusive node usage) because it is not working on hypnos
- disable the test `cuda_memtest` if node is not exclusive allocated
It would be possible to mark this PR as `bug` because the way how `cuda_memtest` is used is wrong.
=> cuda_memtest usage on hypnos

docs/source/install/profile.rst, etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
- add tbg templates for hemera (HZDR) cluster CPU/GPU
- add hemera profiles
Note: PIConGPU will not compile on hemera until https://github.com/ComputationalRadiationPhysics/picongpu/pull/2685/files#diff-d1fb8e3eeab4d2001da0932360713480R373 is removed. We can remove it as soon as PIConGPU based on alpaka 0.3.4
=> hemera tbg templates

INSTALL.rst
This pull request adds an additional bullet point for building hdf5 from source. Based on the discussion on #2667, it is a quite common issue to run into linking errors with MPI when configuring HDF5. This can be solved by specifying to use the MPI compilers instead of the default ones (set e.g. by the GCC/ICC module). This new bullet point adds this missing information.
=> add MPI linking info in install documentation

lib/python/picongpu/plugins/plot_mpl/base_visualizer.py, lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py, lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py, lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
This PR makes the API of the visualizers a bit clearer by passing the matplotlib axes on creation instead of only passing it in the `visualize(ax,...)` call. 
So far this API kind of suggested that it is possible to switch the figures between multiple visualization calls which in fact does not happen since the `self.plt_obj` is still tied to the previous axes.
Now there should be no ambiguity anymore.
Please merge this before #2691 since this still makes use of the API that is currently used.
=> Visualizers: axes passed on startup

docs/requirements.txt, docs/source/conf.py, docs/source/dev/py_postprocessing.rst, docs/source/usage/plugins.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/png.rst
Adds sections on how to develop and use the new python tools.
~~It already includes documentation for the jupyter_widgets as well (see #2691)~~
=> Plugin Docs: Python Tools & Matplotlib

docs/requirements.txt, docs/source/postprocessing/openPMD.rst, docs/source/postprocessing/python.rst
Update projects around openPMD and link openPMD-api.
Also corrects the `docs/requirements.txt` to fix the failing RTD build introduced in #2726.
=> Docs: openPMD Update

INSTALL.rst
This pull request fixes a configuration typo in setting parallel write attributes.
Thanks @psychocoderHPC for pointing to the error. 
Thanks @steindev for showing me the browser based commit system.
=> fix typo in libSplash in install documentation

etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example
Prepare an updated environment for the Taurus SCS5 software stack.
In order to use the new software stack, make sure to log into the login nodes
- tauruslogin4 or
- tauruslogin6
If you are an active Taurus user, please feel free to contribute further to this PR.
- https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/SystemTaurus
- https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/HardwareTaurus
- https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/RuntimeEnvironment
=> Taurus: SCS5 Update

etc/picongpu/bash/mpiexec.tpl, etc/picongpu/bash/mpirun.tpl, share/picongpu/dockerfiles/README.rst, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/modules.yaml, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml, share/picongpu/dockerfiles/ubuntu-1604/start_foil_4.sh, share/picongpu/dockerfiles/ubuntu-1604/start_foil_8.sh, share/picongpu/dockerfiles/ubuntu-1604/start_khi_1.sh, share/picongpu/dockerfiles/ubuntu-1604/start_khi_4.sh, share/picongpu/dockerfiles/ubuntu-1604/start_khi_8.sh, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa_4.sh, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa_8.sh, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa_live.sh, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa_live_4.sh, share/picongpu/dockerfiles/ubuntu-1604/start_lwfa_live_8.sh, share/picongpu/examples/FoilLCT/etc/picongpu/4_isaac.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/8.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/8_isaac.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/1.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/1_bench.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4_bench.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/8_bench.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4_isaac.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8_isaac.cfg
This is a WIP PR documenting the changes to make PIConGPU
- run on the nvidia cloud NGC: https://ngc.nvidia.com/
- run on multiple GPUs inside a docker container
- fix MPI issues inside containers with multiple ranks, e.g. https://github.com/open-mpi/ompi/issues/4948
latest change:
- make MPI CUDA aware
As before, the corresponding [spack](http://spack.io/) recipe is uploaded [here](https://github.com/ComputationalRadiationPhysics/spack-repo/tree/gh-pages/packages/picongpu).
=> Improved Docker & NGC

docs/source/conf.py, lib/python/picongpu/plugins/data/requirements.txt
Mock imports during sphinx build that are not essential. Allows to parse doc strings without the need of accessing and installing otherwise unneeded third-party Python modules.
=> RTD: Mock Sphinx Imports

include/pmacc/types.hpp
Take no risk, replace the (only) occurrence of this header with the Alpaka workaround.
See:
- https://github.com/ComputationalRadiationPhysics/alpaka/pull/606
- https://github.com/boostorg/predef/pull/84
=> Boost 1.68.0 Predef

docs/source/models/field_ionization_comparison_c_ii_ionization.py, docs/source/models/field_ionization_effective_potentials.py, lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py, lib/python/picongpu/utils/find_time.py, src/tools/bin/plot_chargeConservation.py, src/tools/bin/plot_chargeConservation_overTime.py
Python regular expressions need a `r''` literal.
Fix a recently introduced flake8/pycodestyle warning (that let's the CI fail).
=> Python Regex: r Literals

share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param
This syntax is obsolete with the new version (0.4.0). 
Since it was not captured by the compile suite, this case is probably never checked. 
Should we add it to the compile suite?
=> fix outdated derive species

share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param
This pull request fixes a bug in the bunch example.
Thank you @lehnertu for discovering it!
The current deposition should be deactivated for this example since otherwise the bunch gets pulled back by the remaining "virtual" ions.
=> remove current deposition in bunch example

include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp
fix #2763
The number of skipped cells for the functor is due to a bug always dominated by the dimension with the smallest value. If one dimension is one than each cell is used even if other dimensions has a larger value.
=> fix EveryNthCellImpl

docs/source/usage/plugins/radiation.rst
This fixes the documentation of the radiation plugin for 2D simulations.
(re-) close https://github.com/ComputationalRadiationPhysics/picongpu/issues/289
=> Fix docs for radiation in 2D

share/picongpu/dockerfiles/README.rst, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/Singularity
Update docs for containers to latest release. Update singularity registry usage: no public registry anymore unless used with github-controlled builders. Use own registry instead.
=> Containers: Update 0.4.0

include/picongpu/param/pusher.param, include/picongpu/param/species.param, include/picongpu/particles/pusher/particlePusherAcceleration.hpp, include/picongpu/unitless/pusher.unitless
Implements a particle pusher which accelerates particles by a constant force. This resembles the idealized situation of accelerating in the electric field of a planar capacitor.
The electric field strength and duration of acceleration can be adjusted in the `pusher.param`. The pusher was tested by initializing a `gaussianCloud` electron gas and accelerating at a field strength of `1GeV/cm` for 518fs(=2225 DT).
If requested, I can upload an example setup for its use.
=> Particle pusher acceleration

lib/python/picongpu/plugins/data/radiation.py
This pull request closes issue #2759 by adding the missing getters for frequency (omega) and observation direction (n) . It still does not make it compatible to the standard iteration oriented interface.
=> Add getter for omega and n to python module

docs/source/dev/py_postprocessing.rst, lib/python/picongpu/plugins/data/base_reader.py, lib/python/picongpu/plugins/data/energy_histogram.py, lib/python/picongpu/plugins/data/phase_space.py, lib/python/picongpu/plugins/data/png.py, lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py, lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py, lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
This PR makes use of the `FindTime` class and adds it to the data readers. This offers the possibility to query for simulation times directly instead of only query for iterations.
Besides, the readers now return an array of data items when multiple iterations are given in the `get` methods instead of dictionaries. This was done to allow reusing the same function for getting data regardless of whether `time` or `iteration` parameter were provided.
=> Python Tools: Incorporate sim_time into readers and visualizers

include/picongpu/simulationControl/MovingWindow.hpp
If someone is querying the moving window class with a time step which is less than
the current simulation step it can happen that the window is sliding.
- only allow sliding if the time step is larger than the last slide point
=> avoid two slides

share/picongpu/examples/FoilLCT/include/picongpu/param/particle.param
The `_X` syntax was missing in the `OnceIonized` manipulator in the `FoilLCT` example
It now matches the `TwiceIonized` manipulator and also has the correct data type for `protonNumber`.
=> Use _X syntax in OnceIonized manipulator

docs/source/install/instructions/spack.rst
If the bootstrap pulls in environment modules, these need to be activated. Improve command order to avoid sourcing twice.
Fix #2770
=> Spack: Improve Bootstrap

docs/source/usage/plugins/phaseSpace.rst, lib/python/picongpu/plugins/data/phase_space.py, lib/python/picongpu/plugins/data/png.py
This adresses a TODO in the `PhaseSpaceData` class to allow for queries of a list of iterations.
It also changes the parameter order of the interface calls by moving the `ps` argument to the front and providing a default to `species_filter` as in the other reader classes.
=> PhaseSpaceData: allow multiple iterations

thirdParty/cuda_memtest/cuda_memtest.h
Updates cuda_memtest:
- NVML Checks: stderr Writing [#18](https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/18)
From
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/21050ab1b851944e3f9f64348a43abe966ac5379) to
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/6d505ea392f51ac69d02eafd866f6d3456cadec7)
```bash
git subtree pull --prefix thirdParty/cuda_memtest \
```
=> Update cuda_memtest: NVML Noise

lib/python/picongpu/plugins/data/energy_histogram.py
Fixes #2798.
Also fixes an issue with the exception thrown when an invalid iteration is requested. Since the iterations are the index of the `pd.DataFrame` they are not regular columns anymore and can not be indexed by `data['iteration']`
=> Fix Python EnergyHistogramData: skip of first iteration

INSTALL.rst, docs/source/index.rst, docs/source/install/instructions/source.rst, docs/source/install/instructions/spack.rst, docs/source/install/path.rst, docs/source/usage/reference.rst
A little inspired by #2705 , I've read a little portion of the docs as a bedtime literature (no PIC-related dreams, in case someone was wondering) and made some notes.
A short comment on some of the fixes: the installation guide had an absurd amount of `you` and `yours`, reduced somewhat, also 'sub-ideal' is not a word (although would be useful).
In addition to the fixes in the PR, here are things I found strange, but not sure whether or how to fix.
In 'How to Read This Document':
- It says the code is 3D3V, should 2D3V be added?
- `It describes the dynamics of a plasma by computing the motion of electrons and ions in the plasma based on Maxwell’s equations.` is confusing to me. Firstly, one might get an impression the particles move due to Maxwell's equations. Secondly, the grid or …
=> Further improve wording in docs

include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, include/picongpu/fields/MaxwellSolver/None/None.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
Fix the reference to `grid.param` in our static asserts for the CFL of the Maxwell solvers.
=> CFL Static Assert: new grid.param

CHANGELOG.md
Merge back `master` to have the changelog of 0.4.2 included.
Ignore/revert all other changes, such as Alpaka version update.
=> Merge 0.4.2 Changelog

README.md
I propose to change the link to the Computational Radiation Physics group at HZDR.
The new link still leads to the same page as the old but will avoid possible issues with doxygen that I encountered.
In some cases the ampersand in the link will not be automatically escaped by doxygen and this causes and invalid token in the XML file.
I hope that this is fine since this change doesn't fix the actual problem with doxygen but it rather avoids it.
=> Change link to CRP group @ HZDR

include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp, include/picongpu/plugins/adios/ADIOSWriter.hpp
Silence the GCC 7.3 `-Wterminate` warning about `throws` of our `MPI_CHECK` macro in destructors.
Instead, write to `stderr`.
=> Plugins: ADIOS & PhaseSpace Wterminate

docs/source/install/profile.rst
Add more information on system user guides, and production directories so people have a quick time starting with PIConGPU.
=> Doc: Add System Links

docs/TBG_macros.cfg, include/picongpu/fields/FieldManipulator.hpp, include/picongpu/plugins/IsaacPlugin.hpp, include/picongpu/plugins/PngPlugin.hpp, include/picongpu/plugins/adios/WriteSpecies.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/simulationControl/MovingWindow.hpp, include/picongpu/simulationControl/MySimulation.hpp
Sometimes for bunch-bunch or bunch-target collision it could be useful to allow to stop the
moving windows. This option is now available via `stopWindow`.
- add cli option `stopWindow`
- refactor `MovingWindow`: add method `setEndSlideOnStep` and `isEnabled`
=> stop moving window after N steps

docs/source/usage/python/utils.rst, docs/source/usage/workflows/memoryPerDevice.rst
This commit fixes the documentation output of the `MemoryCalculator` example script.
~~So far I cannot check this because my own `sys.path` contains `...lib/python/picongpu`.~~
I built the doxygen versions **1.8. .. 6, 13** and **14** and all of them fail building the picongpu docu on hypnos.
```
Generating XML output for class pmacc::DataBoxUnaryTransform
/home/garten70/src/picongpu/include/pmacc/memory/boxes/DataBoxUnaryTransform.hpp:34: warning: explicit link request to 'result' could not be resolved
Generating XML output for class pmacc::DataConnector
Segmentation fault (core dumped)
```
**Edit:**   
After being able to test it I can now say the fix does actually work
=> MemoryCalculator: fix example output for documentation

docs/source/index.rst, docs/source/usage/param/core.rst, docs/source/usage/param/particles/init.rst, docs/source/usage/plugins.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/reference.rst, docs/source/usage/workflows/particleFilters.rst, include/picongpu/param/speciesInitialization.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/Bunch/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/FoilLCT/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/ThermalTest/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/WarmCopper/include/picongpu/param/speciesInitialization.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesInitialization.param
The headlines and section level for plugins was wrong. Lower period syntax and general post-processing infos.
Also cleans up the particle doc structure in Usage.
Also adds user map in HTML version as iframe.
=> Manual: Plugin & Particle Sections, Map

include/picongpu/fields/MaxwellSolver/Lehe/Curl.hpp
This has been changed a while ago (#2486 , #2492 ), but got accidentally reintroduced during refactoring of field solvers.
(It is not *that PR*, but done in preparation.)
=> Eliminate M_PI (again)

include/picongpu/particles/Particles.tpp
Apply same fixes as in #2506 to other cases which now fail. Same as #2506 , it does not fix the unfortunate naming that lead to hiding, just patches the cases known to fail.
=> Fix MappingDesc name hiding 

include/picongpu/fields/LaserPhysics.hpp, include/picongpu/particles/ParticlesInit.kernel
This issue has been fixed by #2522, apply the same fix to newer code.
=> More fixes for MSVC capturing constexpr in lambdas

include/picongpu/particles/ParticlesInit.kernel
fix #2823
In the case where the density functor is returning a density of zero or negative the functor which calculates the number of macro-particles (called `startPosition` functor) should not be called.
This avoids that the functor write e.g. the user who is using a free functor implementation must handle those edge cases.
changes:
- do not call `startPosition` functor if density is `<= 0.0`
=> fix particle creation if density zero

etc/picongpu/draco-mpcdf/general.tpl, etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/lawrencium-lbnl/fermi.tpl, etc/picongpu/lawrencium-lbnl/k20.tpl, etc/picongpu/pizdaint-cscs/large.tpl, etc/picongpu/pizdaint-cscs/normal.tpl, etc/picongpu/taurus-tud/k20x.tpl, etc/picongpu/taurus-tud/k80.tpl, etc/picongpu/taurus-tud/knl.tpl
Since the `stdout` files are cached and created live by Slurm during the run, we can just symlink `simOutput/output` onto it for scripts and spare the IO latency load of small little writes.
Should fix the problem reported in #2830 on Slurm systems for tools that check e.g. for constants in our output files. Suggested by @psychocoderHPC [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2830#issuecomment-444410184).
Note that links can be created even before a file they point to exists.
=> Slurm: Link stdout live

docs/TBG_macros.cfg, docs/source/usage/workflows/numberOfCells.rst, include/picongpu/simulationControl/DomainAdjuster.hpp, include/picongpu/simulationControl/MySimulation.hpp
Add helper to calculate/adjust the domain sizes and offset of the simulation.
- add class `AdjustDomainSize`
- remove domain validation from `MySimulation`
- add new command line parameter `--autoAdjustGrid`
If the domain is automatically adjusted the changes will be logged on `stdout`. I know that this is not optimal but since we are lacking a logger this is the best way.
=> auto domain adjustment

docs/source/usage/plugins/particleCalorimeter.rst, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
The unitSI in the particle calorimeter plugin should scale the bins (counts). This is not a scaling to energy but just a normalization during data reduction (and still a count).
Energy and opening angles are on the axes of the recorded mesh.
=> Calorimeter: Fix unitSI

lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py, lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
The visualizers for phase space and png still had the `run_directory` parameter instead of its renamed and current version `run_directories` as the base class and energy histogram already had.
=> PlotMPL: fix run_directory arg into run_directories

include/picongpu/fields/currentInterpolation/Binomial/Binomial.hpp
In order to damp numerical radiation at the Nyquist frequency in all 3 spatial directions, current smoothing is used in PIConGPU which acts as a low pass filter for the field solver.
Contrary to the actual implementation, all 26 neighbors of a cell have to be used when averaging the current on the grid to achieve the desired filtering.
The existing implementation does not damp numerical radiation in all three spatial directions but actually amplifies radiation at the Nyquist frequency along almost all directions. That is, the damping factor of many high frequency waves, which can be calculated by a discrete Fourier transform of the smoothing scheme, has a negative sign which should foster the growth of instabilities.
The left panes of the following pictures show contributions to the …
=> Fix binomial current interpolation

docs/source/dev/py_postprocessing.rst, docs/source/usage/plugins.rst, docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/png.rst, lib/python/picongpu/plugins/jupyter_widgets/__init__.py, lib/python/picongpu/plugins/jupyter_widgets/base_widget.py, lib/python/picongpu/plugins/jupyter_widgets/energy_histogram_widget.py, lib/python/picongpu/plugins/jupyter_widgets/phase_space_widget.py, lib/python/picongpu/plugins/jupyter_widgets/png_widget.py, lib/python/picongpu/plugins/jupyter_widgets/requirements.txt, lib/python/picongpu/plugins/jupyter_widgets/utils.py
This PR provides another wrapping layer around the plot_mpl visualizer classes that makes them regular jupyter widgets. 
The advantage here is that all the additional visualization options can be exposed via dropdowns, radio buttons or something like this.
Note: The axis is passed in the constructor, which is atm not done in the plot_mpl widgets but which will be put in another PR.
In a jupyter notebook, simply write the following
```python
import matplotlib.pyplot as plt
from IPython.display import display
from picongpu.plugins.jupyter_widgets import PhaseSpaceWidget
fig, ax = plt.subplots(1, 1)
run_dir = "path/to/simulation/run"
ps_widget = PhaseSpaceWidget(run_dir, ax)
display(ps_widget)
vis.iteration = 2000
```
=> Python visualizers as jupyter widgets

etc/picongpu/bash/mpiexec.tpl, etc/picongpu/bash/mpirun.tpl, etc/picongpu/davide-cineca/gpu.tpl, etc/picongpu/davinci-rice/picongpu.tpl, etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hydra-hzdr/default.tpl, etc/picongpu/hypnos-hzdr/fermi.tpl, etc/picongpu/hypnos-hzdr/k20.tpl, etc/picongpu/hypnos-hzdr/k20_autoWait.tpl, etc/picongpu/hypnos-hzdr/k20_restart.tpl, etc/picongpu/hypnos-hzdr/k20_vampir.tpl, etc/picongpu/hypnos-hzdr/k20_wait.tpl, etc/picongpu/hypnos-hzdr/k80.tpl, etc/picongpu/hypnos-hzdr/k80_restart.tpl, etc/picongpu/hypnos-hzdr/laser.tpl, etc/picongpu/lawrencium-lbnl/fermi.tpl, etc/picongpu/lawrencium-lbnl/k20.tpl, etc/picongpu/taurus-tud/k20x.tpl, etc/picongpu/taurus-tud/k80.tpl
OpenMPI's default for its IO backend is OMPIO, [starting with 2.x](https://www.open-mpi.org/faq/?category=ompio).
Unfortunately, that backend contains severe bugs leading to data corruption and sporadic crashes (as of the latest releases 3.1.3 and 4.0.0). This is most visible with our parallel HDF5 plugin, but ADIOS is potentially affected as well. Please see https://github.com/open-mpi/ompi/issues/6285 for details
For all system templates that rely on OpenMPI (and its derivatives, such as BullMPI), disable the "OMPIO" default IO backend and fallback to the existing ROMIO backend for MPI-I/O.
Other MPI implementations such as MPICH, and [MPICH-based flavors](https://www.mpich.org/about/collaborators/) such as IntelMPI, use ROMIO by default (they develop ROMIO) and are not affected.
Close …
=> OpenMPI: Use ROMIO for IO

lib/python/picongpu/plugins/jupyter_widgets/base_widget.py, src/tools/bin/smooth.py
Fix pyflakes:
```
use ==/!= to compare str, bytes, and int literals
```
=> Fix pyflakes str/bytes/int compares

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/modules.yaml, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
OpenMPI Vader fix:
- instead of disabling vader alltogether, disable the non-functioning copy-mechanism in Docker and allow OpenMPI 3+ usage
OpenMPI fabrics with spack:
- build all possible fabrics, do not rely on auto-detection which will never have IB (psm, psm2 and mxm do not build without actual HW drivers detected during OpenMPI configure time)
OpenMPI parallel IO work-around:
- crashes and data corruption in releases 2.0-4.0, fallback to ROMIO #2857 
OpenMPI CUDA:
- enable CUDA awareness
IceT:
- buggy CMake install path corrected in `package.py` (spack mainline) https://github.com/spack/spack/pull/5014
Docker/Singularity:
- fix access rights to example dirs for non-root users
A big thank you to @AdamSimpson for provided feedback and improvements! :rocket: :sparkles:
=> Docker & Singularity Updates

docs/source/install/profile.rst, etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/V100_restart.tpl
PIConGPU now runs on the Power9 nodes on Taurus. On the `ml`-partition there are 22 nodes with each 6 V100 GPUs.
A working and tested configuration of the V100-profile, as well as the suitable templates with and without restarting can be found in this pull request.
Boost, HDF5, PNG, pngwriter, c-blosc, adios and splash were required to be self-built. The hint from ComputationalRadiationPhysics/alpaka#702 was used as a workaround to make the code compile. The current MPI-version for the Power9 machines is currently not integrated with SLURM. For this reason we created and used machinefiles in the V100-template V100.tpl.
Now PIConGPU runs and both ADIOS and HDF5-output work. However, the "real-life" HDF5-output for larger files (~100GB) is abysmally slow. Hence, use ADIOS for the …
=> Taurus: Power9 V100 Templates

docs/source/usage/workflows/memoryPerDevice.py
Replace "GPU"s with device naming in our memory estimator.
=> Docs: Memory per Device Spelling

.travis.yml
~~Allow more time for the CMake install with Spack on Travis-CI.~~
Use a pre-build CMake on Travis CI to avoid re-compiles of it.
=> Travis CI: Fix Spack CMake Install

LICENSE.md
Sorry, @kossag14 your name was wrong in our `LICENSE.md`.
=> Contributor name typo in LICENSE.md

include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
Fix the unit for the phase space volume in the phase space plugin for 2D3V simulations.
Since we properly switched for 2D3V simulations to represent periodic, one-cell 3D3V scalings, every quantity is properly "volumetric". Before this change, calculating a density by integrating the phase space in p direction was weird and needed (for known species filter volume) an additional division by our normalized length. This fixes it.
=> PhaseSpace: Unit Colorbar 2D3V

include/picongpu/initialization/ParserGridDistribution.hpp, include/picongpu/simulationControl/MySimulation.hpp
verify the number of blocks from the given `--gridDist` matches the number of devices `-d`.
Fix #2875 
(Sorry for the devices renaming parts, I was already on it.)
=> gridDist: verify devices and blocks

lib/python/picongpu/plugins/data/energy_histogram.py, lib/python/picongpu/plugins/data/png.py
This PR fixes the docstring for the return types of the `EnergyHistogramData` s `_get_for_iteration` method.
It also changes the return type of the `PNGData` class to always output the pngs as numpy arrays (3d or 4d)
=> Small update for python visualizers

include/pmacc/particles/boostExtension/InheritGenerators.hpp
PMacc  `types.hpp` is defining `BOOST_MPL_LIMIT_VECTOR_SIZE`.
A duplicated definition is  available in `InheritGenerators.hpp`.
@sbastrakov and me spotted it during investigating #2871
Since 0.4.X is not developed anymore this should be no problem and a backport is not required.
=> remove duplicated definition of `BOOST_MPL_LIMIT_VECTOR_SIZE`

docs/source/usage/plugins/particleCalorimeter.rst, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
The calorimeter trulys stores an energy per bin right now.
Revert https://github.com/ComputationalRadiationPhysics/picongpu/pull/2848 (only in `dev`)
=> Revert Calorimeter Unit Fix

etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example
Use a newer CMake on Hypnos.
For recent builds of openPMD-api and Alpaka a CMake 3.11+ is recommended, saving later troubles for users in post-processing.
=> Hypnos: CMake 3.13.4

include/mpiInfo/CMakeLists.txt, include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, include/pmacc/test/random/CMakeLists.txt, share/pmacc/examples/gameOfLife2D/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
CMake 3.12.0+ honor `<Package>_ROOT` environment hints which are often set on HPC systems. Previously, it was only looking for `<Package>_DIR` paths in `find_package` calls.
This new policy is useful since HPC systems usually set `_DIR`, `_ROOT` or expand the `CMAKE_PREFIX_PATH`. Therefore we want to use it as soon as it is available.
On systems where those env vars are set, e.g. Hypnos, this also throws a warning if the default (OLD) policy is used with CMake 3.12.4 or newer.
- https://cmake.org/cmake/help/v3.12/policy/CMP0074.html
- https://github.com/openPMD/openPMD-api/pull/391
- https://github.com/ComputationalRadiationPhysics/picongpu/pull/2887#issuecomment-463602968
If we update to CMake 3.12+ one day, the policies at this point become `NEW` by default as well:
> The …
=> CMake: Honor _ROOT Env Hints

include/pmacc/mappings/threads/ForEachIdx.hpp, include/pmacc/memory/CtxArray.hpp
In two cases it has not been specified explicitly, which could potentially lead to incorrectly deduced types. For the existing code that did not happen.
Fixes #2900.
=> Explicitly specify template argument for std::forward

bin/pic-configure, etc/picongpu/submitAction.sh
In the case where new parameter files are added to the input parameter into a already compiled parameter set, cmake will ignore the new files.
The option `-f` allows to enforce that cmake flushes the cache and rescans for new files.
This option is required in the following workflow:
- create an input set where e.g `particlesFilter.param` is missing
- run `pic-build`
- run `pic-edit particlesFilter`
- add a new filter
- run `pic-build`
- run `./bin/picongpu --help`
The last command will not show the new filter in the hdf5 source or everywhere else where filters will be used. A way to trigger a full rescan of cmake is to delete the folder `.build` or the new option `-f`.
The option `-f` has the advantage that all changes which were made with `ccmake` will still be in.  This is very often …
=> pic-configure: add `--force/-f` option

bin/pic-edit
follow up of #2901
If a param file is copied to the input set of the user the cmake cache file cache fill be cleaned to avoid that the new param file is not taken into account during the compile.
Note: I added no output to the terminal that the cmake cache is cleared. I think it will only confuse the user at this place.
=> pic-edit: clean cmake file cache if new param added

include/pmacc/PMaccConfig.cmake
Enable boost template aliases. Fix #2907
Boost 1.67.0+ uses `boost::void_t` even though it is only conditionally defined (controlled via `BOOST_NO_CXX11_TEMPLATE_ALIASES`): https://github.com/boostorg/type_traits/issues/113
https://www.boost.org/doc/libs/1_67_0/boost/type_traits/detail/has_binary_operator.hpp
This section in our config was originally designed to work-around https://svn.boost.org/trac10/ticket/11897
The NVCC bug appeared in CUDA 7.0, was fixed in 7.5 and re-appeared in 8.0. During transition to CUDA 8, the work-around was switched from disabling variadic templates to disabling template aliases, as it also excludes boost `mp_defer` code of the original issues. Nevertheless, there seems to be no reason why we would need boost variadic templates with CUDA 8.0 (at least no …
=> Boost 1.67.0+ Template Aliases

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Our currently shipped Docker image build for the CUDA backend with Spack. Due to a concretization issue in OpenMPI's package, we also need to specify the `hwloc` default variant to be with `+cuda`.
Follow-up to #2847.
=> Docker CUDA Image: Hwloc Default

INSTALL.rst, include/picongpu/CMakeLists.txt, include/picongpu/initialization/ParserGridDistribution.cpp, include/picongpu/initialization/ParserGridDistribution.hpp, include/pmacc/debug/abortWithError.hpp
hopefully, fix #2898
- Split the grid parser into an interface file `hpp` and the implementation `cpp` to avoid that boost regex is parsed by nvcc. Boost regex is very often the root of compile issues because nvcc is not able to split the host and device part correctly.
- Define `abortWithError` static to allow the usage in multiple object files without creating the linker error ` multiple definitions of ...
- remove `boost::regex` by `std::regex`
- remove `boost::lexical_cast`
=> split `ParserGridDistribution` into `hpp/cpp` file

INSTALL.rst, src/tools/splash2txt/CMakeLists.txt, src/tools/splash2txt/include/splash2txt.hpp, src/tools/splash2txt/splash2txt.cpp
- fix file pattern to prepare the file name for libsplash
example for a not supported path: `buildPIC/khi_cpu/bin/h5/data_0.h5`
The `_` in `khi_cpu` was misinterpreted an the file path was set to `buildPIC/khi`
- remove `boost::regex` with `std::regex`
- update documentation: remove requirement of `boost::regex` ￼(this step was already mentioned in [#2899](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2899#issuecomment-467798314) )
Note: I marked this PR as bug because due to the original regex pattern used to trimm the file name it could result into the bug that the file is not exists.
=> splash2txt: fix file name trimming

src/tools/splash2txt/CMakeLists.txt, src/tools/splash2txt/tools_splash_parallel.cpp
- fix broken compile due to a wrong interface usage introduced with #2520
- cmake missing include/dependency
- add splash to the cmake target `splash2txt`
- add splash dependency `zlib` to the `splash2txt` target
=> fix compile splash2txt

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
Remove extra 0 which made it so that memory requirements could not be satisfied.
=> Fix a typo in memory requirements for getDevice on Hemera defq

src/tools/splash2txt/CMakeLists.txt
- ~~do not link libz (zlib) since it's not needed directly~~ `ZLIB::ZLIB` without target weirdly injected by Splash 1.7.0
- do link libm only on Unix and not with ICC
- link with proper qualifiers (`PRIVATE` in the case of an executable)
Follow-up to #2912
=> Splash2txt Build: Update deps

include/pmacc/particles/tasks/TaskSendParticlesExchange.hpp
Another revolutionary typo fix
By the way, in order for a user to react to this warning, how you define the _direction_? Foe example, if i get a warning:
```Send/receive buffer for species e is to small (max: 49152, direction: 3, retries: 1)```
should I increase `BYTES_EXCHANGE_Z` or there could be other possibilities?
=> typo fix in Send/receive buffer warning

etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
Updated the hemera cluster gpu_picongpu.profile
- updated the modules to builds based on cuda/10.0
- updated the memory requirement to leave only 2GB free on a node, not 20GB
=> Update modules and memory in gpu_picongpu.profile

include/pmacc/types.hpp
Avoid that we access memory outside of the naming array.
=> `ExchangeTypeNames` avoid illegal memory access

include/pmacc/attribute/Constexpr.hpp, include/pmacc/attribute/Fallthrough.hpp, include/pmacc/attribute/FunctionSpecifier.hpp, include/pmacc/cuplaHelper/ValidateCall.hpp, include/pmacc/debug/VerboseLog.hpp, include/pmacc/dimensions/Definition.hpp, include/pmacc/eventSystem/EventType.hpp, include/pmacc/memory/Align.hpp, include/pmacc/memory/Delete.hpp, include/pmacc/type/Area.hpp, include/pmacc/type/Exchange.hpp, include/pmacc/type/Integral.hpp, include/pmacc/types.hpp
Cleanup the misc header `pmacc/types.hpp` ([our eierlegende Wollmilchsau](https://de.wikipedia.org/wiki/Eierlegende_Wollmilchsau)) to support later refactorings of other classes to support compiling in independent compile units.
Move all definitions from types.hpp in independant files.
This PR is not changing the implementations and is fully backward compatible. To support the backwards compatibility all definitions within a hierarchical namespace is pulled into the pmacc namespace.
=> cleanup `pmacc/types.hpp`

include/picongpu/traits/AdiosToPIC.tpp, include/picongpu/traits/PICToAdios.tpp
Based on the discussion #2928 this PR fixes a bug, in which picongpu fails to compile when both ADIOS and particle merging are activated. Hence `int16` and `uint16` are now included as traits for ADIOS.
=> Include int16 and uint16 types as traits for ADIOS

include/pmacc/particles/tasks/TaskSendParticlesExchange.hpp
Add the direction name to the warning for multiple send operations in `TaskSendParticlesExchange`.
=> Name directions in species buffer warnings

docs/source/install/profile.rst, etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_picongpu.profile.example
New modules where installed for the `ml` partition.
Among other things, the MPI machinefile became unnecessary.
I updated the respective `V100_picongpu.profile.example` and `V100.tpl`.
Furthermore, I compiled a script from @ax3l's older scripts
which installs the libraries on which picongpu depends.
The script can be found at (https://gist.github.com/steindev/cc02eae81f465833afa27fc8880f3473#file-picongpu_0-4-3_taurus-tud-sh).
I included the link in the `V100_picongpu.profile.example` as well.
=> Update taurus-tud profiles for the `ml` partition

etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/jureca-jsc/batch_picongpu.profile.example, etc/picongpu/jureca-jsc/booster_picongpu.profile.example, etc/picongpu/jureca-jsc/gpus_picongpu.profile.example, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example, etc/picongpu/titan-ornl/cpu_picongpu.profile.example, etc/picongpu/titan-ornl/gpu_picongpu.profile.example
Follow up pull request fixing a grammar error in all `.profile.example` files. Except the `taurus-tud/V100_picongpu.profile.example` since it will be fixed by the original pull request anyways.
_Requested by @ax3l in https://github.com/ComputationalRadiationPhysics/picongpu/pull/2903_
=> Fix grammar in all `.profile.example`

etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_restart.tpl
Of course environment variables are not replaced in the sbatch script if they are called with a dollar sign in front. 
The right way with TBG is to use an exclamation mark.
This PR fixes #2931.
Thanks @finnolec for reporting this.
**CC'ing** @wany12
=> Fix k80.tpl and k80_restart.tpl for Hemera

etc/picongpu/hemera-hzdr/k80_restart.tpl
The restart template for hemera's k80 queue was not working.
- fix that stdout and stderr was always overwritten by the batch system
- fix that `tee` was used and all output was written twice into the log file
- fix re-submit (resubmit directly from the node)
- fix mpiexec command
- fix broken start of a simulation where the folder `checkpoint` not exists
- add missing required node memory calculation
=> fix hemera k80_restart.tpl

share/picongpu/examples/Bremsstrahlung/include/picongpu/param/grid.param, share/picongpu/examples/Bunch/include/picongpu/param/grid.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/grid.param, share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param, share/picongpu/examples/WarmCopper/include/picongpu/param/grid.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/grid.param
This variable is set in most examples, but never used in the code or other input files. I assume it is left from some older times.
While looking for encounters of this name, I've found #390 , which seems already outdated and with this PR is definitely outdated.
=> Remove unused ABSORBER_FADE_IN_STEPS from .param files in examples

docs/source/usage/workflows/memoryPerDevice.py, docs/source/usage/workflows/memoryPerDevice.rst
`y1` was not really the target thickness but its rear surface position.
Previously it was estimating number of particles for a 0.5 micron foil, not 1.0 like in the example.
=> Correct target thickness

include/picongpu/fields/FieldB.hpp, include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.hpp, include/picongpu/fields/FieldE.tpp, include/picongpu/fields/FieldJ.hpp, include/picongpu/fields/FieldJ.tpp
This is probably some legacy, that is no longer used.
=> Remove unused getCommTag() in FieldE, FieldB, FieldJ

include/picongpu/fields/FieldTmp.tpp, include/pmacc/memory/MakeUnique.hpp, include/pmacc/memory/buffers/ExchangeIntern.hpp, share/pmacc/examples/gameOfLife2D/include/Evolution.hpp
`std::make_unique` is C++14, so we need own C++11 implementation. It has been [discussed and agreed on long time ago](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2669#discussion_r208204183). Now due to recent offline talks to @psychocoderHPC we will use `std::unique_ptr` more actively and so having a creation routine is useful.
New implementation is taken from cppreference (link in comments). It does not handle arrays in the standard way, but I think this is fine for us.
I've also replaced all current creation of unique pointers with the new function, it was really not a lot.
=> Add pmacc::memory::makeUnique similar to std::make_unique

include/pmacc/math/vector/Vector.tpp
This allows a little nicer and more expressive code, as suggested [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2950#discussion_r281540518).
=> Add an implementation of exp for pmacc vectors

include/picongpu/fields/MaxwellSolver/Yee/Curl.hpp
This type is currently not used anywhere, but will be needed for PML.
The Lehe solver curl is not changed, as it does not have a type ready to use in this role.
As [suggested](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2950#discussion_r281530308), making this a separate PR.
=> Add a using declaration for Difference type to yee::Curl

include/pmacc/math/vector/Float.hpp, include/pmacc/math/vector/Int.hpp, include/pmacc/math/vector/Size_t.hpp, include/pmacc/math/vector/TwistComponents.hpp, include/pmacc/math/vector/UInt32.hpp, include/pmacc/math/vector/UInt64.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/math/vector/Vector.tpp, include/pmacc/math/vector/compile-time/Float.hpp, include/pmacc/math/vector/compile-time/Int.hpp, include/pmacc/math/vector/compile-time/TwistComponents.hpp, include/pmacc/math/vector/compile-time/Vector.hpp, include/pmacc/math/vector/math_functor/abs.hpp, include/pmacc/math/vector/math_functor/cosf.hpp, include/pmacc/math/vector/math_functor/max.hpp, include/pmacc/math/vector/math_functor/min.hpp, include/pmacc/math/vector/math_functor/sin.hpp, include/pmacc/math/vector/math_functor/sqrtf.hpp
Continue transitioning PMacc to C++11 syntax with "using" instead of "typedef".
Avoid adding more outdated syntax (follow-up to #2956).
Committed as generic "tools" user:
```
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
git ...
```
=> PMacc Vector: C++11 Using

docs/source/usage/param/core.rst, include/picongpu/_defaultParam.loader, include/picongpu/_defaultUnitless.loader, include/picongpu/fields/MaxwellSolver/Solvers.def, include/picongpu/fields/MaxwellSolver/Solvers.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp, include/picongpu/fields/MaxwellSolver/YeePML/Parameters.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.def, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel, include/picongpu/param/physicalConstants.param, include/picongpu/param/pml.param, include/picongpu/unitless/physicalConstants.unitless, include/picongpu/unitless/pml.unitless
I've now put my changes on top of the current dev. There are still some leftovers from the previous efforts, and, importantly, the kernel is still not changed to work in the internal area vs. the guard as originally planned. So still WIP, but hopefully just for 1-2 more days.
I'll now close the older PR #2863 .
To enable the new solver, use `YeePML` as the field solver in `fieldSolver.param`. All the PML-related parameters are in `pml.param` (default values should normally be reasonable), parameters of the old exponential damping absorber should still be specified so that the code compiles, but are not actually used. Otherwise, PML behaves exactly the same as the old absorber, in terms of absorbing area location (inside the simulation area, near the outer border) and interaction with …
=> Add implementation of PML

.travis.yml, INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, include/mpiInfo/CMakeLists.txt, include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, share/pmacc/examples/gameOfLife2D/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/png2gas/README.md, src/tools/splash2txt/CMakeLists.txt
Increase the dependencies to CUDA 9.0+, which in turn requires Boost 1.65.1+ to run.
With that prepare, we also update our CI to run on GCC 5.1+ which will make the transition to C++14 possible soon. While GCC 4.9 is technically still okay as long as we stick with C++11, we deprecate support and continuous CI for it to move forward for the aforementioned reasons.
Slightly increased the transitive HDF5 requirement to same version as in openPMD-api.
=> CUDA 9.0+, GCC 5.1+, Boost 1.65.1+

include/pmacc/PMaccConfig.cmake
Throw a readible error message during PIConGPU setup time.
Follow-up to #2961
=> CMake: CUDA 9.0+

docs/requirements.txt
Update Sphinx and Breathe to newer version.
This should fix the failing HTML builds which require a new support for unions: https://github.com/sphinx-doc/sphinx/issues/6285
=> Docs: Update Sphinx

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
For local startup, an SSH daemon is not necessary.
This is a security fix, removing pre-set keys installed alongside the openssh-server package in /etc/ssh which would be known and published in the docker image. The published dockerhub images ax3l/picongpu:0.4.3 and ax3l/picongpu:latest have been replaced with a fixed version.
Affected are users that would run the docker container on a non-private network or shared system which could lead to the security implication of unauthorized login into the running docker instance, if the docker SSH server port is published (note that this is not the default and has to be exposed manually).
Thank you to @AdamSimpson (Nvidia) for reporting the issue!
Also: Avoid Latest Flex by configuring the latest flex with spack applies a patch that reconfigures …
=>  Dockerfile: No SSH Deamon & Keys, Fix Flex Build

include/picongpu/fields/FieldJ.hpp, include/picongpu/simulation/stage/CurrentBackground.hpp, include/picongpu/simulation/stage/CurrentDeposition.hpp, include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp, include/picongpu/simulation/stage/CurrentReset.hpp, include/picongpu/simulationControl/MySimulation.hpp
Create a new functor for each stage (part) of the current processing. Put the new functors to a new directory `picongpu/simulation/stages`.
A similar separation of other stages will follow, as discussed offline earlier today. I believe once we have a proper separation into many translation units, this change should also be helpful, as we could put implementations in .cpp files and instantiate (some) templates only there.
=> Separate the code processing currents from MySimulation

include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/flylite/NonLTE.tpp, include/picongpu/simulationControl/MySimulation.hpp, include/pmacc/dataManagement/DataConnector.hpp
So now there are two scenarios for registering data at `DataConnector`:
- the old `share()` to register and share;
- the new `consume()` to register and consume (the caller gives away ownership to data connector).
The only difference is in ownership. Now it follows [the usual design style](https://herbsutter.com/2013/06/05/gotw-91-solution-smart-pointer-parameters/): taking a shared pointer means "I'll share ownership with caller", taking a unique pointer - "I'll take away ownership from caller".
Previously, all calls to `share()` actually wanted just to `consume()` and had to artificially wrap stuff in shared pointers. Which is no longer needed and I've changed it, which also simplifies code a little bit. It turns out, now there are no external calls to `share()` left at all. However, I …
=> Add DataConnector::consume(), which shares and consumes the input

include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp, include/picongpu/unitless/checkpoints.unitless, include/pmacc/memory/buffers/HostDeviceBuffer.hpp
The original implementation of PML #2950 does not save the additional PML fields in checkpoints. This PR enables full support for checkpointing with PML. The checkpointing of fields has been a tiny bit too narrow, so I have extended it a little bit to fit the PML fields.
=> Enable checkpoints for the PML fields

INSTALL.rst, buildsystem/CompileSuite/autoTests/new_commits.sh, docs/source/install/instructions/spack.rst, include/pmacc/PMaccConfig.cmake, share/picongpu/dockerfiles/README.rst, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
In order to merge the latest Alpaka releases and due to nvcc bugs,
we increase our requirement to CUDA 9.2+. CUDA 10.1 seams to compile as well.
Furthermore, Boost 1.70.0 is working with Alpaka.
Side note: with CUDA 9.2 as the minimum CUDA release, we can also reliably update our code base to C++14 (in upcoming PRs, CUDA 9.0+ supports this).
=> CMake: CUDA 9.2-10.1, Boost <= 1.70.0

include/picongpu/simulation/control/MySimulation.hpp, include/picongpu/simulation/stage/Bremsstrahlung.hpp, include/picongpu/simulation/stage/FieldBackground.hpp, include/picongpu/simulation/stage/MomentumBackup.hpp, include/picongpu/simulation/stage/ParticleIonization.hpp, include/picongpu/simulation/stage/ParticlePush.hpp, include/picongpu/simulation/stage/PopulationKinetics.hpp, include/picongpu/simulation/stage/SynchrotronRadiation.hpp
This is the second and final part of the refactoring started in #2964. Imo, now from the code of `MySimulation::runOneStep()` it is easier to figure out what is going on, or draw a flowchart of simulation stages.
There are a couple of stages that have additional arguments in constructor or `operator()()`, but this is rather manageable, so I suggest to leave it as is for now.
=> Separate the code processing particles from MySimulation

include/pmacc/particles/memory/boxes/ParticlesBox.hpp, include/pmacc/particles/memory/dataTypes/FramePointer.hpp, include/pmacc/particles/memory/dataTypes/Pointer.hpp
Taking into account #2976, there will be no use for alternatives here. So this PR removes this template parameter and now the pointers are always default-initialized with `nullptr`. This does not change the behavior of the existing code, as it has always been the set to zero policy anyways.
Edit: the first commit is the same as in #2976 (merged already at the time of the edit), please review only the second.
=> Remove template parameter for initialization method of Pointer and FramePointer

include/pmacc/particles/memory/dataTypes/Particle.hpp
Was just introduced by #2983 and did not occur on our tests, but is visible with Visual Studio.
=> Fix a compilation issue with ForEach lookup

include/pmacc/fields/SimulationFieldHelper.hpp
add a getter methode access the celldescription of a field
=> SimulationFieldHelper: getter method to access cell description

include/picongpu/fields/LaserPhysics.hpp
`warning: pointless comparison of unsigned integer with zero`
Use a workaround to avoid unsigned zero comparisons.
=> fix warning: comparison of unsigned integer

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/compilers.yaml
Avoid creating a ~/.spack/linux/repos.yaml with spack add and instead modify the "system-wide" (in the container) config files.
Also explicitly move compilers.yaml to the same, system-wide location.
Thanks to @AdamSimpson and Nvidia QA for the report!
Local diff for the 0.4.3 release to build (CUDA 9.0 based):
```diff
diff --git a/share/picongpu/dockerfiles/ubuntu-1604/Dockerfile b/share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
index 2872b24..a1c9b85 100644
--- a/share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
+++ b/share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
@@ -1,4 +1,4 @@
-FROM       nvidia/cuda:9.2-base
+FROM       nvidia/cuda:9.0-base
MAINTAINER Axel Huebl <a.huebl@hzdr.de>
@@ -6,7 +6,7 @@ ENV        DEBIAN_FRONTEND=noninteractive \
FORCE_UNSAFE_CONFIGURE=1 \ …
```
=> Singularity: Avoid Dotfiles in Home

etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/V100_restart.tpl, etc/picongpu/taurus-tud/k80_picongpu.profile.example
Add a getNode alias to `k80_picongpu.profile.example` requesting a node from the gpu2-interactive partition equipped with k80.
Add comment to `V100.tpl` for taurus ml partition equipped with V100 gpus
in order to provide a solution for issues due to too few hostmemory
on the taurusml nodes.
See ComputationalRadiationPhysics/picongpu#2861.
Add `--cpus-per-task` to `V100_picongpu.profile.example` and do `module switch` instead of purge and load.
=> Adjust profiles for taurus-tud

include/pmacc/particles/ParticlesBase.kernel
I started looking into this due to a warning in Visual Studio, but turned out this is probably a bug.
This line: `newParticleInFrame[ idx ] = -particlesInFrame;` [just below](https://github.com/sbastrakov/picongpu/blob/fe8a709269c4da5e5de4f03559f74c69ce6f3d98/include/pmacc/particles/ParticlesBase.kernel#L663) used a negation of a `uint32_t` value. Which is not a problem itself (well-defined, works by modulo), although probably a little weird style and caused the warning. But then the result is assigned to an `int` value and in all realistic scenarios, it would overflow, which is UB for signed ints. I guess it worked by bitwise copying which would give the correct result.
=> Fix signed int overflow in particle migration between supercells

include/picongpu/particles/Manipulate.hpp, include/picongpu/simulation/stage/MomentumBackup.hpp
This is a function-style wrapper around creating a `Manipulate` object and calling its `operator()`. Unlike `picongpu::particles::Manipulate`, it supports both single species and sequences of species.
For a bit of a context: @psychocoderHPC and I had lots of discussions recently on interfaces for the `forEach`-style processing, so that it is easier to express the simple patterns. Like this one - applying a manipulator for a sequence of particle species. #2991 is another step in that direction, this PR is orthogonal to it and (should) work with both the old and new `Manipulate`. More PRs in this direction will be coming, including more actively employing manipulate in the existing code.
=> Add picongpu::particles::manipulate() as a high-level interface to particle manipulation

docs/source/install/instructions/spack.rst
This line shall install a new GCC 7.3.0 only if there is no GCC 7.3.0 already found in `spack compiler list`.
Introduced in #2773, seen by @WenyinWei in #2994
=> Spack: Fix Compiler Docs

docs/source/usage/plugins/radiation.rst, include/picongpu/param/radiation.param, include/picongpu/param/radiationObserver.param, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/radiation/ExecuteParticleFilter.hpp, include/picongpu/plugins/radiation/GetRadiationMask.hpp, include/picongpu/plugins/radiation/Radiation.hpp, include/picongpu/plugins/radiation/Radiation.kernel, include/picongpu/plugins/radiation/amplitude.hpp, include/picongpu/plugins/radiation/calc_amplitude.hpp, include/picongpu/plugins/radiation/check_consistency.hpp, include/picongpu/plugins/radiation/debug/PIConGPUVerboseLogRadiation.hpp, include/picongpu/plugins/radiation/frequencies/radiation_lin_freq.hpp, include/picongpu/plugins/radiation/frequencies/radiation_list_freq.hpp, include/picongpu/plugins/radiation/frequencies/radiation_log_freq.hpp, include/picongpu/plugins/radiation/nyquist_low_pass.hpp, include/picongpu/plugins/radiation/parameters.hpp, include/picongpu/plugins/radiation/particle.hpp, include/picongpu/plugins/radiation/radFormFactor.hpp, include/picongpu/plugins/radiation/taylor.hpp, include/picongpu/plugins/radiation/utilities.hpp, include/picongpu/plugins/radiation/vector.hpp, include/picongpu/plugins/radiation/windowFunctions.hpp, include/picongpu/unitless/radiation.unitless, share/picongpu/examples/Bunch/include/picongpu/param/radiation.param, share/picongpu/examples/Bunch/include/picongpu/param/radiationObserver.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiation.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiationObserver.param
This pull request closes #1643. 
It surrounds the code related to the radiation plugin with the namespace `radiation`.
=> add namespace "radiation" around code related to radiation plugin

include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.tpp, include/picongpu/plugins/ResourceLog.hpp, include/picongpu/plugins/common/txtFileHandling.hpp, include/pmacc/Environment.hpp, include/pmacc/eventSystem/events/CudaEvent.def, include/pmacc/eventSystem/tasks/TaskKernel.hpp, include/pmacc/eventSystem/transactions/Transaction.hpp, include/pmacc/eventSystem/transactions/Transaction.tpp, include/pmacc/misc/splitString.hpp, include/pmacc/nvidia/functors/Add.hpp, include/pmacc/nvidia/functors/Max.hpp, include/pmacc/nvidia/functors/Min.hpp, include/pmacc/nvidia/functors/Mul.hpp, include/pmacc/pluginSystem/containsStep.hpp, include/pmacc/pluginSystem/toTimeSlice.hpp, include/pmacc/traits/GetStringProperties.hpp
These missing `inline` qualifiers cause multiple definitions of the functions in question, in case it is present in multiple object files. This is one (but not only) of the issues preventing us from using more object files.
For functions defined in header files (so almost all our functions) the rules are as follows:
- `inline` should be part of declaration (not definition)
- for class/struct methods defined at declaration `inline` is applied automatically
This PR catches the cases that my Visual Studio reports on. I assume there might be some more, but probably not too many.
Files related to fields are not fixed in this PR, but as part of #3005.
=> Add missing inline qualifiers potentially causing multiple definitions

include/picongpu/CMakeLists.txt
Fix a warning with CMake 3.14+:
```
CMake Warning (dev) at CMakeLists.txt:376 (set):
implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
There is no (cached) `LIST` type in CMake, those are just interpreted
strings.
=> CMake: Warning in 3.14+ Cache List

include/pmacc/PMaccConfig.cmake
Disable `std::auto_ptr` support in Boost.
It's deprecated in C++11 and removed in C++17, unnecessarily compiles although it is unused and causes a warning with NVCC+GCC.
=> Boost: No std::auto_ptr

include/picongpu/plugins/ResourceLog.cpp, include/picongpu/plugins/ResourceLog.hpp
Move the boost property tree for writing of the final
files out of the NVCC compile path. This avoids awkward work-arounds (see #2714), fixes NVCC-caused warnings in host-code (fix #3011) and reduces compile-time by providing a little more parallelism.
Also fixes a potential use-after-free (`temporary.str().c_str()`).
=> Resource Monitor Plugin: Warnings

include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/creation/creation.hpp, include/picongpu/simulation/stage/Bremsstrahlung.hpp, include/picongpu/simulation/stage/ParticleIonization.hpp, include/picongpu/simulation/stage/SynchrotronRadiation.hpp
It is potentially unsafe to pass by pointer in these cases, as we pass a pointer to a local member and inside it could start a kernel asynchronously, then return and destroy the stage class instance. This does not lead to problems now but just unnecessary unsafe and passing by value is more natural anyways.
=> Pass mapping description by value instead of pointer from simulation stages

etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_restart.tpl
On hemera we have no projects like on other system, we have access groups for a few queues.
Since the slurm option `-A` is queue specific and not user-specific (will be never changed by the user) it makes no sense to have it changeable.
The current implementation also breaks the option `tbg -t anytemplate.tpl` because it is not possible to switch the queue via the explicit selection of the used template.
=> hemera-hzdr: remove project definition

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Found by @AdamSimpson (Nvidia) et al., singularity incorrectly sets the permissions of some dirs and files when not `chmod`-ed in the same `RUN` statement.
https://github.com/sylabs/singularity/issues/3880
We just fuse them for now.
Also, disable the UCX backend in OpenMPI due to known issues:
- https://github.com/open-mpi/ompi/issues/4948#issuecomment-512987494
- https://github.com/openucx/ucx/issues/3545
=> Singularity: Workaround Chmod Issue, No UCX

include/picongpu/particles/flylite/helperFields/LocalDensityFunctors.hpp, include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
@psychocoderHPC and I spent quite a long time figuring out the cause of #3010. Our current understanding is that somehow nvcc gets confused with templates and incorrectly decides some code paths to be host-only, and so does not properly generate kernels called inside. This leads to strange `cudaErrorInvalidDeviceFunction` errors with CUDA. To work around such behavior, this PR moves some of the templates inside the functions with kernel calls. Thomas-Fermi is what we believe caused #3010, also noticed a similar pattern in FLYLite. There could be more, but if we understand the issue correctly, that could be fixed once encountered.
Fixes #3010. @psychocoderHPC checked on the test machine that it now works.
=> Fix code causing cudaErrorInvalidDeviceFunction

docs/source/usage/plugins/radiation.rst
This pull request fixes an outdated file name reference in the documenetation of the radiation plugin.
It was discovered by @Anton-Le and reported *by mail* - thanks for finding this error.
=> Fix old file name in radiation doc

include/picongpu/fields/EMFieldBase.hpp, include/picongpu/fields/EMFieldBase.tpp, include/picongpu/fields/FieldB.hpp, include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.hpp, include/picongpu/fields/FieldE.tpp, include/picongpu/fields/FieldJ.hpp, include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/FieldTmp.hpp, include/picongpu/fields/FieldTmp.tpp, include/picongpu/fields/Fields.tpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp
This PR provides several small improvements to the implementations of the fields:
- a new base class for `FieldB` and `FieldE` implementations, since they had a substantially identical part
- add missing `inline` qualifiers
- fix shadowing of the virtual method `SimulationFieldHelper::syncToDevice()`, however, I believe it has never been used polymorphically (via a pointer to the base class); so it was a bug but we did not use this behavior 
- occasionally modernize the code style and other minor things
TODO:
=> Refactor and modernize implementation of fields

include/picongpu/ArgsParser.cpp, include/picongpu/ArgsParser.hpp, include/picongpu/main.cpp, include/picongpu/simulation/control/ISimulationStarter.hpp, include/picongpu/simulation/control/SimulationStarter.hpp
And rename it to Status. Due to this change, the Visual Studio-specific workaround with the `ERROR` macro is no longer needed, so got rid of it.
=> Modernize ArgsParser::ArgsErrorCode

include/picongpu/plugins/radiation/Radiation.hpp
This pull request fixes issue #3020. It rearranges the dependencies for creating specific (hdf5 related) output directories and arrays. Thus hdf5 output is now always produced, even if `--<species>_radiation.totalRadiation` is not set. 
The following run time test still need to be performed:
For testing the default Bunch example will be used. 
@Anton-Le this should solve your issue.
=> Radiation Plugin: fix bool conditions for hdf5 output

include/picongpu/simulation/control/MySimulation.hpp
When developing PML I did not think of the memory allocation order and continued using the old one with field solver being constructed after the particle memory allocation (and my tests were small enough that it worked fine). But since the `YeePML` solver involves allocation of additional field components that lead to out-of-memory error #3027.
Imo there is also room for improvement in terms of design, as such limitations are not obvious at all. I could try to refactor it in a follow-up PR.
=> Fix field solver initialization order

include/picongpu/ArgsParser.cpp, include/picongpu/simulation/control/MovingWindow.hpp, include/picongpu/simulation/control/MySimulation.hpp
Solves #2943.
I spent some time considering how to do such changes without breaking the user sets of input files. The issue is that just adding a new runtime parameter and removing the dependency on the compile-time one would make old files silently produce different results, which is far from desired. So this PR goes for a compromise. Now the old compile-time variable is still required, its value is used as a default for the new runtime parameter. In case the moving window is enabled but the new value is not set (so the setup relies on the old behavior) it would still work as usual for now, but there is an explanatory warning in the log. Then we can remove support for the old way e.g. one release after this change is added.
Also noted a description of how the moving window works seems to …
=> Add a runtime parameter for window move point

include/picongpu/ArgsParser.cpp
Fixes  #3034.
The bug was introduced in #3022.
=> Fix a crash in reporting deprecated parameters

include/picongpu/simulation/control/MySimulation.hpp
This bug caused incorrect behavior in restart mode for visualization, as observed by @n01r.
After some consideration, I went for a more hard-coded solution rather than trying a general one somewhere in `DataConnector`. The reason is that our class hierarchies do not interact too well in this case with `ISimulationData` not providing `reset()`.
=> add reset PML fields in MySimulation::resetAll() 

include/pmacc/identifier/alias.hpp, include/pmacc/identifier/identifier.hpp
Now these variables are `static` and so will exist in each translation unit including the headers in question.
This is however fine, since the variables are only used for template parameter deduction.
This PR is working towards removing limitations on including PMacc stuff to several object files, started with #3006. (but a few more PRs required to reach that goal).
=> Fix multiple definitions of PMacc identifiers and aliases

include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp
This has been spotted during the investigation of #3037 (but is unrelated to that issue).
Now the core code of PIConGPU does not include or use `pthread`, only `cuda_memtest` and `alpaka` do.
=> Remove unused includes of pthread

include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.tpp
The bug has been introduced in #3005 by confusing constructors of `std::vector`.
It causes crashes in all code calling `getUnitDimension()` of `FieldE` and `FieldB`, notably output and checkpoints, such as #3037.
=> Proper Constructor in unitDimension std::vector

etc/picongpu/aris-grnet/gpu_picongpu.profile.example, etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example
This pull request fixes a typo in the documentation of `getNode` and `getDevice` in the example profiles for **all** supported clusters.
=> fix typo in getNode and getDevice

docs/TBG_macros.cfg, include/picongpu/param/grid.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/grid.param, share/picongpu/examples/Bunch/include/picongpu/param/grid.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/grid.param, share/picongpu/examples/FoilLCT/include/picongpu/param/grid.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param, share/picongpu/examples/LaserWakefield/etc/picongpu/16.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/32.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4_gui.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg, share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/grid.param, share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param, share/picongpu/examples/WarmCopper/include/picongpu/param/grid.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/grid.param
Follow-up to #3022: document new usage of the moving window runtime parameter and update examples.
Solves most of #3044.
=> Window move point clean up

docs/source/install/profile.rst, docs/source/usage/tbg.rst, etc/picongpu/cori-nersc/knl.tpl, etc/picongpu/cori-nersc/knl_picongpu.profile.example
Add profiles for Cori's KNL nodes.
As on Taurus' KNL nodes at ZIH, I kept the "one MPI rank per KNL" and "one hyperthread per code" strategy.
I am not sure if we ever tuned this for ideal performance, because e.g. [WarpX](https://warpx.readthedocs.io/en/latest/running_cpp/platforms.html)/PICSAR reported better performance with 8 MPI ranks per device to sub-partition the KNL. If I remember correctly, we just checked some hyperthread performance [here](https://arxiv.org/abs/1706.10086) on KNL and sub-partition all other, multi-socket CPU hardware these days.
Either way, as the Taurus KNL profile, this profile works.
I guess @sbastrakov would have some experience tuning the checked-in KNL profiles further (e.g. on Taurus). Maybe we want to revisit partitioning a KNL into multiple "devices" …
=> Docs: Cori's KNL Nodes (NERSC)

include/picongpu/particles/densityProfiles/FreeFormulaImpl.hpp
`FreeFormulaImpl` allows the user functor to define a constructor to move additional information into the profile.
This allow e.g. filtering by cell position relative to the global volume
```C++
//! example implementation is not supporting moving window
struct RelativeRangeProfile
{
static constexpr float_X start_ratio = 0.1_X;
static constexpr float_X end_ratio = 0.3_X;
static constexpr uint32_t usedDim = 1u;
float_64 first_cell = 0.0_X;
float_64 last_cell = 0.0_X;
RelativeRangeProfile()
{
const SubGrid< simDim >& subGrid = Environment< simDim >::get().SubGrid();
auto globalSize = subGrid.getGlobalDomain().size;
auto deviceOffset = subGrid.getLocalDomain().offset;
first_cell = ( static_cast< float_64 >( globalSize[usedDim] ) * start_ratio ) -
static_cast< float_64 >( deviceOffset[ …
```
=> allow constructor for density free formular functor

docs/source/install/path.rst, docs/source/models/photons.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/positionsParticles.rst
This issues solves a few of the errors/warnings documented in #2564 but does not fix redefinitions caused by doxygen (#2383) nor does it solve the linking issue (#3055). It also avoids issues with the documentation of the radiation plugin, since hose are solved with #3052.
The following issues were solved (see separate commits): 
- fixes syntax error in phase space documentation that prevented showing the python widget code
- fixes warnings of not cited references 
- fixes wrong syntax inline code in particles position plugin
=> fix various sphinx issues not related to doxygen

include/picongpu/fields/FieldTmp.hpp, include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp, include/picongpu/plugins/ChargeConservation.hpp, include/picongpu/plugins/radiation/amplitude.hpp, include/picongpu/plugins/radiation/check_consistency.hpp
Most of this `inline` stuff was covered by #3006, but a couple of things were missed.
For the context: with all these PRs aimed at avoiding double definitions, it is now almost possible to have multiple object files in picongpu that include pmacc and all the real stuff. With a couple more changes, not submitted yet, LWFA is building on both my MSVS and on Hemera in that "multiple object files" mode.
=> Add missing inline specifiers for functions defined in header files

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
switch from for hemera from cmake/3.11.3 to cmake/3.15.2
Edit: the new version is required by the future (upcoming) alpaka release.
=> update profile hemera-hzdr: CMake version

docs/TBG_macros.cfg, docs/source/usage/plugins/radiation.rst, include/picongpu/param/radiation.param, include/picongpu/plugins/radiation/Radiation.hpp, include/picongpu/plugins/radiation/frequencies/radiation_lin_freq.hpp, include/picongpu/plugins/radiation/frequencies/radiation_list_freq.hpp, include/picongpu/plugins/radiation/frequencies/radiation_log_freq.hpp, share/picongpu/examples/Bunch/include/picongpu/param/radiation.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiation.param
In the current implementation the radiation plugin provides a method to set a path tp a list of frequency (omega) values to compute the radiation for. However, the path is set only via command line option and the value set via namespace setting is totally ignored. 
Since various parameters need to be set in `radiation.param` anyway, I removed the command line option (which is not doing anything if the list option has not be selected in `radiation.param` before) end set the path to the path defined in the namespace. 
The documentation was adjusted accordingly.
I would like to do a run-time test just to see whether anything else is not working properly with this frequency option before continuing to work on #800 (for the frequencies). 
----------
**Update:**
With the latest version, all run …
=> refactor: omega read from file

docs/source/usage/workflows/quasiNeutrality.rst
Replace with the up-to-date `ManipulateDerive`. The issue was encountered by @StevE-Ong in #3067.
=> Fix docs using outdated ManipulateDeriveSpecies

docs/source/usage/tbg.rst
I was missing the feature of automated copying of the configuration file into the output directory by ``tbg``.
Well, I found out that ``tbg`` already does it, while trying to add it, so I added these lines to the ``tbg`` documentation instead. It's pretty useful so let people know that it's there. What do you think? @ComputationalRadiationPhysics/picongpu-maintainers
=> Add information about submit.cfg and submit.tpl files to docs.

include/picongpu/particles/filter/generic/Free.def, include/picongpu/particles/filter/generic/FreeRng.def, include/picongpu/particles/filter/generic/FreeTotalCellOffset.def
This pull request fixes a missing name definition in the particle filter examples. (first commit) 
As you can see in the doxygen generated documentation [here](https://picongpu.readthedocs.io/en/latest/usage/param/particles/init.html#manipulation-filters), the names have been missing before. (this also effects previous documentations. @ax3l Do we need to backport this?) 
The second commit fixes a comparison ion the free filter that compares a 3D vector with a scalar. This should probably not work. Do you agree @psychocoderHPC, @sbastrakov ?
=> fix examples particle filters

etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/V100_restart.tpl
This pull request changes the cores per task setting for the `ml` (V100 GPUs) partition on taurus at ZIH. This became necessary after they changed the default to use the SLURM hint `--hint=nomultithread`. Currently, the tpl files do not allow to start any simulations because they allocate too many physical cores. This pull request reduces the allocation to the maximum possible number, that still allows allocating all GPUs.
**node setup of `ml` partition:**
The `ml` partition has a node that has 44 physical CPU cores and 6 V100 GPUs. The 44 cores have the ability to have 4 hyper-threads each resulting in a total number of virtual cores of `44*4=176`. Neither 44 nor 176 are dividable by the number of GPUs (=6). 
Together with @psychocoderHPC and @sbastrakov, we decided to allocate only the …
=> adjust cores per gpu on taurus after multicore update

docs/picongpu-docs-env.yml, docs/source/dev/sphinx.rst
This PR adds a way to create a clean conda environment just for building our docs.
This seems useful since installing the required packages might otherwise break users' previous Python configurations.
=> Docs: create conda env for building docs

include/picongpu/param/ionizationEnergies.param, include/picongpu/param/ionizer.param
For some experiments, for example harmonics from solids, people use silicon-based targets (e.g. fused silica), so it would be good to have `Si` included to the _commonly used elements_ list. This PR fixes it -- i took ionisation potentials from `mendeleev`  and effective nuclear charge from [wiki](http://en.wikipedia.org/wiki/Effective_nuclear_charge) (as recommended).
=> added silicon element to ioniser

include/picongpu/param/speciesAttributes.param, include/picongpu/traits/attribute/GetCharge.hpp, include/picongpu/traits/attribute/GetChargeState.hpp
=> Make dependency between boundElectrons and atomicNumbers more explicit

include/picongpu/plugins/radiation/Radiation.hpp, include/picongpu/plugins/radiation/Radiation.kernel
I added the SpeciesEligibleForSolver for the @PrometheusPi's radiation plugin, so that the `depenciesFulfilled` variable in  `radiation.hpp`, as well as the empty Kernel in `radiation.kernel` are not required anymore.
=> SpeciesEligibleForSolver for radiation plugin

docs/source/usage/plugins/radiation.rst
This pull request closes #3041. It adds a description on how to read the outputted data from the radiation plugin both for text-based output and the HDF5 output. Furthermore it provides python code to read and plot the data. The documentation now also covers how to use the python module to read the HDF5 radiation data. 
This pull requests also fixes an older typo and a table misalignment. 
The separate commits add different content and thus can be reviewed separately. 
@Anton-Le please have a look at this pull request.
=> Add output and python module doc for radiation plugin

include/pmacc/Environment.hpp
If a CUDA device is pre-selected to a MPI rank by e.g. the batch system
with environment variable `CUDA_VISIBLE_DEVICES` than the current
implementations thows an error.
This issue was first seen in #3007
- query device properties for each device instead only for once
- throw an error if no device can be selected
=> fix CUDA device selection

docs/source/install/profile.rst, docs/source/usage/tbg.rst, etc/picongpu/summit-ornl/LSF_Tutorial.rst, etc/picongpu/summit-ornl/gpu_batch.tpl, etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Add a software profile, TBG job template and LSF tutorial for Summit at ORNL.
Also see: https://jsrunvisualizer.olcf.ornl.gov/index.html?s4f1o17n6c7g1r11d1b1l0=
The information below is outdated and was fixed via #3084 
~~Our self-paced `hostRank` assignment in https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.4.3/include/pmacc/communication/CommunicatorMPI.hpp#L285-L333 prevents that we can just use the automatic placement in `jsrun` [resource sets](https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#job-launcher-(jsrun)) with 7 cores + 1 GPU each.~~
```
.TBG_coresPerGPU=7
jsrun -n !TBG_tasks -g 1 -a 1 -c !TBG_coresPerGPU -b packed:!TBG_coresPerGPU -d packed -l GPU-CPU --smpiargs="-gpu" !TBG_dstPath/input/bin/picongpu !TBG_author …
```
=> Summit: Profile & Templates

share/picongpu/examples/Bremsstrahlung/etc/picongpu/8.cfg
This pull request adds the missing calorimeter sub-arguments `file` and `filter` in the `8.cfg` of the Bremsstrahlung example. 
@sbastrakov and @psychocoderHPC I am not yet sure when this bug was introduced since due to the restructuring of the code, its history is not easily accessible. But it definitely affects the latest release. 
This pull request closes #3096.
=> fix 8.cfg for Bremsstrahlung example

include/picongpu/param/transitionRadiation.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/transitionRadiation.param
Allow the case of a single azimuth or polar angle for transition radiation calculation. 
Additionally I added a bit of documentation to make it more clear, what happens if you calculate in a single azimuth / polar direction. This should resolve #3090.
I checked the output of simulations quickly (for the 4 following parameters: `nPhi = 128` and `nTheta = 128`, `nPhi = 1` and `nTheta = 128`, `nPhi = 128` and `nTheta = 1` and `nPhi = 1` and `nTheta = 1` and there are no NaNs anymore and the calculated values look good. But I didn't change the angle discretization, so this is to be expected. 
Edit: There are no test at the moment, but I don't see why it shouldn't work since it's just an addition. 
Edit 2: I tested for `nPhi = 1` and `nTheta = 1` and there are no NaNs.
@PrometheusPi …
=> Fix observation direction of transition radiation plugin

share/picongpu/examples/Bremsstrahlung/etc/picongpu/1.cfg
This pull request adds a single GPU setup `1.cfg` to the Bremsstrahlung example as suggested by @ax3l in issue #3092.
=> add 1.cfg to Bremsstrahlung example

docs/source/usage/plugins/sliceEmittance.rst
As requested by @ax3l, this pull request adds the reference to @kossag14's master thesis in the slice emittance plugin documentation. 
I tested the sphinx build locally and the reference/link works fine. 
Thanks to @n01r for find/asking for the DOI.
=> add reference to thesis for emittance plugin doc

docs/source/usage/plugins/transitionRadiation.rst
There was a wrong underlines in the mark down files of the Transition Radiation radiation plugin documentation. Its reference section escaped the structure and appeared as a separate "plugin". 
Now only
- `Period Syntax` has the same level as a plugin
- `Python Postprocessing` has the same level as a plugin
@ComputationalRadiationPhysics/picongpu-maintainers is this Okay with you or should these sections disappear from the list. 
See: https://picongpu.readthedocs.io/en/latest/usage/plugins.html#
=> fix wrong underline in TrasRad plugin doc

docs/TBG_macros.cfg, docs/source/usage/plugins/transitionRadiation.rst
This pull request resolves some errors and incorrect wordings in the transition radiation plugin documentation and adds a command line flag configuration to the `TBG_macro.cfg`.
The plugin was just recently introduced to the `dev` #3003.  
The fixes are:
- `transitionRaditionMask` is a flag not an attribute
- the command line names were not correct
@psychocoderHPC strangely I could add the flag `transitionRadiationMask` to the particle attributes without causing a compile time error (of course the plugin wasn't compiled) - shouldn't adding a flag to the attributes cause an error?
=> fix doc transition radiation plugin

docs/source/usage/plugins.rst, docs/source/usage/plugins/transitionRadiation.rst
This pull request fixes various errors elated to the CTR plugin documentation:
- the link in the table in the plugin  overview lead to the radiation - not to the transition radiation plugin documentation 
- the table with the three frequency options did not show up online due to the malformatted table 
- a warning regarding the list frequency setup referenced the wrong namespace
=> fix errors in transition radiation documentation

test/hasEOLwhiteSpace, test/hasTabs
Make the code style checks work with both GNU sed as well as OSX/vanilla POSIX sed.
This updates the EOL whitespace as well as the TABs to spaces transformations.
There are a few more tests that you can adjust similarly in a follow-up PR :)
Related to #3060
=> Travis CI: OSX sed Support

include/picongpu/particles/pusher/particlePusherProbe.hpp
It is normally only a warning but the compiler is interpreting it as function call I marked it as bug.
```
picongpu/particles/pusher/particlePusherProbe.hpp:80:34: warning: empty parentheses interpreted as a function declaration [-Wvexing-parse]
ActualPush actualPush();
^~
picongpu/particles/pusher/particlePusherProbe.hpp:80:34: note: replace parentheses with an initializer to declare a variable
ActualPush actualPush();
```
=> fix wrong constructor call

include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.tpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.tpp
Fix places where the method prefix of the declaration and implementation
is not matching. Bugs found with hip-clang.
The latest release 0.4.3 is also effected but I never got an error before using hip-clang.
=> fix wrong used method prefix

thirdParty/cmake-modules/FindADIOS.cmake
Updates the hints how to find ADIOS1:
- https://github.com/ComputationalRadiationPhysics/cmake-modules/pull/19 (@ax3l)
Back-port fixes that were applied to [openPMD-api](https://github.com/openPMD/openPMD-api)'s version of this CMake module:
- https://github.com/openPMD/openPMD-api/commit/2f8b3b3125ef08d79fd621fb7184fdd3ee37c429
Start with emtpy lists for the find module. Avoids append-issues when called multiple times.
- https://github.com/openPMD/openPMD-api/commit/c54f6a1b3ab696991ecf6248c12fa32ae67e70a6
Less Verbose: clean up debug messages and honor `QUIET`
- https://github.com/openPMD/openPMD-api/commit/a78f16db013a5b8cb5873643a4a1d4595f1b5512
Cross-Compile Support
- https://github.com/openPMD/openPMD-api/commit/446a155a4d235eca1ed9c5785188b14072e1ccd0
Static Linking: pthread should …
=> CMake Modules: Update ADIOS FindModule

docs/source/usage/plugins/transitionRadiation.rst, include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp, share/picongpu/examples/TransitionRadiation/include/picongpu/param/speciesDefinition.param
This pull request fixes a bug in the transition radiation plugin that prevented the gamma filter from working.
The `transitionRadiationMask` was set as flag not as attribute, thus the filter was never applied and assumed to be always true. 
The documentation was updated alongside.
=> fix gamma filter transition radiation

include/picongpu/plugins/adios/writer/ParticleAttributeSize.hpp
`timeOffset` should be a scalar, not an array.
Opening this since I needs this when I get to work in the morning.
Fix #3119
=> ADIOS Writer: Fix timeOffset

etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_restart.tpl
The recent SLURM update from version 17.02 to 19.05 changed how the long version of the run time argument of working directory is defined. It changed from `--workdir` to `--chdir`.
This pull request fixes this issue. 
@wmles @Anton-Le This will probably affect your simulations as soon as you start running on hemera again.
=> update hemera tpl after SLURM update 

include/pmacc/dimensions/DataSpace.hpp
While working on #3122 I stumbled upon some non-intuitive automatic conversions of `DataSpace`. This PR makes some of the conversions explicit. After offline discussion with @psychocoderHPC we decided to keep others implicit for now. Also a slight style modernization in a separate commit.
=> Make pmacc::DataSpace conversions explicit

include/picongpu/CMakeLists.txt
The `/bigobj` flag is required for almost all PIConGPU setups, so reasonable to set by default. The other flag is needed for Visual Studio versions after 15.8, I put an explanatory link. Just discovered it recently after updating my VS.
I also now have one more weird error in the cmake-generated VS project (easy to fix manually). It seems to link to the correct Boost program_options but somehow also adds a dependency to the same library but without the path to it. But not yet sure where it comes from, maybe some issues on my system. Adding the directory to the search path helps.
=> Fix cmake flags for MSVS

INSTALL.rst, include/pmacc/PMaccConfig.cmake
remove warning that CUDA 10.2 is untested
I tested CUDA 10.2 (runtime/compile) on our test system with a V100. :fireworks: NVIDIA not introduced breaking changes.
Modules used for the test:
```
boost@1.68.0
cmake@3.15.4
cuda@10.2.89
openmpi@3.1.2
```
=> CMake: mark cuda 10.2 as tested

bin/pic-create, bin/picongpu-completion.bash, etc/picongpu/aris-grnet/gpu_picongpu.profile.example, etc/picongpu/cori-nersc/knl_picongpu.profile.example, etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/jureca-jsc/batch_picongpu.profile.example, etc/picongpu/jureca-jsc/booster_picongpu.profile.example, etc/picongpu/jureca-jsc/gpus_picongpu.profile.example, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/summit-ornl/gpu_picongpu.profile.example, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example
I finished a basic completion for the important PIConGPU scripts as mentioned in #1972. If you want to test it, you can `source $PICSRC/bin/picongpu-completion.bash` after sourcing a PIConGPU profile (Or just source a new profile which does it automatically). 
This is a list of features:
The following points have been considered, but decided for future implementation, not  in this PR:
- Show correct CMAKE variables if the previous option was `--cmake`
- Only show `.tpl` files at `tbg -t [TAB]`
- Show available backends at `--backend`. Here I'm not sure if it is generally possible or too system dependend
- Show available submit systems at `tbg -s [TAB]`. The same with the previous point
It should work so far. Feel free to test it and leave suggestions …
=> Bashcompletion

etc/picongpu/aris-grnet/gpu_picongpu.profile.example, etc/picongpu/cori-nersc/knl_picongpu.profile.example, etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/jureca-jsc/batch_picongpu.profile.example, etc/picongpu/jureca-jsc/booster_picongpu.profile.example, etc/picongpu/jureca-jsc/gpus_picongpu.profile.example, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/summit-ornl/gpu_picongpu.profile.example, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example
It is not possible to source the profiles for the PIConGPU environment
if the file `$PICSRC/bin/picongpu-completion.bash` is not available.
All tpl files are loding the profile inside the jobscript. If the
completion file is not available the simulation will not start.
bug was introduced with #3069
=> fix loading picongpu profile

include/pmacc/memory/buffers/GridBuffer.hpp
Fix a funny typo reported by @jkelling . However, [the wicked which](https://wordwise.typepad.com/blog/2010/01/the-wicked-which.html) is still probably present in multiple places.
=> Fix a typo in exchange communication tag status output

include/picongpu/particles/particleToGrid/derivedAttributes/MidCurrentDensityComponent.def, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/adios/writer/ParticleAttributeSize.hpp, include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/plugins/hdf5/openPMD/patchReader.cpp, include/picongpu/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/writer/Field.hpp, include/picongpu/plugins/hdf5/writer/ParticleAttribute.hpp, include/picongpu/plugins/misc/ComponentNames.cpp, include/picongpu/plugins/misc/ComponentNames.hpp
The previous implementation had two issues:
- for > 4 components it led to out-of-bounds access when iterating by component index
- the logic was copied in multiple places
Create a utility function for text names of vector components. Change hardcoded names to use the new function. The new way guarantees unification and avoids potential out-of-bounds access by index.
~~TODO: do more checks with PML output and checkpointing.~~ (done)
=> Unify output text names of vector components

README.md, docs/source/usage/plugins/radiation.rst
This pull request adds a link to my PhD thesis in the documentation of the radiation plugin and adds the "Dr."-title in front of my name.
=> add PhD thesis reference in radiation plugin

include/pmacc/mappings/simulation/GridController.hpp
Just a small thing that popped up when trying to do a natural `auto const & gridController = Environment<simDim>::get().GridController();` and then `gridController.getGlobalRank()` not compiling due to lack of `const` in this getter.
=> Add missing const to some GridController getters

include/picongpu/fields/FieldJ.hpp, include/picongpu/fields/FieldTmp.hpp, include/picongpu/particles/Particles.hpp, include/picongpu/particles/flylite/helperFields/LocalDensity.hpp, include/picongpu/particles/flylite/helperFields/LocalEnergyHistogram.hpp, include/picongpu/particles/flylite/helperFields/LocalRateMatrix.hpp, include/pmacc/particles/memory/buffers/MallocMCBuffer.hpp, include/pmacc/random/RNGProvider.hpp
Clang is throwing warnings that the qualifier `override` is missing for when
a virtual method is overridden from the child class.
CC-ing: @jkelling
=> Fix missing override flags

include/picongpu/traits/PICToOpenPMD.tpp
Add a trait to rename the `particleId` identifier to `id` during ADIOS and HDF5 I/O.
Although particle id is an optional particle record, [its naming is defined in the openPMD 1.X base standard](https://github.com/openPMD/openPMD-standard/blob/1.1.0/STANDARD.md#particle-records) and required for particle tracking tools, e.g. as used in openPMD-viewer.
I have not tried this at runtime (see #3142) and just picked this up since nobody else did, testing welcome.
cc @n01r @PrometheusPi @steindev 
This is a breaking change for checkpoint data, in case particle ids are activated (non-default). Maybe do not backport.
Close #3142
=> openPMD: use particle id naming

lib/python/picongpu/plugins/jupyter_widgets/base_widget.py, lib/python/picongpu/plugins/jupyter_widgets/energy_histogram_widget.py, lib/python/picongpu/plugins/jupyter_widgets/phase_space_widget.py, lib/python/picongpu/plugins/jupyter_widgets/png_widget.py
This PR adds the optional keyword argument `output_widget` to the jupyter widgets to provide an instance of `widgets.Output` for capturing relevant output of the member functions.
This has the advantage, that we now get control over where the output is written within the notebook and can clear messages without getting an ever increasing stack of lines below the cell of the widget.
The default valufe for the argument is `None` in which case a new `widgets.Output` instance is created and made part of the widgets list of children.
If a reference to an existing output widget is provided, it is the callers responsibility to display the output widget somewhere in the notebook and it is not made part of our widgets children.
=> Jupyter widgets output capture

share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesDefinition.param
While looking into [another potential bug](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3160#issuecomment-584186175), accidentally found out this typo (or a copy-paste error perhaps). Ideally, we would perhaps want to check non-negativity of the resulting densities automatically, however this is probably problematic, same as #3109.
=> Fix a typo in density ratio value of the KHI example

include/picongpu/particles/bremsstrahlung/ScaledSpectrum.tpp
Was triggered in Bremsstrahlung/ScaledSpectrum by having the denominator as a 32-bit floating-point number, not 64-bit.
=> Fix warning #222-D: floating-point operation result is out of range

include/picongpu/fields/LaserPhysics.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/absorber/ExponentialDamping.hpp, include/picongpu/fields/absorber/NumCells.hpp, include/picongpu/simulation/control/DomainAdjuster.hpp
Add a new variable for the absorber size. Change all usage outside of `.param` files to the new variable. This unifies the size of the exponential damping and PML absorbers. It avoids potential issues with compile-time checks pointed out
in the [comments of #3148](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3148#issuecomment-582865342).
=> Unify absorber size for PML and exponential damping

lib/python/picongpu/plugins/plot_mpl/requirements.txt
Removes requirements `sys` and `getopt` that are already part of all python installations anyway.
At the moment, executing `pip install -r <pic_path>/lib/python/picongpu/requirements.txt` crashes due to not finding requirement files for the above mentioned packages.
=> Fix python requirements: remove sys and getopt

include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel, include/picongpu/param/fieldSolver.param, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/WriteFields.hpp, include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/writer/Field.hpp, include/picongpu/traits/IsFieldDomainBound.hpp, lib/python/picongpu/utils/memory_calculator.py, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldSolver.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/fieldSolver.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/fieldSolver.param
By internally storing only the required near-boundary values instead of the whole local domain as for normal E and B. Along the way did small style improvements.
TODO:
=> Reduce PML memory consumption

include/picongpu/particles/bremsstrahlung/ScaledSpectrum.tpp
Add more `constexpr` evaluated maths in Bremsstrahlung physics.
Follow-up to #3170
=> Bremsstrahlung: use more constexpr

etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_restart.tpl, etc/picongpu/taurus-tud/k20x.tpl, etc/picongpu/taurus-tud/knl.tpl
This pull request fixes the working directory setting for taurus/zih/TU Dresden jobs, which became outdated end of last week due to a slurm update.
=> slurm update taurus: workdir to chdir

docs/source/install/instructions/spack.rst
Recent versions of Spack perform `spack load` without requiring modulefiles. The `spack bootstrap` command is deprecated in [0.14.0+](https://github.com/spack/spack/releases/tag/v0.14.0).
Follow-up: someone should check if the workflow for container builds in [`share/picongpu/dockerfiles`](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/dockerfiles) needs an update.
=> Spack: w/o Modules by Default

lib/python/picongpu/plugins/data/requirements.txt
This pull request adds [pillow](https://python-pillow.org/) as dependency before scipy because it conflicts otherwise with matplotlib - suggested by @codingS3b.
=> add pillow as dependency

include/picongpu/plugins/particleMerging/ParticleMerger.kernel
This caused wrong worker indexes which led to deadlocks. The issue was caused by `DataSpaceOperations::map` no longer handling out-of-domain indices, which the plugin relied on. So now perform the modulo operations inside the plugin.
=> Fix mapping of cell indexes in the particle merger plugin

docs/source/models/field_ionization.rst, docs/source/models/field_ionization_charge_state_prediction.py, lib/python/picongpu/utils/__init__.py, lib/python/picongpu/utils/field_ionization.py
This PR adds a python script that plots a charge state population prediction for Neon gas that is irradiated by a laser pulse of 30fs duration.
The maximum a0 is 10 and the pulse is only modeled as a Gaussian envelope.
A documentation section has been added as well.
At the moment the plot it creates in the docs looks like this:
- *top panel*: ionization rates for Neon in the ADK model calculated with the intensity shape given in the lower panel
- *middle panel*: relative charge state population of Neon based on the ADK model
- *lower panel*: temporal intensity distribution in black and BSI model predicted charge state population overlay in colored regions
=> [WIP] Docs: Add ionization prediction plot

include/pmacc/attribute/Constexpr.hpp
Apply workaround for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91377
reported by @jkelling
=> fix GCC constexpr lambda bug

docs/source/usage/plugins/phaseSpace.rst
The code snippet used to illustrate the usage of the phase space visualization widget has to be corrected. `run_dir_options` expects a list of tuples of the type `( <description>, <path to data>)`.
Additionally add an example illustrating how to add additional phase space slices and to set different particle species for visualization.
=> Correct jupyter widget example

docs/source/usage/plugins/energyHistogram.rst, lib/python/picongpu/plugins/data/base_reader.py
Fixes #3140 by updating the example for the `EnergyHistogramData` in the documentation.
Now the correct number of return values for the `.get` method are provided and all arguments are provided as keyword arguments.
However, providing arguments should now also work since the base class function signature got updated as well.
=> EnergyHistogram: allow non-keyword arguments

include/picongpu/particles/ParticlesInit.kernel
=> fix typo: `UNIT_LENGHT` to `UNIT_LENGTH`

lib/python/picongpu/plugins/data/png.py, lib/python/picongpu/plugins/data/requirements.txt
The python reader for the PNG plugin relies on the `scipy.misc.imread` function which was deprecated and removed for `scipy>=1.2.0` according to the docs (https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html).
This PR exchanges the import of the `imread` function as suggested in the scipy docs.
=> Change imread import from scipy.misc to imageio

lib/python/picongpu/plugins/jupyter_widgets/base_widget.py, lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
There are several issues when trying to change the selectable simulation options for a widget using the `set_run_dir_options` function which are addressed in this PR:
1. After updating the dropdown options, for widgets which do not allow multi-selection of simulations (like the png widget), the dropdowns value was also silently set which we do not want since the user has not made a choice on which simulation should be visualized
2. The plot did not get cleared and still visualized a selection of the old run_directories.
3. The simulation time options were not invalidated, possibly containing simulation times from the old selection
4. the plot_mpl object (and therefore also the data readers) was not updated and might have contained data from now outdated simulations.
Moreover, the energy …
=> Python: fix set rundir options for widgets, EnergyHistogram all zeros

include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
The reason that was forgotten is that originally the `YeePML` implementation inherited the `Yee` solver which had the CFL check in place, and so PML did not. The inheritance was later changed, and I forgot to add the check back. Thanks to @cbontoiu  for [reporting](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3207#issuecomment-596948103).
=> Add forgotten CFL check for YeePML

docs/source/usage/plugins.rst
Just noticed it while working on documentation for #2973.
=> Fix a typo in the reference to [Pausch2018]

include/picongpu/fields/absorber/ExponentialDamping.hpp
The bug was introduced in #3161 by my copy-paste mistake, sorry. Was likely the cause of report #3217 (checking right now, but 99% sure). 
This needs to go into the 0.5.0 @psychocoderHPC .
=> Fix wrong exponential absorber strength

docs/source/prgpatterns/lockstep.rst, include/picongpu/fields/FieldJ.kernel, include/picongpu/fields/FieldTmp.kernel, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel, include/picongpu/particles/Particles.kernel, include/picongpu/particles/creation/creation.kernel, include/picongpu/plugins/Emittance.hpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel, include/pmacc/nvidia/reduce/Reduce.hpp, include/pmacc/particles/ParticlesBase.kernel, include/pmacc/particles/operations/CountParticles.hpp
This is a fixup of #3211 which did these renamings for most of the code. Also, update usage in the docs since this is now the preferred way.
Perhaps these were missed in #3211 because only `__syncthreads();` occurances were checked, but not `__syncthreads( );`
I found out as it failed to build on my machine for the CPU accelerator. Wondering why did the tests pass for that PR?
=> Replace remaining cupla renamings with calls to cupla API

etc/picongpu/summit-ornl/gpu_batch.tpl, include/pmacc/Environment.hpp, include/pmacc/eventSystem/tasks/TaskReceive.hpp, include/pmacc/eventSystem/tasks/TaskReceiveMPI.hpp, include/pmacc/eventSystem/tasks/TaskSend.hpp, include/pmacc/eventSystem/tasks/TaskSendMPI.hpp, include/pmacc/memory/buffers/Exchange.hpp, include/pmacc/memory/buffers/ExchangeIntern.hpp, include/pmacc/particles/ParticlesBase.tpp, include/pmacc/particles/memory/buffers/StackExchangeBuffer.hpp, include/pmacc/simulationControl/SimulationHelper.hpp
Add support for MPI direct (e.g. CUDA GPU direct)
- disable the host double buffer for exchanges if MPI direct is enabled
- add command line parameter `--mpiDirect`
- active MPI direct for summit
=> MPI direct support

include/picongpu/fields/absorber/ExponentialDamping.hpp
The bug was introduced in #3161 by a copy-paste mistake.
Was likely the cause of report #3217.
backport of PR #3218
=> Fix a bug with wrong exponential absorber strength

share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
fix `apt` error: `cuda-command-line-tools-9-2 : Depends: cuda-cupti-9-2 (>= 9.2.148) but it is not going to be installed`
solution: explicit install `cuda-cupti-*`
=> fix docker container

docs/source/usage/param/core.rst, docs/source/usage/param/particles/current.rst, include/picongpu/fields/FieldJ.kernel, include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/currentDeposition/Cache.hpp, include/picongpu/fields/currentDeposition/Deposit.hpp, include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp, include/picongpu/fields/currentDeposition/EmZ/EmZ.def, include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.def, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, include/picongpu/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, include/picongpu/fields/currentDeposition/Solver.def, include/picongpu/fields/currentDeposition/Strategy.def, include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.def, include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp, include/picongpu/param/species.param, include/pmacc/nvidia/functors/Atomic.hpp, share/picongpu/examples/Bunch/include/picongpu/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/species.param
Implement different strategies for the reduction of the scattered
current from particles.
- PMacc: Add generic atomic functor
- add strategies:
- StridedCachedSupercells (this is the old strategy used before this PR)
- CachedSupercells
- NonCachedSupercells
- Strategy will be selected based on the cupla accelerator 
- for NVIDIA `CachedSupercells` is used
- other backends use the old strategy `StridedCachedSupercells`
- add class `Cache` to implement different caching strategies
- move the curent deposition kernel call into a separate file: `Deposit.hpp`
update documentation 
- add particle section for the current deposition
- update `species.param` with information about the `Strategies`
This PR improves the performance for NVIDA P100 and V100 up to a factor 1.18 (example KHI).
This PR …
=> strategy for current deposition algorithm

docs/requirements.txt
RTD does not yet provide Sphinx 3 but Breathe 4.15.0+ requires Sphinx 3.
This fixes failing RTD builds of our manual.
Ref.: https://github.com/michaeljones/breathe/issues/495
=> Breathe: <4.15.0

docs/requirements.txt
RTD does not yet provide Sphinx 3 but Breathe 4.15.0+
requires Sphinx 3.
Ref.: https://github.com/michaeljones/breathe/issues/495
=> Backport: Breathe: <4.15.0

lib/python/picongpu/plugins/plot_mpl/utils.py
fix error:
```
$ pyflakes .
727./lib/python/picongpu/plugins/plot_mpl/utils.py:34:18 '...'.format(...) mixes automatic and manual numbering
```
=> fix manual and automatic field specification

docs/source/install/profile.rst, etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
This commit adds the profiles for the new V100-GPUs of the CASUS cluster. The profiles are very similar to the `gpu`-queue.
=> Add profiles for the new GV100 GPUs on Hemera

lib/python/picongpu/plugins/plot_mpl/utils.py
fix error:
```
$ pyflakes .
727./lib/python/picongpu/plugins/plot_mpl/utils.py:34:18 '...'.format(...) mixes automatic and manual numbering
```
This **backport** PR is required to pass the CI.
=> backport: fix manual and automatic field specification

include/picongpu/plugins/particleMerging/ParticleMerger.kernel, include/picongpu/plugins/particleMerging/VoronoiCell.hpp
Replace atomicAllInc, which required the same address for all threads in a block, that сaused incorrect number of macroparticles in Voronoi cells with cupla::atomicAdd.
Add syncthreads after voronoi cells start initialization.
=> Fix incorrect initialization and data race

include/picongpu/plugins/particleMerging/ParticleMerger.kernel, include/picongpu/plugins/particleMerging/VoronoiCell.hpp
backport #3239
- replace atomicAllInc, which required same adress for all threads in block with cupla::atomicAdd
- add syncthreads after voronoi cells initialization
=> Backport: Fix incorrect initialization and data race

include/picongpu/plugins/ResourceLog.cpp, include/picongpu/plugins/ResourceLog.hpp
It is not copyable, but only movable. So replace with just returning the `string` as this is all we need.
I looked into that while investigating #3249. I am not sure if it caused that issue, but this definitely looks like an issue.
=> Fix returning a stringstream by value

include/pmacc/algorithms/math/floatMath/trigo.tpp
Was just introduced by #3245, looks like this configuration is not in our CI.
=> Fix a double bracket typo

.gitignore
Since there are similar excludes for netbeans, VS, etc. I though I would add one for Clion as well.
=> Add JetBrains project dir to .gitignore.

INSTALL.rst, docs/TBG_macros.cfg, docs/source/usage/plugins.rst, docs/source/usage/plugins/checkpoint.rst, docs/source/usage/plugins/openPMD.cfg, docs/source/usage/plugins/openPMD.rst, include/picongpu/CMakeLists.txt, include/picongpu/plugins/Checkpoint.hpp, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/openPMD/NDScalars.hpp, include/picongpu/plugins/openPMD/WriteMeta.hpp, include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDWriter.def, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/openPMD/restart/LoadParticleAttributesFromOpenPMD.hpp, include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp, include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp, include/picongpu/versionFormat.cpp, share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/8.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg, share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg
Implement writing to and reading from openPMD.
**Todo**
For testing purposes, please use [this branch of the openPMD API](https://github.com/franzpoeschel/openPMD-api/tree/topic-advanced-backend-configuration).
As [noted below](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2966#issuecomment-501717152), the HDF5 backend in the openPMD API is currently broken and may not be used in this plugin at the moment.
The resulting storage files are *incompatible* with the files written by the existing plugins: The existing plugin writes datasets `/data/<iteration>/picongpu/idProvider/startID`, but the openPMD API only supports writing datasets `/data/<iteration>/(fields|particles)/*/*(/*)` at the moment, so those datasets have been temporarily relocated to …
=> openPMD Plugin

include/picongpu/param/speciesAttributes.param, include/pmacc/identifier/alias.hpp, include/pmacc/identifier/identifier.hpp
- use `constexpr` for instances e.g. `momentum_`
- enforce a semicolon after the macro
- fix `speciesAttributes.param` - add missing semicolon
Co-authored-by: Jeffrey Kelling <j.kelling@hzdr.de>
Since the namespaces for the types are removed our kernel names will be 300-400 characters shorter :tada:
=> refactor pmacc  identifier and alias

docs/source/usage/plugins/openPMD.rst
The [ReadTheDocs documentation of the openPMD plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html) contains some misalignment which results in the command line argument table not showing. This pull request fixes this issue. 
The issue was introduced to `dev` with today's merge of  #2966.
=> fix openPMD plugin doc

include/pmacc/math/ConstVector.hpp, include/pmacc/math/vector/Vector.hpp
Create a `constexpr` ConstVector instance on the host side to increase
the compatibility with OpenAcc and OpenOmp5.
Co-authored-by: Jeffrey Kelling <j.kelling@hzdr.de>
CC-ing: @jkelling
=> refactor `ConstVector`

include/picongpu/param/pusher.param, include/picongpu/param/species.param, include/picongpu/particles/pusher/particlePusherHC.hpp, include/picongpu/particles/pusher/particlePusherHigueraCary.hpp, include/picongpu/unitless/pusher.unitless, share/picongpu/examples/Bunch/include/picongpu/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/species.param
Add Higuera-Cary pusher as presented in [doi:10.1063/1.4979989](https://doi.org/10.1063/1.4979989).
The HC method is 2nd order, structure preserving, and relativistically correct.
Compared to Vay's method, the HC method has the additional property of being structure preserving while it correctly calculates the velocity in ExB direction when E·B=0 in contrast to Boris' method.
A correction to the formulas given in the original article is applied as documented by the WarpX team: (https://github.com/ECP-WarpX/WarpX/issues/320).
Further references:
* [Higuera's article on arxiv](https://arxiv.org/abs/1701.05605)
* [Riperda's comparison of relativistic particle integrators](https://doi.org/10.3847/1538-4365/aab114)
**Tests performed so far**
* Single particle acceleration in constant electric …
=> Add Higuera-Cary pusher

include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp, include/picongpu/plugins/hdf5/writer/Field.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
Fix #3275 for all three output backends.
Since the three output plugins we have are largely similar, the changes are basically copy-pasted in all 3 plugins. I deliberately did not go into abstracting and reusing, since this is a patch (to a patch for PML support) and the HDF5 and ADIOS plugins will (hopefully) be removed soon.
=> Fix checkpointing and output of PML fields for uneven domains

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
After the IT team at HZDR added a newer openPMD-api module to the module system, this could be included in the PIConGPU example profiles for the hemera cluster. 
- update to CUDA 10.2
- load openPMD module
@psychocoderHPC and @sbastrakov Please see internal  IT ticket number `SR.10732` for details.  
This should be hopefully consistent with the just merged #2966. I have requested the module update due to compile issues with #3134.
=> update hemera modules and add openPMDapi module

include/picongpu/CMakeLists.txt
This pull request adds verbose output for finding and not finding the openPMD-api in CMake. 
Thanks @psychocoderHPC for your help.
=> add verbose output for openPMD-api

share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/fieldSolver.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param
If KHI is compiled for non CUDA devices and the field solver `DirSplitting` is enabled the compile will fail.
`DirSplitting` requires CUDA. One case defined in `cmakeFlags` is using directional splitting.
This PR added a precompiler guard section to switch to the field solver Yee if we compile for non CUDA devices.
=> fix KHI for non CUDA devices

include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/absorber/Absorber.hpp, include/picongpu/param/fieldSolver.param, include/picongpu/param/pml.param, include/picongpu/unitless/pml.unitless, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/pml.param
PMLs could be used in other field solvers, too. But to do so, the variables of the PML in `pml.param` need to be separated from the `YeePML` field solver. This PR puts the definitions of the PML variables in their own namespace `PML` and updates the `YeePML` field solver to use the variables from this namespace.
A test with laser propagation in vacuum using PML boundaries compiles without error. (I am not sure if there is one compile test in the CI using PMLs.)
=> Abstract PML definitions from YeePML field solver

include/picongpu/plugins/openPMD/openPMDWriter.def, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
See https://github.com/ComputationalRadiationPhysics/picongpu/issues/3278
1. A variable was declared and defined equivalently in two scopes
2. Rename `AccessType` (deprecated) → `Access`
=> Fix warnings in the openPMD plugin

.gitlab-ci.yml, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_nvcc_cuda.yml, share/ci/generate.sh, share/ci/run_test.sh
Introcude the infrastructure and basic test for the HDZ gitlab CI.
- provide a matrix yaml generator script for PIConGPU
- test `example/Empty` with clang, gnu, clang-cuda and nvcc
Currently the HZDR CI will not test the empty example to keep the test time low. Clang compiler will still fail until all open clang fixes are merged.
It is not required for merging that the HZDR CI is passing all tests.
=> activate reduced HZDR CI tests

include/picongpu/boost_workaround.hpp, include/picongpu/main.cpp, include/picongpu/versionFormat.cpp
fix #3294
Solve invalid compiler detection in the clang-cuda device compile path.
=> fix clang-cuda and boost compile

share/picongpu/examples/FoilLCT/README.rst
Add reference: This was actually a (significantly thicker) example for our 2018 experiments at Draco PW. Simulation studies are carried out by our collaborators.
=> LCT Example: Add Reference

include/picongpu/CMakeLists.txt, include/picongpu/boost_workaround.hpp, include/picongpu/versionFormat.cpp, include/pmacc/PMaccConfig.cmake, include/pmacc/math/vector/Vector.hpp
- fix clang-cuda boost compatibility
- The include workaround is required for `main.cpp` too. Move the workaround include to `boost_workaround.hpp`
- Fix early evaluation of a static assert.
```
pmacc/math/vector/Vector.hpp:583:9: error: static_assert failed "Vector_dim_0_create_cannot_be_called"
PMACC_CASSERT_MSG(Vector_dim_0_create_cannot_be_called, false);
```
- fix clang-cuda incompatibility with OpenMP
- If clang is used as CUDA compiler and OpenMP is enabled the compilation will crash. It is a general clang-cuda bug which will hopfully be fixed with clang 11.
=> fix clang cuda compile

.travis.yml
Originally it matched mutiple packages, causing error.
Fixes #3304
(I know it fixes, as tried it out in #3303 which [passes](https://travis-ci.org/github/ComputationalRadiationPhysics/picongpu/jobs/711131736))
Thanks @psychocoderHPC for hinting the fix.
=> Set cmake version explicitly for travis CI

include/pmacc/mappings/kernel/MappingDescription.hpp
In the first PR #3266 I accidentally  branched  from `master` instead of `dev`. This one shouldn't have any conflicts. 
> This adds some additional debugging information in a case of a super cell size that's too small to fit the guard. Maybe it could be useful to someone else.
> 
> I've added this lines when I was wondering why my code keeps throwing this. In that particular case the problem was caused by an initialization of an empty mapping description with a SC size (0,0,0). Something that couldn't be addressed by verifying the .param files.
> 
>
=> Additional debug info in guard check for SC size

include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, include/picongpu/fields/MaxwellSolver/None/None.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
Clang is evaluating static asserts within a class even if the class is
not used.
A template dependent condition must be introduced to avoid an to early
evaluation.
note: condition `sizeof(T*) != 0` should be used to avoid incomplete type compile errors
=> fix clang10-cuda compile

include/picongpu/param/pusher.param, include/picongpu/param/species.param, include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.tpp, include/picongpu/particles/pusher/Traits.hpp, include/picongpu/particles/pusher/particlePusherComposite.hpp, include/picongpu/particles/traits/GetMarginPusher.hpp, include/picongpu/unitless/pusher.unitless, include/pmacc/traits/IsBaseTemplateOf.hpp, share/picongpu/examples/Bunch/include/picongpu/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/species.param
Composite pushers allow to switch to one of the underlying pushers. So far it is only for two pushers (however, they could be composite as well), but can be reasonably extended to any amount later (maybe even in this PR, will see).
Note that the decision is done by a user-provided functor. So the easy use is just decide based on the current time iteration. And realistically that's about all one could do right now. But theoretically, this can be used to take into account any globally accessible data, or command-line parameters, once there is a way to access that info from the functor.
Example usage in `species.param`:
```cpp
// Old: always Boris
// using UsedParticlePusher = particles::pusher::Boris;
// New: Boris for 100 time iterations and then Vay
using UsedParticlePusher = …
```
=> Add support for composite pushers

.gitlab-ci.yml, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_nvcc_cuda.yml, share/ci/generate.sh, share/ci/generate_reduced_matrix.sh, share/ci/git_merge.sh, share/ci/n_wise_generator.py, share/ci/run_test.sh
Use n-wise testing to select test configurations for the compiler, cuda,
boost version.
- add n-wise matrix generator `n_wise_generator.py`
- add filter for invalid combinations e.g. compiler, boost, cuda
- build dynamic jobs based on the reduced matrix
=> HZDR gitlab CI

share/ci/git_merge.sh
Accepted pull requests will be tested by the CI too, the script `git_merge.sh` tries always to merge into the destination branch. 
For a merged pull request there is no destination branch. The result is that the CI is failing.
Solution: Disable the automatically merge to the destination branch.
=> fix HZDR CI

include/pmacc/memory/buffers/ExchangeIntern.hpp
Depending of the compiler it can result in compile errors.
- add missing `override`
=> fix missing override for virtual functions

include/pmacc/nvidia/functors/Atomic.hpp
fix warning:
```
pmacc/nvidia/functors/Atomic.hpp:73:40: warning: template template parameter using 'typename' is a C++17 extension [-Wc++17-extensions]
template < typename, int > typename T_DstStorage,
^~~~~~~~
class
```
Warning was found with HIP-clang (clang version 10.0.0)
=> warning: used C++17 extension

include/picongpu/fields/MaxwellSolver/Lehe/Derivative.hpp, include/picongpu/fields/differentiation/BackwardDerivative.hpp, include/picongpu/fields/differentiation/ForwardDerivative.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/math/vector/Vector.tpp, include/pmacc/math/vector/compile-time/Vector.hpp
This is useful to express derivatives more naturally. Especially, and this is what motivated making this function, for the upcoming 2D Lehe solver. Also, to set derivative and therefore curl and solver margins more precisely, e.g. for X derivative to have (1, 0, 0) instead of the current (1, 1, 1).
=> Add pmacc functions to get basis unit vectors

include/picongpu/fields/MaxwellSolver/LehePML/LehePML.def, include/picongpu/fields/MaxwellSolver/LehePML/LehePML.hpp, include/picongpu/fields/MaxwellSolver/Solvers.def, include/picongpu/fields/MaxwellSolver/Solvers.hpp, include/picongpu/fields/absorber/Absorber.hpp, include/picongpu/param/fieldSolver.param, include/picongpu/param/pml.param, include/picongpu/unitless/checkpoints.unitless, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldSolver.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/pml.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/fieldSolver.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/fieldSolver.param
Currently the branch has some version of this combination, that may work, but requires more testing. The code changes are also occasionally hacky, I will refactor if the approach works.
To enable the combination, use this branch and set
```cpp
using Solver = maxwellSolver::YeePML<
CurrentInterpolation,
maxwellSolver::lehe::CurlE< maxwellSolver::lehe::CherenkovFreeDirection_Y >
>;
```
in `fieldSolver.param`.
In case this works, it solves #3296.
@Anton-Le , could you try running your test from that issue with my branch?
=> Add support for Lehe solver with PML absorber

include/picongpu/fields/MaxwellSolver/Lehe/Derivative.hpp, include/picongpu/fields/differentiation/BackwardDerivative.hpp, include/picongpu/fields/differentiation/Curl.hpp, include/picongpu/fields/differentiation/ForwardDerivative.hpp, include/picongpu/fields/differentiation/ZeroDerivative.hpp
Previously, the margins were sometimes overly conservative. E.g. Lehe solver defined upper margin for derivative, and therefore curl, as (2, 2, 2), while it actually used (1, 2, 1) with 2 along the Cherenkov-free direction. Move the margins to be defined for functors, not tags, and put precise values. Make use of recently introduced #3319 compile-time basis vectors to express the margins. Adjust curl margin definition accordingly, to be max of derivative margins.
This PR will allow easier uniform implementation of `Lehe` / `LehePML` solvers for both 3D and 2D. Practically speaking, the current 3D-only implementation will only need a slight adjustment to work for 2D as well. This will be done as a follow-up PR.
=> Refactor margin traits for field derivatives

include/picongpu/fields/MaxwellSolver/Lehe/Derivative.hpp, include/picongpu/fields/MaxwellSolver/Solvers.def, include/picongpu/fields/MaxwellSolver/Solvers.hpp
This combination was already mostly enabled by previous PRs. Add special handling of averaging along z. Remove the guards that conditionally enable Lehe for 3D only. Cherenkov-free direction Z does not make sense in 2D, this is checked at compile time.
=> Add support for Lehe and LehePML solvers in 2D

share/ci/bash.profile, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_nvcc_cuda.yml, share/ci/run_test.sh
[Edit by Sergei] Motivation: the existing CI builds PIConGPU without dependencies and so parts of the code are not compiled. This PR shifts to another container that has all optional dependencies, and so provides better testing coverage.
This PR:
- ship `bash.profile` to setup the path to all dependencies (currently
one fixed version)
- use PIConGPU container instead alpaka container
- isaac is currently disabled (requires testing with all compiler versions)
- include a workaround for clang cuda with HDF5 from the apt source (can be removed after HDF5 is self compiled)
After we merged this PR I will disable the old CI for the `dev` branch. For the `master` branch we will keep the old CI in case we like to ship backports for `PIConGPU 0.5.0`
Thanks @ax3l for hosting the web infrastructure …
=> build CI tests with all dependencies

include/picongpu/traits/GetCellType.hpp
Change `fields::CellType` definition to use the new trait.
The additional level of indirection prevents some circular include dependencies, detected while working on antennas.
=> Add a new trait GetCellType of field solvers

share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg
A typo in the name led to it not being resolved and therefore the `.cfg` files were broken. Notably, that includes the 1.cfg for LWFA which we use in the manual (and that's how it was discovered). This was introduced after 0.5.0, so does not affect the last release.
=> Fix wrong variable name in the LWFA setup

include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp
The previous value was incorrect for CPUs which caused crashes #3329. This is just a quick patch fix that replaces the old hard-coded value with a better one, not a proper check for available memory.
Fixes #3329
=> Fix shared memory size in the PhaseSpace plugin

include/pmacc/cuSTL/algorithm/mpi/Reduce.tpp
Variable `new_ranks` can be empty, and so `new_ranks.front()` is incorrect without a bounds check. This situation occurs, for example, if there is a single process and `setThisAsRoot` is false.
So add a bounds check before the unsafe code.
This was found during investigation of #3329, as it crashed on my machine, and is an actual bug that this PR fixes. But this is not what caused it on Hemera.
=> Fix unsafe access to a vector in cuSTL MPI reduce

include/pmacc/cuSTL/container/CartBuffer.tpp
With CUDA enabled, the memory for `refCount` is not allocated, but then accessed. All other access places have guards for null pointer, except this one. So this change is sufficient.
This bug was found during investigation of #3329, but this is not what causes it. The situation fixed by this PR should have actually occurred when running with CUDA, which surprisingly did not lead to a crash.
Note: this concerns cuSTL's `CartBuffer`, not a `pmacc::memory` one, which is way more frequently used as of now.
=> Fix cuSTL CartBuffer dereferencing a null pointer when CUDA is enabled

include/picongpu/plugins/output/images/Visualisation.hpp
Use cupla math implementation of `abs()` instead of `abs` from the global scope.
This change solves compile issues with HIP, found in my HIP prototype branch.
=> fix usage of `::abs()`

include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/absorber/Absorber.hpp
These are to be used in the upcoming incident field implementation.
I did not change the usage in domain adjuster and exponential absorber so far, only in PML.
=> Add generic utilities to get absorber thickness

share/pmacc/examples/gameOfLife2D/main.cpp
While working on #3351 I've found out the default values for arguments are not set. Particularly for the number of steps and rule, which when not set lead to confusing behavior. This PR adds default values for these two.
=> Set default values for some PMacc game of life example arguments

include/pmacc/nvidia/atomic.hpp, include/pmacc/nvidia/warp.hpp
- introduce support for HIP
- change the way how `atomicAllInc` is implemented if no accelerator is
given
- use alpaka intrinsics and warp functions
=> PMacc warp and atomic function refactor

include/picongpu/plugins/xrayScattering/XrayScatteringWriter.hpp
`AccessType` is now `Access` in the `openPMD-api`. This PR updates `XrayScatteringWriter.hpp` and gets rid of the compiler warning.
=> Fix openPMD warning in XrayScatteringWriter

include/picongpu/plugins/adios/WriteMeta.hpp, include/picongpu/plugins/openPMD/WriteMeta.hpp, include/pmacc/traits/GetStringProperties.hpp
As mentioned [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2472#issuecomment-698180089), the `fieldOutputParameters` attribute of openPMD was not output. For all existing field solvers (after #3362 is merged) it was optional, so this is not a bug, however, with new field solver #3338 coming soon, the extension is needed.
Only modify the openPMD and ADIOS plugins to avoid conflicts with removal of HDF5 in #3361.
=> Add output of fieldSolverParameters attribute to output

include/picongpu/fields/MaxwellSolver/LehePML/LehePML.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
Absorber properties are handled separately and properly already.
=> Fix names in string properties of PML solvers to be openPMD-compatible

etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
Juwels has two codes for the allocation project (e.g., hhh123) and account (chhh123). This PR proposes to put them in two separate variables. This fixed the `#SBATCH -A ...` bug reported in https://github.com/ComputationalRadiationPhysics/picongpu/issues/3365.
=> Separate project and account for Juwels profile

etc/picongpu/juwels-jsc/batch.tpl, etc/picongpu/juwels-jsc/gpus.tpl
This pull request solves the SLURM interface issue discovered in #3365. 
`--workdir` needs to be replaced by `--chdir` with the last SLURM update.
=> juwels adjust tpl

include/picongpu/plugins/openPMD/openPMDWriter.hpp
I apparently forgot some instances when posting the same PR [some while ago](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3289). `grep` doesn't report any more findings of `AccessType` within `include`, so I hope things are more complete now.
=> Remove deprecated openPMD::AccessType and replace with openPMD::Access

include/picongpu/particles/pusher/particlePusherHigueraCary.hpp
The name update ensures conformity with the openPMD standard.
See openPMD/openPMD-standard#225.
=> Update "name" property of Higuera-Cary pusher

docs/source/models/field_ionization.rst, include/picongpu/param/ionizer.param, include/picongpu/particles/ionization/byField/ADK/ADK.def, include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp, include/picongpu/particles/ionization/byField/ADK/AlgorithmADK.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSI.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSIEffectiveZ.hpp, include/picongpu/particles/ionization/byField/BSI/AlgorithmBSIStarkShifted.hpp, include/picongpu/particles/ionization/byField/BSI/BSI.def, include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp, include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.def, include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.hpp, include/picongpu/particles/ionization/byField/IonizationCurrent/IonizerReturn.hpp, include/picongpu/particles/ionization/byField/IonizationCurrent/JIonizationAssignment.hpp, include/picongpu/particles/ionization/byField/IonizationCurrent/JIonizationCalc.hpp, include/picongpu/particles/ionization/byField/Keldysh/AlgorithmKeldysh.hpp, include/picongpu/particles/ionization/byField/Keldysh/Keldysh.def, include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, include/picongpu/simulation/control/MySimulation.hpp, share/picongpu/examples/FoilLCT/cmakeFlags, share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesDefinition.param
This PR adds the implementation of ionization current.    
Every field ionization routine now also calculates an ionization current that reduces the local electric field according to the energy used in ionization processes while correctly accounting for the macroparticle shape.
References:
[1] (Eq. 21) http://stacks.iop.org/0741-3335/57/i=11/a=113001?key=crossref.907aa156b73b99b125b1a0ae886c4c22
[2] (p. 223) https://linkinghub.elsevier.com/retrieve/pii/S0021999112007097
[3] (Eq.   2) http://aip.scitation.org/doi/10.1063/1.1814367
[4] (Eq. 15) https://link.aps.org/doi/10.1103/PhysRevA.46.1084
[5] (Eq. 10) https://link.aps.org/doi/10.1103/PhysRevA.43.3100
=> Feature: Ionization Current

include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp, include/picongpu/particles/shapes/CIC.hpp, include/picongpu/particles/shapes/Counter.hpp, include/picongpu/particles/shapes/NGP.hpp, include/picongpu/particles/shapes/P4S.hpp, include/picongpu/particles/shapes/PCS.hpp, include/picongpu/particles/shapes/TSC.hpp, include/picongpu/plugins/adios/ADIOSCountParticles.hpp, include/picongpu/plugins/openPMD/WriteSpecies.hpp
This PR introduces some cleanup of the particle shapes in a few directions. The implementation is not changed, just slightly modernized and better documented. Hopefully, this avoids confusion like I had when discussing it with @psychocoderHPC a couple of days ago. Along the way, it fixes a bug with the `Counter` shape used in the SAXS test that resulted in output shape being -1.
=> Cleanup particle shape structs

etc/picongpu/summit-ornl/gpu_picongpu.profile.example
This pull request updates out example profile for summit/ORNL. The modules loaded now includes adios2 2.6.0 and openPMD-api 0.12.0. This was set up by @ax3l for https://github.com/ECP-WarpX/WarpX/pull/1369 and reported in #3382.
=> update summit profile to include openPMD

etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
The HZDR cluster team added a openPMD 0.12.0 and ADIOS2 module on hemera today. 
This pull request updates the example configuration files. Only the `defq` example is left unchanged, since the modules seem to be installed only for the setup we use for the GPU partitions. 
I am currently testing, whether it works - (together with the fix provided in #3383)
=> update openPMD and ADIOS module

include/pmacc/algorithms/math/floatMath/trigo.tpp, include/pmacc/math/complex/Complex.tpp
The issues were introduced in #3245 and went unnoriced until #3379 .
Fix wrong formula in `Abs` implementation.
Make return types of `Abs` and `Abs2` real, as they were before that change.
Fixes #3379 .
=> Fix complex math abs and abs2 issues

docs/source/usage/workflows/probeParticles.rst
It did not match to implementation, while the exact names are required by probe pusher
=> Fix the name of probe fieldE and fieldB attribute in docs

include/picongpu/CMakeLists.txt, include/picongpu/plugins/openPMD/openPMDWriter.hpp
See [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3382#issuecomment-708935904) for a reasoning.
=> Deactivate support for writing to ADIOS1 via the openPMD plugin

include/pmacc/cuplaHelper/ValidateCall.hpp
Now in this mode it catches exceptions that cupla + alpaka can throw, prints kernel information and re-throws.
This change should hopefully help debugging crashes like #3381 by providing proper kernel name and file + line details.
=> Improve output of kernel errors in PMacc with PMACC_BLOCKING_KERNEL=ON

etc/picongpu/bash/mpiexec.tpl
fix missing `"` introduced with #3327
fix #3388 (https://github.com/ComputationalRadiationPhysics/picongpu/issues/3388#issuecomment-714744204)
=> fix mpiexec.tpl

include/picongpu/CMakeLists.txt
The openPMD plugin has always required features from that version (configuring backends via JSON), but CMake still lists the older version since 0.12.0 hadn't been released yet at the time of merging the openPMD plugin. 
(The reason why version 0.11.0 on Hemera was apparently able to be used for the plugin was that that module was not actually taken from a release, but from the dev-branch of the openPMD API)
=> Update required openPMD version to 0.12.0

etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
This pull request solves the issue #3409. The IT department separated the adios modules to an adios and and an adios2 base module. Both adios(1) and adios2 can thus be loaded in parallel.
=> add both adios and adios2 module on hemera

include/picongpu/plugins/openPMD/openPMDWriter.hpp
When I wrote the openPMD plugin, this method was not yet available, so the only way to guarantee the release of filehandles was to intermittently close and re-open the `openPMD::Series`. No longer necessary.
=> Use Iteration::close() in openPMD plugin

include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.hpp, include/picongpu/particles/ionization/byField/IonizationCurrent/JIonizationCalc.hpp
There was an issue with the ionization current where there was a division by zero. When the electric field was zero (such as before a laser pulse), the ionization current was still called with ionization energy being zero. I fixed with an if-else-statement as you can see in the IonizationCurrent.hpp. The ionization current is now working (tested).
=> Fix Ionization Current

include/picongpu/particles/ParticlesInit.kernel, include/picongpu/particles/densityProfiles/IProfile.hpp
This was tiggered by looking at this code while thinking of #3391. This PR does not solve it, merely improves documentation so that it's more clear what are the requirements to density profiles and so what things can and cannot be changed earily. I will provide a follow-up PR shortly to directly address #3391.
=> Improve clarity of comments concerning density calculation and profile interface

include/picongpu/particles/densityProfiles/FreeFormulaImpl.hpp
Motivation is described in #3391, and user functors are already required to be evaluatable at any point. Thus, the change should merely improve accuracy and potentially avoid some rounding issues, without breaking anything.
This is technically independent from changes in #3414 .
=> Modify FreeFormulaImpl density profile to evalute a functor in centers of cells

include/picongpu/particles/manipulators/unary/Temperature.def, include/picongpu/particles/manipulators/unary/Temperature.hpp
During investigation of #3377 , for a brief moment I thought that the temperature was applied incorrectly. It turned out to be not the case, just some comments were not full. This PR clarifies it, specifies this is only valid for the non-relativistic case and makes it more obvious the used random numbers are normally distributed.
=> Clarify comments for generating momentums based on temperature

include/picongpu/CMakeLists.txt, include/picongpu/fields/FieldJ.tpp, include/pmacc/nvidia/memory/MemoryInfo.hpp
Required changes to support HIP.
Note: HIP can currently not enabled via `pic-build`, this will be
allowed when all requirements (alpaka, cupla and mallocMC) support the latest HIP version.
- update few defines to support HIP
- add CMake flag `PIC_COMPUTE_CURRENT_THREAD_LIMITER` to work around a compiler bug in HIP-clang
=> changes to support HIP

share/picongpu/tests/compileParticlePusher/README.rst, share/picongpu/tests/compileParticlePusher/cmakeFlags, share/picongpu/tests/compileParticlePusher/include/picongpu/param/density.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/dimension.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/fileOutput.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/particle.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/precision.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesDefinition.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesInitialization.param
Some pushers were not enabled in any example, and so were not compile-time tested.
=> Add a new compile-time test suite to test all particle pushers

include/picongpu/versionFormat.cpp
The `openPMD API` has a `std::string getVersion()` since `0.12.0`, so we don't need to construct the version string manually any longer.
=> Use openPMD::getVersion() function

README.md
Replace travis status badges with gitlab CI pipeline status.
The master branch badge must be changed before the next release.
=> gitlab pipeline badges

docs/COMMIT.md, docs/source/dev/styleguide.rst
Clang format was not interpreting all file extensions used as C++ files.
This PR updates the clang format section and add the required commands
to set file extension for `git clang-format`
@BeyondEspresso This solves the issue you had with the code formatting.
=> fix documentation for `git clang-format`

include/pmacc/random/methods/XorMin.hpp
fix bug introduced with # #3356
The HIP state `hiprandStateXORWOW_t` is not giving access to the underlaying protected *rocrand* state.
=> HIP: fix RNG method XorMin

bin/pic-configure
Update `pic-build` to support `-b hip`.
#3455 is required to compile the HIP backend succesfully.
=> expose HIP backend

bin/pic-compile
The error code handling differ for parallel and non parallel builds.
- unifying the error handling
=> fix pic-compile

INSTALL.rst, include/pmacc/PMaccConfig.cmake
With #3454 we are now supporting CUDA 9.2 - 11.1.
=> Update supported CUDA versions

share/ci/generate_reduced_matrix.sh, share/ci/pr_has_label.sh
CI is checking the pull request labels and is skipping compile/runtime tests if the label `CI:no-compile` is pinned.
Currently, our CI is only performing actions when the code is updated by a push/force push.
Therefore the label should be set before the PR is opened or a force push to update the PR is required after the label is set.
By adding the label and later removing it is easy to pass the CI without any compile tests. This can be used to sneak broken code into the mainline. Labels can only be set by maintainers and I assume they will not abuse the flag to bypass the CI.
The flag should be used for documentation updates where compile tests are useless.
**Note:** My original idea was to parse the PR description for actions e.g. `CI:no-compile, CI:reduced-tests, …
=> CI: skip compile

include/picongpu/plugins/output/GatherSlice.hpp, include/picongpu/plugins/output/header/MessageHeader.hpp, include/pmacc/dimensions/DataSpace.hpp, include/pmacc/eventSystem/events/EventTask.hpp, include/pmacc/mappings/simulation/Selection.hpp, include/pmacc/mappings/simulation/SubGrid.hpp, include/pmacc/math/complex/Complex.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/memory/buffers/DeviceBufferIntern.hpp, include/pmacc/memory/buffers/HostBufferIntern.hpp
With gcc 9.3 I saw we got many warnings about deprecated behaviors.
The warning will be fixed by adding explicit `constexpr` copy constructors and assignment constructors.
The second type of warning was coming from *memset* usage which can be removed by casting the pointer given to *memset* to `void*`
e.g.
```
warning: implicitly-declared ‘constexpr pmacc::EventTask::EventTask(const pmacc::EventTask&)’ 
is deprecated [-Wdeprecated-copy]
```
=> fix deprecation warnings

include/picongpu/_defaultParam.loader, include/picongpu/param/memory.param, include/picongpu/param/speciesAttributes.param, include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.tpp, share/picongpu/examples/FoilLCT/include/picongpu/param/memory.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/memory.param, share/picongpu/examples/ThermalTest/include/picongpu/param/memory.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/memory.param
Add support to scale the particle exchange size at runtime automatically based on the local domain size and a reference size.
This feature is required for the upcoming SPEC benchmark example.
This feature allows that we can also fine-tune the required memory for particle exchanges depending on the example. Currently, we need to configure the particle exchanges for the largest config file of an example.
- Add `REF_LOCAL_DOM_SIZE` and `DIR_SCALING_FACTOR` to exchange configurations. The new attributes are optional and therefore backward compatible. This means that old param files still work.
- change the param include order to support PIConGPU float types in `memory.param`
=> Scale particle exchange buf

share/ci/bash.profile, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_nvcc_cuda.yml
- switch to conatiner v1.1
- activate ISAAC 1.6.0-dev tests
- fix silently disabled openPMD tests
ISAAC code should now be fixed to be able to compile together with PIConGPU.
=> CI: latest container v1.1

bin/pic-configure
When enabling asynchronous CPU backends in alpaka/cupla PIConGPU will block one core per MPI rank to poll for the task (alpaka kernel,memcopy) state. This will block one core and also an asynchronous will oversubscribe the CPU which results mostly in bad performance.
By switching to synchronous task execution, by setting the cmake flag `-DCUPLA_STREAM_ASYNC_ENABLE` we can get up to 30% more performance (example KHI).
MPI calls will still be asynchronous executed.
Since the year 2020 is ending and was definitely not the best year, compared to the years before, I would give this improvement to our CPU user-community. :christmas_tree:
=> disable async device streams for CPU backends

.gitlab-ci.yml, share/ci/generate_reduced_matrix.sh, share/ci/run_picongpu_tests.sh, share/picongpu/benchmarks/SPEC/etc/picongpu/1.cfg, share/picongpu/benchmarks/SPEC/include/picongpu/param/density.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/fileOutput.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/particle.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesDefinition.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesInitialization.param
- Add benchmark case used in SPEC benchmarks.
- Check `benchmarks` examples with the CI
Note: In the original SPEC benchmark PIConGPU is manipulated that the random number generator will not be initialized. This means that the overall runtime between a benchmark with the SPEC benchmark suite and native PIConGPU will differ.
@jkelling The param files for the SPEC example are differing slightly from the example we currently use in SPEC. The difference is in the name of the second species. Instead of the name the species `i` for ions the name is now correct and called `p` for positions. The runtime parameter to create the energy files are therefore different.
```
--p_macroParticlesCount.period 100        
--e_macroParticlesCount.period 100         
--fields_energy.period 100 …
```
=> add SPEC benchmark example

include/mpiInfo/mpiInfo.cpp
The previously used return false rightfully triggered clang `warning: bool literal returned from 'main' [-Wmain]`. Change it to 0.
=> Fix return value of main() in mpiInfo

docs/source/dev/picongpu.rst, include/picongpu/param/components.param, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/unitless/starter.unitless, share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
This is not a big or important change at all. Just to me personally `MySimulation` always felt like a name associated with throwaway code like used in small code snippets to test smth e.g. in online compilers.
=> Rename picongpu::MySimulation to picongpu::Simulation

USAGE.rst
The goal is to help explaining that regardless of how PIConGPU was installed, it is used uniformly.
This is what some recent users via spack, and some developers as well, seem to have missed from the docs.
Not sure if this addition is enough, but it's at least something.
=> Extend reminder to load environment in the docs with instructions for spack

include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel
The previously used scheme mistakenly assumed that updating by dt/2 twice is equivalent to updating by dt.
It resulted in worse than expected absorption.
The new scheme properly performs update of B for convolutional components.
The changes are fully contained inside the YeePML field solver and so the rest of the code is not affected.
Added comments of why do we have to update B by dt/2 this way.
Fixes #3418. Attaching a plot with new absorption after the fix for the test problem discussed there and in #3417: Taflove 3rd ed., section 7.11.1. edit: CPML uses parameter alpha = 0.2 as in the Taflove book for this test problem. By UPML, same as in Taflove, I mean CPML with alpha = 0. Theoretically it is supposed to be worse or about same as CPML. It would be more accurate to actually call it …
=> Fix the scheme of updating convolutional B in PML by half time step

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
The openPMD 0.11.0 module used for the defq example setup leads to a compile error. 
Most likely version 0.12.0 is required. @psychocoderHPC and @sbastrakov do we check the openPMD version in the CMake file?
The error is:
```
In file included from /.../picongpu/include/picongpu/plugins/PluginController.hpp:50:0,
from /.../picongpu/include/picongpu/unitless/starter.unitless:23,
from /.../picongpu/include/picongpu/simulation_defines.hpp:53,
from /.../picongpu/include/picongpu/main.cpp:27:
/.../picongpu/include/picongpu/plugins/openPMD/openPMDWriter.hpp: In member function ‘void picongpu::openPMD::openPMDWriter::write(picongpu::openPMD::ThreadParams*, std::__cxx11::string)’:
/.../picongpu/include/picongpu/plugins/openPMD/openPMDWriter.hpp:1192:84:error: ‘using mapped_type = std::map<long …
```
=> remove openPMD 0.11.0 module for defq

include/pmacc/random/distributions/normal/Normal_double.hpp, include/pmacc/random/distributions/normal/Normal_float.hpp
Using RNG in PIConGPU on AMD devices results into a compile error.
Add missing condition to use `XorMin` together with HIP.
=> fix: HIP random number generator compile

include/pmacc/nvidia/memory/MemoryInfo.hpp
A nonexisting define was used to select if a HIP GPU is used.
The result of this BUG is that on AMD devices only half GPU main memory was used which results in crashes if the problem size of the simulation is too large.
=> HIP: fix memory allocation

INSTALL.rst, docs/source/usage/plugins/openPMD.rst, include/picongpu/CMakeLists.txt, include/picongpu/plugins/openPMD/NDScalars.hpp, include/picongpu/plugins/openPMD/WriteMeta.hpp, include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDVersion.def, include/picongpu/plugins/openPMD/openPMDWriter.def, include/picongpu/plugins/openPMD/openPMDWriter.hpp
[openPMD API 0.13.0 beta](https://openpmd-api.readthedocs.io/en/0.13.0/) has been released yesterday, including support for streaming IO. This PR applies this to the openPMD plugin.
Also adds some timing output which I found to be useful.
TODO
EDIT: Not strictly necessary since we will further support openPMD API 0.12.0
EDIT: Not strictly necessary since we will further support openPMD API 0.12.0
=> Use Streaming API in openPMD plugin

include/pmacc/assert.hpp
Since cuda supports assertion checks ((https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#assertion)), for compute compatibility 2.x and higher, I thought it would be nice to have something similar to `PMACC_ASSERT` that works on device side. So this PR would introduce `PMACC_DEVICE_ASSERT` that basicaly just renames the standard `assert` macro from the `assert.h`. I just added a little compatibility check for older cuda devices. According to the [HIP documentation](https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html#assert) asserts are supported in the latest release but maybe we need to check the version  for HIP as well, no idea :sweat_smile: . I tried this out with a dummy assert in `ParticlesInit.kernel` with the `defq_picongpu.profile` and …
=> add device side assert macro

include/picongpu/plugins/openPMD/WriteSpecies.hpp
fix warning:
```
include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on
'picongpu::openPMD::Strategy<pmacc::Frame<picongpu::OperatorCreateVectorBox,
...
```
Fixed by using a virtual contructor.
=> fix warning

include/picongpu/particles/densityProfiles/FromHDF5Impl.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/LoadSpecies.hpp, include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp, include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
The returned object from `getGlobalDomain()` and `getLocalDomain()` is accessed inside of PIConGPU over a references which is pointing on a temporary object.
It looks like it is a copy past issue we have since years inside our codebase :-(
=> fix access to temporary variable

include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/WriteSpecies.hpp, include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/output/WriteSpeciesCommon.hpp, include/picongpu/simulation/control/Simulation.hpp, include/pmacc/particles/memory/buffers/MallocMCBuffer.hpp, include/pmacc/particles/memory/buffers/MallocMCBuffer.tpp
Until now it was not possible to dump data with ADIOS or OpenPMD-api if HIP was enabled.
This PR provides the required fixed to enable IO support.
note: Missing abstractions in cupla require the usage of native API calls to HIP, similar to what we do with CUDA.
I restructure the `MallocMCBuffer` to minimize the usage of `#ifdef` precompiled guards in the code.
=> enable IO possibility for HIP

include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
The old implementation assumed that the MPI rank can be used to find the
particle information in the OpenPMD file.
This is wrong because there is no guarantee that the rank is the same.
Fix: use openPMD particle patch information to find particles that correspond
to the local domain.
This patch is backward compatible, which means you can restart with data written before this patch.
Note: It would also be possible to use the linearized position of the simulation domain within the simulation volume during the write and load of particle data but the provided fix is already the base to implement loading from a simulation that was running with a different number of devices.
I tested the patch with a 2D and 3D LWFA.
=> fix restart with openPMD

src/tools/bin/plot_chargeConservation_overTime.py
- use openPMD-api
- add command line parameter `--start` and `--last` to define used iterations
- the usage changed a little bit: instead of pass folder you give openPMD file names in
```
plot_chargeConservation_overTime.py  --start 1200 ./simData_%T.bp ./test2/simData_%T.bp
```
I disabled CI compile time checks for this PR, code style is still checked e.g. flake8 and pep8.
=> openPMD support for `plot_chargeConservation_overTime.py`

src/tools/bin/plot_chargeConservation.py
- add new option `-t` to set the time step which should be loaded
- support openPMD file pattern for series
- fix option names two dash `--` are for long options
- use openPMD-api instead of native hdf5
CI test for compiling are disabled because python is not checked.
=> openPMD support for `plot_chargeConservation.py`

include/pmacc/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp
Now it matches the rest of the code. Previously used `DEVICEONLY` is for variables, probably is a leftover.
Found accidentally, while looking at another thing.
=> Change SharedMemAllocator function qualifiers from DEVICEONLY to DINLINE

docs/source/dev/styleguide.rst
The current documentation does not mention that clangFormat is not included with git, but must be installed/loaded in addition.
In addition I added a short example workflow based on my short introduction by S.Bastrakov.
=> improved documentation of clang-format usage

include/pmacc/assert.hpp
When using pmacc assert macros in host/device methods compile can fail.
This PR is adding guards to avoid macro evaluation of device assert macros on host and vice versa.
This will avoid that https://github.com/ComputationalRadiationPhysics/picongpu/blob/be3986413fcdbae7cbff8c6558604c013526e9ac/include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/Weights.hpp#L66-L70 will break compiling with hipcc.
=> guard ASSERT macros

include/pmacc/simulationControl/SimulationHelper.hpp
valgrind reported a conditional jump based on an uninitialized variable.
=> fix jump on uninitialized variable

include/pmacc/math/ConstVector.hpp, include/pmacc/particles/IdProvider.hpp, include/pmacc/traits/GetNumWorkers.hpp
This PR adds preliminary support for picongpu to run on Alpaka's [OpenMP 5 target offload](https://github.com/alpaka-group/alpaka/pull/1126) and (experimental) [OpenACC](https://github.com/alpaka-group/alpaka/pull/1127) backends.
* add specializations of `pmacc::GetNumWorkers` for OpenMP5 and OpenACC
* declare global variable `pmacc::idDetail::nextId`as OpenMP/OpenACC device variable
* explicitly map `pmacc::ConstVector` types to target device (it is debatable whether this is a workaround neccessitated by lacking compiler support or required by the OpenMP/OpenACC standards)
[SPEC benchmark example](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/benchmarks/SPEC):
* OpenMP target: compiles an runs correctly using clang 11 with x86_64 as target device
* …
=> Add support for Alpaka OpenMP target/OpenACC

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
Previously, there was system git avaialble without loading the module, but it was just removed following support ticket submitted by @BrianMarre . And rightfully so, as that standard version was really outdated.
So update the profiles to load the `git` module and so keep the workflow described in the docs (which includes cloning repository) intact.
=> Update Hemera profiles to load the git module

docs/TBG_macros.cfg, docs/source/usage/plugins/checkpoint.rst
This was noticed during a mattermost discussion on checkpoints.
=> Fix some outdated docs regarding output and checkpoint backends

include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/currentDeposition/Strategy.def, include/picongpu/param/species.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/tests/XrayScattering/include/picongpu/param/species.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
Allow the user to tune the number of worker/threads uses to compute the current.
The worker multiplier is now part of the strategy used to configure the compute current task and kernel behavior.
The default for CUDA devices is changed from `2` to `1` with this PR.
This will result in better performance for all devices with compute architecture 6.0+. 
On Kepler the performance will be slightly reduced.
note: It is not possible, without increasing the compile-time, to switch automatically based on the GPU used between the old and the new default number for the multiplier.
- add new compute current strategies
- update doxygen documentation
This PR will **not** break existing param files. The implementation is backward compatible.
=> expose compute current worker multiplier 

include/picongpu/plugins/IsaacPlugin.hpp
Adds compatibility to isaac glm PR with changed interface and isaac types
[https://github.com/ComputationalRadiationPhysics/isaac/pull/130](url)
[psychocoder edited] CI do not need to be updated, this PR is compatible with ISAAC 1.5.2
=> Adds compatibility to isaac glm PR

INSTALL.rst
=> Add installation instructions for ADIOS2 and HDF5 backends of openPMD API

include/picongpu/param/pml.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/pml.param
That was probably just forgotten when this solver was added. I made a fix, since this file is included to readthedocs.
=> Add missing artibrary order solver to the list of PML-enabled field solvers

include/picongpu/fields/FieldJ.hpp, include/picongpu/fields/FieldJ.kernel, include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/currentInterpolation/Binomial/Binomial.def, include/picongpu/fields/currentInterpolation/Binomial/Binomial.hpp, include/picongpu/fields/currentInterpolation/CurrentInterpolation.hpp, include/picongpu/fields/currentInterpolation/None/None.def, include/picongpu/plugins/adios/WriteMeta.hpp, include/picongpu/plugins/openPMD/WriteMeta.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
As we discussed on the VC, I split the transition into run-time current interpolation parameters into two PRs.
This PR only does the internal stuff and does *not* change the user interface of PIConGPU.
The only difference is that custom current deposition functors declared in `.param` files are no longer allowed (but I am not aware of such a use case at all).
It made internal changes necessary for a full transition of this parameter towards run-time, to be done in a following PR.
To avoid confusion, I renamed names and template parameter names of old instances of current interpolation into functors (which they were already and remain that way). Also due to a name conflict with .param file naming the new class is called `CurrentInterpolationInfo`, to be renamed into `CurrentInterpolation` …
=> Switch internal handling of current deposition from compile-time to run-time

include/picongpu/simulation_types.hpp
Was probably removed previously with another change, and left out.
=> Remove unused enum picongpu::FieldType

docs/TBG_macros.cfg, include/picongpu/fields/background/cellwiseOperation.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/simulation/stage/CurrentBackground.hpp, include/picongpu/simulation/stage/FieldBackground.hpp, include/pmacc/memory/buffers/DeviceBufferIntern.hpp
This is a, so far draft, implementation of another mode of field background operation #3521. The switch between old and new mode is done as a command-line flag `--fieldBackground.duplicateFields`, by default not set which corresponds to old behaviour (since it does not increase memory footprint then).
Implementation is more or less complete, but not properly tested yet. I will proceed with that tomorrow. I can do a technical setup and test that it didn't break the old mode, and the new one works the same, also that it operates fine with checkpoints.
For a real, physically meaningful test, however we do not have any standard example relying on field background. Perhaps to measure performance change and maybe effects on accuracy (although that should be a really long simulation than) you …
=> Add option to duplicate field storage for FieldBackground aka superPusher

include/picongpu/fields/EMFieldBase.hpp, include/picongpu/fields/EMFieldBase.tpp, include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.tpp, include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/FieldTmp.tpp, include/picongpu/particles/Particles.tpp, include/picongpu/simulation_types.hpp, include/pmacc/memory/buffers/GridBuffer.hpp, include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp, include/pmacc/traits/GetUniqueTypeId.hpp
The old scheme was causing some tags to be outside of the valid range #982.
Apply fixes and modernization of the tag generation scheme.
Document the requirements of the new scheme.
The remaining pieces of `picongpu::CommunicationTag` are no longer used for communication.
But they are left to keep the field solver traits, to be fixed in a following PR.
Resolves #982.
@jprotze thanks for reporting the issue. Hopefully this PR solves it, but I haven't tested it fully yet, will continue tomorrow.
=> Fix and modernize the generation scheme for MPI communication tags

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
Upgrade to newer versions of modules:
* cuda/11.2
* openmpi/4.0.4-cuda112
* hdf5-parallel/1.12.0-cuda112
* libfabric/1.11.1-co79
* adios2/2.7.1-cuda112
* openpmd/0.13.2-cuda112-adios271
Remove module
* libsplash/1.7.0-cuda102
since it does not compile against hdf5 anymore and we are in the process of abandoning it, see #3357.
Upgrade to the newer versions of CUDA and openMPI came with a requested upgrade of openPMD and ADIOS2 in order to use blosc compression, see #3506 and #3530.
I added the `CI:no-compile` label as I think the CI won't make use of the profile anyway, correct?
=> Update hemera-hzdr profiles

bin/pic-configure, etc/picongpu/submitAction.sh
This introduces a new file `cmakeFlagsSetup` generated by `pic-configure` if there's `cmakeFlags` in the input directory. It stores the setup number used from `cmakeFlags`. `cmakeFlagsSetup` is copied to `<output directory>/input` for reference.
=> Save, for reference, the used cmakeFlags setup.

include/picongpu/fields/EMFieldBase.hpp, include/picongpu/fields/EMFieldBase.tpp, include/picongpu/fields/FieldB.hpp, include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.hpp, include/picongpu/fields/FieldE.tpp, include/picongpu/fields/FieldTmp.tpp, include/picongpu/fields/MaxwellSolver/None/None.def, include/picongpu/fields/MaxwellSolver/None/None.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.def, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/simulation_types.hpp, include/picongpu/traits/GetMargin.hpp
This was noticed during work on #3558. But since that one was a bugfix and to be backported, while the removal required some refactoring as well I separated it into this PR. Said removal required modifying and modernizing several places. I didn't split this modernizing part into several commits or PRs as I didn't initially estimate how many changes were required. There are two more cleanup things I will do as follow-ups, will mark it in the code.
=> Remove enum picongpu::CommunicationTag

include/picongpu/fields/FieldTmp.tpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
It gives margins for the solver as a whole, so max of its E and B update margins.
This is the final part of refactoring of this part, started with #3561 and then #3564.
=> Add a version of GetTrait taking only field solver type as a parameter

include/picongpu/particles/Particles.tpp
This PR fixes the scaling of the memory size allocated for particle exchange with rank-local  grid size.
The idea in the original code is to keep the size of of the particle exchange buffers proportional to the volume of a surface slices of the local domain with fixed thickness (times `userScalingFactor`). This is implemented correctly for domain faces in 3D, which scale proportional to the size of the in-plane domain sizes. The sizes for edges an corners are not computed correctly making the memory for corner, and to a lesser degree edge, exchanges explode for large local domains.
The correct generalization of this idea is to scale buffer sizes proportional to the domain extents *normal* to the exchange direction. While for a face exchange, the in-plane extents are normal to the exchange …
=> Fix Particles<>::exchangeMemorySize

include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp
GPU-only code was executed also when building non-GPU Alpaka backends.
Fix #3576
=> Fix openPMD plugin for non-GPU builds

include/picongpu/fields/FieldTmp.hpp, include/picongpu/fields/FieldTmp.kernel, include/picongpu/fields/FieldTmp.tpp, include/picongpu/fields/Fields.def, include/picongpu/param/fileOutput.param, include/picongpu/param/isaac.param, include/picongpu/particles/filter/RelativeGlobalDomainPosition.def, include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp, include/picongpu/particles/manipulators/binary/DensityWeighting.def, include/picongpu/particles/manipulators/binary/ProtonTimesWeighting.def, include/picongpu/particles/manipulators/binary/UnboundElectronsTimesWeighting.def, include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def, include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp, include/picongpu/particles/particleToGrid/FilteredDerivedAttribute.hpp, include/picongpu/plugins/IsaacPlugin.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, share/picongpu/examples/LaserWakefield/include/picongpu/param/particle.param
This PR introduces derived fields of filtered species. See #3554.  `CreateEligible_t` used in `fileOutput.param` has now an additional template argument that defaults to `filter::All`. The filter is optional and by default `All` in all other relevant structs and methods (like `FieldTmp::computeValue`) so it shouldn't brake any code that is not using filters.  
I did a quick test with the Kelvin-Helmholtz example and it compiles and works as excepted with the `openPMD` plugin  when I use one of the filters from `particleFilter.param` in `fileOutput.param`.  Maybe someone can verify that it works with `isaac` too?  I've never used it before.
Also I did move  `SpeciesEligibleForSolver` in the `RelativeGlobalDomainPosition` to the `.def` file so I don't have to include the `.hpp` file too …
=> introduce filtered particleToGrid algorithm

INSTALL.rst
@PrometheusPi found that we missed updating our documentation with the latest supported boost version.
https://github.com/ComputationalRadiationPhysics/picongpu/pull/3341#discussion_r519823002
The CI is already testing boot 1.74.0: https://github.com/ComputationalRadiationPhysics/picongpu/blob/a9306d2eb2dfd7c93503dd48a507fda91b35c83c/share/ci/n_wise_generator.py#L191
=> documentation: add support for boost 1.74.0

include/picongpu/unitless/collision.unitless, share/picongpu/tests/CollisionsThermalisation/cmakeFlags, share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/collision.param
Fix #3584 It is not possible to change the precision for collision.
CI: Test compilation with 32bit collision precision.
=> fix collision compile error

include/picongpu/CMakeLists.txt, include/picongpu/plugins/IsaacPlugin.hpp, share/ci/bash.profile, share/ci/compiler_clang.yml, share/ci/compiler_gcc.yml, share/ci/compiler_nvcc_cuda.yml, share/ci/install/isaac.sh
Updates IsaacPlugin.hpp with the new ISAAC naming standard used in PIConGPU coming with the rework PR ComputationalRadiationPhysics/isaac#132
- reaktivate CI tests for ISAAC
- keep clang-cuda tests disabled due to compile issues
=> Compatibility to new unified ISAAC naming scheme

include/picongpu/plugins/PluginController.hpp
I believe it was forgotten to be updated in #3570.
Resolves #3588.
=> Fix wrong ifdef guard in enabling the macroparticle counter plugin

include/picongpu/CMakeLists.txt, share/ci/run_picongpu_tests.sh, share/picongpu/examples/WarmCopper/cmakeFlags
Allow to set cmake option `PIC_USE_<dependency>=ON` to enforce the usage
of a dependency.
- fix #3473: use new option to avoid that CI is not compiling without optional dependencies.
- re-enable ISAAC support for the example `WarmCopper`. It was disabled in the file `cmakeFlags`, I assume to save compile time in our old CI.
This PR is inspired by openMPD-api but the implementation is different.
At the end of the CMake output a summary for optional dependencies is printed.
This allows the user to check which dependencies will be used without reading the complicated verbose output of CMake.
```
...
-- Implicit conversions are disabled
-- Found PNGwriter: /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-9.3.0/pngwriter-develop-tb5tuy4rlryfy2zsfybpya6ydfyjnogv/lib/cmake/PNGwriter
-- …
```
=> CMake: add option to enforce dependencies

include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/tests/XrayScattering/include/picongpu/param/species.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param
Use EmZ as the default current solver.
We discussed in the PIConGPU developer meeting to set EmZ as the default current solver.
There are no known issues with EmZ and the user should not realize any difference except that the simulation should run faster.
=> set current solver EmZ as default

share/picongpu/benchmarks/SPEC/cmakeFlags, share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/precision.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param
Add two additional configurations to compile for
- 32bit and TSC particle shape
- 64bit and TSC particle shape
The particle exchange buffer memory is increased from 6MiB to 8MiB to avoid that we need to send particles within one simulation step twice.
The default case will not compile for 64bit because of the limited shared memory.
At all the selection should help in the CAAR project to validate the performance of 32bit and 64bit runs.
=> SPEC bechmark: add new configurations

include/picongpu/particles/debyeLength/Estimate.hpp
With #3582 the `DataConnector` method `releaseData()` was removed.
Bug was introduced with #3446
=> fix compile: debye length

docs/source/usage/param/core.rst, include/picongpu/_defaultParam.loader, include/picongpu/param/iterationStart.param, include/picongpu/param/speciesInitialization.param, include/picongpu/particles/InitFunctors.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/simulation/stage/IterationStart.hpp, share/picongpu/tests/compileIterationStart/README.rst, share/picongpu/tests/compileIterationStart/include/picongpu/param/iterationStart.param, share/picongpu/tests/compileIterationStart/include/picongpu/param/particle.param, share/picongpu/tests/compileIterationStart/include/picongpu/param/speciesDefinition.param, share/picongpu/tests/compileIterationStart/include/picongpu/param/speciesInitialization.param
Allow specifying a sequence of functors to be called at start of each time step. So this is similar to `InitPipeline`, but called repeatedly and not once. It is set in a new input file `iterationStart.param`. The pipeline is empty by default. The way of setting and requirements for functors are exactly the same as in `InitPipeline`, updated comments there as well. (Also note that `InitPipeline` could actually be whatever functors and doesn't have to deal with particles, even though the namespace and comments suggest it)
Note that if we didn't have awkward include order stuff, the whole PIC loop could have been put there externally in theory. Actually, almost all simulation stages already have the same interface as functors in the pipeline. So in far (well, or depends on prioritization) …
=> Add iteration start pipeline

include/pmacc/simulationControl/SimulationHelper.hpp
Print our screen statistics for the init, calculation, and full simulation time including milliseconds.
```
initialization time: 37sec 324msec = 37.324 sec
...
calculation  simulation time: 11sec 929msec = 11.929 sec
full simulation time: 49sec 515msec = 49.515 sec
```
This feature was a request from @frobnitzem and is a CAAR requirement.
=> screen output: print milliseconds

etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
updated the current profile for hemera/defq to use the new non cuda modules to allow running picongpu on the cpu only nodes
=> Updated defq profile for hemera/defq

include/picongpu/particles/InitFunctors.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/simulation/stage/IterationStart.hpp, include/pmacc/functor/Call.hpp, include/pmacc/functor/Interface.hpp
Also move the file accordingly. The change was suggested [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3607#discussion_r619392750).
The second commit is unrelated refactoring, that I noticed along the way. I assume that is some old workaround, as I never heard of this `std::is_same<void, void>` issue.
=> Rename picongpu::particles::CallFunctor to pmacc::functor::Call 

etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_restart.tpl
This pull request adds the option to use the respective low partition instead of the regular (gpu) partition for `k20`, `k80`, `gpu` and `fwkt_v100`. 
**check:**
=> Add option for hemera low (gpu) partitions

include/picongpu/fields/LaserPhysics.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/absorber/Absorber.hpp, include/picongpu/fields/absorber/Absorber.tpp, include/picongpu/fields/absorber/ExponentialDamping.hpp, include/picongpu/fields/absorber/Pml.hpp, include/picongpu/plugins/adios/WriteMeta.hpp, include/picongpu/plugins/common/openPMDWriteMeta.hpp, include/picongpu/simulation/control/DomainAdjuster.hpp
Move more responsibility into `fields::absorber::Absorber`.
Now more things are handled run-time.
This is to prepare the following transition to run-time absorber setting and unification of PML and non-PML field solvers.
User interface is unchanged yet.
=> Refactor common field absorber implementation

docs/source/usage/param/core.rst, include/picongpu/_defaultParam.loader, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/incidentField/Profiles.def, include/picongpu/fields/incidentField/Profiles.hpp, include/picongpu/fields/incidentField/Solver.hpp, include/picongpu/fields/incidentField/Solver.kernel, include/picongpu/fields/incidentField/Traits.hpp, include/picongpu/param/incidentField.param, share/picongpu/examples/IncidentField/cmakeFlags, share/picongpu/examples/IncidentField/etc/picongpu/1.cfg, share/picongpu/examples/IncidentField/etc/picongpu/4.cfg, share/picongpu/examples/IncidentField/include/picongpu/param/dimension.param, share/picongpu/examples/IncidentField/include/picongpu/param/fieldSolver.param, share/picongpu/examples/IncidentField/include/picongpu/param/grid.param, share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param, share/picongpu/examples/IncidentField/include/picongpu/param/pml.param, share/picongpu/examples/IncidentField/include/picongpu/param/png.param
This PR (draft so far) adds a new way of generating incoming lasers. It uses the total field / scatter field formulation and takes user-set values for values of E and B. Those values are provided as a pair of functors in a new `incidentField.param` file.
Implementation is based on the review paper M. Potter, J.-P. Berenger. A Review of the Total Field/Scattered Field Technique for the FDTD Method. FERMAT, Volume 19, Article 1, 2017. And the Taflove book explaining more or less same with more details.
Differences vs. the standard PIConGPU laser:
- Requires explicit expressions for E and B, not just E.
- Uses soft source, not hard source. When applicable, should be easier to use: a user just provides actual field values, also no need to know the workarounds of the laser implementation
- Not …
=> Incident field generation (aka laser antenna)

include/picongpu/CMakeLists.txt
Bug was introduced with #3586.
=> CMake: fix lib splash selection

include/picongpu/plugins/openPMD/WriteSpecies.hpp
fix #3624
The number of local particles prepared was incorrect and additionally the assert to validate that the correct number of particles is processed was wrong too.
Use `PMACC_VERIFY` instead of `PMACC_ASSERT` to verify the number of processed particles even if we not compile with debug enabled.
=> fix broken OpenPMD IO plugin

docs/TBG_macros.cfg, docs/source/expert/deviceOversubscription.rst, docs/source/index.rst, include/picongpu/simulation/control/Simulation.hpp, include/pmacc/device/MemoryInfo.hpp
- Add option `--numRanksPerDevice` and `-r` to allow multiple MPI ranks to
use a device together.
- Documentation:
- add section `EXPERT`
- describe the usage of the new option
- change interface of `isSharedMemoryPool()`
=> device oversubscription

include/pmacc/static_assert.hpp
fix
```
include/pmacc/../pmacc/math/vector/Vector.hpp(181): error: variable in constexpr function does not have automatic storage duration
PMACC_CASSERT_MSG(math_Vector__constructor_is_only_allowed_for_DIM3, dim == 3&& sizeof(Storage));
```
@jkelling Said to me a long time ago that there is an issue with ICC. I forgot about it and watched the issue during my tests again :-(
=> fix compile with icc

include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
That was a slight mistake when this feature was introduced. The bracket change is unrelated, they were just redundant there.
=> Fix wrong helpline for current interpolation kinds

etc/picongpu/spock-ornl/caar_picongpu.profile.example
The ROCm module has been fixed.
Now we can use it and do not need to use the system installation
anymore.
(Tested with LWFA example which had problems with the old module)
=> Update spock-ornl profile

etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_restart.tpl
With #3633 got broken. The signal forward script must be called with `source` and not via `$(...)`.
@ComputationalRadiationPhysics/picongpu-developers Everyone how used the dev branch on hemera from last week should update to the latest version as soon as this PR is merged.
=> fix hemera tpl files

include/pmacc/lockstep/Config.hpp, include/pmacc/lockstep/ForEach.hpp, include/pmacc/lockstep/Variable.hpp
Split the forEach compile-time loop into peel and reminder part.
This is slightly better for CPU compiler and is more human-readable compared to the original implementation.
Add two helper types to derive if a functor is callable with or without Idx as an argument. 
This was suggested by @sbastrakov in #3616.
=> refactor `lockstep::ForEach`

docs/source/install/instructions/spack.rst
Minor change of description for more clarity. Seperated the addition of the downloaded repo to the spack installation into a seperate step.
=> Update of spack installation guide

include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp, include/picongpu/fields/MaxwellSolver/CFLChecker.hpp, include/picongpu/fields/MaxwellSolver/Lehe/Lehe.def, include/picongpu/fields/MaxwellSolver/None/None.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
For a very long time, CFL checks were wrong for each solver but the standard `Yee`. This PR fixes it for all other solvers:
- `None`
- `Lehe` (thanks @psychocoderHPC for pointing it out recently)
- arbitrary order #3581
I also added a new functor to check those, to provide easier specialization, and fixed a typo in Lewy.
The basic check is what we rely on in current deposition: a particle can't move by more than one cell size in one time step. For `None` and `Lehe` that is enough, Yee and arbitrary-order FDTD pose more strict conditions in their specializations.
Note: it is probably possible to make the arbitrary-order check compile-time as well. However, the `Weights` class there claims to be constexpr, but making a `constexpr` object of it doesn't work. @steindev could you comment on …
=> Fix CFL conditions

share/ci/run_pmacc_tests.sh
We observed issues on the CI where it is not clear if the CI runner is not working correctly or if the issues are real.
To avoid blocking the development the PMcc runtime CI tests are disabled.
=> CI: disable PMacc runtime tests for HIP

include/pmacc/communication/CommunicatorMPI.hpp, include/pmacc/eventSystem/Manager.hpp, include/pmacc/eventSystem/Manager.tpp, include/pmacc/simulationControl/SimulationHelper.hpp
With #3633 we introduced signal handling.
@Anton-Le observed deadlocks when using signaling. 
The reason for the deadlocks was that PMacc used MPI collective blocking operations to handle signals, together with blocking operations in PIConGPU plugins or other simulation phases this can result in deadlocks.
This PR provided two interface extensions for PMacc to be able to handle signals correctly.
- add method `pmacc::Manager::waitFor(T_Functor&&)` to wait for a user given functor.
- extend interface with `pmacc::CommunucatorMPI::getMPISignalComm()` 
Additionally, the signal processing in `pmacc::SimulationHelper` is updated to avoid that the event system is blocked and signals are allowed to be handled even if MPI ranks of the simulation are in different time steps.
=> fix signal handling

include/pmacc/math/ConstVector.hpp
Because an instance of this consexpr variabe is required  at runtime, it needs to be explicitly mapped to be compliant OpenMP.
This is a fix for the OpenMP target support already present in `ConstVector`. It also includes the same mapping for OpenACC, which may be requires by the OpenACC standart at the moment.
=> pmacc::ConstVector: Add omp declare target around Name

etc/picongpu/spock-ornl/caar_picongpu.profile.example
openPMD-api module has been upgraded to 0.13.4. The old one is not available
anymore.
=> Update spock profile

include/picongpu/particles/debyeLength/Check.hpp, include/picongpu/particles/debyeLength/Estimate.kernel
In `Estimate.kernel`, if the temperature drops to zero (particles are initialized with zero momentum variance), floating point math makes the variances become small, but sometimes negative inaccurate output.
This patch adds a `max` in `Estimate.kernel` to keep the variances from becoming negative.
```diff
< PIConGPUVerbose PHYSICS(1) | 0 (0 %) supercells had local Debye length estimate not resolved by a single cell
< PIConGPUVerbose PHYSICS(1) | Estimated weighted average temperature -7.58771e-11 KeV and corresponding Debye length -nan m.
<    The grid has -nan cells per average Debye length
---
> PIConGPUVerbose PHYSICS(1) | 1536 (100 %) supercells had local Debye length estimate not resolved by a single cell
> PIConGPUVerbose PHYSICS(1) | Estimated weighted average temperature 0 keV and …
```
=> Ensure variances are >= 0

include/picongpu/fields/MaxwellSolver/CFLChecker.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
During the work on #3641 I didn't notice that at some point the check was no longer deferred for the classic Yee solver. This results in the check being done for al setups, which is incorrect. Add dependance on template parameters to make it deferred again.
[On another thing discussed on VC](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3641#issuecomment-862327513), for Lehe solver the default checks seems fine (and checking it lead to discovering this bug).
=> Make the CFL check deferred (again)

include/picongpu/particles/collision/detail/ListEntry.hpp
This doesn't solve the freezing issue that's happening on cuda devices but I noticed that we request memory via `deviceHeapHandle` for both cuda and hip but we free it only for cuda. This makes the two `#if` macros guarding `deviceHeapHandle` calls identical.
=> Free memory in collisions when using HIP

include/pmacc/eventSystem/events/kernelEvents.hpp
We were basically doing `typeid(typeid(kernelFucntor.name()).name()`. That's one `typeid().name()` too much. This is why `DEBUG_EVENTS` was printing `TaskKernel NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` for all slow kernel events.
=> Fix kernelName in kernelEvents.hpp

lib/python/picongpu/utils/memory_calculator.py
Due changes in species.param (#3431) the explanation of "shape order" needs to be adjusted.
=> Update documentation of memory calculator

etc/picongpu/spock-ornl/caar_picongpu.profile.example
Explicit compile for gfx908 only.
This will reduce the compile time because by default alpaka compiles for the HIP architecture 906 and 908.
=> spock-ornl: compile for MI100 architecture only

etc/picongpu/spock-ornl/caar_picongpu.profile.example
Fix warnings:
```
clang-12: warning: argument unused during compilation: '-L/opt/cray/pe/mpich/8.1.4/gtl/lib' [-Wunused-command-line-argument]
clang-12: warning: argument unused during compilation: '-L/opt/cray/pe/mpich/8.1.4/ofi/gnu/9.1/lib' [-Wunused-command-line-argument]
clang-12: warning: argument unused during compilation: '-L/opt/cray/pe/mpich/8.1.4/gtl/lib' [-Wunused-command-line-argument]
clang-12: warning: -lmpi: 'linker' input unused [-Wunused-command-line-argument]
clang-12: warning: -lmpi_gtl_hsa: 'linker' input unused [-Wunused-command-line-argument]
```
=> spock-ornl: fix compile warning

USAGE.rst
Not sure this is the most fitting place for it. But basically it tries to explain two points to potential new users:
- when is it required to recompile PIConGPU (after any change in `.param` files, but not in `.cfg` files)
- `.build/picongpu --help` is usedful for available command-line options
=> Extend the basic usage with beginner tips for making an own simulation

docs/source/usage/workflows/boundaryConditions.rst, include/picongpu/fields/absorber/Absorber.hpp, include/picongpu/fields/absorber/Absorber.tpp, include/picongpu/fields/absorber/none/None.hpp, include/picongpu/param/fieldAbsorber.param, include/picongpu/simulation/stage/FieldAbsorber.hpp, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldAbsorber.param, share/picongpu/examples/FoilLCT/include/picongpu/param/fieldAbsorber.param
To enable the smooth transition, this PR also adds a new `None` absorber type and implementation that does nothing. It is not chooseable by a user directly, but is set when all boundaries are periodic. This is done for the following reasons, all valid only for the all-periodic case:
- compatibility with older checkpoints (otherwise PML would have tried to load its fields, although zero-sized, and that would not work)
- efficiency reasons: as @psychocoderHPC told me earlier, even writing a zero-sized field may take time
- also to lower confusion if someone looks in checkpoint and sees the PML fields
With this change, the setups with absorbing boundaries, default absorber, and particles present in the absorbing area may behave somewhat differently in this area besides just absorption. The …
=> Make PML default field absorber

include/picongpu/plugins/openPMD/WriteSpecies.hpp
fix: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3389#discussion_r663311000
The extent for the OpenPMD attribute charge and mass requires the number of particles in the simulation even if they are constant/equal for all particles.
=> OpenPMD plugin: fix attribute charge/mass

etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Use latest openpmd-api/0.13.2 and adios2/2.7.1 module.
To do so, first, gcc module has to be downgraded due to module incompatibilities of gcc/9.3.0 with other required modules.
Second, adios1 can not be used anymore as it is incompatible with e4s module (which is on the other hand required for adios2 and openpmd-api).
But adios1 is deprecated anyway.
LaserWakefield example compiles and runs with these changes on summit.
=> Update summit profile

include/picongpu/particles/startPosition/QuietImpl.hpp
This changes how the `QuietImpl` `startPosition` functor positions particles when the number of created macro particles has to be reduced to satisfy `weighting >= MIN_WEGHTING` . The new code matches the previous calculation in `numMacroParticles`.
Now the number of particle rows / layers is reduced along the direction  with the highest amount of rows / layers until the condition is fulfilled. This is how the `numMacroParticles` was calculated before but this adjusted particle spacing was ignored in the operator body.
=> change how QuietImpl positions reduced number of particles

include/picongpu/param/radiationObserver.param, share/picongpu/examples/Bunch/include/picongpu/param/radiationObserver.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiationObserver.param
In case of ultra high gamma particles, the precision of the observation direction needs to be increased since the radiation cone decreases with ~1/gamma. `float_32` are not precise enough for particles above gamma>800. 
This fix removed the hard coded `float_32` implementation of the observation direction calculation and sets it to `float_X`. Thus it can be adjusted by setting PIConGPU's precision. This will coast a bit of performance, but can currently not be handled otherwise.
=> fix observation direction precision to float_X

include/picongpu/plugins/openPMD/openPMDWriter.hpp
It is currently impossible to specify different plugin parameters for checkpointing and restarting. ADIOS2 reading routines do apparently read the `InitialBufferSize` parameter even when opened in read-only mode. See screenshot below: Memory profile when reading 16 iterations, one time not specifying the `InitialBufferSize`, one time specifying it.
Since there is currently no useful configuration to use for reading routines when restarting, just don't use JSON configurations at all when reading.
=>  openPMD plugin: do not use JSON configurations when restarting #3674 

include/picongpu/fields/FieldTmp.tpp, include/picongpu/particles/collision/InterCollision.hpp, include/picongpu/particles/collision/IntraCollision.hpp
Without this only particle filters with a default constructor would work. With `IUnary` filters with a `Filter(uint32_t currentStep)` constructor should work as well.
=> use IUnary with filters in collisions and FieldTmp

include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp, include/picongpu/fields/MaxwellSolver/FDTD/FDTD.kernel, include/picongpu/fields/MaxwellSolver/Yee/StencilFunctor.hpp, include/picongpu/fields/absorber/pml/Pml.kernel
This PR refactors the field update, this removes the requirements that the update kernel required stencil information on the host side we only need within the kernel.
The new update kernel could be removed by a simple `ForEach` kernel with support of cached fields/Boxes but since we do not have it in pmacc or PIConGPU the explicit implementation is required.
- Make the stencil functor for field update more descriptive.
- The functor is providing the required stencil width information.
- Remove the duplicated implementation of `KernelUpdateE` and `KernelUpdateB`
=> refactor field update functor

lib/python/picongpu/plugins/data/radiation.py
This pull request fixes a design error in the python module to load the hdf5 radiation data that will break using the module with the upcoming  transfer from libSpalsh to openPMD-api #3566. 
The `unitSI` attribute currently exists for both the group and the data, thus it dies not break existing code
=> fix getting unitSI for amplitude

docs/requirements.txt
The docutils 0.17+ release uses more semantic HTML5 tags, which the RTD theme does not (yet) know.
This breaks side bar, lists and other elements.
fix /vs. broken:
=> Fix: RTD Docutils Build

lib/python/picongpu/plugins/data/radiation.py
The `.value` syntax to get data in h5py is now deprecated for quite a while. 
This pull request replaces it by the ellipsis `[...]` syntax. 
This enables usability of the python library again.  
This bug was discovered while testing #3566.
=> update h5py data-getter syntax in radiation python module

include/picongpu/fields/background/templates/TWTS/BField.hpp, include/picongpu/fields/background/templates/TWTS/BField.tpp, include/picongpu/fields/background/templates/TWTS/EField.hpp, include/picongpu/fields/background/templates/twtsfast/BField.hpp, include/picongpu/fields/background/templates/twtsfast/BField.tpp, include/picongpu/fields/background/templates/twtsfast/EField.hpp
Bugs discovered during testing of TWEAC for Frontier.
* Add missing `phiPositive` in `BField::calcTWTSBz_Ey` of `twtsfast`.
* Add missing `phiPositive` in `BField::calcTWTSBz_Ey` and `BField::calcTWTSBz_Ex` of TWTS.
* Clarify documentation of the interaction angle
Comparing plasma dynamics before and after the fixes are applied to `TWTS` and `twtsfast`.
We expect symmetric behavior of plasma electrons as it is only apparent with the fixes.
=> Fix TWTS implementations

docs/source/install/profile.rst, etc/picongpu/cori-nersc/a100.tpl, etc/picongpu/cori-nersc/a100_picongpu.profile.example
Add documentation to compile & run on Cori's A100 GPUs.
Preparation: load profile once and build (HDF5,) ADIOS2, openPMD-api & PNGwriter:
```bash
. ~/a100_picongpu.profile
export SW_DIR=/global/cfs/cdirs/ntrain/dgx  # only Axel can write here, use $HOME/sw in doubt
getNode 8
mkdir src
cd src
curl -Lo hdf5-1.10.7.tar.gz https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz
tar -xzf hdf5-1.10.7.tar.gz
cd hdf5-1.10.7
./configure --enable-parallel --enable-shared --prefix $SW_DIR/openmpi/hdf5-1.10.7 CC=mpicc CXX=mpic++
make -j 16
make install
cd ..
git clone https://github.com/ornladios/ADIOS2.git adios2
cd adios2
git checkout v2.7.1
cmake -S . -B build -DADIOS2_USE_Fortran=OFF -DCMAKE_INSTALL_PREFIX=$SW_DIR/openmpi/adios-2.7.1
cmake --build build -j 16 …
```
=> Cori: Add DGX (A100) Profile

include/picongpu/plugins/radiation/Radiation.kernel
It was a logical mistake.
However, with guards present it resulted in only an extra empty iteration. So does not need backporting.
But found during the hackathon.
=> Fix inaccurate supercell loop stop condition in the radiation kernel

include/picongpu/param/density.param, include/picongpu/particles/densityProfiles/FromOpenPMDImpl.hpp
The original implementation was technically correct, as it worked as documented, so I did not add the bug label. But it was not easy to use in the common case of using output of the previous simulation as input. Now all Cartesian axis orders should be supported properly. Also extend the comments to the parameters.
Edit: the preceeding paragraph concerns only the axis part.
There was also a bug with reading incorrect parts of the file when having multiple MPI ranks. This is unrelated to axes, but also fixed in this PR.
This PR includes the comment improvements from #3684, I will close that one.
Resolves #3685.
=> Fix FromOpenPMD density and make it account for axisLabels attribute

.gitlab-ci.yml, share/ci/compiler_hipcc.yml, share/ci/n_wise_generator.py
fix #3713
- avoids that apt-get waits for user interaction. (fix clang-format)
- fix outdated ROCm keys
=> CI: fix clang-format and ROCm

include/pmacc/communication/CommunicatorMPI.hpp
Changed visibilit of pmacc function `ExchangeTypeToRank` from protected to public.
This change is needed for later features in the `IsaacPlugin.hpp`.
=> pmacc ExchangeTypeToRank changed from protected to public

docs/TBG_macros.cfg
The pull request #3672 introduces PMLs as default absorber. This was not updated in the `TBG_macros.cfg`. This pull request adjusts the documentation accordingly.
=> change wrong default

etc/picongpu/taurus-tud/k80.tpl
This pull request fixes the first part of #3722 that was introduced with #3181. 
It changes the outdated `--workdir` command to `--chdir`.
=> switch to new 'chdir' SLURM command

include/picongpu/plugins/openPMD/openPMDWriter.hpp
The check itself and the fact exception is thrown are fine.
Just the old message referred to the ADIOS1 plugin, which no longer exists.
=> Fix outdated exception message for openPMD plugin with ADIOS1

docs/TBG_macros.cfg, docs/source/usage/plugins/isaac.rst, include/picongpu/param/isaac.param, include/picongpu/plugins/IsaacPlugin.hpp, share/ci/install/isaac.sh, share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/isaac.param, share/picongpu/tests/compileFieldSolver/include/picongpu/param/isaac.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param
- Added compatibility to the isaac vector field visualization and usage of vector field sources
- Benchmarking code example, can be enabled in .cfg files with the parameter `--isaac.timingsFilename [PATH/FILENAME.csv]`
Known issues:
- Moving window creates artifacts (for LIC visualization) at front GPUs as the seeding positions for the vector field visualization are stationary
=> Isaac plugin vector field vis compatility and benchmarking

include/picongpu/plugins/common/openPMDWriteMeta.hpp
Background: Using steps in openPMD/ADIOS2 with BP files is currently experimental and will stay so for a while (likely until we switch to an entirely new ADIOS2 schema). Until then, we should try to get PIConGPU to work in combination with steps without spamming warnings to stderr.
To fix the warning about attributes from previous steps not being modifiable, write the `date` attribute only once. (The other attributes are not affected since openPMD compares the attributes against those already specified, and does not write them anew if nothing changes)
I've already tested this and verified that the warnings do no longer occur.
This also fixes some low-key unspecified behavior: The `date` attribute is global in openPMD. If you specify it time after time again, there is no guarantee which …
=> Fix warning: Attribute /date cannot be overwritten (openPMD plugin)

include/picongpu/plugins/IsaacPlugin.hpp, share/ci/install/isaac.sh
Fixes moving window issues https://github.com/ComputationalRadiationPhysics/isaac/issues/146#issue-968862927 and https://github.com/ComputationalRadiationPhysics/isaac/issues/145#issue-968860368 by keeping the local volume sizes constant and only adjust the local volume position. 
Clipping to the global volume is done by ISAAC with the ISAAC PR https://github.com/ComputationalRadiationPhysics/isaac/pull/148#issue-716605360, which is required.
Update CI to use ISAAC dev branch continuing: https://github.com/ComputationalRadiationPhysics/isaac/pull/148#issue-716605360
=> ISAAC fix for particle vis and vector field vis in moving window simulation

include/picongpu/plugins/radiation/Radiation.kernel, include/picongpu/plugins/radiation/amplitude.hpp, include/picongpu/plugins/radiation/nyquist_low_pass.hpp, include/picongpu/plugins/radiation/radFormFactor.hpp, include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
This PR is based on the work we did last week during the NERSC hackathon. It is basically a nice way to implement [these changes](https://github.com/sbastrakov/picongpu/tree/topic-hackathonRadiationOptimization).
These changes should not be reducing accuracy. The results are not bitwise-identical due to reordering, but should not be consistently less accurate. Moving to all-float calculation would be of course faster, but that may be a significant loss of accuracy that should be studied before getting applied.
From what we observed at the hackathon, on the benchmark setup #3683 the commits 1 and 2 together (well, almost all must be 2) gave 1.11 x speedup of the radiation kernel. Note that these also make the previously proposed #3696 obsolete. Commit 3 gave further 1.19 x speedup.
Another …
=> Optimize radiation plugin math

include/picongpu/plugins/openPMD/WriteSpecies.hpp
The issue was in the condition of position filter activation.
Fixes #3742.
The same bug was probably present in other output backends (when we had those) and got copypasted here.
=> Fix crash in output after moving window stopped

docs/source/usage/plugins/radiation.rst, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/radiation/Radiation.hpp
This pull request changes the use of libSplash in the radiation plugin from libSplash to openPMD-api as requested in #3357. 
Be aware that this is still a draft.
**ToDo:**
=> Change rad plugin from libSplash to openPMD

etc/picongpu/spock-ornl/caar_picongpu.profile.example
The software ecosystem changed and a lot of modules are preloaded now.
The profile just adds modules required by PIConGPU to the pre-loaded
modules.
LWFA example compiles and runs.
=> Update spock profile after update to RHEL8

include/picongpu/particles/Manipulate.hpp, include/pmacc/particles/algorithm/CallForEach.hpp, include/pmacc/particles/algorithm/ForEach.hpp
By default it is `CORE + BORDER`, which was hard-set before.
Thus, no existing code needs to be changed, but more flexibility is added.
I think this change will become useful for implemeting other types of particle boundary conditions, like reflective or thermal, that require per-particle processing in kernel. Then we can use this extended version with `T_area = GUARD`. Based on discussions with @steindev 
Edit: for now PIConGPU operates with compile-time areas and area mappings. In principle it would of course be nice to allow run-time ones as well at some point, as that would add much flexibility to e.g. define an area for absorber region, or maybe apply particle boundary conditions at adjustable points.
=> Extend particles::Manipulate and the underlying implementation with area parameter

etc/picongpu/cori-nersc/a100_picongpu.profile.example
Missing in #3694 and recommended by docs.
(Not part of the Cori Cray system software env.)
=> Cori DGX: Module purge

include/picongpu/simulation/control/DomainAdjuster.hpp
In this case, both sides of absorber must fit, not just one side.
Fixes #3757.
=> Fix domain adjuster for absorber in case there is a single domain along a direction

include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/pmacc/random/RNGProvider.hpp, include/pmacc/random/RNGProvider.tpp
Previously they were re-initialized after loading thus potentially causing differences.
In case the states can't be loaded, the old scheme is used.
Thus, for old checkpoints there is no change in behavior.
Current status: compiles ~~but not checked yet~~ and works.
=> Add checkpointing of internal RNG states

.gitlab-ci.yml, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_hipcc.yml, share/ci/compiler_nvcc_cuda.yml
To reduce the CI load allow to interrupt the previous CI jobs if a branch is updated.
see: https://docs.gitlab.com/ee/ci/yaml/#interruptible
=> CI: allow to interrupt job

docs/TBG_macros.cfg, docs/source/usage/workflows/boundaryConditions.rst, include/picongpu/param/speciesAttributes.param, include/picongpu/particles/Particles.hpp, include/picongpu/particles/Particles.tpp, include/picongpu/particles/boundary/Apply.hpp, include/picongpu/particles/boundary/Kind.hpp, include/picongpu/simulation/control/Simulation.hpp, include/picongpu/simulation/stage/ParticleBoundaries.hpp
By default, same boundaries as set in `--periodic` are used. In fact, this is the only supported combination so far as other boundaries are not yet implemented. So there are no actual features added immediately by this PR.
However, it does some preparatory work and interfaces it to the command-line parameters:
- command-line options are added and propagated to species
- hook to put other boundary conditions is added with explanations for requirements
- the calling code to detect active boundaries and only process those is implemented for the general case
**For review**: might make sense to review commit-by-commit, however up to you
=> Enable support for custom particle boundaries

share/picongpu/examples/SingleParticleTest/include/picongpu/param/particle.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesInitialization.param
Name suggested y-drift, but it is x-drift
=> Fix drift manipulator in SingleParticle Example

include/picongpu/plugins/PluginController.hpp
In case OpenPMD is not available and PIConGPU is compiled for the CUDA backend the code is not compiling because of a syntax error.
=> fix compile

docs/TBG_macros.cfg, docs/source/usage/plugins/openPMD.rst, docs/source/usage/plugins/xrayScattering.rst, include/picongpu/plugins/openPMD/NDScalars.hpp, include/picongpu/plugins/openPMD/openPMDWriter.def, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp, include/picongpu/plugins/xrayScattering/XrayScattering.hpp, include/picongpu/plugins/xrayScattering/XrayScatteringWriter.hpp
This parameter was for legacy-style selection of compression in openPMD
which is implemented only in ADIOS1. The openPMD plugin does not support
ADIOS1, so this is inaccessible functionality.
The legacy-style compression support will likely be removed in openPMD,
compression should be configured in a backend-specific style via JSON.
=> Remove --openPMD.compression parameter

.gitlab-ci.yml, share/ci/compiler_clang.yml, share/ci/compiler_clang_cuda.yml, share/ci/compiler_gcc.yml, share/ci/compiler_hipcc.yml, share/ci/compiler_nvcc_cuda.yml, share/ci/generate_reduced_matrix.sh, share/ci/n_wise_generator.py, share/ci/run_tests.sh
Separate PMacc and PIConGPU jobs. PIConGPU is currently not executed on GPU therefore we can run the compile tests on CPU CI runner and only perform PMacc tests on the accelerator-specific runners. This is reducing the CI load and should result in result in faster CI response times.
To reduce the load PMacc is only testing each second boost version. The newest boost version is always included.
Update the CI base job descriptions to simplify switching to a new container tag or cuda/hip version.
The time to pass the CI is reduced from over 200 min to less than 100 min.
=> CI: compile on x86 runners 

include/pmacc/mappings/kernel/AreaMapping.hpp, include/pmacc/mappings/kernel/AreaMappingMethods.hpp, include/pmacc/mappings/kernel/BorderMapping.hpp, include/pmacc/mappings/kernel/ExchangeMapping.hpp, include/pmacc/mappings/kernel/ExchangeMappingMethods.hpp, include/pmacc/mappings/kernel/MapperConcept.hpp, include/pmacc/mappings/kernel/StrideMapping.hpp
Fix mixing up of block and supercell indexing in the naming.
Move the `MapperConcept` and `MapperFactoryConcept` to a new file.
Link in the comments all mapping templates to the `MapperConcept` and the only (so far) existing factory to the factory concept.
=> Clarify naming and comments for pmacc kernel mapping types

include/picongpu/plugins/radiation/vector.hpp
```
picongpu/include/pmacc/../picongpu/plugins/radiation/particle.hpp: In constructor ‘picongpu::plugins::radiation::Particle::Particle(const vector_X&, const vector_X&, const vector_X&, picongpu::float_X)’:
picongpu/include/pmacc/../picongpu/plugins/radiation/particle.hpp:75:119: warning: implicitly-declared ‘constexpr picongpu::plugins::radiation::cuda_vec<pmacc::math::Vector<float, 3>, float>::cuda_vec(const picongpu::plugins::radiation::cuda_vec<pmacc::math::Vector<float, 3>, float>&)’ is deprecated [-Wdeprecated-copy]
75 |                     const picongpu::float_X mass_set)
...
picongpu/plugins/radiation/vector.hpp:76:40: note: because ‘picongpu::plugins::radiation::cuda_vec<pmacc::math::Vector<float, 3>, float>’ has user-provided ‘picongpu::plugins::radiation::cuda_vec<V, T>& …
```
=> plugin radiation: fix warning

include/pmacc/mappings/kernel/MapperConcept.hpp
Was accidentally introduced by me recently, was using C++17 syntax.
=> Fix a warning in MapperConcept

.gitlab-ci.yml, share/ci/n_wise_generator.py
Group the downstream pipe into stages to reduce the load on the CI.
Additionally, this had the advantage that in case a job in the first stage is not passing the checks other stages will not be started, which keeps more CI resources free.
thx @SimeonEhrig for the hint that downstream pipes can have their own stages.
@SimeonEhrig said I should clean the python code, this will be a task for a follow-up PR.
=> CI: use stages for downstream pipe

include/picongpu/plugins/openPMD/openPMDWriter.def, include/picongpu/plugins/openPMD/openPMDWriter.hpp
The function `writeField()` *is* already templated on the type to use for writing, but so far does a compile-time check if that type is `float_X`. Make it generic, close #3754.
TODO:
=> openPMD plugin: no hardcoding of float_X in writeField()

docs/source/dev/extending.rst, docs/source/index.rst
I think we are missing such documentation for a very long time. It is unfortunately quite hard to write, which is partially caused by PIConGPU being not very simple to extend. This is my effort to hopefully jumpstart this activity. If relatively recent contributors like @pordyna @BrianMarre can also have a look, it would be nice.
Note: this only extends readthedocs, you can see the result (once it builds) at the bottom, under "show all checks", where CI is.
=> Add a documentation page for developers that explains how to extend PIConGPU

include/picongpu/particles/Particles.kernel
The pusher kernel contains a status flag per supercell which is a marker to know if at least one particle is leaving the supercell.
This status flag is located in shared memory and manipulated via an atomic function by each thread.
This PR aggregates the status per thread first into a register and uses atomic to synchronize the state between threads only if needed and not for each particle that leaves the cell.
=> optimize kernel MoveAndMark

docs/TBG_macros.cfg, include/picongpu/ArgsParser.cpp, include/picongpu/param/grid.param, include/picongpu/simulation/control/Simulation.hpp, share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/grid.param, share/picongpu/examples/Bunch/include/picongpu/param/grid.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/grid.param, share/picongpu/examples/FoilLCT/include/picongpu/param/grid.param, share/picongpu/examples/IncidentField/include/picongpu/param/grid.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/grid.param, share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/grid.param, share/picongpu/examples/WarmCopper/include/picongpu/param/grid.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/grid.param, share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/grid.param, share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/grid.param, share/picongpu/tests/XrayScattering/include/picongpu/param/grid.param, share/picongpu/tests/compileFieldSolver/include/picongpu/param/grid.param
We already had a runtime parameter for it, now it is the only way to set it.
Update all `grid.param` files.
=> Remove compile-time movePoint from grid.param

docs/source/usage/workflows/probeParticles.rst, docs/source/usage/workflows/tracerParticles.rst, include/picongpu/param/speciesAttributes.param, include/picongpu/particles/pusher/particlePusherAcceleration.hpp, include/picongpu/particles/pusher/particlePusherAxel.hpp, include/picongpu/particles/pusher/particlePusherBoris.hpp, include/picongpu/particles/pusher/particlePusherFree.hpp, include/picongpu/particles/pusher/particlePusherHigueraCary.hpp, include/picongpu/particles/pusher/particlePusherPhoton.hpp, include/picongpu/particles/pusher/particlePusherProbe.hpp, include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp, include/picongpu/particles/pusher/particlePusherVay.hpp, include/pmacc/meta/InvokeIf.hpp
Add functionality to all pushers to record particle attribute probeB and probeE data.
PMacc: add meta function `executeIf` and `executeIfElse`.
All pushers record field data if a particle as the attribute `probeB` or `probeE`. 
There is no need anymore to add attributes, depending on which attributes are available to corresponding data will be recorded.
=> Record probe data with all pusher Pusher

include/picongpu/fields/FieldTmp.tpp, include/picongpu/fields/currentDeposition/Deposit.hpp, include/pmacc/mappings/kernel/StrideMapping.hpp, include/pmacc/particles/ParticlesBase.hpp
I called the new factory / factory function with `area` explicitly, as it is more descriptive and also I plan to add a new stride mapping for intervals introduced by #3783. This will be useful for particle absorber optimizations after #3776 is merged.
The second commit parametrizes the `shiftParticles()` with an area factory. It is in the same fashion as `picongpu::particles::manipulate()`. We will need this one, again, for particle absorbers.
=> Add a factory and a factory function for pmacc::StrideMapping

docs/source/usage/plugins/openPMD.rst, docs/source/usage/workflows/particleFilters.rst
I think this was rather unclear for users: #3666 , #3774 , #3780 . This PR at least clarifies the common use case of needing particle global position.
And may help do other `particle + some custom data` cases by example. Of course, there an issue is that in case there is no pre-existing wrapper, a user has to do it themselves. Which is mostly a copy-paste of existing wrappers, but not very intuitive.
=> Extend doc section on particle filter workflows

include/pmacc/boost_workaround.hpp, include/pmacc/meta/String.hpp
This PR improves the readability of error messages during compilation by shrinking the template argument list of `pmacc::meta::String` to the necessary amount of characters. It uses `BOOST_METAPARSE_STRING` to convert a string literal into a char pack.
Example error before this change (typo in `pmacc::Frame`):
```
/mnt/c/dev/picongpu/include/picongpu/../pmacc/particles/memory/frames/Frame.hpp:74:47: error: no type named 'asdf' in 'pmacc::ParticleDescription<pmacc::meta::String<'e', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', …
```
=> Replace custom compile-time string creation by BOOST_METAPARSE_STRING

include/picongpu/particles/MoveParticle.hpp, include/picongpu/particles/Particles.kernel
relocate function to move particles with mulitmask status from
Particles.kernel to a new separat file for further usage e.g. the
function will be required in custom particle boundary conditions
as discussed with @sbastrakov
=> relocate function to move particles

.gitignore
Cline is creating a python environment within the project, this environment should not be checked in.
=> add python env to gitignore

include/pmacc/cuSTL/algorithm/kernel/detail/SphericMapper.hpp, include/pmacc/cuSTL/algorithm/kernel/run-time/Foreach.hpp, include/pmacc/cuSTL/algorithm/mpi/Reduce.tpp, include/pmacc/cuSTL/cursor/navigator/CartNavigator.hpp, include/pmacc/dimensions/DataSpace.hpp, include/pmacc/kernel/operation/Atomic.hpp, include/pmacc/math/ConstVector.hpp, include/pmacc/math/vector/Float.hpp, include/pmacc/math/vector/Int.hpp, include/pmacc/math/vector/Size_t.hpp, include/pmacc/math/vector/TwistComponents.hpp, include/pmacc/math/vector/UInt32.hpp, include/pmacc/math/vector/UInt64.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/math/vector/Vector.tpp
* simplify `T_Storage` policy to a normal type parameter
* make derived vectors for specific types aliases
* implement tuple interface for Vector (allows structured bindings)
* replace alias `This` by injected class name `Vector`
This PR fell out of the LLAMA integration.
=> Refactor and extend Vector

include/picongpu/particles/boundary/Utility.hpp
Thanks to Long Yang for pointing out the bug.
For 3d it was also going one extra. But in 2d that one passed the filter and caused a bug, and for 3d it never got through the filter and so had no effect.
=> Fix a bug in particle boundaries in 2d simulations

include/picongpu/param/density.param
I failed to compile PIConGPU without OpenPMD and I had to guard the offending line.
Do we have CI runners testing without OpenPMD?
=> Guard definition of FromOpenPMD

include/picongpu/particles/boundary/Utility.hpp, include/pmacc/particles/ParticlesBase.hpp
This PR fixes a warning on an unused variable and an error when compiling with MSVC.
=> Fix warning and MSVC error

include/picongpu/particles/bremsstrahlung/PhotonEmissionAngle.hpp, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.tpp, include/pmacc/cuSTL/container/DeviceBuffer.hpp, include/pmacc/cuSTL/container/HostBuffer.hpp, include/pmacc/math/Tuple.hpp, include/pmacc/traits/GetUniqueTypeId.hpp, include/pmacc/types.hpp
Among easily removable Boost parts I think only `result_of` is remaining.
=> Remove more old boost includes and replace with std:: counterparts

etc/picongpu/summit-ornl/gpu_batch.tpl, etc/picongpu/summit-ornl/gpu_batch_pipe.tpl, etc/picongpu/summit-ornl/gpu_picongpu.profile.example
fix #3814
Workaround IBM optimized barriers.
Co-authored-by: Axel Huebl <axel.huebl@plasma.ninja>
Note: I added the bash variable which is required to work around the bug to the profile and template to take care that interactive sessions started with `getNode` were fixed too.
=> fix Summit(ORNL) MPI collectives

include/pmacc/memory/boxes/DataBox.hpp, include/pmacc/memory/boxes/DataBoxDim1Access.hpp, include/pmacc/memory/boxes/DataBoxUnaryTransform.hpp, include/pmacc/memory/boxes/PitchedBox.hpp, include/pmacc/memory/boxes/SharedBox.hpp
This PR simplifies `DataBox` and its related classes.
Here are two quick runs on fwk394:
PR:
calculation  simulation time: 31sec 423msec = 31.423 sec
calculation  simulation time: 32sec 870msec = 32.870 sec
dev:
calculation  simulation time: 31sec 311msec = 31.311 sec
calculation  simulation time: 32sec 903msec = 32.903 sec
=> Refactor DataBox

include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp, include/picongpu/fields/MaxwellSolver/CFLChecker.hpp, include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp, include/picongpu/fields/MaxwellSolver/None/None.hpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/initialization/InitialiserController.hpp
fix #3201
Simplify the log output for the field solver condition and omega_p.
@sbastrakov The field condition for our Lehe solver is currently `c * dt <= min(dx, dy, dz)` is this correct. 
I assume that we do not know the correct condition and therefore we fall back to the default.
=> adjust physics log output

include/picongpu/plugins/output/GatherSlice.hpp, include/picongpu/plugins/output/images/PngCreator.tpp, include/picongpu/plugins/output/images/Visualisation.hpp
This PR replaces chained uses of the subscript operator on `DataBox`es by their corresponding call operators. This eases a potential later LLAMA integration.
=> Use multidim access instead of two subscripts

include/picongpu/plugins/output/GatherSlice.hpp, include/pmacc/memory/boxes/PitchedBox.hpp, include/pmacc/memory/buffers/DeviceBufferIntern.hpp, include/pmacc/memory/buffers/HostBufferIntern.hpp, include/pmacc/particles/memory/boxes/ExchangePushDataBox.hpp, include/pmacc/particles/memory/boxes/PushDataBox.hpp, include/pmacc/particles/memory/boxes/TileDataBox.hpp
Replace `PitchedBox` ctor with offset by `DataBox.shift()`. This unifies the shifting with how `SharedBox` is shifted and simplifies the ctor overload set of `PitchedBox`.
No change in CUDA register consumption.
=> Replace PitchedBox ctor with offset by DataBox.shift()

include/picongpu/fields/cellType/Centered.hpp, include/picongpu/fields/cellType/Yee.hpp, include/pmacc/math/MapTuple.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/particles/memory/boxes/TileDataBox.hpp, include/pmacc/particles/memory/dataTypes/Particle.hpp, include/pmacc/particles/memory/dataTypes/StaticArray.hpp, include/pmacc/particles/memory/frames/Frame.hpp, include/pmacc/particles/operations/Deselect.hpp, include/pmacc/random/Random.hpp
This PR removes all machinery related to `boost::result_of`, which in many cases can be replaced by C++11 deduction features.
=> Remove boost::result_of

include/picongpu/particles/manipulators/manipulators.def, include/picongpu/particles/manipulators/manipulators.hpp, include/picongpu/particles/manipulators/unary/FreeTotalCellOffsetRng.def, include/picongpu/particles/manipulators/unary/FreeTotalCellOffsetRng.hpp
This functor is effectively a combination of two wrappers around `T_Functor`: `FreeTotalCellOffset` and `FreeRng`. Currently there is no easy way to achieve such a combination via sequantial application. So here is a special wrapper for it. We discussed with @psychocoderHPC a few times that ideally we should have some generic way for a functor to describe used resources (not in redgrapes sense, but logically it is similar) so that we don't have to specialize for each new case.
This functor is to enable work on thermal particle boundaries.
=> Add a new particle manipulator combining total cell offset and rng

share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
I discovered a missing -d flag. So when specifying a number of devices for the different axis that can be used, which wasn't possible without -d
=> fix -d in 1.cfg in SingleParticleExample

include/picongpu/particles/boundary/Utility.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.kernel
By mistake it was using internal instead of external range. Also slightly change some variable names there for more clarity.
cc @pordyna
=> Fix cell range in calorimeter plugin processing leaving particles

include/picongpu/algorithms/AssignedTrilinearInterpolation.hpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp, include/pmacc/cuSTL/cursor/Cursor.hpp, include/pmacc/cuSTL/cursor/FunctorCursor.hpp, include/pmacc/cuSTL/cursor/accessor/CursorAccessor.hpp, include/pmacc/cuSTL/cursor/accessor/FunctorAccessor.hpp, include/pmacc/cuSTL/cursor/accessor/LinearInterpAccessor.hpp, include/pmacc/cuSTL/cursor/accessor/MarkerAccessor.hpp, include/pmacc/cuSTL/cursor/accessor/PointerAccessor.hpp, include/pmacc/cuSTL/cursor/accessor/TwistAxesAccessor.hpp
This PR renames `type` in Cursor to `Reference` to better reflect their semantic.
=> Rename type to Reference in Cursor

include/picongpu/particles/pusher/particlePusherAcceleration.hpp
Bug was introduced in #3714. But how did it pass through CI, is there some configuration missing as well? Edit: yes, there is also a bug in the compile-time pusher test suite missing this one
=> Fix compile error in the accelerating pusher

docs/source/usage/workflows/particleFilters.rst
We should have this link somewhere else. But currently I do not see any fitting place in the existing readthedocs structure.
=> Add a link to the domain definitions wiki in the particle global filter workflow

INSTALL.rst, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
This PR updates the profiles for hemera to fulfill the current CMake version requirement. It also updates the documentation for the current requirement.
=> Update hemera profiles and documentation for current cmake requirements

include/picongpu/plugins/openPMD/GetComponentsType.hpp, include/picongpu/plugins/openPMD/restart/LoadParticleAttributesFromOpenPMD.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
ADIOS2 backend does not support bools which caused exceptions.
Redefine `GetComponentsType` trait to treat bools as chars.
Fixes #3732
@Anton-Le I checked that this version compiles, writes checkpoints, and restarts from them on our dev machine. I had no easy way to check if the read values are correct. Could you check it? In case you use some older PIConGPU, should be no problem, could apply the same changes.
=> Fix treatment of bool particle attributes in openPMD plugin

include/picongpu/fields/MaxwellSolver/FDTD/FDTD.kernel, include/picongpu/fields/MaxwellSolver/FDTD/StencilFunctor.hpp, include/picongpu/fields/absorber/pml/Pml.kernel
This functor "concept" was introduced at the same time the general FDTD part of the `Yee` solver was separated. So this general functor stayed at Yee because of this (mis)ordering. Move it now to FDTD directory and namespace where it is more fitting.
=> Move yee::StencilFunctor to fdtd::StencilFunctor

include/picongpu/param/particle.param, include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/startPosition/RandomPositionAndWeightingImpl.def, include/picongpu/particles/startPosition/RandomPositionAndWeightingImpl.hpp, include/picongpu/particles/startPosition/functors.def, include/picongpu/particles/startPosition/functors.hpp, share/picongpu/tests/compileParticlePusher/include/picongpu/param/particle.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesInitialization.param
It generates both randomly.
In terms of position, it is same uniformly distributed as in `RandomImpl`.
The weightings are sampled randomly, guaranteed to be within the constraints.
This is what we discussed on a dev meeting today.
=> Add a new functor for start position and weightings of macroparticles

include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp, include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
In case two virtual particles were used, the implementation was incorrect.
It resulted in proper total amount of Jz, but generally incorrect distribution in x, y.
See #3889 for more details.
This PR implements [the suggested fix](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3889#issuecomment-952019984).
Now it produces same Jz values as `Esirkepov` implementation.
Solves #3889.
We have to port this fix to the release candidate branch. This error also seems to have been present in all PIConGPU versions on github.
It is hard to evaluate what was the effect of it. The bug affected only 2d case, and only particles with the two-virtual-particles schema, so the particles that changed the closest cell or half-cell (depending on even/odd shape support) in x or y due to …
=> Fix incorrect assignment of Jz in 2d EmZ implementation

include/picongpu/particles/Particles.hpp
This resulted in some imprecise meta information in the output. Did not affect calculations. So i think it is not necessary to port to the release candidate.
=> Add missing string property output for reflecting and thermal particle boundaries

include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
The error was reported in #3899.
It seems the wrong logic was introduced in #3507. The patch offset calculation was wrong. It double-counted the shift of the moving window. So after the window have slided, the domains were loading wrong patches, which could have led to all sorts of trouble: incorrect results, crashes, etc.
We investigated with @psychocoderHPC , found the issue and made the fix. The second commit also adds a check that this situation is reported more clearly (e.g. would have helped to find this one).
=> Fix restarting with moving window

include/pmacc/kernel/atomic.hpp
When running PIConGPU with HIP 4.3+ and in single precision the
performance is by a factor 3 worse compared to HIP 4.2.
The reason are slow shared memory atomicAdd operations.
Solution: Add a float specialization for atomics between threads which
is emulating atomicAdd via atomicCAS (as in good old days^^)
Note: This fix should be ported to alpaka too to provide better performance to other projects too.
=> fix performance issue with HIP 4.3+

include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp, include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp, include/picongpu/plugins/openPMD/GetComponentsType.hpp, include/picongpu/plugins/openPMD/restart/LoadParticleAttributesFromOpenPMD.hpp, include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp, share/picongpu/dockerfiles/ubuntu-2004/Dockerfile, thirdParty/mallocMC/src/include/mallocMC/alignmentPolicies/Noop.hpp, thirdParty/mallocMC/src/include/mallocMC/alignmentPolicies/Shrink.hpp, thirdParty/mallocMC/src/include/mallocMC/creationPolicies/OldMalloc.hpp, thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter.hpp, thirdParty/mallocMC/src/include/mallocMC/device_allocator.hpp
Backport to 0.6.0-rc1
- Fix treatment of bool particle attributes in openPMD plugin #3890
- Fix incorrect assignment of Jz in 2d EmZ implementation #3892
- Fix restarting with moving window #3902
- Spack load: no more "-r" #3873
- Topic update malloc mc #3897
=> backport to 0.6.0-rc1

etc/picongpu/taurus-tud/k80_picongpu.profile.example
I updated the k80 profile for taurus. One has to build c-blosc, PNGwriter, ADIOS2, HDF5, openPMD-api and Boost themselves with the [mentioned script](https://gist.github.com/finnolec/3004deeb6251d1e76f2250f99a8a2170). I ran a `LaserWakefield` simulation on the current `dev` branch with ADIOS2 output and one with HDF5 output and both didn't crash. So I think that this script + this profile should work.
Additionally I added a `getDevice` command :)
=> Update profile for taurus k80 partition

include/picongpu/plugins/multi/Option.hpp
I need this in the TOML PR. The logic was already being used inside `Option::get<>()`, this extracts it to another method and also uses that inside `get()`.
Also, make `getName()` a `const` method, I also need that for the TOML PR.
=> Add optionDefined() to plugins::multi::Option struct

include/picongpu/particles/InitFunctors.hpp, include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/particles/access/Cell2Particle.tpp, include/pmacc/math/MapTuple.hpp, include/pmacc/particles/memory/frames/Frame.hpp
During my experiments with LLAMA I found that if the particle frame data is not overaligned with `PMACC_ALIGN` we have slight performance gains.
E.g. running the SPEC example on fwk394:
```
./picongpu -d 1 1 1 -g 256 256 256  -s 100 -p 5 --periodic 1 1 1 # dev
calculation  simulation time: 30sec 607msec = 30.607 sec
./picongpu -d 1 1 1 -g 256 256 256  -s 100 -p 5 --periodic 1 1 1 # this PR
calculation  simulation time: 29sec 512msec = 29.512 sec
```
That is a speedup of 1.037. I wonder if that effect is also visible in larger benchmarks. If it is, I would recommend merging this PR.
----------------------
update by @psychocoderHPC:
=> Avoid overaligning particle frame data

include/picongpu/particles/collision/binary/RelativisticBinaryCollision.hpp
`std::sinh` can not be used on device side.
The bug was showing up with HIP 4.5 but in general the code should be wrong in CUDA too.
This bug should be backported to 0.6.0.
=> fix using host function in device code

share/picongpu/dockerfiles/ubuntu-2004/Dockerfile
Fixes to be compatible with the latest spack development branch.
backport of #3921 to 0.6.0-rc1
=> fix docker recipe

docs/source/usage/plugins/openPMD.rst, etc/picongpu/summit-ornl/gpu_batch.tpl, etc/picongpu/summit-ornl/gpu_batch_pipe.tpl
~~Copied~~ Inspired from https://github.com/ECP-WarpX/WarpX/pull/2495/files
TODO:
=> Summit templates: Add performance hints

docs/source/usage/plugins/openPMD.rst, include/picongpu/plugins/openPMD/Json.cpp, include/picongpu/plugins/openPMD/Json_private.hpp
We specify `export OMPI_MCA_io=^ompio` in some templates and that somehow makes HDF5 segfault when chunking is enabled. Chunking is only a recent addition in the openPMD-api so the error probably did not came up too often for now, but we should clarify this before merging [this one](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3913).
TODO:
=> Disable hdf5 chunking by default

docs/source/in5min.rst, docs/source/index.rst, docs/source/tutorials/hemeraIn5min.rst
Dear Maintainer,
I'm currently working through the documentation of PIConGPU and getting familiar with the software.
I oftentimes found myself lacking context, and generally missing a good *overview* over the matters discussed in the individual sections.
(I'd propose creating a new manual section "Overview" outlining general architecture, capabilities, usage, an FAQ for further reading and some short guides -- a "REAMDE++" if you will. However writing and maintaining such a section would consume considerable ressources.)
As an intermediary solution I want to contribute a very brief guide which touches some of those aspects named "PIConGPU in 5 Minutes". It explains how to get a basic example scenario running from scratch. It assumes that the reader:
- uses an existing HPC cluster with an …
=> "PIConGPU in 5 Minutes": Short Introduction for new Users

docs/source/usage/workflows/tracerParticles.rst, include/picongpu/param/species.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/tests/XrayScattering/include/picongpu/param/species.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
Revert #3599 and switch back to Esirkepov as the default current solver.
@steindev and me working currently on the EmZ publication. There are some open questions, therefore we decided to switch back to the well-known and understood Esirkepov current deposition method until all open questions are answered.
Note: all our tests show that EmZ is charge conserving and not introducing any artificially heating.
This PR will be ported back to 0.6.0 before the release.
=> Set back Esirkepov as default current solver

docs/source/usage/plugins/openPMD.rst, include/picongpu/plugins/common/openPMDVersion.def
This affects all plugins that use openPMD, and especially that use its span-based storeChunk() API.
While this helps us reduce memory usage, it is [incompatible with compression operators](https://github.com/ornladios/ADIOS2/issues/2965) since these take advantage of working with two buffers (compression is not in-place).
So we make this feature opt-in.
Note that with the upcoming BP5 engine, there will be no need for the span-based storeChunk API any longer, so this is the right call to make.
TODO
=> Make the span-based storeChunk API opt-in in various openPMD-based IO routines

include/picongpu/plugins/xrayScattering/XrayScattering.hpp
I think we discussed when I was writing  the `XrayScattering` plugin that the `GUARD` to `BORDER` communication is not required but I think this was wrong. I finally understood what this does and I think this is missing. Without the communication the contributions from particles on the edges of the GPUs are not correctly added to the adjacent GPU borders. I was using `Counter` particle shape in my tests back then so this never caused any problems. Note, this is how it is done in other places in `PIConGPU`.
=> Add missing communication in XrayScattering

.zenodo.json, README.md
This PR is opened against the release 0.6.0 and will be merged back into the development branch as soon as we released 0.6.0.
Add missing contributors and update creators of the current release.
I updated the creators and contributors for the zenodo file, I followed the rules we used for alpaka [[link](https://github.com/alpaka-group/alpaka/pull/1236)] too.
- **creators** are everyone how contributed to the current release version e.g. 0.6.0
- the list is alphabetically ordered
- **contributors** everyone who contributed in the past
- the list is alphabetically ordered
- affiliation based on the time of the contributions
In the README file, I kept the maintainer and core developers list shorter to reduce the maintenance overhead for the list.
A core developer is someone who is regularly …
=> update zenodo and README file

docs/source/usage/plugins/openPMD.rst, docs/source/usage/workflows/tracerParticles.rst, include/picongpu/param/species.param, include/picongpu/plugins/common/openPMDVersion.def, share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param, share/picongpu/tests/XrayScattering/include/picongpu/param/species.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
PR's:
- Set back Esirkepov as default current solver #3932
- Make the span-based storeChunk API opt-in in various openPMD-based IO routines #3933
=> backport last fixes for the release 0.6.0

include/picongpu/plugins/xrayScattering/XrayScattering.hpp
backport: `Add missing communication in XrayScattering` #3937 to 0.6.0-rc1
=> backport: fix missing communication in XrayScattering

bin/pic-configure
The architecture string for AMD GPUs could contain `:`. The old way how we
separated the backend from the architecture details is therefore not
working.
```
pic-build -b "hip:gfx906:sramecc+:xnack-"
```
I marked this behavior as bug but it is somehow more a feature. There is no need to backport this PR to the current ongoing release process of 0.6.0.
=> HIP: allow full architecture definition

etc/picongpu/hemera-hzdr/defq.tpl, etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_restart.tpl
Fixes #3926. It reverts #3853 and also adds `-np` to `mpiexec`. The new combination seems to work on Hemera for all cases: 1 node (full and not full), several full nodes, several not full nodes.
I think the change should be backported to the release candidate branch as well.
=> Add --ntasks-per-node and -np to .tpl files on Hemera

share/ci/compiler_hipcc.yml, share/ci/run_picongpu_tests.sh
- The old AMD Fiji double slot GPU from the CI is removed therefore we must use device zero (default).
- The second commit is disabling ISAAC usage for the foilLCT test because the CI is very often running out of memory.
- fix that we build HIP tests for the wrong architecture, this was overseen in #3915
Backport to 0.6.0 required
=> CI: change AMD CI node configuration

include/picongpu/plugins/openPMD/Json.cpp
I noticed this while testing that #3933 actually fixes the bugs fixed by it (it does). If using the extended PIConGPU-defined JSON schema for specifying dataset-specific compression and *not* specifying a default pattern, the pattern list under `json[<backend>]["dataset"]` will be forwarded as-is to the openPMD-api. This does not actually make the openPMD-api crash, but it's still a bug on PIConGPU's side.
Fix: If no pattern is found, delete that key.
```json
{
"adios2": {
"unused": "parameter",
"engine": {
"usesteps": true,
"rabimmel": "rambamel",
"parameters": {
"InitialBufferSize": "2Gb",
"Profile": "On"
}
},
"dataset": [
{"cfg": {}}, // <--- default pattern
{
"select": ".*/E/.*",
"cfg": {
"operators": [
{
"type": "bzip2"
}
]
}
}
]
}
}
```
=> Extended JSON configuration of openPMD plugin: Erase dataset options if no default is given

include/picongpu/CMakeLists.txt, include/picongpu/plugins/common/openPMDVersion.def, include/picongpu/plugins/common/openPMDWriteMeta.hpp, include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp, include/picongpu/plugins/openPMD/NDScalars.hpp, include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp
openPMD-api version 0.14.3 has recently been [released](https://github.com/openPMD/openPMD-api/commit/00532a7873f1ec3eff9aa4238f303597bd039b6b) and includes fixes that are necessary for usage with C++17. With older versions, there are ABI incompatibilities if building openPMD-api with C++14, but including it into a C++17 project.
Since PIConGPU is currently being released (still on C++14), this marks a good time for bumping the minimum required version once the release is out. This also removes a number of workarounds for newer features (namely: the streaming API, the span-based storeChunk() API, dataset-specific backend configuration) that were not available in openPMD-api 0.12.0.
TODO:
Update: There seem to be issues with chunking. This can be deactivated, but should be clarified before …
=> Version bump: openPMD-api from 0.12.0 to 0.14.3

include/picongpu/fields/FieldTmp.hpp, include/picongpu/fields/FieldTmp.kernel, include/picongpu/fields/FieldTmp.tpp, include/picongpu/particles/particleToGrid/CombinedDerive.def, include/picongpu/particles/particleToGrid/CombinedDerive.hpp, include/picongpu/particles/particleToGrid/CombinedDerivedAttribute.hpp, include/picongpu/particles/particleToGrid/ComputeFieldValue.hpp, include/picongpu/particles/particleToGrid/combinedAttributes/AverageAttribute.def, include/picongpu/particles/particleToGrid/combinedAttributes/AverageAttribute.hpp, include/picongpu/particles/particleToGrid/combinedAttributes/CombinedAttributes.def, include/picongpu/particles/particleToGrid/combinedAttributes/CombinedAttributes.hpp, include/picongpu/particles/particleToGrid/combinedAttributes/RelativisticDensity.def, include/picongpu/particles/particleToGrid/combinedAttributes/RelativisticDensity.hpp, include/picongpu/plugins/IsaacPlugin.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, share/picongpu/tests/compileCombinedAttributes/README.rst, share/picongpu/tests/compileCombinedAttributes/include/picongpu/param/fileOutput.param, share/picongpu/tests/compileCombinedAttributes/include/picongpu/param/memory.param
This PR introduces derived attributes which are a function of two primary derived attributes (such like we had until now). This is something I need for my online Faraday Rotation calculation but I found this a generally useful feature. 
What I needed was 1/gamma^2 * density, where gamma is the Lorentz factor for the average kinetic energy in the cell. Because of the square it wasn't possible to just add another usual derived field. This new combined field is introduced as `RelativisticDensity`. 
This PR also includes a template for an average value of any derived quantity `AverageAttribute` ( from: average value = total quantity density / number density) as an example of a more general use of this feature. 
I also changed how the `computeValue` algorithm is called in the `openPMD` and …
=> add combined derived attributes

include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp, include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Base.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp, include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp
Move duplicated code to shared base class, cleanup constants' suffixes, improve naming of EmZ grid shifts.
Solves #3893.
=> Cleanup current deposition implementation
