examples/SingleParticleCurrent/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleRadiationWithLaser/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleTest/include/particles/ParticlesInitOneParticle.hpp, src/libPMacc/include/particles/memory/dataTypes/Particle.hpp, src/libPMacc/include/particles/operations/SetAttributeToDefault.hpp, src/picongpu/include/particles/ParticlesInit.kernel
- add functor to set an attribute of a particle to their default value
- extend the particle assign definition (set attributes which are not defined in the source particle to their default value)  [discussion](https://github.com/ComputationalRadiationPhysics/picongpu/pull/595#discussion_r22087654)
- remove old usage of `SetValueToDefault` with the new PMacc functor
**Tests**
=> extend particle assign specialization 

doc/TBG_macros.cfg
Fixed typo: `TGB` to `TBG`
found by @dengshuan #616
=> fix #616 typo TGB -> TBG

src/tools/bin/tbg
This feature shortens the `tbg` call dramatically without harming its generality.
The `-s | --submit` option is the batch system and unique for each machine. That is a perfect candidate for a `picongpu.profile` or a general `.profile` setting (as a default).
The `-t | --tpl` file is useful if you have various queues or debug templates. 99% of the users always submit to the same queue and would love a default, too. Developers or power users with varying queues can still use `-t` to overwrite the default.
If `TBG_SUBMIT` or `TBG_TPLFILE` are not set, the default values are still `""` which will result in a standard error from `tbg`.
=> TBG: Add Defaults via Env for -s|-t

src/picongpu/include/plugins/output/images/Visualisation.hpp
- set extern shared memory to float_X
this bug only effect runs with double precision
=> fix memory bug in Visualisation.hpp

src/libPMacc/examples/gameOfLife2D/include/GatherSlice.hpp
VLA`s  are a GCC extension and are not part of any C++ standard.
See: https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html
=> variable length arrays are not C++ standard

src/libPMacc/include/memory/buffers/Buffer.hpp
The override of 'PMacc::Buffer<...>::setCurrentSize' in 'PMacc::DeviceBuffer<...>::setCurrentSize' differs by a const from the base class method declaration.
=> add missing const in method override

src/libPMacc/include/algorithms/math/doubleMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/floatMath/floatingPoint.tpp
The operator() of struct Float2int_rd<float> is used to convert the incoming float to an integer.
This should be reflected by the code.
=> fix wrong return type in Float2int_rd

src/cuda_memtest/CMakeLists.txt, src/cuda_memtest/cmake/FindNVML.cmake, src/cuda_memtest/cuda_memtest.cu, src/cuda_memtest/cuda_memtest.h, src/cuda_memtest/misc.cpp, src/cuda_memtest/misc.h, src/cuda_memtest/tests.cu
Close #584
- removes the "nvidia-smi", "grep" and "gawk" calls
- adds optional support for `libnvidia-ml` ([NVML](https://developer.nvidia.com/nvidia-management-library-nvml)) which is either part of the driver or the `gdk` ([GPU Deployment Kit](https://developer.nvidia.com/gpu-deployment-kit)) to:
- measure the device temperature
- get the device serial number (by `index`, let's hope it is the same index as in cuda for now - else we have to use the [PIC bus id](http://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1gcfea8661435e6a8f26485c5c42eadd2f) if that works for 2-chip cards like K80)
- adds initial support for 8 GPUs/node (previous config was 4 GPUs) but needs additional testing
- thanks to @jirikraus for the support and initial hint to use …
=> Close #584 Memtest Without External Tools

src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, src/picongpu/include/plugins/hdf5/restart/LoadSpecies.hpp
- fix #609 particle read during restart hangs if some GPUs have no particles and others do
=> Fix #609 Restarts with Full/Empty GPUs

doc/INSTALL.md, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp
Radiation causes a compile error since it is not consequently disabled on missing hdf5.
=> Fix Radiation: No HDF5

src/picongpu/submit/hypnos/picongpu.profile.example, src/picongpu/submit/taurus/picongpu.profile.example
- use `TBG_` environent variables for `-s` and `-t` (feature from #613)
- update hypnos modules to recent `libSplash`/`HDF5` und `cmake 3.0.1`
=> Taurus/Hypnos: Update Examples with new TBG Hints

examples/Empty/cmakeFlags
The empty example ensures that the reference files in `src/picongpu/include/simulation_defines/` are all in valid syntax.
The `empty` files are needed for git to check in the not-empty-anymore directories.
=> Add an Empty Example

src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/hypnos/fermi_profile.tpl, src/picongpu/submit/hypnos/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos/k20_profile.tpl, src/picongpu/submit/hypnos/k20_vampir_profile.tpl, src/picongpu/submit/hypnos/k20_wait_profile.tpl, src/picongpu/submit/hypnos/picongpu.profile.example
`Hypnos` environment updates:
- add `grcat` example (picongpu.profile: development) 	
- add `export MY_MAIL` for email delivery (picongpu.profile)	
- add `k20f` queue (2x4 C2070)
- add `mallocmc/2.0.1` (picongpu.profile: development)
`Bash` environment update:
- forward `LD_LIBRARY_PATH` in `mpirun` template, too
**Note:** we might add `mallocMC` later on via [git subtree](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) directly in `libPMacc` to keep the dependencies/install barriers low.
=> Hypnos: grcat, fermi, mails

src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/CountParticles.hpp, src/picongpu/include/plugins/EnergyFields.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/plugins/common/txtFileHandling.hpp
This avoids loosing the data before the restart, basically the same implementation as #540.
- code clean up: "frequency" is a period, `#pragma once`
- refactored common code, also in `BinEnergyParticles`
=> Add Restart For CountParticles, EnergyFields & EnergyParticles

src/libPMacc/include/nvidia/memory/MemoryInfo.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
SoC-like boards share the same memory for the device and host. Since we still do double buffering, we should only reserve *half* of the available "device" memory for particles.
Add `8` for `MEMORY` to `PIC_VERBOSE`, e.g.:
```bash
$PICSRC/configure -a sm_35 -c"-DPIC_VERBOSE=9" ../paramSets/lwfa
```
Still needs run time testing:
Also:
=> Fix #631 Allocation Of Memory On Jetson Boards

src/picongpu/include/simulationControl/MySimulation.hpp
- still allows to specify *less* arguments
- avoids segfault on "too many" arguments (more are ignored)
related to #637 but does not cause the issue
=> Parse gridDist: Avoid Out-of-Bounce Access

src/libPMacc/include/communication/CommunicatorMPI.hpp, src/libPMacc/include/communication/ICommunicator.hpp, src/libPMacc/include/mappings/simulation/GridController.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp
- call `setNumSlides(...)` only if movingWindow is active, since this function redistributes the y-offsets (intentionally)
=> Fix #637 Restart y-direction --gridDist

doc/INSTALL.md, src/picongpu/CMakeLists.txt, src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
Remove work-around introduced with #611 and force fixed libSplash version
- the work around was valid but is not needed any more (as of [libSplash 1.2.4](https://github.com/ComputationalRadiationPhysics/libSplash/pull/150))
- simplify code-base again
the update of all CMake files (even for tools) is a bit opportunistic of me, sry for that.
=> Fix #609 Splash NULL Reads

src/libPMacc/include/dataManagement/DataConnector.hpp, src/libPMacc/include/eventSystem/Manager.hpp, src/libPMacc/include/eventSystem/streams/StreamController.hpp, src/libPMacc/include/eventSystem/tasks/Factory.hpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp, src/libPMacc/include/mappings/simulation/EnvironmentController.hpp, src/libPMacc/include/mappings/simulation/Filesystem.hpp, src/libPMacc/include/mappings/simulation/GridController.hpp, src/libPMacc/include/mappings/simulation/SubGrid.hpp, src/libPMacc/include/memory/buffers/GridBuffer.hpp, src/libPMacc/include/nvidia/memory/MemoryInfo.hpp, src/libPMacc/include/particles/tasks/ParticleFactory.hpp, src/libPMacc/include/pluginSystem/PluginConnector.hpp
fix `warning: extended friend syntax is a C++11 feature` by adding class key word
This warning was announced from @ax3l in #630.
Reverence:
https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/introduction_to_the_c_11_feature_extended_friend_declaration3?lang=en
=> fix extended friend syntax

src/picongpu/include/plugins/radiation/Radiation.hpp
This pull request fixes a bug caused by the *radiation plugin* if:
- the radiation plugin is active: `#define ENABLE_RADIATION 1`
- the plugin is not used: no `--radiation_e.period 1`
- checkpoints are created: `--checkpoints 5000`
Under these conditions, a checkpoint for the radiation should be written, but no memory for the data is allocated causing a **segfault**.
This pull request now **checks if the radiation plugin is called before writing and reading checkpoints**.
*The code has been tested and is running fine with radiation and checkpoints on, but no radiation calculation active.*
Thanks to @psychocoderHPC and @ax3l for pointing in the right direction. :+1:
Background information:
This bug was introduced with #419 and is in `dev` since 2014-12-21. It does not affect the `master`.
=> Fix Segfault Checkpointing Radiation Plugin

README.md
- The 2 links that were supposed to point to the milestones resulted in a 404-Error.
- Links now to the same place as the entry in [`CHANGELOG.md`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/CHANGELOG.md)
- alternatively, could link to [all milestones](https://github.com/ComputationalRadiationPhysics/picongpu/milestones)
=> Updated wrong link in README.md

src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp
fix wrong offset calculation for three dimensional device buffer
*This bug effects all released versions but has no effect, because we never used `getPointer()` for three dimensional device buffers.*
=> fix `DeviceBuffer<*,DIM3>::getPointer()` calculation

src/libPMacc/include/particles/ParticlesBase.kernel
- the last frame in the supercells was never removed because of the [short circuit usage](http://en.wikipedia.org/wiki/Short-circuit_evaluation)
`... = isValid && ...;`
- the effect of this bug is a larger memory foot print of an empty (zero particles) supercell
*This bug effects all previous releases but is not critical!*
=> Frames: Reduce Empty Supercell Memory Foot Print

src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Part of @BeyondEspresso changes for the TWTS implementation in the original pull #597.
The bg fields are now still available during the plugin/output phase for easier debugging.
A follow up could write the background fields to an independent output field.
=> Add BG Fields in Plugins

src/picongpu/include/plugins/BinEnergyParticles.hpp
**Workaround to avoid wrong overflow**
This pull request solves issue #570.
It introduces a branch divergence to avoid an yet unexplained error in the binning algorithm.
If not used, the overflow count will go in the underflow bin and the overflow bin will contain zero.
=> workaround - overflow BinEnergy

src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
This pull request fixes the **CUDA 6.5 int(bool) bug**(#570) in the **phase space plugin**.
It uses *short if notation* (`bool condition ? true return : false return`) to avoid the `int` cast of bool values bug in CUDA 6.5.
=> fix CUDA6.5 int(bool) bug in PhaseSpace

src/libPMacc/include/cuSTL/algorithm/kernel/Reduce.hpp, src/libPMacc/include/cuSTL/algorithm/mpi/Gather.hpp, src/libPMacc/include/cuSTL/algorithm/mpi/Reduce.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/IndexBuffer.hpp, src/libPMacc/include/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp, src/libPMacc/include/cuSTL/container/compile-time/CartBuffer.hpp, src/libPMacc/include/cuSTL/cursor/navigator/BufferNavigator.hpp, src/libPMacc/include/cuSTL/zone/StaggeredZone.hpp, src/libPMacc/include/math/Vector.hpp, src/libPMacc/include/math/vector/UInt32.hpp, src/libPMacc/include/math/vector/UInt64.hpp, src/libPMacc/include/math/vector/compile-time/UInt32.hpp, src/libPMacc/include/math/vector/compile-time/UInt64.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp, src/picongpu/include/plugins/SliceFieldPrinter.tpp
The libPMacc vectors such as `Int` and `UInt` use implicit (machine-dependent) vector sizes.
This pull tries to refactor that.
=> Refactor libPMacc UInt Vectors

src/picongpu/include/plugins/adios/ADIOSCountParticles.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp
`defineAdiosVar` caused a down-cast to 32bit for counter attributes such as offsets.
That caused problems with counters and offsets for particles, that are traditionally stored in a long 1D array and can exceed the size of uint32_t (the base type of `DataSpace<DIM>`) easily.
First spotted by @psychocoderHPC - thanks!
=> Fix #663 ADIOS Avoid 32bit Down-Cast

src/picongpu/include/plugins/adios/ADIOSWriter.hpp
`GridController` was used to get number of MPI processes before it was initialized.
- set number of aggregators to `mpi size` if not defined by the user
- remove `GridController` usage in ~~`pluginLoad()`~~ `pluginRegisterHelp()`
=> fix adios number aggregator default

src/picongpu/submit/hypnos/k20_autoWait_profile.tpl
This pull request fixes a bug introduced with commit ~~[`d0a80a3`](https://github.com/PrometheusPi/picongpu/commit/d0a80a3c043fd83902863ba1f38b998304861483)~~ ff14d8855dd67320fa109f05d78d8df39b769f33.
The `TBG_waitJob` variable was removed and is now added again.
=> fix k20_autoWait_profile.tpl

examples/Bunch/include/simulation_defines/param/physicalConstants.param, examples/KelvinHelmholtz/include/simulation_defines/param/physicalConstants.param, examples/LaserWakefield/include/simulation_defines/param/physicalConstants.param, examples/WeibelTransverse/include/simulation_defines/param/physicalConstants.param, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp, src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/simulation_defines/param/physicalConstants.param
Energy for particles with only non-relativistic energies was zero.
since the magic number `1.005` for gamma values "close to 1.0" is used the third time now, I exposed that number in `physicalConstants.param` now (second commit).
also: we still have that ugly "bump" in `BinEnergyParticles` since the round-off around `1.005` is hard to control for adjacent bins.
=> Fix Particle2Grid: Non-Relativistic Particle Energy

src/libPMacc/include/Environment.hpp
On multi gpu cluster nodes without `default` compute mode the device is normally selected by the gpu driver with the first cuda call.
It might be that this is not the case if the first call is `cudaStreamCreate`. 
In this case streams are created on the wrong device. This breaks our event system and triggers random crashes.
*This error was seen with CUDA 7.0rc, but it might be that it was not checked by the driver before.*
**Solution:**
- set device explicitly independent of the compute mode
**Tests**
=> fix device selection BUG

src/picongpu/include/plugins/adios/ADIOSCountParticles.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttribute.hpp, src/picongpu/include/plugins/output/WriteSpeciesCommon.hpp
If some of the processes write zero amount of data with
adios they hang.
Changes:
- take care that all processes call collective adios write methods
- all processes calculate it's adios index table
- set freed memory to `NULL`
- move calculation of domain sizes before `forEachCollectFieldsSizes` and `adiosCountParticles`
Tests:
Why is this pull request blocked:
- ~~during the third dumps we got a warning: `adios_group_size (data): Not buffering. needs: 314532206 available: 114294784.`~~
- ~~during the third dump the adios plugin hangs ( 2 of 8 processes)~~
=> Fix ADIOS: Zero Writes, Collects and Buffers

src/tools/bin/plotNumericalHeating
This pull request adds a python program that can compare the energy evolution and thus the numerical heating of two PIConGPU simulation runs.
Writing a seperate tool for this task was suggested by @ax3l in #657.
The program has the following features:
- help via `--help` or `-h`
- auto check existence of directories and files
- checks that dump period is equal for all output files
- creates a plot with labels, legend, etc.
- optional: use other lables as `dev` and `branch`
- forbids *cheating* by comparing the same results :smiling_imp:  
I tested it with the last numerical heating run and it works fine with `python/2.7.8` on `hypnos`.
=> add analyzer tool for numerical heating

src/picongpu/include/plugins/output/header/MessageHeader.hpp
use `__deleteArray` to free memory
=> fix MessageHeader, wrong array deletion

src/picongpu/include/algorithms/ShiftCoordinateSystem.hpp
This pull request ~~fixes~~ avoids the CUDA6.5 int(bool) #570 bug in `src/picongpu/include/algorithms`.
(as suggested by @psychocoderHPC, the CUDA6.5 fixes will come in seperate pull requests depending on the code they affect.)
=> fix CUDA6.5 int(bool) bug in algorithms

src/picongpu/include/particles/Particles.kernel
This pull request solves the CUDA6.5 `int(bool)` bug (#570) in `Particles.kernel`.
In order to work with the bool arrays of size `simDim`, `for` loops were used. These also avoid using *ugly* pre-compiler `#if`.
**TO DOs:**
=> fix CUDA6.5 int(bool) bug in particle kernel

src/picongpu/include/plugins/hdf5/writer/Field.hpp
the index names in `hdf5/writer/Field.hpp` are not ideal (even if the implementation is correct): once `d` is used as an index `[0; simDim-1]` and once as an index `[0; nComponents-1]` and same mixed with `i`.
we now use `n` consequently for vector components (x, y, z and w) of fields and `d` for *spatial* counts from `0` to `simDim-1`. `i` is only used if we iterate over linear memory.
=> HDF5 WriteField: Fix Wrong Doc String and Index

src/picongpu/include/plugins/output/images/PngCreator.hpp
- increases file by about 12%
- decreases time for write_png() call by ~2.3x
- part of optimizations in #693
=> PNG Plugin: Use less compression

src/picongpu/include/plugins/hdf5/restart/RestartFieldLoader.hpp
**Fix #688 2D Restart Fields**: in 2D simulations, the last component (z) of FieldE and FieldB was not initialized again (default: zero).
**unrelated:**
- wrong docs string and index names in `hdf5/writer/Field.hpp` -> extra pull #690
the index names in `hdf5/writer/Field.hpp` are not ideal (even if the implementation is correct): once `d` is used as an index `[0; simDim]` and once as an index `[0; nComponents]` and same mixed with `i`.
=> Fix #688 2D Restart Fields

src/cmake/FindPNGwriter.cmake
The message on PNGwriter "NOT FOUND" was wrong, this fixes it.
**As a background information:**
Traditionally, the environment vars controlling a cmake module are all upper case, such as PNGWRITER_ROOT, BOOST_ROOT.
On the other hand cmake variables are internally used case sensitive, such as PNGwriter, Boost, ...
=> FindPNGwriter: Fix misleading Not-Found Message

src/tools/bin/plotNumericalHeating
With this pull request the `plotNumericalHeating` tool  supports any number of species (#684).
It goes through the `simOutput` directory and looks for `Energy*.dat` files with first row *time* and second row *energy*. 
I've tested it with some nonsense files and it worked fine.
=> Close #684 Heating Analyser for Multi Species

examples/LaserWakefield/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSI.hpp, src/picongpu/include/particles/ionization/ionizationEnergies.param, src/picongpu/include/particles/traits/GetAtomicNumbers.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param
Here is another topic concerning **multiple species** and **ionization**. 
This PR adds a ***flag for proton and neutron number*** of the ion species.
In detail:
- flags `protonNumber` and `neutronNumber`
- traits `GetProtonNumber` and `GetNeutronNumber`   
(these contain a `static_assert` which is thrown if someone tries to get these numbers from, say, electrons)
- ionization algorithm has been edited to ionize until `chargeState` = `protonNumber`
- ionization is now always active if ions are enabled (deactivate by deleting the flags)
(everything until *Make proton/neutronNumber a float* is safe)
=> Flag for proton and neutron number

src/picongpu/include/plugins/common/txtFileHandling.hpp
This pull request solves issue #702:
If we add plugin calls via command line after a restart, checkpoint files for the plugin do not exists thus crashing PIConGPU during the attempt to copy checkpoint files to output files.
This pull request now checks whether a checkpoint file exists. If it does, everthing is handled as before. If the required checkpoint file does not exist, a warning is printed and we just start with data output from the restart point. PIConGPU does not crash anymore.
**To Do:**
=> Fix #702 Activate new plugins after restart

doc/TBG_macros.cfg
That flag is needed pretty often and it should be documented at `doc/TBG_macros.cfg` too that it needs to point to `<run>/simOutput/checkpoints`.
Wiki article, as linked some lines above in that file: http://git.io/PToFYg
=> TBG Macros: Add Restart Dir

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSI.hpp, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/particles/ionization/ionizationMethods.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/simulation_defines/unitless/speciesDefinition.unitless, src/picongpu/include/traits/attribute/GetCharge.hpp, src/picongpu/include/traits/attribute/GetChargeState.hpp
In this PR the following has been refactored:
- remove attribute `chargeState`, add `boundElectrons`
- add trait `GetChargeState.hpp`
- replace all uses of `chargeState` with `boundElectrons`
=> Remove attribute chargeState, add boundElectrons

src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/Unit.hpp
Is this small change how the comments on the unitless flags should look like and should the other ones also get more comments? 
I also changed the indents from 2 spaces to our 4 space standard. Was that correct?
=> Close #707 Document Unit Trait for Plain Numbers

src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp
- `particlesOffset` are element offsets in the *global* particle attribute array (that can be more than `uint32_t` / `size_t`)
- `elements` are promoted to `uint64_t` too for convenience
- very similar to the unholy #666 bug
=> Fix #719 Restart HDF5: Avoid 32bit Downcast

src/picongpu/include/particles/Particles.hpp
remove unused `curandState* randState`
=> remove unused member variable

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param
In #687 I did not prevent the introduction of ~~Hydrogen~~"Helium" for the LWFA example.
That is actually wrong so far, since correct ~~hydrogen~~helium would require to increase either the number of initialized electrons or their weighting. Also, the constants in `physicalConstants.param` do not agree for that species.
So far, the proton/neutron number is only an attribute - partly used for the BSI models - but it should be still consistent for each example.
=> Fix LWFA Example: Keep Hydrogen

src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
This pull request fixes the CUDA 6.5 `int(bool)` bug in the Esirkepov current deposition scheme.
The changes applied also changed a workaround of a [CUDA5.5+ bug](https://devtalk.nvidia.com/default/topic/752200/cuda-programming-and-performance/nvcc-loop-bug-sin%5Cce-cuda-5-5) found and implemented by @psychocoderHPC. Therefore, we have to carefull check if the *CUDA5.5+ unroll bug* is now in again. 
Between `dev` and `fix-04boolBugCUDA6.5` for both `2D` and `3D` we need to:
Full list of current work arounds for CUDA bugs: #652
=> fix and refactor CUDA bugs in Esirkepov

src/libPMacc/include/math/Tuple.hpp
With the new taurus config today (#622), it was a bit hard to find a corresponding [cuda/intel/boost combination](https://gist.github.com/ax3l/9489132) but I found a very recent one.
- `intel/2013-sp1` (aka intel 14.0)
- `boost/1.57.0-intel2013-sp1`
- `cuda/6.5.14`
This pull already fixes a problem in `src/libPMacc/include/math/Tuple.hpp` where `mpl::integral_c` from `<boost/mpl/integral_c.hpp>` was missing an include.
@psychocoderHPC Do you know why you used the `mpl_` namespace instead of `mpl::` for the integral type? it jammed with that, too so I changed it to the regular namespace.
I can not say if it affects `master` since boost 1.56+ is in it yet not supported in it. Anyway, since `icc` support is still experimental there is no need to backport it, we can simply fix it in `dev` and …
=> Tuple: correct boost mpl namespace

src/libPMacc/include/eventSystem/events/kernelEvents.hpp
I found `PMACC_BLOCKING_KERNEL` to be way more useful when adding that line.
Probably it should be added above with `CUDA_CHECK_KERNEL_MSG` instead but this pull is a reminder that useful CUDA error message may not be delivered directly but only at the end of the sim.
Example:
```
picongpu/include/fields/FieldJ.tpp>:247
[1,0]<stderr>:terminate called after throwing an instance of
'std::runtime_error'
[1,0]<stderr>:  what():  [CUDA] Error: too many resources requested for
launch
```
-> btw: the `FieldJ` error can not be reproduced by me or @psychocoderHPC any more. so no need to open an issue.
=> blocking/sync_kernel: getLastError

examples/WeibelTransverse/include/simulation_defines/param/physicalConstants.param, src/picongpu/include/plugins/radiation/calc_amplitude.hpp, src/picongpu/include/simulation_defines/param/physicalConstants.param
This pull requests moves the threshold *magic number* used in `calc_amplitude.hpp` to `physicsConstants.param` where we started to store numerical thresholds since #669.
=> add threshold radiation gamma to params 

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.tpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp
fix #743 *MovingWindow: out of memory after slide*
- move `picongpu::Particles::reset()` to `PMacc::ParticlesBase`
- `ParticlesBase`: add method `deleteParticlesInArea`
Tests:
=> Fix #743 moving window out of mem

src/libPMacc/include/math/vector/Vector.tpp
fix #736 `precisionCast` implementation for `PMacc::math::Vector<...>`
=> close #736 cast CONST_VECTOR

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
This change allow to store a particle in global/shared memory.
- store pointer to the parent frame instead of a reference
- add alignment for member variables
**There is no disadvantage in simulation runtime or register usage**
=> change internal `particle` representation

src/libPMacc/include/memory/boxes/MultiBox.hpp, src/libPMacc/include/memory/boxes/PitchedBox.hpp, src/libPMacc/include/particles/memory/boxes/ExchangePushDataBox.hpp, src/libPMacc/include/particles/memory/boxes/PopDataBox.hpp, src/libPMacc/include/particles/memory/boxes/PushDataBox.hpp, src/libPMacc/include/particles/memory/dataTypes/SuperCell.hpp
In some cases were a pointer is equivalent to a reference the nvcc compiler can better optimize the code if the aligned pointer is defined as last member in a class/struct.
This pull request reduce the register and stack frames in some kernel e.g.
before:
```
[0mptxas info    : Function properties for _ZN5PMacc14kernelSetValueINS_7DataBoxINS_10PitchedBoxINS_9SuperCellINS_5FrameINS_15ParticlesBufferINS_19ParticleDescriptionIN5boost3mpl6stringILi101ELi0ELi0ELi0ELi0ELi0ELi0ELi0EEENS_4math2CT6VectorIN4mpl_10integral_cIiLi8EEESG_NSF_IiLi4EEEEENS8_6v_itemIN8picongpu24placeholder_definition179weightingENSJ_INSK_24placeholder_definition158momentumENSJ_INSK_24placeholder_definition128positionINSK_24placeholder_definition1412position_picENS_24placeholder_definition1113pmacc_isAliasEEENS8_7vector0IN …
```
=> move member pointer to end of the class

src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp
- if `mallocMC::malloc` return NULL, retry 13 times to allocate memory
- write warning/error if we detect out of memory
If we can not allocate memory after 13 tries *bad things will happen* :-)
close #753
This pull request not implement the detection with a mallocMC OOM-Policy because retry the malloc call is not possible in a OOM-Policy.
**Tests:**
=> close #753 add out of memory message

src/picongpu/include/plugins/PhaseSpace/PhaseSpace.tpp
fix #749
solve warning by explicit call of `operator()` with the hint (for the compiler) that it uses template
**~~Do not merge before~~ #748**
=> close #749 warning in `PhaseSpace` plugin

src/tools/bin/plotNumericalHeating
This pull requests improves the graphics of the `plotNumericalHeating` tool as suggested by @psychocoderHPC .
The new look can be seen here:
Compare this to [the following plot](https://github.com/ComputationalRadiationPhysics/picongpu/pull/730#issuecomment-77185517) where the small scale oscillation of `branch` is not visible due to the dashed line.
=> improve graphics of numerical heating tool

src/picongpu/include/plugins/radiation/Radiation.hpp
This pull requests removes the text based unit output of the radiation plugin and adds the unit conversion factor as hdf5 attribute.
The attribute is stored in `/custom`.
=> Radiation Plugin: add unit as attribute to HDF5

examples/Bunch/include/simulation_defines/param/componentsConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/componentsConfig.param, examples/LaserWakefield/include/simulation_defines/param/componentsConfig.param, examples/SingleParticleCurrent/include/simulation_defines/param/componentsConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/componentsConfig.param, examples/SingleParticleTest/include/simulation_defines/param/componentsConfig.param, examples/ThermalTest/include/simulation_defines/param/componentsConfig.param, examples/WeibelTransverse/include/simulation_defines/param/componentsConfig.param, src/picongpu/include/simulation_defines/param/componentsConfig.param
This pull request adds the missing `laserPolynom` to `componentsConfig.param`. 
@ax3l:
This pull request adjusts `componentsConfig.param`.
=> add laserPolynom as option to `componentsConfig.param`

examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param
This pull request adjusts `DELTA_T_SI` to improve the Courant-Friedrichs-Lewy condition depending on the dimension of the simulation `SIMDIM`. It closes issue #763. 
For 2D we now get:
```
PIConGPUVerbose PHYSICS(1) | Courant c*dt <= 1.00204 ? 1
```
For 3D we now get:
```
PIConGPUVerbose PHYSICS(1) | Courant c*dt <= 1.00556 ? 1
```
=> adjust DELTA_T_SI depending on SIMDIM to improve the CFL condition

thirdParty/cuda_memtest/cuda_memtest.cu, thirdParty/cuda_memtest/cuda_memtest.h, thirdParty/cuda_memtest/tests.cu
Follow-Up to #759: Update `thirdParty/cuda_memtest` with latest changes from it's [upstream](https://github.com/ComputationalRadiationPhysics/cuda_memtest) repo.
Includes:
- https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/1 (replace deprecated cuda calls in cuda_memtest)
Update performed via:
```bash
git subtree pull --prefix thirdParty/cuda_memtest/ \
```
=> Topic update cuda memtest

examples/Bunch/include/simulation_defines/param/radiationObserver.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationObserver.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationObserver.param, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/amplitude.hpp, src/picongpu/include/plugins/radiation/calc_amplitude.hpp, src/picongpu/include/plugins/radiation/nyquist_low_pass.hpp, src/picongpu/include/plugins/radiation/parameters.hpp, src/picongpu/include/plugins/radiation/particle.hpp, src/picongpu/include/plugins/radiation/radFormFactor.hpp, src/picongpu/include/plugins/radiation/taylor.hpp, src/picongpu/include/simulation_defines/param/radiationObserver.param, src/picongpu/include/simulation_defines/unitless/radiationConfig.unitless
This pull request **replaces** the float types used in the radiation plugin by standard PIConGPU types and it **renames** the vector classes  as suggested by @psychocoderHPC in issue #697. 
- `numtype1` -> `picongpu::float_32`
- `numtype2` -> `picongpu::float_64`
- `vec1` -> `vector_32` 
- `vec2` -> `vector_64`
**ToDo:**
**Notice:**
@ax3l This pull request adjusts `*.param` and `*.unitless` files.
=> close #697: fix radiation types

src/picongpu/include/simulationControl/MySimulation.hpp
fix that restart loads particle from hdf5 and use `InitPipeline` to create particles
This bug only applies `dev` since #730 *add multi species gas functors*
Thanks to @BeyondEspresso
=> fix broken restart

examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPlaneWave.hpp, src/picongpu/include/fields/laserProfiles/laserPolynom.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp, src/picongpu/include/fields/laserProfiles/laserWavepacket.hpp, src/picongpu/include/simulation_defines/param/laserConfig.param, src/picongpu/include/simulation_defines/unitless/laserConfig.unitless
This pull request adds a **phase** to **all laser** implementation thus allowing to run simulations suggested by @ssstuvz.
**ToDo:**
check if setting phase works for:
@ax3l:
This pull request adjusts:
- `laserConfig.unitless`
- `laserConfig.param`
and thus needs an entry to the `CHANGELOG.md` after it is merged to `master`.
=> add phase to all laser implementations

src/tools/bin/plotNumericalHeating
This pull request fixes a bug found by @psychocoderHPC in the `plotNumericalHeating` tool. It occures, when `dev` and `branch` energies deviate strongly.
With this fix, the **following rules** are applied for coloring:
- `red` ... means *worse* energy conservation in `branch` than in `dev`
- `orange` ... means *better* energy conservation in `branch` than in `dev`
**Example 1:**
**`dev`:**
**`pull request`:**
**Example 2:**
**`dev`:**
**`pull request`:**
=> fix logic behind fill color of numerical heating tool

src/picongpu/include/fields/laserProfiles/laserPolynom.hpp
This pull request unifies the float types used in `laserPolynomial`.
It closes issue #775.
Differences are in the float precission.
=> Close #775: laser polynom - convert float_64 to float_X

src/mpiInfo/main.cpp
- errored on Titan (ORNL) with GCC 4.8.2 in cross-compile mode
=> Add Missing <iostream> include

examples/Bunch/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/SingleParticleCurrent/include/simulation_defines/param/species.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/species.param, examples/SingleParticleTest/include/simulation_defines/param/species.param, src/picongpu/include/fields/currentDeposition/ZigZag/EvalAssignmentFunction.hpp, src/picongpu/include/particles/shapes.hpp, src/picongpu/include/particles/shapes/P4S.hpp, src/picongpu/include/simulation_defines/param/species.param
- add assignment shape P4S called *piecewise biqudratic spline*
- add explicit rules for the shape `P4S` evaluation for the current solver `ZigZag`
**Tests:**
thx @PrometheusPi for giving me a lesson in `mathematica`
=> assignment shape piecewise biqudratic spline `P4S`

src/tools/bin/tbg
Fix #795: Check if the `mkdir` commands are successful.
If not, abort.
=> Fix #795 TBG Exit on mkdir Error

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/windowFunctions.hpp, src/picongpu/include/simulation_defines/param/radiationConfig.param
This pull request:
- enables using window function in 2D now
- removes the precompiler flag used to enable the window function
- replace `radWindowRectangular` with faster `radWindowNone` and use this as default
Needs to be checked:
=> add radiation window function for 2D/3D

src/libPMacc/include/math/vector/Vector.hpp, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, src/picongpu/include/plugins/adios/restart/LoadSpecies.hpp, src/picongpu/include/plugins/adios/restart/RestartFieldLoader.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttribute.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp
Close a point from #56.
- adds checkpointing and restart via ADIOS
- prefers ADIOS over HDF5 if both are found (for checkpointing/restarting)
- ~~unifies some logs to be coherent with HDF5/ADIOS~~
=> ADIOS Checkpoint/Restart Capability

src/libPMacc/include/math/vector/compile-time/Vector.hpp
allow that non integral types can be stored in `PMacc::math::CT::vector`
=> extend CT::vector

src/picongpu/CMakeLists.txt
close #769 **Ubuntu: libPMacc not found by CMake (system `types.h`)**
use hard coded path to `PMacc` to avoid wrong detection by using cmake `find_path`
=> fix #796 wrong PMacc path detection

src/tools/bin/egetopt
fix #694 `tbg -s "qsub -h"` was broken
- quote all non options
- call `getopt` via `echo "command" | bash`
=> fix #694 tbg wrong quoting interpretation

src/libPMacc/include/eventSystem/events/EventPool.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.tpp, src/libPMacc/include/mappings/kernel/MappingDescription.hpp, src/libPMacc/include/simulationControl/SimulationHelper.hpp
The CUDA includes in these files are not necessary because those classes neither use any CUDA methods nor data types.
=> remove superfluous CUDA includes

src/libPMacc/include/algorithms/math/doubleMath/sqrt.tpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/sqrt.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
change MSVC compatibility for host and device
```C++
#if defined(_MSC_VER)
```
to host only
```C++
#if defined(_MSC_VER) && !defined(__CUDA_ARCH__)
```
Discussion see #816.
=> use intrinsics in CUDA code with MSVC

src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp
- fix wrong velocity for for z-flux calculation
The zigzag implementation split all particle trajectories for any direction in two independent trajectories.
The current implementation also need to does it for the z-direction in 2D, therefore the velocity must halved.
affects simulations only **all** of the following applies:
- 2D3V simulations with a *relevant* component **v.z** (e.g., a warm plasma)
- `ZigZag` solver was used for charged species
=> fix 2D zigzag z-flux calculation

src/picongpu/include/particles/gasProfiles/GaussianCloudImpl.hpp
fix that exponent is not set-able *per direction*
- fix that `float_X` is assigned to `floatD_X`
- fix `int` to `float_X` assign
=> fix assign bug in `GaussianCloudImpl`

src/libPMacc/include/memory/dataTypes/Mask.hpp
add explicit int cast to avoid compiler warnings
=> add missing int cast

src/picongpu/include/particles/ionization/ionization.hpp
This small commit removes unused global memory reads and writes from `ionization.hpp`
close #822 *Ionization: unused memory read and write*
=> close #822 Remove unused memory access

src/tools/bin/plotNumericalHeating
This pull request
- fixes #811 which was caused due to an array like structure of the normalization after adjusting the start energy introduced with #779
- fixes a wrong indentation introduced from start
=> close #811: numerical heating tool wrong normalization 

src/picongpu/include/plugins/radiation/Radiation.hpp
This pull request enables compression vor the hdf5 ouput created by the radiation plugin.
Since it is using the `serialDataCollector` of `libSplash`, using compression is possible.
Still to test/decide:
=> enable compression for radiation hdf5 output

src/libPMacc/include/math/vector/math_functor/abs.hpp
=> add abs functor to libPMacc

examples/Bunch/include/simulation_defines/param/speciesInitialization.param
With the new particle initialization scheme #730, the electrons of the `Bunch` example were missing their non-zero momentum.
This pull request fixes the missing momentum initialization.
=> add electron momentum initialization

examples/Bunch/include/simulation_defines/param/fieldBackground.param, src/picongpu/include/fields/background/templates/TWTS/BField.hpp, src/picongpu/include/fields/background/templates/TWTS/BField.tpp, src/picongpu/include/fields/background/templates/TWTS/EField.hpp, src/picongpu/include/fields/background/templates/TWTS/EField.tpp
This update includes the new feature of a TWTS laser, which now can be also polarized within the plane of the pulse-front tilt (in-plane) instead of normal polarization. This option can be controlled with an (optional) flag in the interface. The laser pulse has been extensively tested, both analytically and numerically.
Furthermore, this update fixes some variable normalization bugs, as well as some obscure, crippling arithmetic issues between double and single precision calculations. This means now, single precision calculations also deliver correct results and have the benefit of a 4-5 times speed-up in time step performance within vacuum. Have fun! :smile:
=> [BG fields] Add in-plane polarization to TWTS laser

src/libPMacc/include/math/ConstVector.hpp
split the creation of `ConstVector` definition and instantiation
- add macro `PMACC_STATIC_CONST_VECTOR_DIM_INSTANCE`
- add macro `PMACC_STATIC_CONST_VECTOR_DIM_DEF`
- add macro `PMACC_CONST_VECTOR_DEF`
**This pull request is fully backward compatible to the old version**
=> split `ConstVector` definition and instantiation

src/picongpu/submit/hypnos/k80_profile.tpl
add K80_profile.tpl
**The new k80 submit template need the picongpu.profile from #861**
The file `k80_profile.tpl` is a copy of `k20_profile.tpl` with the following changes:
- change queue to k80
- set `TBG_gpusPerNode` to 8
=> add k80 submit template for hypnos

src/picongpu/submit/hypnos/fermi_profile.tpl, src/picongpu/submit/hypnos/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos/k20_profile.tpl, src/picongpu/submit/hypnos/k20_vampir_profile.tpl, src/picongpu/submit/hypnos/k20_wait_profile.tpl
If a fewer amount of gpu's were used as in a node exists `cuda_memcheck` crashed if another process already used the gpu with `ID=0`. To avoid this we always reserve nodes exclusive.
- add option `-n` (exclusive node reservation) to hypnos submit templates
=> add exclusive node reservation for hypnos

src/picongpu/submit/hypnos/picongpu.profile.example
- update openmpi to `1.8.4.kepler` (k20/k80 compatible)
- update adios to `1.8.0` and correct module name
- update libsplash to `1.8.0`
=> update hypnos `picongpu.profile.example`

src/picongpu/include/fields/laserProfiles/laserPlaneWave.hpp
Due to the arbitary length of our laser envelope and the arbitary phase, the integral along the propagation direction of the plane wave might not be zero.
By deriving the electric field from a scalar potential, this pull request ensures that the electric field vanishes if integrated from -infinty to +infinity.
Thanks @ssstuvz for telling us about this error.
with ![f2](https://cloud.githubusercontent.com/assets/1353258/7417908/d5555630-ef69-11e4-9008-1695a992a7f7.png)
=> avoid non zero E-field integral in plane wave

doc/TBG_macros.cfg, examples/Bunch/submit/bunch_0032.cfg, examples/SingleParticleRadiationWithLaser/submit/0008gpus.cfg, src/picongpu/include/plugins/radiation/Radiation.hpp
This pull request replaces the `po::value<bool >` workaround with [`po::bool_switch`](http://www.boost.org/doc/libs/1_57_0/doc/html/boost/program_options/bool_switch.html).
This simplifies the command line flags of the radiation plugin.
**ToDo:**
**Update:**
Old submit scripts will **not result in a crash of `picongpu`**. 
However,  `--e_radiation.lastRad 0` will be **switch its meaning** and activate `lastRad` while `--e_radiation.lastRad 1` **keeps its meaning** and activate `lastRad` (integer values will be ignored).
=> Add boost bool_switch to radiation plugin

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param
If **ions and radiation** are both used in a setup derived from the `examples/LaserWakefield`, a massiv template error occures which, due to its lengthy error message, is hard to fix. 
This "bug" exists since the creation of `speciesDefinition.param` in this directory on **Jan. 27 2015**.
Thus this pull request adds radiation attributes to the ions to avoid a compile time error.
In a future pull request we should :
- set the automated compile suite up to check if radiation still works for the *Laser Wakefield example* 
- allow radiation plugins only for suited species
=> fix radiation if ions are used in LWFA example

src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/SliceFieldPrinter.hpp, src/picongpu/include/plugins/SliceFieldPrinter.tpp, src/picongpu/include/plugins/SliceFieldPrinterMulti.tpp
2D support for SliceFieldPrinter plugin.
=> Feature SliceFieldPrint 2D

src/picongpu/ArgsParser.cpp, src/picongpu/include/ArgsParser.hpp, src/picongpu/include/simulationControl/ISimulationStarter.hpp, src/picongpu/include/simulationControl/SimulationStarter.hpp, src/picongpu/main.cu
- add command line option `validate`
- `ArgsParser`:
- add enum `ArgsErrorCode`
- change return code of parse from `bool` to `ArgsErrorCode`
- `main.cu`: handle ArgsParser error codes
`validate` validates the command line options without starting the simulation
=> ArgsParser: add `validate` command line option

src/picongpu/include/fields/laserProfiles/laserPlaneWave.hpp
This pull request fixes a bug introduced with #851 introduced two weeks ago.
@stetie and me found it during code comparison between PIConGPU and the Jena code.
Since we define our temporal laser envelope over intensity not over electric field, the correction factor should be
```
tau = PULSE_LENGTH * sqrt(2)
```
**not**
```
tau = PULSE_LENGTH / sqrt(2)
```
=> fix intensity normalization of tau

src/picongpu/include/fields/laserProfiles/laserWavepacket.hpp
Similiar to #851, this corrects the laser pulse formular to account for extra terms arrising from deriving the formular from the vector potential. It ensures the integration along the propagation direction is 0. This is important for few-cycle laser pulses.
=> Fix: Correction to laser pulse formular for few-cycle wavepackets

CHANGELOG.md, src/picongpu/include/simulation_types.hpp, src/picongpu/include/version.hpp
Merge back update from the release branch of the `0.1.0` release.
Performed with
```bash
git merge -Xours mainline/master
```
to avoid introducing changes from hotfixes into `dev`.
Adds:
- Changelog updates
- `src/picongpu/include/version.hpp` (0.1.0)
=> Update `dev` with `0.1.0` Release Updates

src/libPMacc/include/math/ConstVector.hpp, src/libPMacc/include/math/vector/Vector.hpp
The current implementation of `math::Vector<>` takes no care whether the used internal data storage is const (not copyable). This produce compile time errors if a `ConstVector`  from `math/ConstVector.hpp` is used as member in a class and the class is copied.
- add functor CopyElementWise<bool>
- use CopyElementWise in implicit math::Vector copy constructor
**This pull request affects the `master` and the `release-0.1.0` but there is no usage of `ConstVector` as class member.** 
example what kind of code not compiles:
```C++
CONST_VECTOR(float_64, simDim, GaussianCloudParam_center, 1.134e-5, 1.134e-5, 1.134e-5);
struct GaussianCloudParam
{
const GaussianCloudParam_center_t center_si;
};
```
=> math::Vector<...> fix const storage handling

src/libPMacc/include/communication/CommunicatorMPI.hpp
Removes the following warnings (seen in clang and MSVC):
* the counts given to MPI_Isend and MPI_Irecv are implicitly converted from unsigned to signed integer
-> explicit cast
* UpdateHostRank has a local variable with the same name as the class member and returns this value just to be immediately assigned to the member.
-> directly use the class member and do not return a value (correcting the function name from PascalCase to camelCase by the way)
Removes dead code (exit method)
=> remove implicit cast and member shadowing warnings

src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/currentInterpolation/Binomial/Binomial.def, src/picongpu/include/fields/currentInterpolation/Binomial/Binomial.hpp, src/picongpu/include/fields/currentInterpolation/CurrentInterpolation.def, src/picongpu/include/fields/currentInterpolation/CurrentInterpolation.hpp, src/picongpu/include/fields/currentInterpolation/None/None.def, src/picongpu/include/fields/currentInterpolation/None/None.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/param/fieldSolver.param, src/picongpu/include/simulation_types.hpp
This commit adds the general infrastructure to call functors before adding `FieldJ` to the electro-magnetic fields (in `Yee`: before manipulating the `E` field).
The previous method `None` without interpolation is added as a default in `fieldSolver.param`. Additionally, a simple second order Binomial filter for 2D and 3D is added to test the new functionality.
Run time tests:
=> Current Interpolation: During add to EMF

src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.kernel
twist `blockDim` before kernel call
close #889 *DirectionalSplitting not twitstet blockDim*
**Tests:** 
**The bug affects master thus `Directional Splitting` is not well tested I think there is no back port needed**
=> close #889 field solver DS out of memory access

src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/initialization/InitialiserController.hpp
Check for cuda errors to spare the time for writing a checkpoint and also synchronize again afterwards to ensure a checkpoint can really be considered "valid" (not corrupted).
=> Checkpoints: Check for CUDA Errors

src/picongpu/CMakeLists.txt
- move mallocMC find call after `boost` and `cuda` is loaded
If `boost` or `cuda` is not loaded before mallocMC find is called
the module result always `not found`
=> fix that always `thirdParty/malloc` is used

src/libPMacc/examples/gameOfLife2D/include/Evolution.hpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldTmp.kernel, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.kernel, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/ionization/ionization.hpp
=> Fix spelling in `ThreadCollective` instances

thirdParty/mallocMC/INSTALL.md, thirdParty/mallocMC/src/include/mallocMC/mallocMC_hostclass.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_overwrites.hpp
Update thirdParty/mallocMC with latest changes from it's upstream **dev** repo.
- new feature of the upcoming mallocMC 2.2.0crp release 
- added host function to return heap pointer
Update performed via:
```
GIT_AUTHOR_NAME="Third Party" \
GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
git subtree pull --prefix=thirdParty/mallocMC  \
git@github.com:ComputationalRadiationPhysics/mallocMC.git dev --squash
```
=> Topic update mallocMC thirdParty

src/libPMacc/include/eventSystem/Manager.hpp, src/libPMacc/include/eventSystem/Manager.tpp
The full definition of EventPool is not required within Manager.hpp, therefore a forward declaration is enough.
=> use forward declaration of EventPool in Manager.hpp

src/libPMacc/include/eventSystem/tasks/TaskKernel.hpp, src/libPMacc/include/eventSystem/tasks/TaskSetCurrentSizeOnDevice.hpp, src/libPMacc/include/eventSystem/tasks/TaskSetValue.hpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.tpp
Dynamic exception declarations with throw(...) are deprecated.
In C++11 destructors will implicitly be marked noexcept(true).
Therefore the destructor of TransactionManager will have to be declared noexcept(false) then.
=> remove deprecated throw declarations

src/libPMacc/include/eventSystem/Manager.tpp, src/libPMacc/include/eventSystem/tasks/TaskSetValue.hpp, src/libPMacc/include/math/vector/math_functor/abs.hpp, src/libPMacc/include/memory/buffers/Buffer.hpp, src/libPMacc/include/memory/buffers/MultiGridBuffer.hpp, src/libPMacc/include/particles/memory/boxes/PushDataBox.hpp
EDIT (by @PrometheusPi):
ADD: This pull request fixes logical errors, typos and white space issues in the comments.
=> correct spelling in comments

src/libPMacc/include/types.h
EDGE_TO_MASK is only used in IS_EDGE_SET and IS_EDGE_SET is unused, so both can be removed.
TO_BITS is only ever used in BitData.hpp but it has a duplicate definition so the global one can be removed.
=> remove unused defines

src/picongpu/CMakeLists.txt
- remove message if OpenMP can't found
- change cmake internals to lowercase spelling
follow up to #904
=> cleanup OpenMP section in `CMakeLists.txt`

src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/ionization/None/AlgorithmNone.hpp, src/picongpu/include/particles/ionization/None/None.def, src/picongpu/include/particles/ionization/None/None.hpp, src/picongpu/include/particles/ionization/None/None_Impl.hpp, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSI.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI.def, src/picongpu/include/particles/ionization/byField/BSI/BSI.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp, src/picongpu/include/particles/ionization/byField/ionizers.def, src/picongpu/include/particles/ionization/byField/ionizers.hpp, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/particles/ionization/ionizationMethods.hpp, src/picongpu/include/particles/traits/GetIonizer.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Formerly ionization was started from a `Particles` class member function `void ionize()`. This seems unnatural, though, since ionization should start from an ionization model and be performed **on** the various particle species.
It was thus refactored and now allows for a more variable ionization routine. Different models can call kernels with or without loading random generators, for example.
=> Refactor ionization: remove from `Particles` class member functions

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
`typename` cannot be used outside a template declaration.
Only gcc allows this code in c++98. Clang correctly rejects this as it is only allowed in c++11.
=> remove invalid typename keyword

src/picongpu/include/algorithms/LinearInterpolateWithUpper.hpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/fields/currentInterpolation/CurrentInterpolation.def, src/picongpu/include/fields/currentInterpolation/CurrentInterpolation.hpp, src/picongpu/include/fields/currentInterpolation/NoneDS/NoneDS.def, src/picongpu/include/fields/currentInterpolation/NoneDS/NoneDS.hpp, src/picongpu/include/fields/numericalCellTypes/EMFCenteredCell.hpp, src/picongpu/include/fields/numericalCellTypes/NumericalCellTypes.hpp, src/picongpu/include/fields/numericalCellTypes/YeeCell.hpp, src/picongpu/include/simulation_defines/param/fieldSolver.param, src/picongpu/include/simulation_defines/unitless/fieldSolver.unitless
This pull request introduces the correct handling for the binding of electro-magnetic fields to currents in the directional splitting (DS) scheme.
In the directional splitting cell *only* the electro-magnetic fields are centered<sup>1</sup>. Both `B` and `E` are furthermore defined at the same time `t`.<sup>2</sup>
The particles are still moved between the updates of `B` and `E` making their current density `J` be defined at `t-1/2`.
Let's have a look at the cell for our **DS** implementation<sup>3</sup>, `E`<sup>t</sup> and `B`<sup>t</sup>:
Compared to the **Yee cell**<sup>3</sup>, `E`<sup>t</sup> and `B`<sup>t-1/2</sup>:
Nevertheless the source terms<sup>3</sup> (only `J` printed) are still at:
the last image can be derived from either analytically checking the DS scheme for a plane …
=> Direction Splitting: Self-Consistent J & EMF

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/picongpu/include/particles/MallocMCBuffer.hpp, src/picongpu/include/particles/MallocMCBuffer.tpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
- add `MallocMCBuffer` to syncronize *mallocMC* heap
- add interface `getHostParticleBox()` to `ParticleBuffer.hpp`
- `ParticlesBox.hpp`
- add new constructor
- add method `mapPtr()`
~~Please do not merge before https://github.com/ComputationalRadiationPhysics/mallocMC/pull/86 is merged to our `thirdParty` libraries~~
~~Please do not merge before #906 is merged to our `thirdParty` libraries.~~
=> add support to read particles on host side

src/libPMacc/include/cuSTL/algorithm/mpi/Gather.hpp
This removes a warning because the type was declared with struct but declared as friend with class.
=> fix struct/class declaration mix

src/libPMacc/include/math/vector/Float.hpp, src/libPMacc/include/mpi/GetMPI_StructAsArray.tpp, src/picongpu/include/particles/pusher/particlePusherAxl.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/WriteFields.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp
To decouple the code from CUDA headers, this commit removes some usages of cuda types in host code where standard C++ types can be used.
=> remove usage of cuda types in host only code

src/libPMacc/include/cuSTL/container/allocator/HostMemAllocator.hpp
VC 2015 RC does not allow the usage of `dim` defined as `static const int dim = 1` to be used in further  type definitions within the template specialization. Only the direct usage of the value `1` seems to work.
This change makes the code equivalent to the DeviceMemAllocator template specialization with the same purpose.
=> fix MSVC compiler error

src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/fields/currentDeposition/ZigZag/EvalAssignmentFunction.hpp, src/picongpu/include/initialization/ParserGridDistribution.hpp, src/picongpu/include/plugins/EnergyFields.hpp, src/picongpu/include/plugins/SumCurrents.hpp
typename cannot be used outside a template declaration.
Only gcc allows this code in c++98. Clang correctly rejects this as it is only allowed in c++11
This is the same as #926 and #917.
=> remove invalid typename keywords

src/libPMacc/include/cuSTL/cursor/Cursor.hpp, src/libPMacc/include/cuSTL/cursor/accessor/TwistAxesAccessor.hpp
navigators may modify their members
- rename: pureType -> ValueType (cuSTL/cursor)
=> refactor cuSTL/cursor

examples/Bunch/include/simulation_defines/param/gridConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param, examples/LaserWakefield/include/simulation_defines/param/gridConfig.param, examples/SingleParticleCurrent/include/simulation_defines/param/gridConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/gridConfig.param, examples/ThermalTest/include/simulation_defines/param/gridConfig.param, examples/WeibelTransverse/include/simulation_defines/param/gridConfig.param, src/picongpu/include/simulation_defines/param/gridConfig.param
`gridConfig.param`: "strange of the absober" -> "strength of the absorber"
=> fix spelling errors in gridConfig.param files

src/libPMacc/include/mpi/MPIReduce.hpp, src/picongpu/include/plugins/output/GatherSlice.hpp
The usage of variable length arrays is a GCC extension not supported by standard C++.
Their usage is replaced by `std::vector`.
=> remove variable length arrays

src/libPMacc/include/cuSTL/cursor/navigator/MapTo1DNavigator.hpp
Add cuSTL/MapTo1DNavigator which can be used to wrap a ndim-cursor into a 1D-cursor.
=> Feature: cuSTL/MapTo1DNavigator

src/picongpu/submit/titan-ornl/batch_profile.tpl, src/picongpu/submit/titan-ornl/batch_scorep_profile.tpl, src/picongpu/submit/titan-ornl/picongpu.profile.example, src/picongpu/submit/titan-ornl/pythonOnComp.profile.example, src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example
This pull requests updates the `picongpu.profile` example that we provide for Titan/ORNL.
I also added an example profile that can be used for python on compute nodes, similar to my gist at https://gist.github.com/ax3l/7d1fa52bb7f39a657920 .
=> Titan/ORNL: Update Modules

src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp, src/picongpu/include/simulation_defines/param/gasConfig.param
This pull request solves issue #882:
It changes to interface from gasFreeFormular from *cell offset* back to *position in SI units*.
**No examples** are affected by this pull request.
`gasConfig.param` was changed for the reference file.
=> close #882 - fix gas free formular

examples/Bunch/include/simulation_defines/param/memory.param, examples/KelvinHelmholtz/include/simulation_defines/param/memory.param, examples/KelvinHelmholtz/include/simulation_defines/param/particleConfig.param, examples/LaserWakefield/include/simulation_defines/param/memory.param, examples/LaserWakefield/include/simulation_defines/param/particleConfig.param, examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/ThermalTest/include/simulation_defines/param/memory.param, examples/WeibelTransverse/include/simulation_defines/param/memory.param, examples/WeibelTransverse/include/simulation_defines/param/particleConfig.param
This is a follow up fixing missed files from #926.
=> remove invalid typenames from example param files

src/libPMacc/include/memory/boxes/MultiBox.hpp, src/libPMacc/include/memory/boxes/PitchedBox.hpp, src/libPMacc/include/memory/boxes/SharedBox.hpp
When getting a box by const reference you should be able to get a pointer to the const values.
=> add const value pointer getter for const boxes

src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/plugins/output/WriteSpeciesCommon.hpp
- prepare particles on host instead of device
- add host functor `CopySpeciesToGlobal` to transform particles before
write operation
- `WriteSpeciesCommon.hpp`
- add functor `MallocHostMemory`
- add `CopySpeciesToHost`
- add `FreeHostMemory`
**Todo:**
~~**Do not merge before #905 and #902**~~
This pull request is related/closes #858
=> ADIOS: speedup particle preparation before dump

src/picongpu/include/plugins/adios/restart/LoadSpecies.hpp
During restart, the written N files by N aggregators (N <= |MPI_Size|)
are read again by each rank which causes NxN open files and fails for
large numbers of aggregators on parallel file systems.
~~We read our individual chunk now instead and perform a rather light
weight |MPI_Scan| on it to retreive the offsets.~~
Note 1: This bug is basically the same problem we had once with the
|libSplash| |SerialDataCollector| when we assumed that in general, a
re-sorting of GPUs /could/ have happened. (A pre-|alpha| bug during
GB2013.) On the ADIOS side, this can actually be achieved very
efficiently with an |ADIOS_READ_METHOD_BP_AGGREGATE| but is still very
experimental (did not work with zero-reads and/or zlib transport enabled).
Note 2: The HDF5 implementation …
=> ADIOS Restart: Avoid NxN access pattern with Aggregators

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_types.hpp
- add communication tag `SPECIES_FIRSTTAG`
- `simulation_types.hpp`: remove explicit communication tag for ions and electrons
- `Particles.tpp`: use `SPECIES_FIRSTTAG` as comminucation id offset
- changes in `speciesDefinition.param`
- add unique integer to define `CommunicationId<>`
- change code formatting of the species definition
- remove usage of `MakeSeq<>` to define species methods
=> refactore usage of `communicationId`

src/libPMacc/include/compileTime/conversion/OperateOnSeq.hpp, src/libPMacc/include/particles/ParticleDescription.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/libPMacc/include/particles/memory/dataTypes/ListPointer.hpp, src/libPMacc/include/particles/memory/frames/Frame.hpp
- `OperateOnSeq`: add compile time method that runs an operator on each element of a sequence 
- remove fixed `nextFrame` and `previousFrame` pointer in a frame
- refactor `ParticleDescription` -> add FrameExtensionList
- extent `Frame<>`: now inherits from all extensions
to allow optional double linked list support on frames
- add new type `PreviousFramePtr<>` with member previousFrame
- add new type `NextFramePtr<>` with member nextFrame
This pull request removes the problem that every frame includes two pointers (to create a double linked list) on itself. The pointers result in 16 Bytes extra memory per frame. Since `BorderFrame`s consists of only one particle, the typical particle size growths by 50%.
The refactoring allows to send more particles to neighboring GPUs within the same …
=> Topic make ptr in frame optional

src/picongpu/include/initialization/InitialiserController.hpp
remove usage of `ENABLE_IONS` to calculate the number of species
=> remove method to calculate info: particles on GPU

src/libPMacc/include/identifier/alias.hpp, src/libPMacc/include/identifier/identifier.hpp, src/libPMacc/include/math/ConstVector.hpp
Only define the CUDA \__constant\__ variables if CUDA is available.
This refactoring allows to use these defines without the CUDA compiler.
=> refactor host/device identifier defines

src/picongpu/include/particles/ParticlesFunctors.hpp
This commit unifies the different namings in the particle functors to be consistent.
=> Particle Functors: Unify Signatures

examples/Bunch/include/simulation_defines/param/speciesInitialization.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesInitialization.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/ThermalTest/include/simulation_defines/param/speciesInitialization.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/param/speciesInitialization.param
Adds documentation to all `speciesInitialization.param` files.
Moves the `InitPipeline` into the `particles` namespace.
Documents (but does not depend) on the changes in #959.
=> Doc: speciesInitalization.param

src/libPMacc/include/traits/GetUniqueTypeId.hpp
fix that `GetUniqueTypeId` creates negative id
**The master is not affected**
=> fix invalid id's from `GetUniqueTypeId`

src/libPMacc/include/traits/GetUniqueTypeId.hpp
- operator `<<` has lower priority than `-`
added parentheses to avoid wrong calculation
- add cassert to avoid negative ids
**This bug not affects the master**
=> fix wrong default maxValue calculation

src/picongpu/include/particles/InitFunctors.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/manipulators/AssignImpl.def, src/picongpu/include/particles/manipulators/AssignImpl.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/particles/manipulators/DriftImpl.hpp, src/picongpu/include/particles/manipulators/FreeImpl.hpp, src/picongpu/include/particles/manipulators/IManipulator.hpp, src/picongpu/include/particles/manipulators/IfRelativeGlobalPositionImpl.hpp, src/picongpu/include/particles/manipulators/NoneImpl.def, src/picongpu/include/particles/manipulators/NoneImpl.hpp, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/SetAttributeImpl.hpp, src/picongpu/include/particles/manipulators/TemperatureImpl.hpp, src/picongpu/include/particles/manipulators/manipulators.def, src/picongpu/include/particles/manipulators/manipulators.hpp
Particle manipulators are now quasi-binary, that means they always take *two* particle species as an attribute (+ additional parameters such as localCellIdx and 2x isParticle).
This allows to use the manipulators both during `Manipulate` of a single species and during `CloneSpecies`. A new `ManipulateCloneSpecies` functor was introduced that
allows for easier cloning-and-adjusting of, e.g., gas profiles that contain of multiple ion species and need to adjust the weighting of the created electrons directly during clone (when cloned in a common electron species).
=> Particle Manipulators: Make Quasi-Binary

src/libPMacc/include/algorithms/math/doubleMath/sqrt.tpp, src/libPMacc/include/algorithms/math/floatMath/sqrt.tpp
```rsqrt``` is not available without CUDA and therefore can not be used.
=> only use rsqrt when in CUDA code

src/libPMacc/include/lambda/CT/Expression.hpp
It is not allowed to use qualified names when specializing a class template.
This is reported by gcc 4.9.2.
=> remove invalid namespace qualifier from template specialization

src/libPMacc/include/Environment.hpp
gcc 4.9.2 errors on this code.
The problem is described [here](http://stackoverflow.com/questions/15537023/declaration-of-method-changes-meaning-of-symbol).
=> add namespace prefix to fix ambiguity error

src/libPMacc/include/preprocessor/facilities.hpp, src/libPMacc/include/preprocessor/struct.hpp
- add facilities macros
- add struct macros
This pull request allows to create struct with macro magic. 
Static constant vectors, strings and variable members are handled by the macro.
**Example:**
```C++
PMACC_STRUCT(Gauss,
(PMACC_C_VECTOR(float,center,2.0,2.0,2.0))
(PMACC_VALUE(int,a,2))
(PMACC_C_VALUE(int,b,4))
(PMACC_VALUE(int,x,23))
(PMACC_C_VECTOR_DIM(float,3,center2,1.0,2.0,2.0))
(PMACC_C_STRING(filename,"test.dat"))
(PMACC_C_STRING(filename2,"test2.dat"))
(PMACC_C_EXTENT(typedef float Float;))
);
``` 
**Result:**
```C++
namespace pmacc_Gauss0
{
typedef float center_t;
typedef float center2_t;
struct EmptyStruct{};
struct Gauss : private EmptyStruct 
{
Gauss(): a(2), x(23), EmptyStruct() 
{ }
static const int b = 4;
int a;
int x;
static const center_t center;
static const center2_t …
```
=> add preprocessor macros to create structs

src/libPMacc/include/algorithms/math.hpp, src/libPMacc/include/algorithms/math/doubleMath/comparison.tpp, src/libPMacc/include/algorithms/math/floatMath/comparison.tpp, src/libPMacc/include/math/vector/Vector.tpp
When not using CUDA, the calls to global namespace ```::min``` and ```::max``` would fail.
Using the wrappers inteded for this usage solves this and makes the calls equal to those in other functions in this file.
=> add namespace qualifier to min and max calls

src/libPMacc/include/algorithms/math/doubleMath/abs.tpp, src/libPMacc/include/algorithms/math/doubleMath/comparison.tpp, src/libPMacc/include/algorithms/math/doubleMath/erf.tpp, src/libPMacc/include/algorithms/math/doubleMath/exp.tpp, src/libPMacc/include/algorithms/math/doubleMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/doubleMath/sqrt.tpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/abs.tpp, src/libPMacc/include/algorithms/math/floatMath/comparison.tpp, src/libPMacc/include/algorithms/math/floatMath/erf.tpp, src/libPMacc/include/algorithms/math/floatMath/exp.tpp, src/libPMacc/include/algorithms/math/floatMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/floatMath/sqrt.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
This fixes the missing `#include "math.h"` in *libPMacc* as dicovered in #969.
=> add include math.h to libPMacc algorithms

src/picongpu/include/particles/gasProfiles/SphereFlanksImpl.hpp
The exponent of the density profile SphereFlanks is in units of 1/m which requires a multiplication with `UNIT_LENGTH` to make it unitless.
Bug is only in the current `dev` version due to a full refactoring of the density profiles.
=> Fix Gas Profile: Sphere Flanks Unit Exponent

src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp, src/picongpu/include/simulation_defines/param/gasConfig.param
I overlooked a few types in #899 (`dev` only) which should cause the `position_SI` argument always to
be zero and the `cellSize_SI` argument to potentially overflow (or at least to loose precision).
This pull request fixes that.
=> Fix Gas Profile: Free Formula Types

src/libPMacc/include/math/ConstVector.hpp
ConstVector is not defined as const, therefore it is
possible to access data member with the `operator[]` which
results is in a not const reference.
Solution:
- define `ConstVector` as const class
- remove non const `operator[]`
**This pull request effects master but there is no code known where this bug was triggered**
=> Fix `ConstVector` const ref operator[]

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/plugins/radiation/check_consistency.hpp, src/picongpu/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/unitless/radiationConfig.unitless
- move `check_consistency()` from global namespace to `picongpu` namespace
- move all configurations in `param/unitless` for radiation to `picongpu` namespace
=> change namespaces of radiation `param/unitless`

examples/SingleParticleCurrent/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleRadiationWithLaser/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleTest/include/simulation_defines/unitless/physicalConstants.unitless, src/picongpu/include/simulation_defines/unitless/physicalConstants.unitless
`physicalConstants.unitless`: remove usage of native `double` with `float_64`
=> change type `double` to `float_64`

src/picongpu/include/particles/gasProfiles/FromHDF5Impl.hpp, src/picongpu/include/plugins/PhaseSpace/DumpHBufferSplashP.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/simulation_types.hpp
- remove splash traits from `simulation_types.hpp`
- add missing include in `FromHDF5Impl.hpp`
Splash traits can depend on PIConGPU types like `float_64` but `simulation_types.hpp` is loaded before all PIConGPU types are known. Therefore splash traits must be removed from global scope.
=> remove splash traits from global scope

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param
radiationConfig.param: remove in `*.param/unitless` the usage of the native type `float` with `float_32`
=> Radiation: remove native `float` in `*.pram/unitless`

src/libPMacc/include/debug/VerboseLog.hpp
Fixed width types are used without including stdint.h breaking compilation on some (C++11?) compilers
=> Add missing include

src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp, src/picongpu/include/simulation_defines/param/gasConfig.param
This fixes a remnant template I oversaw in #976 :flushed: and an additional error caused by a nvcc bug while using const variables on the device.
@ComputationalRadiationPhysics/picongpu-maintainers 
As discussed offline with @ax3l, we need to add a test for free formular in the examples to verify the GasFreeFormular with the compile test.
=> fix gas free formular remaining errors 

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/TemperatureImpl.hpp, src/picongpu/include/particles/startPosition/RandomImpl.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param
- use new `UniqueTypeId` to generate unique id for a species
- `speciesAttributes.param`: remove `CommunicationId`
=> remove `CommunicationId` from species

src/picongpu/include/particles/InitFunctors.hpp
```-Wall``` noted that this typedef is not used anywhere.
=> remove unused local typedef

src/picongpu/include/plugins/radiation/amplitude.hpp
To ease the porting to non-CUDA back-ends the CUDA types should not be directly used in non kernel related code.
=> replace usage of CUDA uint by uint32_t

src/picongpu/include/plugins/radiation/Radiation.kernel
- add check if particle is ~~moving~~ accelerating/breaking
Disable radiation calculation for non ~~moving~~ accelerating/breaking particles. A particle which is not ~~moving~~ accelerating/breaking can't radiate, therefore we can skip the complex calculation.
=> speedup radiation

src/libPMacc/include/algorithms/math/doubleMath/pow.tpp, src/libPMacc/include/algorithms/math/floatMath/pow.tpp
Workaround is required for CUDA + C++11 + GCC:
Compiling with C++11 shows a problem with C++98 compatible CUDA compilers:
http://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-tools-title-known 
C++98 defines a pow(double, int) function, but CUDA (in the above config) has only pow(double, double)
Therefore the host function would be called (see comment)
Note that this lack results in reduced performance for int exponents but you got to wait for NVIDIA to fix that.
This DOES change the behavior compared to previous implementation for the case if there was actually a pow(double, int) function which does not just forward to pow(double, double)
=> Workaround for device call to pow

src/picongpu/include/particles/ParticlesInit.kernel
The variables superCellIdx and block are initialized with the same value.
Therefore one definition can be removed
=> remove duplicate computation and definition of superCellIdx/block

src/libPMacc/include/eventSystem/tasks/TaskSend.hpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/EvalAssignmentFunction.hpp, src/picongpu/include/fields/currentInterpolation/Binomial/Binomial.hpp, src/picongpu/include/fields/currentInterpolation/None/None.hpp, src/picongpu/include/fields/currentInterpolation/NoneDS/NoneDS.hpp, src/picongpu/include/plugins/EnergyFields.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/plugins/PositionsParticles.hpp, src/picongpu/include/plugins/SumCurrents.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/simulation_defines/param/visColorScales.param, src/picongpu/include/simulation_defines/param/visualization.param, src/picongpu/include/simulation_defines/unitless/gridConfig.unitless
Nothing from the headers that are removed is used in the respective files.
It has been checked that this does not introduce any missing (transitive) includes in those or other files because those headers have completely been removed in my develop branch.
=> remove unneeded headers

src/libPMacc/include/eventSystem/events/kernelEvents.hpp
The current macro version needs to be used from inside PMacc namespace or with a "using namespace PMacc" declaration which is bad practice.
This commit adds namespace qualifiers to the macro
=> Add namespace qualifier to cuda_kernel macro

src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/parameters.hpp, src/picongpu/include/plugins/radiation/particle.hpp, src/picongpu/include/plugins/radiation/radFormFactor.hpp
This pull request renames `vector_32` to `vector_X` (which it actually is) and adds a `vector_32` class just in case someone needs an explicit `float32` type 3D vector.
This pull request closes issue #997.
=> close #997 - fix `vector_32` in radiation

src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/operations/CountParticles.hpp
use warp aggregated `atomicAllInc()` to speedup particle operations
=> use `atomicAll*()` to speedup particle operations

src/picongpu/include/fields/FieldManipulator.kernel, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel
use warp aggregated `atomicAll*()` to speedup atomic operations in PIConGPU
=> use `atomicAll*()` to speedup atomic operation

src/libPMacc/include/traits/GetUniqueTypeId.hpp
- assert in getUniqueTypeId is triggert with a special environment on hypnos
- baseUId is not smallest created id
fix:
- ~~explicit initialize the base `TypeId` with `GetUniqueTypeId<uint8_t>::byte`~~
- remove pointer address magic
- add base type with static global counter
- add [`boost::numeric::bounds`](http://www.boost.org/doc/libs/1_58_0/libs/numeric/conversion/doc/html/boost_numericconversion/bounds___traits_class.html) for max value calculation
Environment:
```
module load gcc/4.8.2
module load cmake/3.0.1
module load cuda/6.5
module load openmpi/1.8.4.kepler
module load boost/1.54.0
module load pngwriter/0.5.4
module load hdf5-parallel/1.8.14 libsplash/1.2.4
module load numactl/2.0.7
module load paraview/3.98.laser
module load svn
module load gnuplot/4.2.6
```
Tested with:
=> fix traits `GetUniqueTypeId`

src/libPMacc/examples/gameOfLife2D/include/GatherSlice.hpp
The offset for the example fullData is wrong. This breaks, when there is a layout that has "columns" of GPUs. E.g. 2x2 instead of 1x4
=> GoL: Fix offset for example

src/libPMacc/include/eventSystem/events/kernelEvents.hpp
Follow-Up to #1017: The namespace defined here is misleading, since macros are not in a namespace.
=> Follow-Up to #1017: Remove Misleading Namespace

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleCurrent/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleRadiationWithLaser/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleTest/include/simulation_defines/unitless/physicalConstants.unitless, src/picongpu/include/particles/ionization/byField/BSI/AlgorithmBSI.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI.def, src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.def, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.hpp, src/picongpu/include/particles/traits/GetIonizationEnergies.hpp, src/picongpu/include/simulation_defines/param/ionizationEnergies.param, src/picongpu/include/simulation_defines/param/ionizerConfig.param, src/picongpu/include/simulation_defines/param/physicalConstants.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/ionizerConfig.unitless, src/picongpu/include/simulation_defines/unitless/physicalConstants.unitless
In preparation for the upcoming ADK model, some of the non-model related changes have been removed from #922 to be implemented before. 
This pull request features:   
- some renaming of the ionization framework and relocation of includes
- ionization energies that are pinned to the particle species itself
- the atomic unit system for ionization energy input
Should be merged **before** #922!
=> Ionization: update barrier suppression and energies

src/libPMacc/include/math/vector/Vector.hpp
- `math::Vector<>::operator==()`: remove early return in comparison operator
The early return results in `stack frame` (slows down the simulation) usage in some cases.
@PrometheusPi : This pull request should solve the performance decrease from #996.
=> performance improvement `Vector<>::operator==()`

examples/LaserWakefield/include/simulation_defines/param/gridConfig.param
This commit closes #1001 by increaseint the time step of the LWFA example so it's closer to the CFL.
This lowers numerical dispersion and also has positive impact on time-to-solution.
=> Close #1001 LWFA Example: Increase dt to CFL

src/libPMacc/include/compileTime/conversion/TypeToPointerPair.hpp
Moves the generic header to PMacc
Requires confirmation by @psychocoderHPC
=> Move header to PMacc

src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.hpp, src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.tpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
This class might also be useful outside of PIConGPU as it's pretty generic
- Requires mallocMC when used
- Also some minor changes to formatting, C-Style casts and includes
Requires permission by @psychocoderHPC
=> Move MallocMCBuffer to PMacc

src/picongpu/include/particles/startPosition/RandomImpl.hpp
Instead of setting the instance variable a local variable was created and ignored. This results in different local indices instead of same ones which may cause collisions when xoring with already local seeds.
only affects `dev`.
=> Actually set the total GPU offset

src/picongpu/include/particles/gasProfiles/profiles.def
The include for HDF5 support is not included when ENABLE_HDF5 !== 1 but gasConfig.param used it anyway.
Make this consistent and completely remove it when ENABLE_HDF5 is not set to 1
=> Gas Profiles: Correct Definiton List is HDF5 is disabled

src/libPMacc/include/dataManagement/ISimulationData.hpp, src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/simulationControl/SimulationHelper.hpp
This adds some more includes that were missing. Detected by using another include order than in PIConGPU.
Also adds virtual destructors to 2 virtual classes. One of them is in the same file as the include fix and this is only a minor change. Tell me, if a separate PR is still required.
Reasoning: Virtual classes should have virtual destructors in case anyone deletes it through a base pointer.
=> Add missing includes and virtual destructors

src/libPMacc/include/algorithms/reverseBits.hpp
Can be used for seeds to put lower bits into upper bits to allow for wider ranges
Code used is public domain
=> Implement reverseBits function

src/libPMacc/include/traits/GetEmptyDefaultConstructibleType.hpp
- define new trait to get shared memory compatible types
It is not allowed that a object in cuda shared memory initialize any member in it's default constructor.
This trait returned a shared memory compatible type.
This pull request shipped only the definition of the trait, at the moment there is no specialized type that can used with the new trait.
=> add trait  GetDefaultConstructibleType

src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp
* `BSI_Impl.hpp`:    
* added `__syncthreads()` after fields are copied   
from global to shared memory   
* renamed `totalCellOffset` to `localCellOffset`   
because that's what it is
@n01r Rebase #922 on `dev` after this is merged
=> Fix: missing `__syncthreads()` after shared mem usage

src/libPMacc/include/particles/memory/dataTypes/FramePointer.hpp
- add new class FramePointer (special pointer class for frames)
- define trait `GetEmptyDefaultConstructibleType<>`
`FramePointer` is a specialized `Pointer` which defines equivalent to a frame the `operator[]()`
=> add `FramePointer`

examples/Bunch/include/simulation_defines/param/fieldBackground.param, examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/simulation_defines/param/laserConfig.param
This pull request adjusts the wrong conversion from laser intensity to a_0 in `laserConfig.param` and one `fieldBackground.param` as discussed last week in person with @ax3l and @psychocoderHPC.
Since it was only a commented code part, it is **not a bug** but a **fix of documentation**.
@BeyondEspresso please have a look at this pull request as well since I adjusted your `fieldBackground.param`.
=> remove wrong intensity to a_0 conversion

src/libPMacc/include/algorithms/reverseBits.hpp, src/libPMacc/include/mpi/SeedPerRank.hpp, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/TemperatureImpl.hpp, src/picongpu/include/particles/startPosition/RandomImpl.hpp
This improves the global  uniqueness of the seeds by using local seeds that vary in the upper bits.
When XORing those with e.g. cellIdxs that are counted (from 0-N) the resulting seeds are still globally unique. Previously the counted rank and the counted cellIdx could cancel each other out resulting in "seed collisions" over different ranks.
Helps e.g. @n01r :)
=> Calculate better seeds

src/libPMacc/include/particles/ParticlesBase.kernel
- remove race condition with a refactoring
- new more simple algorithm
loops over frames:
- step 1 - all threads: count leaving particles per direction
- step 2 - only master threads: add frames for all leaving particles (for each direction)
- step 3 - all threads: copy particle memory
- step 4 - only master threads: cleanup helper variables
This pull request close #1044.
Tests:
=> close #1044: racecondition in `kernelShiftParticles`

src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
- add functor `PushAllSpecies`
- add functor `CommunicateSpecies`
- add functor `PushSpecies`
- remove functor `CallUpdate`
This pull request optimize the overlapping of the species push calculation and the communication.
The optimization results in a constant time step reduction of `2ms/species`
Tests:
=> refactor particle update

examples/Bunch/include/simulation_defines/param/fieldBackground.param, src/picongpu/include/simulation_defines/param/fieldBackground.param
The default example for background fields is not aligned.
Additionally, we avoid the -Wshadow warning in the constructor with a `m_` member prefix for `unitField` (related to #1042)
=> fieldBackground.param: Align and Wshadow

doc/TBG_macros.cfg, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/restart/RestartFieldLoader.hpp
This pull request updates the ADIOS file output plugin, used for output and checkpoints.
**Change in behaviour:**
- adios errors are now causing the application to abort (only affects errors that we are unable to handle anyway, such as failing `schedule_read` calls)
**New Options Exposed to the User:**
- online meta file creation (a light-weight file describing the individual outputs of aggregators) can be disabled (poor performance for highly parallel runs), use `bpmeta <fileName>_<step>.bp` offline to create it for a directory `<fileName>_<step>.bp.dir/`
- further options such as `striping=0` can be set. example means: *system default*, each file of an aggregator will now ask the file system *where* (OST-name(s)) and *how* (striping over *N* OSTs) to create it's file (avoids adios-based …
=> ADIOS: Log, Striping & No Meta File

doc/INSTALL.md, src/picongpu/CMakeLists.txt, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp, src/picongpu/submit/hypnos/picongpu.profile.example, src/picongpu/submit/titan-ornl/picongpu.profile.example
Changes the commit to require ADIOS 1.9.0 due to various bugs in the previous versions (main problem: aggregated files > 2GB).
By that, a good amount of legacy code can be removed:
- transformations (at least "none") are always available (>= 1.7.0) (zlib support for compression is one of those but depends on compile, see `adios_config -m` output)
- manual c-stringization of C attributes can be removed (1.9.0 feature)
- zero-read work-around for zlib transformed data is not necessary any more (fixed in 1.9.0), but still avoids API overhead so we keep it with a note
Runtime tests look correct! :)
=> ADIOS: 1.9.0 Updates

doc/INSTALL.md
- I created an AUR package for ADIOS: https://aur4.archlinux.org/packages/libadios/
=> ADIOS install instructions for ArchLinux

src/picongpu/include/particles/pusher/particlePusherPhot.hpp
No namespace was used which could resolve to std::abs instead of the vector version
=> Use correct namespace for abs function

src/libPMacc/include/memory/buffers/GridBuffer.hpp
- add possibility to define `sizeOnDevice` separate for send
end receive exchanges
- extent interface for `addExchange()`
- extent interface for `addExchangeBuffer`
The interface change is backwards compatible to the old version.
=> extent `GridBuffer<>::addExchange*`

buildsystem/CompileSuite/autoTests/new_commits.sh, src/picongpu/CMakeLists.txt
Before now we used the release branch of PNGwriter.
With the new release of 0.5.5 we can require the version in the CMake module.
Documents also some minor updates as they currently are used in our compile suite (module loads).
=> PNGwriter: 0.5.5 Release

src/libPMacc/include/Environment.def, src/libPMacc/include/Environment.hpp, src/libPMacc/include/cuSTL/algorithm/kernel/run-time/Foreach.hpp, src/libPMacc/include/eventSystem/EventSystem.tpp, src/libPMacc/include/eventSystem/Manager.hpp, src/libPMacc/include/eventSystem/streams/StreamController.hpp, src/libPMacc/include/eventSystem/tasks/TaskKernel.hpp, src/libPMacc/include/eventSystem/tasks/TaskKernel.tpp, src/libPMacc/include/eventSystem/transactions/Transaction.hpp
This solves a compilation failure when EventSystem.hpp is included AFTER Environment.hpp due to circular inclusion of those. Example:
Environment.hpp ->   
EventSystem.hpp ->
StreamTask.tpp ->
Environment.hpp (Ignored due to pragma once)
[Use Environment]
[Define Environment]
As you see, Environment will be used before it is defined in this case. This PR solves that, by splitting the hpp and tpp inclusions of the eventsystem into 2 files. The hpps are included as usual, but the tpps are included on the bottom of Environment.hpp (As already done for another tpp)
Issue already discussed with @psychocoderHPC
=> Split EventSystem.hpp into hpp and tpp

src/picongpu/include/fields/MaxwellSolver/None/NoSolver.def
With simDim equal to 2 (2D3V simulation), the MaxwellSolver `NoSolver` did cause a compile error due to a missing trait specialization.
This commit fixes that, in 2D3V simulations we still have 3 components of each vector field (E and B) but only 2 directions for neighbors (the third direction is assumed to be "periodic" or "infinitely identical").
Thanks to @n01r for reporting the issue!
=> Fix NoSolver in 2D

src/picongpu/submit/titan-ornl/picongpu.profile.example
Close #1060 Compiling with cmake 3+ caused a wrong detection of the `-ccbin` host-side compiler by cmake.
The compile wrappers on titan seem to have changed so that our work-around is not needed any more (`target` is also now deprecated). We remove it to address the issue. Compiles with the last cmake2 version we support still work.
=> Close #1060 CMake3 on Titan: Cross Compile

src/libPMacc/include/nvidia/atomic.hpp, src/libPMacc/include/nvidia/warp.hpp, src/libPMacc/include/types.h
This adds overloads for (I think) all possible types that can be used with atomicAddInc and warpBroadcast. (atomicAddInc depends on the latter so this change is very related)
This also adds a macro PMACC_CUDA_ARCH which is equivalent to __CUDA_ARCH__ but defined to be 0 when __CUDA_ARCH__ is not defined. The reason for this is, that even while atomicAddInc is marked DINLINE it seems to be passed to the host compiler which throws as __CUDA_ARCH__ is an undefined symbol.
Code is based on code by @psychocoderHPC so I'd suggest him to review this.
=> Improve atomicAddInc

src/libPMacc/include/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp, src/libPMacc/include/memory/boxes/SharedBox.hpp, src/libPMacc/include/nvidia/reduce/Reduce.hpp, src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/operations/CountParticles.hpp
- remove all `__syncthreads()` after shared memory allocation
- related to #518
Tests:
- I tested #1083 and this one together
=> Close #518 No `__syncthreads()` shared memory alloc

src/picongpu/submit/titan-ornl/picongpu.profile.example, thirdParty/cmake-modules/FindPNGwriter.cmake
Pull in third-party update: Adds version support to the PNGwriter's CMake module.
Follow-up to #1076, see https://github.com/ComputationalRadiationPhysics/cmake-modules/pull/11
--
Third party update for `FindmallocMC.cmake` in `thirdParty/cmake-modules` performed via
```bash
git subtree pull --prefix thirdParty/cmake-modules/ \
git@github.com:ComputationalRadiationPhysics/cmake-modules.git dev --squash
```
=> CMake: PNGwriter Version Support

examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp, src/libPMacc/include/communication/AsyncCommunication.hpp, src/libPMacc/include/fields/SimulationFieldHelper.hpp, src/libPMacc/include/particles/AsyncCommunicationImpl.hpp, src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp
This makes the asyncCommunication a functor instead of a virtual method.
This has the advantage (besides beeing more TMP like) that a call preserves the actual type compared to "concreteParticleInstance->asyncCommunication(event)" where functors down the chain only have access to ParticleBase.
As requested by @psychocoderHPC the functor can be specialized for any type. Particles are the only one used right now, but a specialization can be defined for buffers too without much effort.
For inheritance detection a tag is used ->"SimulationDataTag" type member. This is similar to e.g. iterator_tag from STL and solves the problem, that one cannot detect, whether a type is derived from a templated type.
=> Add a policy for async communication

src/picongpu/include/plugins/kernel/CopySpeciesGlobal2Local.kernel
This uses atomicAllInc instead of atomicAdd(..., 1) which is optimized for causing less collisions
=> Use optimized atomicAllInc

thirdParty/cmake-modules/FindPNGwriter.cmake, thirdParty/cmake-modules/FindmallocMC.cmake
Minor third-party updates in our modules:
- documentation: typos
- PNGwriter: regex refactor
--
```bash
git subtree pull --prefix thirdParty/cmake-modules/ \
git@github.com:ComputationalRadiationPhysics/cmake-modules.git dev --squash
```
=> CMake: Modules Minor Updates

src/libPMacc/include/cuSTL/container/HostBuffer.hpp, src/libPMacc/include/memory/buffers/HostBuffer.hpp
As a interface to cuSTL cartBuffer() is implemented for DeviceBuffers. However a similar function for HostBuffers is missing.
This adds that missing function.
Function is tested for correctness in XRT-Library (WIP) and similar to the device counterpart.
Related to #1091 as a move is used for this factory method.
=> Implement cartBuffer for HostBuffer

src/libPMacc/include/cuSTL/container/CartBuffer.tpp
This fixes the wrong implementation of the move operators. The current implementation called the copy assignment operator which calls e.g. actual cuda memCopies which is neither required nor wanted.
This also fixes some warnings about calling host function from host-device functions somewhere down the call chain
=> Fix move operators of cart buffer

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
This fixes the underestimation of the amplitude of the laser implementations for Gaussian Beam (and based on it for pulse front tilted Gaussian Beams) in 2D3V simulations.
Calculations of the pre-factor are performed on the host-side and therefore a simple `if` avoids code duplication.
Fixed image:
=> Fix #1052 Gaussian Beam Envelope 2D

src/picongpu/submit/submitAction.sh
This issue is related to #1100 : `cmakeFlags` in examples are copied if they exist so later
`createParameterSet` calls and/or following `configure` calls can use the `-t` options again to select a specific example
this is still discouraged for users since it is actually a CI feature, but it at least documents the available options (still not the one that was choosen for the binaries in the run)
=> submitAction.sh: copy cmakeFlags

src/libPMacc/include/mpi/GetMPI_StructAsArray.tpp
This allows e.g. MPI reduces of unsigned, unsigned long etc. It also removes the specialization of uint64_cu as this is not defined in the MPI interface. This does not break existing implementations as uint64_cu is an alias for unsigned long long for which this is specialized.
As a minor improvement it also removes a (long forgotten) tpl file lingering in that folder.
There will be no impact on runtime/correctness of existing implementations.
Side note: The use of e.g. `unsigned` or `long long` instead of `unsigned int` and `long long int` is C++ standard compliant as the name is only the *specifier* for the *type* (see e.g. http://stackoverflow.com/questions/11779704/c-type-unsigned-long-int) As most MPI implementations define e.g. `MPI_UNSIGNED_LONG_LONG` but not …
=> Add more specializations to GetMPI_StructAsArray

examples/Bunch/submit/bunch_0032.cfg, examples/KelvinHelmholtz/submit/0004gpus.cfg, examples/KelvinHelmholtz/submit/0016gpus.cfg, examples/LaserWakefield/submit/0001gpus.cfg, examples/LaserWakefield/submit/0008gpus.cfg, examples/LaserWakefield/submit/0016gpus.cfg, examples/LaserWakefield/submit/0032gpus.cfg, examples/SingleParticleCurrent/submit/0001gpus.cfg, examples/SingleParticleRadiationWithLaser/submit/0008gpus.cfg, examples/SingleParticleTest/submit/0008gpus.cfg, examples/ThermalTest/submit/0001gpu.cfg, examples/ThermalTest/submit/0004gpus.cfg, examples/ThermalTest/submit/0008gpus.cfg, examples/ThermalTest/submit/0032gpus.cfg, examples/ThermalTest/submit/0064gpus.cfg, examples/WeibelTransverse/submit/0004gpus.cfg, src/libPMacc/examples/gameOfLife2D/submit/1gpu.cfg, src/libPMacc/examples/gameOfLife2D/submit/2gpus.cfg, src/libPMacc/examples/gameOfLife2D/submit/4gpus.cfg
This pull request closes issue #1106 by removing the unneeded shebang in all `*.cfg` files.
The tool used was:
```python
import os
import stat
import re
executable = stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH
def remove_shebang(filename):
f = open(filename, "r")
text = f.readlines()
f.close()
f = open(filename, "w")
for line in text:
if not re.search("#!", line):
f.write(line)
f.close()
for dire in os.walk("../PIConGPU/picongpu/"):
directory = dire[0]
if not re.search("\.git", directory):
for file in dire[2]:
if re.search(".cfg\Z", file):
filepath = directory + "/" + file
st = os.stat(filepath)
mode = st.st_mode
if not (mode & executable):
f = open(filepath, "r")
try:
first_line = f.readline()
f.close()
if first_line[:2] == "#!":
print(filepath)
remove_shebang(filepath)
except …
```
=> close #1106: remove shebang from *.cfg files

src/picongpu/submit/taurus/picongpu.profile.example
~~With the update of taurus, there are only two cmake version available with the module system:~~
- `cmake/2.8.1`1(default) 
- `cmake/2.8.2`
~~But if no cmake from the module system is selected, `cmake version 2.8.12.2` is used instead (which is our minimal requirement on `dev`). 
Thus I removed getting cmake via module.~~
**Update:** I contacted the support and they added version 2.8.12.2 and version 3.3.2.
Additionally I added the so far missing openmpi and zlib modules to `picongpu.profile.example`.
=> update modules on taurus

src/libPMacc/include/math/vector/Vector.hpp
The return type had the wrong storage type which made it impossible to e.g. shrink constant vectors or in general any vector that has a non-default storage policy.
=> Fix shrink function

src/picongpu/submit/taurus/picongpu.profile.example
This pull request removes the `module load openmpi/1.6` I introduced with #1111.
Now `bullxmpi` is preferred again.
=> remove openMPI module load

src/picongpu/submit/taurus/picongpu.profile.example
Avoids wrong linkage if system-wide libraries are available that shall not be used (hdf5, boost, ...).
Fixes the issue reported in
https://github.com/ComputationalRadiationPhysics/libSplash/issues/191
Detailed analysis above and in
https://www.mail-archive.com/cmake@cmake.org/msg50018.html
=> Taurus: CMake & LIBRARY_PATH

src/libPMacc/include/Environment.hpp
The wrong device ID was used in the request
=> Use correct device number

src/libPMacc/include/Environment.hpp
Backport of #1115: Corrects the mapping of device when querying their properties.
=> [BP] #1115: Correct Device ID

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
Backport of  #1090
--
This fixes the underestimation of the amplitude of the laser implementations for Gaussian Beam (and based on it for pulse front tilted Gaussian Beams) in 2D3V simulations.
Calculations of the pre-factor are performed on the host-side and therefore a simple `if` avoids code duplication.
=> [BP]  #1090: Gaussian Beam Envelope 2D

src/tools/bin/plot_chargeConservation.py
This pull request is based on a off-topic refactoring request in #1131 by @ax3l - it **does not** close the issue.
@ax3l suggested to change the used colorbar from rainbow to blue-white-red to improve the identification of non-charge-conserving regions.
=> adjust colorbar in charge conservation tool

src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherPhot.hpp
Currently, the **Free Pusher** and the **Photon Pusher** do not support 2D simulation setups. 
The compiler throws an error when using these pushers in 2D.
This pull request fixes this, by keeping the type of speed ~~`float3_X`~~ **Update:** `MomType`.
=> Photon & Free Pusher: 2D3V Support

src/tools/bin/plot_chargeConservation.py
This pull request closes issue #1131.
It adds python 3 compatibility by avoiding the `file` type available in `python2` and getting only a `str` to the file. Then it checks if `str` is an actual file path. 
If tested it with `python/2.7.5` and `python/3.4.3` on hypnos. The later worked, but did not produce a window for me (probably some wrong backend setup on hypnos). I furthermore checked it with `python` `version 3.4.3` on my own machine again and got the window.
=> close #1131: add python3 compatibility

CMakeLists.txt
This change forces out-of-source builds for CMake.
Since the paths that are compared are absolute paths, it also matches wrong placed `build/` directories anywhere inside our source.
=> CMake: Force Out-of-Source Builds

src/picongpu/CMakeLists.txt
- remove deprecated `make_directory` call (thx @Flamefire for catching this in GoL)
- move "lost" `CMAKE_INSTALL_PREFIX` defaults up
=> CMake: PIConGPU Minor Updates

src/picongpu/include/particles/gasProfiles/GaussianCloudImpl.hpp
The implementation in `dev` for the gas profile GaussianCloud was broken with the following effect: powers != 2 (which is the standard Gaussian) do not permute and caused to initialize a "smoothed cuboid" instead of an ellipsoid.
This commit fixes that by calculating r0 over sigma first, instead of working component-wise. The previous implementation in `master` as of the `0.1.0` release was correct, too.
=> Fix GaussianCloud: Powers

src/tools/share/gnuplot/BinEnergyPlot.gnuplot
Close #1109 the file is just a template for an other script, only used in memory via `echo "$script" | gnuplot -persist` and has a clear suffix.
=> Close #1109 Remove Shebang from *.gnuplot

src/picongpu/CMakeLists.txt, thirdParty/mallocMC/.travis.yml, thirdParty/mallocMC/CHANGELOG.md, thirdParty/mallocMC/CMakeLists.txt, thirdParty/mallocMC/INSTALL.md, thirdParty/mallocMC/src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_hostclass.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_overwrites.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_utils.hpp, thirdParty/mallocMC/src/include/mallocMC/oOMPolicies/BadAllocException.hpp, thirdParty/mallocMC/src/include/mallocMC/version.hpp
- mallocMC dependency in `CMakeLists.txt` increased
- Squashed the new mallocMC master branch (which is at 2.2.0crp) into the `thirdParty` folder
=> mallocMC 2.2.0crp dependency

src/libPMacc/include/memory/dataTypes/Mask.hpp
This fixes a comment for Mask::getRelativeDirections where the description did not match the behaviour.
This is "critical" as it would be used wrong, if one relies on the comment and does not evaluate the mask-modulo-divide trickery going on inside the function
=> Correct wrong comment

doc/INSTALL.md, src/picongpu/CMakeLists.txt
PMacc uses `boost::result_of` to get the return type of arbitrary functions from a couple of structs. For example it is used, to get the result of the []-operator.
This violates the standard protocol which specifies that the result<> template member type should return the return type of the ()-operator and therefore breaks once decltype() (C++11) can be used (which is then automatically chosen by boost) This makes compiling with C++11 impossible --> #1147
This PR adds a define that forces boost to keep that behaviour. Note that the related ` BOOST_RESULT_OF_USE_TR1_WITH_DECLTYPE_FALLBACK` define cannot be used in **CUDA 7.0** due to a nvcc compiler bug ~~that should be fixed in the next CUDA release after 7.5 (according to NVIDIA)~~ (not in CUDA 6.5; fixed in CUDA 7.5).
Source for …
=> Close #1035 usage of boost::result_of

src/tools/bin/tbg
This pull request solves issue #1108 by transferring the UNIX-permissions of the `*.tpl` file to submit.start.
Now permissions can be set for each cluster/setup individually by adjusting the permissions of the associated `*.tpl`.
**Warning:** the used `stat` command differs between UNIX systems. E.g. the used flags would be different on OS X.
=> close #1108: transfer permissions from *.tpl to submit.start

doc/INSTALL.md
Replaces the `~` with `$HOME` in install prefixes to avoid weirdness on some systems (like creating an actual `~` dir)
(thx to @flamefire for reminding me)
=> Doc: Install Prefix with $HOME

thirdParty/cuda_memtest/.travis.yml, thirdParty/cuda_memtest/CMakeLists.txt, thirdParty/cuda_memtest/cuda_memtest.cu, thirdParty/cuda_memtest/cuda_memtest.h, thirdParty/cuda_memtest/tests.cu
This PR updates `cuda_memtest` with the latest updates from our [upstream repository](https://github.com/ComputationalRadiationPhysics/cuda_memtest):
https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/2
https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/3
https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/4
https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/6 (follow up of #1156)
Updated via:
```bash
git subtree pull --prefix thirdParty/cuda_memtest/ \
```
=> Third Party: cuda_memtest update

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
This commit fixes missing calls to our `math::` wrappers for `cos` calculations.
This caused compile problems with varying include orders in combination with thrust.
Related to #1152
=> Gaussian Lasers: Fix Missing `math::`

src/libPMacc/examples/gameOfLife2D/CMakeLists.txt
Close #1135, updates the GoL `CMakeLists.txt` with PIConGPU-style groups and modernized commands, dependencies, warnings, includes, `sm` > 2.0, dependency version requirements and scripts.
=> Close #1135 Modernize GoL CMakeLists.txt

src/libPMacc/include/dimensions/DataSpace.hpp
This simplifies quite some kernels as no explicit conversion is required anymore from threadIdx and blockIdx. Example:
// Old
const PMacc::DataSpace<3> superCellIdx(mapper.getSuperCellIndex(PMacc::DataSpace<3>(blockIdx)));
//New
const PMacc::DataSpace<3> superCellIdx(mapper.getSuperCellIndex(blockIdx));
There is a chance for an overflow if a value from the source is greater than INT_MAX. However this cannot happen for threadIdx and blockIdx as those are limited to 2^31 - 1 which is INT_MAX. (https://en.wikipedia.org/wiki/CUDA#Version_features_and_specifications)
=> Add conversion operator from uint3

thirdParty/mallocMC/src/include/mallocMC/mallocMC_hostclass.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_overwrites.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_utils.hpp
Fixes the *two* bugs after the `2.2.0crp` release of mallocMC:
https://github.com/ComputationalRadiationPhysics/mallocMC/pull/107
https://github.com/ComputationalRadiationPhysics/mallocMC/pull/105
Since this is a pre-release (dev) version of mallocMC, there needs to follow an other PR as soon as `2.2.1crp` of mallocMC is released that will also update PIConGPU's `CMakeLists.txt` [version requirement](https://github.com/ComputationalRadiationPhysics/picongpu/blob/bfe45e86f5494e6bf128ece6652231ab610b8070/src/picongpu/CMakeLists.txt#L307).
Updated via:
```bash
git subtree pull --prefix thirdParty/mallocMC/ \
git@github.com:ComputationalRadiationPhysics/mallocMC.git dev --squash
```
=> mallocMC: update to pre-2.2.1 version (dev)

src/libPMacc/include/algorithms/math/defines/floatingPoint.hpp, src/libPMacc/include/algorithms/math/doubleMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/floatMath/floatingPoint.tpp
This adds a function for rounding to nearest even value (result converted to int) and ceil function
This can be used in cases, where a rounded value is required and one does not want it to be always rounded down. For CUDA the intrinsic function is used (similar to *_rd) and for the host, this functions is emulated with a +-0.5 as there is no intrinsic function for that.
=> Add more rounding functions

src/libPMacc/include/mappings/kernel/BorderMapping.hpp
This improves the border mapper by allowing combinations of directions. This effectively reduces the area that is mapped. (See the class description for examples)
=> Allow direction combinations for border mapping

src/picongpu/include/algorithms/DifferenceToLower.hpp, src/picongpu/include/algorithms/DifferenceToUpper.hpp, src/picongpu/include/algorithms/FieldToParticleInterpolation.hpp, src/picongpu/include/algorithms/FieldToParticleInterpolationNative.hpp, src/picongpu/include/algorithms/LinearInterpolateWithUpper.hpp, src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/fields/currentInterpolation/Binomial/Binomial.hpp, src/picongpu/include/fields/currentInterpolation/None/None.hpp, src/picongpu/include/fields/currentInterpolation/NoneDS/NoneDS.hpp, src/picongpu/include/fields/tasks/TaskFieldReceiveAndInsert.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/shapes/CIC.hpp, src/picongpu/include/particles/shapes/Counter.hpp, src/picongpu/include/particles/shapes/NGP.hpp, src/picongpu/include/particles/shapes/P4S.hpp, src/picongpu/include/particles/shapes/PCS.hpp, src/picongpu/include/particles/shapes/TSC.hpp, src/picongpu/include/plugins/PhaseSpace/PhaseSpace.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/amplitude.hpp
This replaces all usages of `static const` by `BOOST_STATIC_CONSTEXPR` to make those values usable in C++11 `constexpr`
Follow up to #1155
=> PIConGPU: Use BOOST_STATIC_CONSTEXPR where possible

src/libPMacc/include/compileTime/AllCombinations.hpp, src/libPMacc/include/debug/VerboseLog.hpp, src/libPMacc/include/debug/VerboseLogMakros.hpp, src/libPMacc/include/dimensions/DataSpace.hpp, src/libPMacc/include/dimensions/DataSpace.tpp, src/libPMacc/include/eventSystem/tasks/TaskSetValue.hpp, src/libPMacc/include/lambda/CT/Expression.hpp, src/libPMacc/include/mappings/threads/ThreadCollective.hpp, src/libPMacc/include/math/ConstVector.hpp, src/libPMacc/include/math/MapTuple.hpp, src/libPMacc/include/math/Tuple.hpp, src/libPMacc/include/math/vector/Vector.hpp, src/libPMacc/include/math/vector/Vector.tpp, src/libPMacc/include/math/vector/compile-time/Float.hpp, src/libPMacc/include/math/vector/compile-time/Vector.hpp, src/libPMacc/include/memory/boxes/DataBoxDim1Access.hpp, src/libPMacc/include/memory/boxes/DataBoxUnaryTransform.hpp, src/libPMacc/include/memory/buffers/MultiGridBuffer.hpp, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/particles/memory/dataTypes/Particle.hpp, src/libPMacc/include/particles/memory/dataTypes/StaticArray.hpp, src/libPMacc/include/particles/particleFilter/PositionFilter.hpp, src/libPMacc/include/preprocessor/struct.hpp, src/libPMacc/include/traits/GetNComponents.hpp, src/libPMacc/include/traits/IsSameType.hpp, src/libPMacc/include/traits/Limits.tpp, src/libPMacc/include/traits/NumberOfExchanges.hpp
This replaces all usages of `static const` by `BOOST_STATIC_CONSTEXPR` to make those values usable in C++11 `constexpr`
Follow up to #1155
=> PMacc: Use BOOST_STATIC_CONSTEXPR where possible

src/libPMacc/include/cuSTL/algorithm/kernel/detail/SphericMapper.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/allocator/DeviceMemAllocator.hpp, src/libPMacc/include/cuSTL/container/allocator/DeviceMemEvenPitchAllocator.hpp, src/libPMacc/include/cuSTL/container/allocator/HostMemAllocator.hpp, src/libPMacc/include/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp, src/libPMacc/include/cuSTL/container/assigner/DeviceMemAssigner.hpp, src/libPMacc/include/cuSTL/container/assigner/HostMemAssigner.hpp, src/libPMacc/include/cuSTL/container/compile-time/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/copier/D2DCopier.hpp, src/libPMacc/include/cuSTL/container/copier/H2HCopier.hpp, src/libPMacc/include/cuSTL/cursor/BufferCursor.hpp, src/libPMacc/include/cuSTL/cursor/Cursor.hpp, src/libPMacc/include/cuSTL/cursor/SafeCursor.hpp, src/libPMacc/include/cuSTL/cursor/compile-time/SafeCursor.hpp, src/libPMacc/include/cuSTL/cursor/navigator/BufferNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/CartNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/MapTo1DNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/MultiIndexNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/compile-time/BufferNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/compile-time/TwistAxesNavigator.hpp, src/libPMacc/include/cuSTL/cursor/navigator/compile-time/TwistedAxesNavigator.hpp, src/libPMacc/include/cuSTL/zone/SphericZone.hpp, src/libPMacc/include/cuSTL/zone/ToricZone.hpp, src/libPMacc/include/cuSTL/zone/compile-time/SphericZone.hpp
This replaces all usages of `static const` by `BOOST_STATIC_CONSTEXPR` to make those values usable in C++11 `constexpr`
Follow up to #1155
=> cuSTL: Use BOOST_STATIC_CONSTEXPR where possible

src/libPMacc/include/pluginSystem/PluginConnector.hpp
The plugins were loaded in reverse order. This is at the very least unexpected.
The C++ convention for loading/unloading is, that everything is deleted in the reverse order than what it was created (stack like behaviour)
This ensures e.g. that plugins could rely on each other (an other plugin that was available on load will still be available on unload)
In my specific use case I need a plugin to be executed before others. I expected registering it first would do that, but it did not. Maybe a follow-up could add priorities to plugins?
=> Load plugins in registered order

src/libPMacc/include/cuSTL/algorithm/mpi/Gather.tpp
The recv buffer pointer is not meaningful and not used for non-root processes of a MPI gather operation. Therefore we do not need to allocate the memory for that.
This is important in low-memory environments where e.g. one distributed the root process for each gather operation in a round-robin fashion to counter load imbalances and expect, that the non-roots actually do less and need less memory.
=> Do not allocate memory if not root

src/libPMacc/include/cuSTL/container/allocator/DeviceMemAllocator.tpp, src/libPMacc/include/cuSTL/container/allocator/DeviceMemEvenPitchAllocator.tpp, src/libPMacc/include/cuSTL/container/allocator/HostMemAllocator.tpp, src/libPMacc/include/memory/buffers/Buffer.hpp
This sets the pointers to NULL before calling cudaMalloc and also calls it only on non-zero sizes. See #1179 for details on the issue
Closes #1179
Note: Affects only cuSTL. PMacc seems to be fine. A single change for consistency in PMacc is included but it's not worth mentioning, so 1 PR should be ok.
=> Set pointers to NULL before calling cudaMalloc

src/picongpu/include/simulationControl/MySimulation.hpp
As described in #1187 this avoids a possible underflow causing undefined behaviour of the available memory is less then the amount of memory that needs to be reserved.
Renaming as mentioned in the issue is in a 2nd PR #1190 which must not be merged before this one (may need (conflict free) rebase)
=> Fix possible underflow on low memory situations

examples/Bunch/include/simulation_defines/param/memory.param, examples/KelvinHelmholtz/include/simulation_defines/param/memory.param, examples/LaserWakefield/include/simulation_defines/param/memory.param, examples/ThermalTest/include/simulation_defines/param/memory.param, examples/WeibelTransverse/include/simulation_defines/param/memory.param, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/param/memory.param
Split from #1188 and needs to be merged AFTER #1188:
Changes the bad/misleading name to a better one as it is not the free gpu memory that is meant but amount the amount of memory that should be reserved for random stuff.
=> Rename totalFreeGpuMemory to reservedGpuMemorySize

src/picongpu/include/simulationControl/MySimulation.hpp
As suggested by @psychocoderHPC in https://github.com/ComputationalRadiationPhysics/picongpu/pull/1190#discussion_r42345229 the error message should be improved when there is not enough free gpu memory.
=> Make error message better

src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp, src/libPMacc/include/cuSTL/container/assigner/DeviceMemAssigner.hpp, src/libPMacc/include/cuSTL/container/assigner/HostMemAssigner.hpp, src/libPMacc/include/cuSTL/container/copier/D2DCopier.hpp, src/libPMacc/include/cuSTL/container/copier/H2HCopier.hpp
This makes it possible to use the assignments of Host/DeviceBuffers on both host on device (where possible, so assigning Host->Host in a device function will still not work)
=> [cuSTL] Implement correct assignment operators

examples/Bunch/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/SingleParticleCurrent/include/simulation_defines/param/species.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/species.param, examples/SingleParticleTest/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/species.param
This pull request fixes to typos in the selection of possible pushers.
This avoids selecting a wrongly spelled and thus non-existing pusher.
=> fix typo Axl-> Axel and Phot->Photon

src/picongpu/include/particles/pusher/particlePusherAxl.hpp, src/picongpu/include/particles/pusher/particlePusherBoris.hpp, src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherNone.hpp, src/picongpu/include/particles/pusher/particlePusherPhot.hpp, src/picongpu/include/particles/pusher/particlePusherVay.hpp
This pull request is a branching from #1201. It updates only the pusher interface to agree with the current coding standard of *PIConGPU*. 
- all template variable names are changed from `XxxType` to `T_Xxx`
- `typedef` are used instead of direct reference to template variable name
=> update pusher interface to work with coding standard

src/picongpu/include/particles/pusher/particlePusherAxl.hpp
This pull request fixes an outdated `Vector` constructor use in the `Axel` pusher.
Now, this pusher compiles again.
=> Axel pusher: Use new ::create Contruct for Vectors

src/libPMacc/include/math/complex/Complex.hpp
This is required if one has a buffer of complex numbers and needs to change only real or imag parts e.g. with `atomicAdd`
=> Add reference accessors to complex type

src/libPMacc/include/cuSTL/algorithm/mpi/Gather.hpp, src/libPMacc/include/cuSTL/algorithm/mpi/Gather.tpp, src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/math/vector/Vector.hpp
Before this patch the gather functor could not accept e.g. Views. 
It now also checks for pitches and copies the memory transparently if required. This was not required before as (currently) HostBuffers were densely packed, but now it is as e.g. a View is mostly not densely packed.
=> Make cuSTL gather accept CartBuffers and handle pitches

src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp
Assigning a HostBuffer to a DeviceBuffer is not logically possible from device side. So we need `HINLINE` rather than `HDINLINE`
This fixes also the related **warning** about calling a host function from a host-device function
@Heikman
=> Disallow assigning a HostBuffer to a DeviceBuffer from device

src/tools/png2gas/png2gas.cpp
Allocate the memory after checking if the image we want to convert was actually valid.
Removes a (return from `main`) memory leak in `data` as spotted by Julien (@several2412) with `cppcheck` in #1172 via refactoring.
=> Png2Gas: Allocate Mem Later

src/libPMacc/include/math/vector/Vector.hpp
The unconditional use of `const type&` in the vector leads to 2 problems for arithmetic types:
1. The code may not be inlined so const& get more costly than plain consts or the reference type might make the compiler not inline a call that could otherwise be inlined (I have a case where I strongly suspect that this happened although it's hard to confirm as one cannot see the reasons why the compiler inlined or not)
2. Passing a `constexpr` in device code is not possible. https://docs.nvidia.com/cuda/cuda-c-programming-guide/#constexpr-variables : `Let 'V' denote a namespace scope variable ... that has been marked constexpr  Device source code cannot contain a reference to V or take the address of V. `
This PR uses the boost trait for selecting the 'best' type to be used
=> Use better type for params in vector

examples/SingleParticleTest/cmakeFlags, examples/SingleParticleTest/include/simulation_defines/param/dimension.param, examples/SingleParticleTest/include/simulation_defines/param/species.param
This pull request adds cmake tests for all pushers in 2D and 3D (except the `Axel` pusher, which does not support 2D).
The tests are added  to the `example/SingleParticleTest`. This should avoid bugs as #1204 or missing 2D support as #1126 in the future.  
This pull request requires:
to be merged.
=> add cmake Test for all pushers in 2D and 3D

src/libPMacc/include/compileTime/AllCombinations.hpp
fix compile time error if input sequence is empty (e.g. boost::mpl::vector0<>)
=> fix `AllCombinations<...>`

src/libPMacc/include/Environment.hpp, src/libPMacc/include/eventSystem/Manager.tpp, src/libPMacc/include/eventSystem/tasks/StreamTask.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.tpp, src/libPMacc/include/eventSystem/tasks/TaskCopyDeviceToDevice.hpp, src/libPMacc/include/eventSystem/tasks/TaskCopyDeviceToHost.hpp, src/libPMacc/include/eventSystem/tasks/TaskCopyHostToDevice.hpp, src/libPMacc/include/eventSystem/tasks/TaskLogicalAnd.hpp, src/libPMacc/include/eventSystem/tasks/TaskReceive.hpp, src/libPMacc/include/eventSystem/tasks/TaskReceiveMPI.hpp, src/libPMacc/include/eventSystem/tasks/TaskSend.hpp, src/libPMacc/include/eventSystem/tasks/TaskSendMPI.hpp, src/libPMacc/include/eventSystem/transactions/Transaction.hpp, src/libPMacc/include/eventSystem/transactions/Transaction.tpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.tpp, src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp, src/libPMacc/include/memory/buffers/GridBuffer.hpp, src/libPMacc/include/memory/buffers/MappedBufferIntern.hpp, src/libPMacc/include/particles/tasks/TaskParticlesReceive.hpp, src/libPMacc/include/particles/tasks/TaskParticlesSend.hpp, src/libPMacc/include/particles/tasks/TaskReceiveParticlesExchange.hpp, src/libPMacc/include/particles/tasks/TaskSendParticlesExchange.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/fields/tasks/TaskFieldReceiveAndInsert.hpp, src/picongpu/include/fields/tasks/TaskFieldSend.hpp, src/picongpu/include/plugins/adios/restart/LoadSpecies.hpp, src/picongpu/include/plugins/hdf5/restart/LoadSpecies.hpp
- simplify transaction rules
- remove `__startAtomicTransaction()`
- refactor usage of transactions in tasks
**Tests:**
=> refactore eventsystem

src/tools/livevis/client/mainwindow.cpp
the "presentation mode" / disable-all key `F11` shall not hide the timestep/fps pane
=> disable that fps panel hide function

src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp
- use trait `particles::FilterByFlag` to define the alias `particlePusher<>`
optional for a species
- remove fallback to `pusher::None`
Tests:
=> remove workaround for optional particle pusher

src/picongpu/include/particles/InterpolationForPusher.hpp, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/pusher/particlePusherAxl.hpp, src/picongpu/include/particles/pusher/particlePusherBoris.hpp, src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherNone.hpp, src/picongpu/include/particles/pusher/particlePusherPhot.hpp, src/picongpu/include/particles/pusher/particlePusherVay.hpp
This pull request refactors the particle pusher interface to support:
- inter pusher field to  particle interpolation
- ~~use of weighting in pusher~~ --> #1213 
None of the current  pushers need this update, but with the coming radiation reaction pusher, these will be necessary.
=> move field to particle interpolation into pusher

src/picongpu/include/particles/traits/GetIonizer.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
- remove fallback to `particles::ionization::None<...>`
- `MySimulation.hpp` - filter species with ionizer before call of `CallIonization<>`
=> refactor traits::GetIonizer

src/libPMacc/include/cuSTL/container/allocator/DeviceMemAllocator.tpp, src/libPMacc/include/cuSTL/container/copier/Memcopy.hpp
until now:
```
cudaPitchedPtr.xsize = numElements
```
now:
```
cudaPitchedPtr.xsize = numElements * sizeof(Type)
```
solves #1231
=> fix cudaPitchedPtr.xsize

doc/INSTALL.md
While installing picongpu on my machine I was irritated that it was suggested to install picgpu into your home directory. So why not put the install location into a environment variable $PICHOME and use this for the rest of the description. This would be more general.
Other question: Why is picongpu a mandatory dependency of picongpu ?
Because you have a duplication of the picongpu git clone commands in the
description.
=> Introduce PICHOME in install description

doc/INSTALL.md, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/picongpu/submit/lawrencium-lbnl/picongpu.profile.example, src/picongpu/submit/taurus-tud/picongpu.profile.example
This PR increases the boost requirement to be at least 1.56.0+ (first required by #995).
This allows us to drop a list of work-arounds as a result.
=> Boost: 1.56.0+ Requirement

examples/SingleParticleCurrent/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleRadiationWithLaser/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleTest/include/particles/ParticlesInitOneParticle.hpp, src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/particles/memory/dataTypes/SuperCell.hpp, src/libPMacc/include/particles/operations/CountParticles.hpp, src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldTmp.kernel, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/particles/access/Cell2Particle.tpp, src/picongpu/include/particles/ionization/ionization.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp, src/picongpu/include/plugins/PositionsParticles.hpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/plugins/kernel/CopySpeciesGlobal2Local.kernel, src/picongpu/include/plugins/makroParticleCounter/PerSuperCell.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel
- refactor interface of the `ParticlesBox`
- use `FramePointer<...>` instead of plain C pointer
- use coding guide line for code formation
Sry that this pull request contains code style changes, I pressed button for auto formation in my IDE.
This pull close #1191
**Tests:**
=> refactor particle box interface

src/picongpu/include/simulation_defines/param/laserConfig.param
This is a **follow up** pull request to #1155 where some `CONSTEXPR` in `laserConfig.param` were not replaced by `BOOST_CONSTEXPR_OR_CONST`.
@Flamefire please have a look if I used `BOOST_CONSTEXPR_OR_CONST` correctly.
Using `CONSTEXPR` does not compile.
=> fix missing replacement of CONSTEXPR to BOOST_CONSTEXPR_OR_CONST

src/picongpu/include/fields/FieldManipulator.hpp
fix clang warning: self-comparison always evaluates to true
This is not marked as **BUG** because the order of the if conditions prevent that the result is wrong.
=> fix warning in FieldManipulator

src/libPMacc/include/dimensions/DataSpaceOperations.hpp, src/libPMacc/include/memory/boxes/MultiBox.hpp, src/libPMacc/include/memory/boxes/PitchedBox.hpp, src/libPMacc/include/memory/buffers/Buffer.hpp, src/libPMacc/include/memory/buffers/DeviceBuffer.hpp, src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp, src/libPMacc/include/memory/buffers/HostBuffer.hpp, src/libPMacc/include/memory/buffers/HostBufferIntern.hpp, src/libPMacc/include/memory/buffers/MappedBufferIntern.hpp, src/libPMacc/include/memory/buffers/MultiGridBuffer.hpp
- fix that a buffer that points to an existing buffer calculates and uses the
wrong pitch to move over x-y plane
- Buffer.hpp:
- add member `m_physicalMemorySize`
- add getter `getPhysicalMemorySize()`
- DataSpaceOperation.hpp: add missing map method for 1D
- Multibox and PitchedBox
- rename parameter `size` in constructor to `memSize` to make it more
clear which size is needed
- *Buffer.hpp: use `getPhysicalMemorySize()` to create boxes
**This bug affects all previous (libPMacc) releases but PIConGPU simulations were not affected!**
~~The result in PIConGPU is wrong communicated current on the GPU borders, the effect can not be estimated.~~ The old KHI heating and the new one show no differences.
Tests:
=> Buffer: Fix Invalid Pitches

src/libPMacc/include/compileTime/GetKeyFromAlias.hpp, src/libPMacc/include/compileTime/conversion/ResolveAliases.hpp, src/libPMacc/include/compileTime/errorHandlerPolicies/ReturnType.hpp, src/libPMacc/include/compileTime/errorHandlerPolicies/ReturnValue.hpp, src/libPMacc/include/compileTime/errorHandlerPolicies/ThrowValueNotFound.hpp, src/libPMacc/include/particles/memory/frames/Frame.hpp
This allows e.g. `ResolveAndRemoveFromSeq` to not fail if a value did not exist in the first place.
Current policies are:
1. Fail if alias is not in the sequence
2. Return the (supposed to be) alias
3. Return a given type
Default policy is to return bmpl::void_ so it does not change current behaviour.
Partly based on offline discussion with @psychocoderHPC
=> Add a policy to GetKeyFromAlias

src/libPMacc/include/memory/buffers/HostBufferIntern.hpp
**It does not effects PIConGPU**. It is only a PMacc bug.
--
Found that failure while test case generation.
Leads to : 
/home/zenker64/projects/picongpu/src/libPMacc/include/memory/buffers/HostBuffer.hpp(44): error: Buffer is not a template
/home/zenker64/projects/picongpu/src/libPMacc/include/memory/buffers/HostBuffer.hpp(44): error: not a class or struct name
/home/zenker64/projects/picongpu/src/libPMacc/include/memory/buffers/DeviceBuffer.hpp(51): error: Buffer is not a template
/home/zenker64/projects/picongpu/src/libPMacc/include/memory/buffers/DeviceBuffer.hpp(51): error: not a class or struct name
/home/zenker64/projects/picongpu/src/libPMacc/include/memory/buffers/DeviceBuffer.hpp(63): error: Buffer is not a template
Changing from Buffer to HostBuffer include solved the Problem.
=> HostbufferIntern depends on HostBuffer not on Buffer

src/tools/bin/position2Trace.sh
This pull request adjusts the `position2Trace.sh` tool to
- work  with the new plugin name
- remove the commas for separating vector components
=> adjust "position to trace" tool to new plugin name

examples/Bunch/include/simulation_defines/param/gasConfig.param, src/picongpu/include/simulation_defines/param/gasConfig.param
This adds the missing documentation in `gasConfig.param` for the GaussianCloud profile.
Was removed during refactoring since even the [original documentation](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f31b31ab5afe8951ba58754fc6266a4ac07ffd20/src/picongpu/include/simulation_defines/param/gasConfig.param#L167-L173) was copy-pasted from an other profile (and therefore wrong).
=> Gas Gaussian Cloud: Add Missing Documentation

src/picongpu/include/particles/pusher/particlePusherAxel.hpp, src/picongpu/include/particles/pusher/particlePusherPhoton.hpp, src/picongpu/include/simulation_defines/param/pusherConfig.param, src/picongpu/include/simulation_defines/unitless/pusherConfig.unitless
Follow-Up to #1202 #1211:
- Forgot to move and rename Photon/Axel pusher
- forgot to update `pusher.param`
Makes the docs/namings/namespaces consistent again in the backend.
=> Finish Renaming of Photon/Axel Pusher

src/tools/bin/tbg
- remove parameter `-p/--project`
- add `projectPath` as optional directory parameter before `destinationPath`
- update `help()`
The new usage is equal to the linux `cp` and `rsync` command (Copy something from source to destination)
**old:**
```
tbg -p ./params  -t ./params/submit/hypnos-hzdr/k20_profile.tpl \
-c ./params/submit/0016gpus.cfg \
./params/khi/001_testCase
```
**new:**
```
tbg -t ./params/submit/hypnos-hzdr/k20_profile.tpl \
-c ./params/submit/0016gpus.cfg \
./params ./params/khi/001_testCase
```
=> refactor parameter `-p/--project` usage

src/picongpu/include/fields/FieldTmp.kernel
- close #1271 *hdf5 plugin - FieldTmp broken*
- fix missing negation ( [result of refactoring](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1243/files#diff-5b3d392fb808a21b5b3d279ee32a34d8L70) in #1243 )
=> close #1271 broken FieldTmp

README.md
@erikzenker is now taking over the maintenance work of @BenjaminW3 - welcome on the one hand and a big thanks to Benjamin for his PIConGPU work. We are very glad he is still actively contributing a lot to [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka), so stay tuned :)
Moved other members that are no longer active to the contrib section.
=> Readme: Update Active Team

src/picongpu/include/plugins/output/GatherSlice.hpp
free mpi gatherv memory after usage
related to #1279
**Tests:**
- 2D LWFA with sliding window
=> reduce `GatherSlice` host memory footprint

src/picongpu/include/plugins/output/images/Visualisation.hpp
allocate image memory only if gpu participate on the visualization
related to #1279
**Tests:**
=> reduce visualization gpu memory footprint

doc/TBG_macros.cfg, src/picongpu/include/plugins/ChargeConservation.hpp, src/picongpu/include/plugins/ChargeConservation.tpp, src/picongpu/include/plugins/PluginController.hpp
adding --chargeConservation.period <frequency> option to picongpu now returns the maximum charge deviation between particles and div E in a separate output file chargeConservation.dat:
```
#timestep max-charge-deviation unit[As]
0 7.59718e-06 5.23234e-17
100 8.99187e-05 5.23234e-17
200 0.000113926 5.23234e-17
300 0.00014836 5.23234e-17
400 0.000154502 5.23234e-17
500 0.000164952 5.23234e-17
```
=> add charge conservation plugin

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/Density.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Density.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorEnergy.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorEnergy.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/WriteFields.hpp
Refactors the particle solvers that populate `FieldTmp`, e.g., the HDF5 and ADIOS plugins.
The primarily goal of this refactoring is to make the current structure cleaner with separate classes and to allow later on to add solvers that populate `FieldTmp`, e.g., from pure field sources (e.g., div of E, |S|, etc.).
Additionally, namings and results of solvers have been clearified and standardized.
- all namings (according to openPMD ED-PIC extension, [version 1.0.0](https://github.com/openPMD/openPMD-standard/blob/1.0.0/EXT_ED-PIC.md#naming-conventions-for-mesh-records-field-records))
- `<species>_chargeDensity` (previously called wrong "density", related to #909)
- `<species>_energyDensity` (now without charge, previously created an
energy-charge-density)
- `<species>_density` (an actual …
=> Refactor FieldTmp Particle Solvers

src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/UnitDimension.hpp
Adds a new trait `UnitDimension` that returns the powers of the seven SI base units as defined in [openPMD 1.0.0](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#required-for-each-record)
=> Species Attributes: New Trait UnitDimension

src/libPMacc/CMakeLists.txt, src/libPMacc/test/memory/HostBufferIntern/setValue.hpp, src/libPMacc/test/memory/memoryUT.cu
This PR test the method `setValue` of HostBufferIntern by calling `setValue(255)` and checking afterwards wether the values have been set correctly by iterating over all elements in the HostBufferIntern.
=> Test checks setValue of HostBufferIntern

thirdParty/cmake-modules/FindSplash.cmake
Update with [upstream](https://github.com/ComputationalRadiationPhysics/cmake-modules) update:
- `FindSplash.cmake` https://github.com/ComputationalRadiationPhysics/cmake-modules/pull/13: fixes a false positive on `Splash_FOUND` when the found version of libSplash is older than the requirement
--
```bash
git subtree pull --prefix thirdParty/cmake-modules/ \
git@github.com:ComputationalRadiationPhysics/cmake-modules.git dev --squash
```
=> CMake: Splash_FOUND Version

src/picongpu/include/plugins/kernel/CopySpecies.kernel
- close #1274
- explicit copy deep copy of the filter to each OpenMP thread
Tests:
=> fix racecondition in `ConcatListOfFrames`

src/picongpu/include/particles/manipulators/AssignImpl.hpp, src/picongpu/include/particles/manipulators/DriftImpl.hpp, src/picongpu/include/particles/manipulators/FreeImpl.hpp, src/picongpu/include/particles/manipulators/NoneImpl.hpp, src/picongpu/include/particles/manipulators/ProtonTimesWeightingImpl.def, src/picongpu/include/particles/manipulators/ProtonTimesWeightingImpl.hpp, src/picongpu/include/particles/manipulators/RatioWeightingImpl.def, src/picongpu/include/particles/manipulators/RatioWeightingImpl.hpp, src/picongpu/include/particles/manipulators/SetAttributeImpl.hpp, src/picongpu/include/particles/manipulators/manipulators.def, src/picongpu/include/particles/manipulators/manipulators.hpp
This commit adds new manipulators that can be used during the species init-pipeline.
- `RatioWeightingImpl`: Useful to clone one ion species from an other ion species by still satisfying the `densityRatio` of the new created species.
- `ProtonTimesWeightingImpl`: Useful to clone electron species from an ion species for pre-ionized plasmas. The weighting of the electrons is simply multiplied by the proton number of the initial ion species.
in `particleConfig.param`:
```c++
namespace picongpu
{
namespace particles
{
// [...]
namespace manipulators
{
// [...]
typedef ProtonTimesWeightingImpl ProtonTimesWeighting;
typedef RatioWeightingImpl RatioWeighting;
} /* namespace manipulators */
// [...]
} /* namespace particles */
} /* namespace picongpu */
```
in `speciesInitialization.param`: …
=> Particle Manipulators: Init Multi Ion Species

src/picongpu/ArgsParser.cpp, src/picongpu/include/particles/gasProfiles/FromHDF5Impl.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/makroParticleCounter/PerSuperCell.hpp, src/tools/livevis/client/mainwindow.cpp, src/tools/png2gas/png2gas.cpp, src/tools/splash2txt/splash2txt.cpp, src/tools/splash2txt/tools_splash_parallel.cpp
C++ catch parameters should be passed by const reference.
Sorry for the cross-over change.
Did not see relevant implications right now, but should be fixed.
References:
- http://en.cppreference.com/w/cpp/language/try_catch
=> Catch By Reference

src/picongpu/ArgsParser.cpp
Found by @erikzenker: if no parameters are set while calling `./picongpu` the *required* parameter `-g` for the grid size will also be missing. This should call `--help` as one would expect for zero arguments.
New behaviour:
```bash
./picongpu --help
./picongpu
./picongpu -d 1 1 1
```
=> ArgsParser: Help on Missing Params

src/libPMacc/include/Environment.hpp, src/libPMacc/include/simulationControl/SimulationDescription.hpp, src/libPMacc/include/simulationControl/SimulationHelper.hpp
The singleton `SimulationDescription` collects a general description of the simulation, such as maximum and current time step and the author that configures and controls it.
The later idea is, that general simulation controls such as the ones described in #19 can manipulate these (e.g., extend or shorten the maximum simulation step or "pause" after next iteration.) Additionally, it might allow to reduce some interfaces that do not depend on "a timestep" but on "the current time step".
Related to #1260
=> SimulationDescription: New Environment Singleton

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorEnergy.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param
This pull request closes issue #1262. It fixes the calculation of the [Larmor energy](https://en.wikipedia.org/wiki/Larmor_formula).
=> Close #1262 Fix Larmor Power in FieldTmp

src/picongpu/include/plugins/output/images/PngCreator.hpp
Uses the new simulation author from ~~#1296~~ as meta information for the created png files.
=> PNG Plugin: Write Simulation Author

src/libPMacc/include/Environment.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
Removes the odd "Env" prefix for the `MemoryInfo` singleton in our `Environment`.
=> Environment: Remove "Env" Prefix from `MemoryInfo`

src/libPMacc/include/random/RNGHandle.hpp, src/libPMacc/include/random/RNGProvider.hpp, src/libPMacc/include/random/RNGProvider.tpp, src/libPMacc/include/random/RNGState.hpp, src/libPMacc/include/random/Random.hpp, src/libPMacc/include/random/distributions/Normal.hpp, src/libPMacc/include/random/distributions/Uniform.hpp, src/libPMacc/include/random/distributions/normal/Normal_float.hpp, src/libPMacc/include/random/distributions/uniform/Uniform_Integral32Bit.hpp, src/libPMacc/include/random/distributions/uniform/Uniform_float.hpp, src/libPMacc/include/random/methods/Xor.hpp, src/libPMacc/include/random/methods/XorMin.hpp
This implements a buffer for storing the random states `RNGProvider` to avoid reinitialising the RNG on every step.
All functionality currently provided by the RNG implementation of PMacc is also provided by this, so it can be used instead of the current implementation.
Typical usage: 
***1) Setup***
1. Create a typedef for the RNGProvider(s) you want to use: `using RNGProvider = PMacc::random::RNGProvider<simDim>;`
2. Create a (per rank) instance of the provider with the required size: `new RNGProvider(Environment::get().SubGrid().getLocalDomain().size)`   
You can optionally specify an id for this instance. The default id is sufficient if there is only one instance per `RNGProvider` type.
3. Initialize it with a (per rank) seed: `rngProvider_->init(seed);`
***2a) Usage with reusable …
=> Implement random buffer

examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/simulation_defines/param/laserConfig.param
This ~~changes~~ adds additional information to the the doc-string for the [beam waist](https://github.com/ComputationalRadiationPhysics/picongpu/blob/71af8e8bf07d9fb36c33df561cc1f796133fc16f/src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp#L138) W0 of the Gaussian Beam and the tilted version of it for laser implementations.
~~Before that, the in-focus intensity was still correct but the waist would have been to small if one was following the documentation. This is an old documentation bug that someone changed in pre-review (svn) times that slipped through.~~ The very short documentation before caused some confusion when trying to compare to experiments (for me :) ).
~~Users: if you are using the GaussianBeam profile in your simulation, please cross-check if the beam waist …
=> Doc Laser Waist: GaussianBeam, PulseFrontTilt

doc/INSTALL.md, src/picongpu/CMakeLists.txt
Adds pre-compiled `boost::math` libraries in our CMake dependency chain. `boost::math` is mainly header-only but some functionality *can* be used as pre-compiled [which saves a lot of compile time](http://www.boost.org/doc/libs/1_59_0/libs/math/doc/html/math_toolkit/overview_tr1.html#math_toolkit.overview_tr1.usage_recomendations) for PIConGPU itself.
Currently, we only need `tr1 double` precision libs, otherwise we have to add more libs in the future. [Here is the full list](http://www.boost.org/doc/libs/1_59_0/libs/math/doc/html/math_toolkit/overview_tr1.html).
The first update explicitly using the pre-compiled `boost::math` functions from `special_functions/bessel` is #1299 to save compile time (see https://github.com/ComputationalRadiationPhysics/picongpu/pull/1299#discussion_r47672450 …
=> Boost: Add pre-compiled math_tr1 (double)

src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/pusher/particlePusherAxel.hpp, src/picongpu/include/particles/pusher/particlePusherBoris.hpp, src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherNone.hpp, src/picongpu/include/particles/pusher/particlePusherPhoton.hpp, src/picongpu/include/particles/pusher/particlePusherVay.hpp, src/picongpu/include/particles/traits/GetMarginPusher.hpp, src/picongpu/include/particles/traits/GetPusher.hpp
This pull request adds an option in ~~`pusher.unitless`~~ *the particle pusher* to extend the margin for field to particle interpolation for the in-pusher interpolation.
This will be necessary for sub-sampling if a particle moves out of the currently stored field data (by one cell) and then wants to interpolate again. 
**Update:**
I use the pusher margins for calculating the neighbors in fields too.
=> add option to extend margin for pusher interpolation

buildsystem/CompileSuite/autoTests/new_commits.sh, doc/INSTALL.md, src/libPMacc/examples/gameOfLife2D/CMakeLists.txt, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/tools/png2gas/CMakeLists.txt, src/tools/png2gas/README.md
Updates the requirements to use PNGwriter 0.5.6+
The latest release fixes a bug with creation time meta data that can potentially cause data corruption (malformed time entry occurred randomly; outside-png data corruption was not seen in the wild with valgrind) and refactors several parts of internal code due to coverity-scan results. The full change log can be [seen here](https://github.com/pngwriter/pngwriter/blob/0.5.6/CHANGELOG.md#056).
The compile suite is already updated and a ticket for a new module on `hypnos-hzdr` was opened (no5200) -> update: is now installed.
=> PNGwriter 0.5.6: Bug Fix and Refactoring

src/picongpu/include/particles/bremsstrahlung/SynchrotronFunctions.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/_defaultUnitless.loader, src/picongpu/include/simulation_defines/param/bremsstrahlung.param, src/picongpu/include/simulation_defines/unitless/bremsstrahlung.unitless
Implements synchroton functions via lookup table. 
The file is located in `particles/bremsstrahlung` because it is used by a follow-up pull request for the bremsstrahlung effect.
See [here](https://en.wikipedia.org/wiki/Synchrotron_function) for the definition.
=> synchrotron functions

examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/fields/laserProfiles/laserWavepacket.hpp, src/picongpu/include/simulation_defines/param/laserConfig.param
Follow-Up to #1232: the implementation of the laser wavepacket regarding the *beam waist* does not fit its [documentation in `laserConfig.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/7bf113456bf64d82b6571171fc039c1f3fba929c/src/picongpu/include/simulation_defines/param/laserConfig.param#L227-L234).
This commit updates the implementation to match the documentation which is then identical to the other laser pulses. Currently, the parameter that was specified is a factor `sqrt(2)` off making the pulse waist effectively *tighter* by this factor than intended.
=> Laser Wavepacket: Implementation != Doc

thirdParty/cmake-modules/FindADIOS.cmake, thirdParty/cmake-modules/FindPNGwriter.cmake
The modules `_FOUND` variable was not set to false on VERSION mismatch. Same as #1284.
See ComputationalRadiationPhysics/cmake-modules#14
=> CMake: ADIOS, PNGwriter _FOUND Var

src/picongpu/CMakeLists.txt
Close #1314 Throws a well-described error during configure with cmake for boost 1.60.0 when used with a C++98 compiler.
See https://svn.boost.org/trac/boost/ticket/11852 for details and https://github.com/boostorg/config/pull/83 for a patch that allows compiling against this version of boost with nvcc and C++98.
=> Close #1314 Boost 1.60.0 Requires C++11

src/picongpu/submit/taurus-tud/k20x_profile.tpl
This pull requests avoids mixing of two gpu types (k20x and k80) on taurus/ZIH/TU Dresden.
The old k20x are back and are also available in the `gpu` queue. To only acces k80 one needs to specify `gpu2` as queue. Additionly the k20x are available via queue `gpu1`.
This pull requetst:
- add k20x queue (gpu1)
- specify k80 queue to only run on gpu2
see:
https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/SystemTaurus#Partitions
for more details on the current setup of the taurus cluster
=> Taurus-TUD: K20X and K80 Queues

src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp, src/libPMacc/include/cuSTL/container/assigner/DeviceMemAssigner.hpp, src/libPMacc/include/cuSTL/container/assigner/HostMemAssigner.hpp, src/libPMacc/include/memory/buffers/DeviceBuffer.hpp
fix crash in cuSTL `DeviceBuffer::assign()`, a kernel was called within an #ifdef block.
Introduced by #1197.
Solves the general problem of calling a host function from a
host device function for the Assigner policy in CartBuffer by inheriting from the policy.
Implements [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern).
Tested with PhaseSpace plugin.
@Flamefire
=> fix DeviceMemAssigner

src/picongpu/include/plugins/common/stringHelpers.hpp
Adds common helpers to create strings (implemented: dates) for plugins as [used in openPMD](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#hierarchy-of-the-data-file).
Example usage for openPMD files (and libSplash/HDF5):
```C++
#include "plugins/common/stringHelpers.hpp"
// [...]
{
std::string date = getDateString("%F %T %z");
ColTypeString ctDate(date.length());
dc->writeGlobalAttribute( threadParams->currentStep,
ctDate, "date",
date.c_str() );
}
```
=> Plugins: Common String Helpers (Dates)

src/libPMacc/include/cuSTL/algorithm/mpi/Gather.hpp, src/libPMacc/include/cuSTL/algorithm/mpi/Gather.tpp, src/picongpu/include/plugins/SliceFieldPrinter.tpp
Before this pull request, cuSTL::algorithm::mpi::Gather assumed all local containers to have an equal size. Now, the algorithm asks each participating rank for its local container size before perfoming the gather operation.
Dependencies:
Tests:
solves #1195
=> fix cuSTL/Gather for supporting static load balancing

src/picongpu/include/fields/background/templates/TWTS/BField.tpp, src/picongpu/include/fields/background/templates/TWTS/EField.tpp, src/picongpu/include/fields/background/templates/TWTS/getFieldPositions_SI.tpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/fields/numericalCellTypes/EMFCenteredCell.hpp, src/picongpu/include/fields/numericalCellTypes/YeeCell.hpp, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ionization/byField/ADK/ADK_Impl.hpp, src/picongpu/include/particles/ionization/byField/BSI/BSI_Impl.hpp, src/picongpu/include/simulation_defines/unitless/fieldSolver.unitless
Refactors the getter of field positions into a trait. Read commit-wise (commit 1: refactor, commit 2: update usage in code).
Adds the previously just commented positions of FieldTmp (currently used in ParticleToGrid always at zero corner.)
Used in the upcoming openPMD branch.
=> Trait: FieldPosition

src/picongpu/include/simulationControl/MovingWindow.hpp
- close #568 *MovingWindow localDimension Values Not Updated*
- fix that offsets for local and global dimensions always set to zero
- copy full selction from `SubGrid` instead only the size
- remove hard overwrite of the global window offset by add tu current value
Additional to the `window.localDimensions.offset` the `window.globalDimensions.offset` was also always zero.
Tests:
=> Fix MovingWindow localDimension

src/libPMacc/include/memory/buffers/GridBuffer.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp
- `GridBuffer.hpp` and `ParticlesBuffer.hpp`: set gpuFree event to communication event
- close #1322 **Freeze of picongpu if used MPI_Allgather in plugin**
A deadlock in the async communication is triggered when process one opened a `MPI_Receive` while the destination process two not opened the `MPI_Send` and starts a MPI collective operation. In this case the event system stops and not start the `MPI_Send` from process two which wait in a side dependency chain. Process one wait for finish of the `MPI_Receive` before it can start the collective operation. Now we had a classical deadlock.
This patch only solve the deadlock a cleanup of the interfaces will done in a separate pull request.
**Tests:**
=> fix deadlock in asyncSend

src/picongpu/CMakeLists.txt
Fix #1324 Work around as found by @Flamefire to mitigate a CUDA <=7.0 bug that prevents Boost 1.60.0 from building.
Previous boost versions are not affected.
fantastic work @Flamefire ! Can you confirm the work-around works for you?
=> Fix #1324 CUDA<7.5 + Boost 1.60.0 + C++11

src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp, src/libPMacc/include/memory/buffers/DeviceBuffer.hpp, src/libPMacc/include/memory/buffers/HostBuffer.hpp
This implements the cartBuffer functions correctly by calling constructors that actually take parameters. Allowing the default ctor is dangerous.
This also adds the missing move operators required for effective returning.
This also supersedes #1093
=> [WIP] cuSTL Host/DeviceBuffers: Contructors (Pointers)

doc/TBG_macros.cfg, examples/SingleParticleCurrent/include/OneParticleSimulation.hpp, examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp, examples/ThermalTest/include/ThermalTestSimulation.hpp, src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
This is a port of the `--softRestarts` option added to libPMacc `SimulationHelper`. It can be used to loop whole simulation for presentations, etc. by splitting `init()`:
- `init()`: allocate memory
- `fillSimulation()`: fill allocated memory with data (from checkpoint or t=0)
- `resetAll()`: reset to state after `init()` so `fillSimulation()`
can be called again (does *not* deallocate memory)
We used it first in our 3D Live visualization and this PR ports it to the mainline.
Unfurtunately, we have to update PIConGPU examples ~~and GoL~~ at the same time since the `SimulationHelper` interface change requires it. The individual changes are in separate commits in this PR.
- ~~update~~ GoL example: ~~add `resetAll` and `fillSimulation`~~ does not use `SimulationHelper` and does therefore not …
=> SimulationHelper `softRestarts`: split `init` and add `resetAll`

examples/SingleParticleCurrent/include/OneParticleSimulation.hpp, examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
`Clear()` in STL language might resize members. What this member does is `assign` a value.
Related to #1333 (naming collision).
@psychocoderHPC @erikzenker
=> FieldJ: `clear()` -> `assign(value)`

src/tools/share/python/modules4picongpu/__init__.py, src/tools/share/python/modules4picongpu/hdf5Radiation.py
This  pull request adds a python module for reading the radiation amplitudes from hdf5 files.
One can add the `modules4picongpu` directory to one's `PYTHONPATH` and use it directly via:
```python
from module4picongpu import radiationHDF5 as h5Rad
a = h5Rad("./simOutput/radiationHDF5/radAmplitudes_{}_0_0_0.h5".format(10000))
plt.imshow(a.get_Spectra()) # spectra in SI units
```
@Heikman @ax3l Who wants to review this pr?
=> add python module to read hdf5 radiation data

src/picongpu/include/plugins/common/stringHelpers.hpp, src/picongpu/stringHelpers.cpp
Adds ArrayOfString helpers for libSplash write calls.
See
https://github.com/ComputationalRadiationPhysics/libSplash/issues/220
for the description of the problem.
If a user wants to write a list of strings into a single HDF5 attribute or date they need to be padded to the longest one, `\0` separated and concatenated. This helper does that.
Use it like this:
```C++
#include "plugins/common/stringHelpers.hpp"
// [...]
// create some strings
std::list<std::string> myListOfStr;
myListOfStr.push_back("short");
myListOfStr.push_back("middle");
myListOfStr.push_back("loooong");
// convert to splash format
helper::GetSplashArrayOfString getSplashArrayOfString;
helper::GetSplashArrayOfString::Result myArrOfStr;
myArrOfStr = getSplashArrayOfString( myListOfStr );
ColTypeString ctSomeListOfStr( …
```
=> Plugins: Common String Helpers (Splash)

src/picongpu/include/simulation_defines/param/gasConfig.param
This pull request updates the naming of charge density used in gas profiles.
=> fix new naming for gas from hdf5 

src/picongpu/include/particles/InterpolationForPusher.hpp, src/picongpu/include/particles/interpolationMemoryPolicy/ShiftToValidRange.hpp
This pull request allows to shift memory during the particle to field interpolation, that  allows to perform interpolation during sub-stepping **if a particle leaves its cell**.
It was suggested by @psychocoderHPC in [this comment](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1201/files#r44545194).
The following test have to be performed  before merging:
Issue #1338 requires using `PMacc::math`.
=> add memory shift option to particle to field interpolation

src/libPMacc/include/memory/buffers/DeviceBuffer.hpp, src/libPMacc/include/memory/buffers/HostBuffer.hpp
`getPhysicalMemorySize()` returns the size in elements, not in bytes.
Also `getPhysicalMemorySize()[0] * sizeof(Type)` may not be the pitch for device pointers (See #1344)
@Heikman: Please merge urgently
introduced by #1094.
=> Use correct pitch for cartBuffer conversion

examples/Bunch/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/SingleParticleCurrent/include/simulation_defines/param/species.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/species.param, examples/SingleParticleTest/cmakeFlags, examples/SingleParticleTest/include/simulation_defines/param/species.param, src/picongpu/include/particles/pusher/particlePusherReducedLandauLifshitz.hpp, src/picongpu/include/simulation_defines/param/pusherConfig.param, src/picongpu/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/unitless/pusherConfig.unitless
This pull request adds the reduced Landau Lifshitz pusher (see [paper by M. Vranic](http://arxiv.org/abs/1502.02432)). It takes care of the classical radiation reaction, that reduces the energy of accelerated, charged particles due to radiation.
This pull request requires to  following pull requests to be merged:
**Without these pull requests, the pusher will not work.**
The following physics tests need to be performed **before** merging to `dev`:
**Requires code update:**
=> add reduced Landau Lifshitz pusher

src/tools/bin/plot_chargeConservation.py, src/tools/bin/plot_chargeConservation_overTime.py, src/tools/png2gas/png2gas.cpp
Follow up to #1259: Due to the update of the naming of some fields in hdf5, the charge conservation tools were outdated. This pull request changes the naming to the new convention. 
```
Density_e -> e_chargeDensity
```
=> Tools: Fix Naming of HDF5 Density

src/libPMacc/include/eventSystem/tasks/Factory.hpp, src/libPMacc/include/eventSystem/tasks/Factory.tpp, src/libPMacc/include/eventSystem/tasks/TaskSend.hpp, src/libPMacc/include/memory/buffers/ExchangeIntern.hpp, src/libPMacc/include/memory/buffers/GridBuffer.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/libPMacc/include/particles/tasks/TaskSendParticlesExchange.hpp, src/picongpu/include/fields/tasks/TaskFieldSendExchange.hpp
- remove copyEvent from all send methods in buffer and tasks
- `TaskSend`: remove member `EventTask copyEvent`
- `tasks/Factory`:
- remove copy event from interface
Follow up of ~~#1326~~
Tests:
=> clean up send interfaces

src/picongpu/include/particles/Particles.tpp, src/picongpu/include/plugins/output/header/MessageHeader.hpp, src/picongpu/include/plugins/output/header/NodeHeader.hpp, src/picongpu/include/plugins/output/header/SimHeader.hpp, src/picongpu/include/plugins/output/header/WindowHeader.hpp, src/picongpu/include/plugins/output/sockets/SocketConnector.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/frequencies/radiation_list_freq.hpp, src/picongpu/include/simulation_defines/param/seed.param
Fix all includes in PIConGPU to use correct [C++ include style](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library) instead of C-style.
~~`stdint` is not standard before C++11 and is replaced with `<boost/cstdint.hpp>` instead.~~ (later when switched to C++11, else will change prefix to `boost` for those types)
=> C Includes: Fix Correct C++ Style

src/tools/livevis/server/include/VisualizationServer.h, src/tools/livevis/server/src/net/tcp_acceptor.cpp, src/tools/livevis/server/src/net/tcp_connector.cpp, src/tools/splash2txt/tools_adios_parallel.cpp
Fix all includes in PIConGPU tools to use correct [C++ include style](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library) instead of C-style.
~~`stdint` is not standard before C++11 and is replaced with `<boost/cstdint.hpp>` instead.~~ (later when switched to C++11, else will change prefix to `boost` for those types)
=> C Includes Tools: Fix Correct C++ Style

src/libPMacc/include/algorithms/math.hpp, src/libPMacc/include/algorithms/math/defines/fmod.hpp, src/libPMacc/include/algorithms/math/doubleMath/fmod.tpp, src/libPMacc/include/algorithms/math/floatMath/fmod.tpp
Recently I used the `fmod()` function at several occasions (TWTS pulse, upcoming fix for the moving Window). So we have to include this math-function in the templates of libPMacc.
Note: The `fmod` function is entirely distinct from the `modf` function, which is already part of libPMacc.
=> Add fmod-function to libPMacc

examples/SingleParticleCurrent/include/OneParticleSimulation.hpp, examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp, examples/ThermalTest/include/ThermalTestSimulation.hpp
Fix all `cassert` (RT assert) includes in PIConGPU examples to use correct [C++ include style](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library) instead of C-style.
=> C Includes Examples: Fix Correct C++ Style

src/libPMacc/include/algorithms/math/doubleMath/abs.tpp, src/libPMacc/include/algorithms/math/doubleMath/comparison.tpp, src/libPMacc/include/algorithms/math/doubleMath/erf.tpp, src/libPMacc/include/algorithms/math/doubleMath/exp.tpp, src/libPMacc/include/algorithms/math/doubleMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/doubleMath/modf.tpp, src/libPMacc/include/algorithms/math/doubleMath/pow.tpp, src/libPMacc/include/algorithms/math/doubleMath/sqrt.tpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/abs.tpp, src/libPMacc/include/algorithms/math/floatMath/comparison.tpp, src/libPMacc/include/algorithms/math/floatMath/erf.tpp, src/libPMacc/include/algorithms/math/floatMath/exp.tpp, src/libPMacc/include/algorithms/math/floatMath/floatingPoint.tpp, src/libPMacc/include/algorithms/math/floatMath/modf.tpp, src/libPMacc/include/algorithms/math/floatMath/pow.tpp, src/libPMacc/include/algorithms/math/floatMath/sqrt.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp, src/picongpu/include/fields/LaserPhysics.hpp
Fix all the `<cmath>` includes to be [C++](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library).
=> cmath: Use Correct C++ Include

examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp
use generic call for particle update
With the current implementation it is not possible to use a particle species without a pusher.
This pull request is needed for #1227.
=> refactor particle update call

src/picongpu/include/plugins/output/header/MessageHeader.hpp, src/picongpu/include/plugins/output/header/NodeHeader.hpp, src/picongpu/include/plugins/output/header/SimHeader.hpp, src/picongpu/include/plugins/output/header/WindowHeader.hpp
Fixes places where stdlibs are not included via
`#include <name>`.
Reported in
https://github.com/ComputationalRadiationPhysics/picongpu/pull/1348/files#r52447267
=> Fix Includes of StdLibs

src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp
before this PR a device-to-device copy was not possible.
=> fix cuSTL/DeviceBuffer assign operator.

compile
It was not possible to e.g. specify multiple cmake options like `-c "-DFoo=1 -DBar=2`
@ax3l
=> Fix incorrect mangling of params

src/picongpu/include/plugins/SliceFieldPrinter.hpp
Corrects a wrong include of std `<string>` that *should never* be put into a namespace.
=> SliceFieldPrinter: Include in Namespace

src/picongpu/CMakeLists.txt
This allows using user defined libraries from the paths in the environment variables (like CMAKE_PREFIX_PATH or BOOST_ROOT) even if a library of the same name is in `/usr/lib/x86_64-linux-gnu/`
@ax3l
=> Fix wrong order in CMAKE_PREFIX_PATH

src/libPMacc/include/preprocessor/struct.hpp
Corrects the wrong usage of `@example` in doxygen blocks.
This generated warnings during doxygen generation.
- [`@example`](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdexample)
is used to cross link example *files*
- [`@code/@endcode`](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdcode)
can be used to add code snippets
=> Doxygen `@code` Snippet Examples

src/libPMacc/include/memory/buffers/ExchangeIntern.hpp, src/libPMacc/include/memory/buffers/GridBuffer.hpp, src/libPMacc/include/memory/buffers/HostDeviceBuffer.hpp, src/libPMacc/include/memory/buffers/HostDeviceBuffer.tpp
The GridBuffer had actually 2 functions: Combine a Host- with a DeviceBuffer and provide exchange methods. This is a design flaw.
Also: Sometimes you know, you never need exchange methods, but only want a simple Buffer, that is on host and device. The GridBuffer is overkill for that usecase.
This splits off the DoubleBuffering to a new class `HostDeviceBuffer`
=> Split off HostDeviceBuffer from GridBuffer

src/libPMacc/examples/gameOfLife2D/include/types.hpp, src/libPMacc/include/memory/buffers/HostDeviceBuffer.hpp
Follow-Up to #1367, fixes forgotten GoL and parallely merged PR #1370 that still used the old include.
Fixes the broken `dev` from the morning, spotted by @Heikman (thx!) :)
=> Fix `pmacc_types.hpp` Includes

src/libPMacc/include/pluginSystem/IPlugin.hpp, src/libPMacc/include/pluginSystem/PluginConnector.hpp, src/picongpu/include/simulationControl/GuardHandlerCallPlugins.hpp
add a new guard region policy class that calls the new method `IPlugin::onParticleLeave()` for each registered plugin whenever particles are leaving the global simulation volume.
Solves #517.
Tested with #1376.
=> Notify plugins on leaving particles

src/tools/share/python/sliceFieldReader.py
The sample script for reading the output files of the SliceFieldPrinter was very slow. This change speeds up execution by approximately a factor of 60. In tests, the readout of a single file is now performed in 30 seconds.
=> Speed up sliceFieldReader.py

src/picongpu/include/particles/gasProfiles/GaussianCloudImpl.hpp
minor fix: `float_32` -> `float_X`
`float_32` causes a compiler error in the Bunch example with 64 bit precision.
=> minor fix: float_32 -> float_X

src/picongpu/include/particles/bremsstrahlung/SynchrotronFunctions.hpp, src/picongpu/include/particles/bremsstrahlung/SynchrotronFunctions.tpp
split `SynchrotronFunctions.hpp` into a hpp and a tpp file.
The reason is, that in the hpp file there is no access to the constants in `SynchrotronFunctions.unitless`
if one includes `SynchrotronFunctions.hpp` in `MySimulation.hpp` due to include dependencies.
=> fix SynchrotronFunctions

src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp
The include is required for the boost move semantics.
The function fixed caused problems in C++11 mode (compile failure) as there the class does not exist. The correct move assignment is here: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp#L103
The bug was introduced by @Heikman in #1375.
=> Add include and fix wrong assignment operator

src/libPMacc/examples/gameOfLife2D/CMakeLists.txt
Followup so that the CMake for the GoL example finds PMacc as the `types.h` is now `pmacc_types.hpp`
=> Find PMacc after #1367

src/libPMacc/include/particles/ParticlesBase.hpp
Use `StrideMapping<AREA, 3,...>` instead of `StrideMapping<AREA, DIM3,..`.
Second parameter of `StrideMapping` is the distance between the SuperCells.
This is a follow up of #1405 but not depend on it.
=> cleanup usage of `StrideMapping`

src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.tpp
- fix `FieldTmp::computeValue`
- fix `FieldJ::computeCurrent`
added by @ax3l:
The result of the wrong usage are race conditions in 2D during *current deposition*: the stride of super cells was accidentally set to `2` super cells instead of `3`. The result of that is, that current writes in the strided ("skipped") super-cell (with the reminiscence of particles close to the super-cells border) are not protected by atomic adds.
For this to have a negative effect in form of a race condition (resulting in *lowered* current deposited in this area), the support of the particle shape must be at least the size of the shortest super-cell-edge, *this is usually not the case*.
3D simulations are not effected.
=> fix `StrideMapping` usage for 2D

src/libPMacc/include/particles/IdProvider.hpp
This can be used to create unique particle IDs as requested in #194 
As requested by @psychocoderHPC everything is done in a static context to allow setting the particle id to the next id as a default, e.g. when assigning particles from a species without an Id to one with an Id.
Getter and setter is implemented for checkpointing.
=> Implement IdProvider for unique ids

compile
@ax3l 
This fixes the bug, that "NO" is ignored by the compilesuite in non-parallel mode
=> Actually exit when pression no

src/libPMacc/PMaccConfig.cmake, src/picongpu/CMakeLists.txt, src/picongpu/main.cu, src/picongpu/submit/titan-ornl/picongpu.profile.example
All cmake files were cleaned up from scorep. We are now using scorep wrapper scripts to instrument the code, see https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Performance-Analysis.
For longer runs manual instrumentation is useful. Since manual instrumentation is guarded by SCOREP_USER_ENABLE we can put this into the source code.
cudaDeviceSynchornize() at program exit is required for scorep to flush the cuda buffers. This prevents the use of flushatexit.
=> Score-P 2.0 instrumentation

src/tools/bin/smooth.py
This pull request fixes a bug causing array size mismatch in the `smooth.py` routine (used by the `plotRadiation` tool) if run under python 3. 
No other python code in `src/tools` seems to rely on int division.
=> fix int division bug if python 3 is used

src/picongpu/CMakeLists.txt
This throws a CMake error when trying to compile with nvcc 7.5 but without C++11 due to the problem as described here: https://github.com/ComputationalRadiationPhysics/picongpu/issues/1290
Discussed with @ax3l
=> Add error when trying to compile picongpu with CUDA 7.5 w/o C++11

src/tools/livevis/client/README.md
`F12` opens a menu with available simulation streams.
That option is so obfuscated, we need to document it.
Also added a note on our tunnel example.
=> Doc: LiveVis Client F12

src/libPMacc/include/particles/IdProvider.def, src/libPMacc/include/particles/IdProvider.hpp
This stores an ever-increasing number maxNumProc in addition to the current next id. This is the maximum number of processes ever used to generate ids. With this, an overflow can be detected on all ranks in cases where it was not possible before.
Due to this change the get/setNextId was changed to get/setState which is more appropriate.
ccing @psychocoderHPC
=> Improve overflow detection

src/picongpu/include/particles/ParticlesInit.kernel
This pull request re-enables the gamma filter flag for the radiation plugin. 
It was not usable before. 
This **does not** fix #1420.
=> fix gamma filter for radiation

buildsystem/CompileSuite/autoTests/new_commits.sh, doc/INSTALL.md, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
The changes in 1.3 (PDC) and 1.4 (SDC) are needed to write the [openPMD standard](https://github.com/openPMD/openPMD-standard/tree/1.0.0).
This changes the API of libSplash and also the files created by it (bool representations, some internal vars, pathes of global attributes).
For more information, please read the libSplash [change log](https://github.com/ComputationalRadiationPhysics/libSplash/blob/v1.4.0/CHANGELOG.md).
- #1053 (enables correct global attributes for this PR)
- #1376 (enables correct global attributes for this PR)
- #1410 (might be unaffected)
- the upcoming `topic-openPMD` PR of mine
=> libSplash: Update to 1.4.0

src/picongpu/include/plugins/common/particlePatches.hpp, src/picongpu/include/plugins/hdf5/openPMD/patchReader.hpp, src/picongpu/particlePatches.cpp, src/picongpu/patchReader.cpp
@psychocoderHPC @erikzenker 
Implements a helper class `PatchReader` to read libSplash HDF5 files with particle patches and to build up a class containing the full list of particle patches for each rank.
For storing the read patches in RAM on each node, a common `ParticlePatches` storage class was implemented (that can also be used with the ADIOS plugin later on).
Compilation of the HDF5 class only occures when libSplash was found (guarded by `ENABLE_HDF5` macros).
Usage, see `plugins/hdf5/restart/LoadSpecies.hpp` in #1428
```C++
#include "plugins/common/particlePatches.hpp"
#include "plugins/hdf5/openPMD/patchReader.hpp"
// [...]
const std::string speciesSubGroup(
std::string("particles/") + FrameType::getName() + std::string("/")
);
// load particle patches offsets to find own patch …
```
=> openPMD: Particle Patch Reader

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Density.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.def, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/SIBaseUnits.hpp
Added alongside `getUnit()` the new interface to get the openPMD dimensionality of a data set for all basic fields and `FieldTmp` solvers.
=> Fields: Add getUnitDimension() Interface

src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp
This supersedes #1432 and closes #1434.
As the documentation of boost.Move states (http://www.boost.org/doc/libs/1_49_0/doc/html/move/how_the_library_works.html), one has to use `BOOST_COPY_ASSIGN_REF` for the copy assignment. This was not done in #1375 and #1401 and resulted in failures as the one in #1434/#1376
With this PR #1376 compiles on hypnos5
Note: Minor changes to have `HostBuffer.hpp` and `DeviceBuffer.hpp` symmetric for easier comparison
TLDR: RTFM :+1: 
@Heikman
=> Fix move emulated classes copy assignment

src/libPMacc/include/communication/CommunicatorMPI.hpp
The current implementation makes the compiler throw some warnings about out-of-bounds array accesses which are especially correct for an instantiation with `DIM=1`
This implementation fixes this by adding appropriate checks.
It also closes the open TODO in the code.
=> Make CommunicatorMPI dim-safe

src/libPMacc/include/particles/IdProvider.def, src/libPMacc/include/particles/IdProvider.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/NDScalars.hpp, src/picongpu/include/plugins/adios/restart/ReadAttribute.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.def, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/hdf5/NDScalars.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/AdiosToPIC.tpp, src/picongpu/include/traits/PICToAdios.tpp, src/picongpu/include/traits/PICToSplash.tpp, src/picongpu/include/traits/SplashToPIC.tpp
Requires:
This adds a speciesAttribute `particleId`, the traits for units and initializes the `IdProvider` in `MySimulation`.
It also implements saving and loading from HDF5 and ADIOS just like the moving window slider.
=> Particle ids

src/picongpu/include/plugins/hdf5/HDF5Writer.hpp
Follow up on #1410 to fix its newly introduced RT error.
Might only have shown up with log level `INPUT_OUTPUT` enabled.
=> HDF5: Fix Log RT Error

src/picongpu/submit/lawrencium-lbnl/picongpu.profile.example
=> Lawrencium (LBNL): Module Updates

src/picongpu/include/fields/background/templates/TWTS/BField.hpp, src/picongpu/include/fields/background/templates/TWTS/BField.tpp, src/picongpu/include/fields/background/templates/TWTS/EField.hpp, src/picongpu/include/fields/background/templates/TWTS/EField.tpp
This is a bugfix/feature upgrade, which enables to also use negative tilt angles `phi`. Until now the code was already running for `phi<0`. However, the results were subtly wrong, because the original TWTS field solution is only defined for `phi>0`, but nevertheless returns an *almost* correct result for `phi<0`.
In this specific implementation that issue is fixed by using symmetry properties of the TWTS pulse. In the laser specific coordinates of the TWTS pulse the entire pulse is rotated by 180° around the z-axis in order to achieve an inverted pulse front tilt. The rest of the code then already takes care of the correct field positions and field vector orientations.
Have fun! :boom:
=> Range of validity: TWTS pulses with negative tilt angles

src/picongpu/include/fields/background/templates/TWTS/BField.tpp, src/picongpu/include/fields/background/templates/TWTS/EField.tpp
use `DIM2` instead of `simDim` in methods which are specialized to a specific simulation dimension
The compiler evaluates all methods which are specialized for a simulation dimension. In the three dimensional case `pos[i+1]` in the 2d specialization inside a loop from `[0;simDim)` creates a out of array access even this specialization is not used in the three dimensional case.
CC-ing: @BeyondEspresso
=> fix warning in TWTS

src/picongpu/submit/pizdaint-cscs/SLURM_Tutorial.md, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/picongpu.profile.example, src/picongpu/submit/pizdaint-cscs/total_profile.tpl
- close issue #1442
- add template file `*.tpl` for the queue `normal` and `total`
- copy and update SLURM tutorial from `../tarus-tud/`
- add `picongpu.profile.example` for a currently working environment
#1442 gives a short summary over the **Piz Daint** HPC system
=> add templates for the system piz daint

src/picongpu/include/particles/traits/MacroWeighted.hpp, src/picongpu/include/particles/traits/WeightingPower.hpp, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless
This commit adds a new trait to the particle attributes describing each attribute's correlation in PIConGPU regarding macro particles.
Depending on the implementation of an attribute, it might be sometimes useful to return a quantity regarding one of the underlying real particles (false: "this attribute is not weighted accordingly for the whole ensemble of particles in its macro particle) or just handle the whole macro particle at once (true: "this attribute is already weighted").
This trait defines for each attribute if it needs to be scaled with the weighting. *How* the scaling with weighting is applied can be queried in the trait `WeightingPower`.
This trait defines how each attribute needs to be scaled with the weighting (linear, quadratic, ...) to convert between "real" and "macro" …
=> Particles: Weighting Traits

src/picongpu/include/particles/creation/creation.hpp, src/picongpu/include/particles/creation/creation.kernel
Add a general module for particle creation. A `particleCreator` functor may generate one or multiple new target particles out of a single source particle.
=> Add general particle creation module

src/libPMacc/include/math/vector/Vector.tpp, src/libPMacc/include/traits/GetInitializedInstance.hpp
add a libPMacc trait for creating a vector or scalar object with a single parameter.
=> add trait: GetIinitializedInstance

src/libPMacc/include/random/methods/XorMin.hpp
There were some C++11 only features that slipped in. Replaced this with C++98 compatible ones
=> Remove C++11 syntax

doc/TBG_macros.cfg, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.kernel, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/param/particleCalorimeter.param
Adds the particle ~~detector~~ calorimeter plugin.
See the [wiki entry](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Plugin%3A-ParticleCalorimeter) for a detailed description.
Dependencies:
Tested with #1354. The spectrum has also been tested against this python script:
```python
import numpy as np
import h5py as h5
import matplotlib.pyplot as plt
%matplotlib notebook
timestep = 1
species = "ph"
f = h5.File("<path/to/hdf5-calorimeter-file>")
calorimeter = np.array(f["/data/{}/calorimeter".format(timestep)])
unitSI = f["/data/{}/calorimeter".format(timestep)].attrs["unitSI"]
minEnergy = f["/data/{}/calorimeter".format(timestep)].attrs["minEnergy[keV]"]
maxEnergy = f["/data/{}/calorimeter".format(timestep)].attrs["maxEnergy[keV]"]
UNITCONV_Joule_to_keV = 6.241509e15 …
```
=> Feature: Calorimeter Plugin

examples/Bunch/include/simulation_defines/param/radiationObserver.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationObserver.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationObserver.param, src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_lin_freq.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_list_freq.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_log_freq.hpp, src/picongpu/include/simulation_defines/param/radiationObserver.param
This pull request follows the idea behind openPMD and adds information on frequencies and propagation directions computed with the radiation plugin to the hdf5 output.
This pull request adjusts also some examples since the `radiationObserver.param` needed some updates.
@RemiLehe and @ax3l Is this in agreement with todays offline discussion?
**needs:**
=> Output Radiation detector's directions & frequencies

src/picongpu/include/fields/numericalCellTypes/EMFCenteredCell.hpp, src/picongpu/include/fields/numericalCellTypes/YeeCell.hpp
Fix `FieldPosition` trait for `FieldTmp`. ~~The vector dimensions were mixed up.~~
The `FieldTmp` trait was not wrappend in it's one-dimensional vector-vector wrapper.
=> FieldPosition Trait: ReturnType of FieldTmp Consistent

src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/hdf5/WriteFields.hpp, src/picongpu/include/plugins/hdf5/WriteSpecies.hpp, src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, src/picongpu/include/plugins/hdf5/restart/LoadSpecies.hpp, src/picongpu/include/plugins/hdf5/writer/Field.hpp, src/picongpu/include/plugins/hdf5/writer/ParticleAttribute.hpp, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/PICToOpenPMD.hpp, src/picongpu/include/traits/PICToOpenPMD.tpp, src/picongpu/include/traits/Unit.hpp, src/tools/bin/plot_chargeConservation.py, src/tools/bin/plot_chargeConservation_overTime.py, src/tools/bin/splash2vtk.sh
@psychocoderHPC 
This PR implements:
- the openPMD base standard, [v1.0.0](https://github.com/openPMD/openPMD-standard/tree/1.0.0), for our HDF5 output
- much of the [`ED-PIC` extension](https://github.com/openPMD/openPMD-standard/blob/1.0.0/EXT_ED-PIC.md) (just missing a few string-attributes)
- constant particle records: `mass`, `charge`
- [`particlePatches`](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#sub-group-for-each-particle-species) instead of the old `particle_info` object
- restarts from same GPU configuration (tested with `-m` in LWFA example)
- checkpoints and dumps tested with openPMD validator scripts (base standard is passing)
- change: unitless attributes now have the `unitSI` of `1.0` since we can identify those already via an all-zero …
=> openPMD 1.0.0: Base Standard in HDF5

src/picongpu/submit/titan-ornl/batch_profile.tpl, src/picongpu/submit/titan-ornl/batch_scorep_profile.tpl
I think it is better to have picongpu.profile in $PROJWORK/$projid/$USER, since each user should use his own configuration.
=> Changed path for picongpu.profile on lustre.

examples/Bunch/include/simulation_defines/param/radiationObserver.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationObserver.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationObserver.param, src/picongpu/include/simulation_defines/param/radiationObserver.param
This pull request fixes wrong documentation in the `radiationObserver.param` 
The laser propagation was wrongly stated as towards `+x direction.
Thanks @Heikman for pointing me to these errors.
=> fix documentation (and values) in radiationObserver.param

src/libPMacc/include/nvidia/functors/Add.hpp, src/libPMacc/include/nvidia/functors/Assign.hpp, src/libPMacc/include/nvidia/functors/Max.hpp, src/libPMacc/include/nvidia/functors/Min.hpp, src/libPMacc/include/nvidia/functors/Mul.hpp, src/libPMacc/include/nvidia/functors/Sub.hpp
This pull request fixes the wrong namespace indentation, removes superfluous empty lines and adds ending comments to namespaces in `libPMacc/include/nvidia/functors` as discussed in #1455 with @ax3l .
=> fixe code formating in nvidia/functors

src/picongpu/include/plugins/radiation/Radiation.hpp
This pull request enables radiation restart and any multi species hdf5 output with more than one radiating species. This closes issue #1424.
=> Close #1424: add species name to file name of hdf5 rad files

src/libPMacc/include/random/RNGProvider.tpp
remove c++11 syntax from RNGProvider.
@Flamefire
=> remove c++11 syntax from RNGProvider

src/libPMacc/include/math/vector/Vector.hpp
Currently `sqrtf` was used, which is the floating point function. This is crucially wrong for double vectors, especially as taking the square root already looses significant digits.
This uses the type generic version from `PMacc::algorithms::math`
=> Use correct sqrt function for abs(Vector)

src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp
The (or another) last PR in a series for fixing the copy and move assignment of cuSTLs Host<->Device transfers.
Problem was, that the template version of the assignment operator was to greedy, so it takes either the boost move instances `boost::rv` or the `const DeviceBuffer&`, but making the correct function take both is not possible, as on involves a conversion in C++98. In C++11 the boost class will not exist, so one can't use it directly either.
Solution: Only enable the function if we actually have a HostBuffer. Same is applied for the HostBuffer itself and the includes were also cleaned up in the process.
@Heikman
=> Use enable_if to deselect template version

src/picongpu/include/algorithms/FieldToParticleInterpolation.hpp
Up to this PR FieldToParticleInterpolation could only handle fields of 3D vectors.
This PR extends it to 1D and 2D vectors.
=> extend FieldToParticleInterpolation to 1D- and 2D-valued fields.

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp, src/picongpu/include/particles/pusher/particlePusherVay.hpp, src/picongpu/include/plugins/EnergyParticles.hpp
This is a pull request replaces `sqrtf` by `algorithms::math::sqrt` in the picongpu main code.
This is similar to #1461 where @Flamefire replaced `sqrtf` in libPMacc.
=> replace sqrtf with algorithms::math::sqrt

src/libPMacc/include/mappings/simulation/ResourceMonitor.hpp, src/libPMacc/include/mappings/simulation/ResourceMonitor.tpp, src/libPMacc/include/particles/operations/CountParticles.hpp
This PR was split from PR #1403.
The resource monitor is located in libPMacc and provides information about allocated resources of the library. Currently, particle count and cell count per rank are provided.
=> Resource monitor class

src/libPMacc/include/debug/DebugBuffers.hpp, src/libPMacc/include/math/vector/compile-time/Float.hpp, src/libPMacc/include/pmacc_types.hpp
Titel says it all. Just discovered that.
Did not cause any problems because files were not used.
=> Fix 2 includes and a duplicate define

src/libPMacc/include/algorithms/math/doubleMath/abs.tpp, src/libPMacc/include/algorithms/math/floatMath/abs.tpp
- on device use `::fabs()` for double values
- on host use `std:abs()` for double values
- use `::fabsf()` for float values
[Documenation `fabsf`](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html)
[Documenation `fabs`](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__DOUBLE.html)
I can't find a documentation for `::abs()` in the cuda header files. The wrong usage for float values should only result in an implicit cast and a slow abs call (maybe optimized by the compiler beauce we use fast_math)
This bug effects the latest release but we saw no issues in the past.
=> fix usage of wrong `abs()` function

src/picongpu/include/plugins/hdf5/writer/Field.hpp
Corrected the order of `axisLabels` to be correctly `z;y;x` as in `F[z][y][x]`.
(Or in 2D: `y;x` as in `F[y][x]`)
Also moves the allocation of the static size c-array of strings from heap to the stack.
=> openPMD (HDF5): `axisLabels` Order Corrected

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Counter.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Density.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/Energy.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/EnergyDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/LarmorPower.def
The `getUnitDimenions` interfaces create a `std::vector` which is only usable on host side (and only needed there for now).
Caused a warning in an other (upcoming) implementation.
=> `getUnitDimensions`: Use only `HINLINE`

examples/Bunch/include/simulation_defines/param/laserConfig.param, examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param, src/picongpu/include/simulation_defines/param/laserConfig.param
Remove confusing comments from `laserConfig.param`. (Reported a user on the mailing list.)
=> `laserConfig.param`: Remove Confusing Comments

src/libPMacc/include/algorithms/math/defines/trigo.hpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
This pull request adds `atan` to `algorithm::math::` in **libPMacc** as requested by @psychocoderHPC in #1468.
=> add atan to algorithms::math

examples/SingleParticleCurrent/include/CheckCurrent.hpp, src/libPMacc/include/cuSTL/cursor/navigator/CartNavigator.hpp, src/libPMacc/include/math/vector/Vector.hpp, src/picongpu/include/particles/interpolationMemoryPolicy/ShiftToValidRange.hpp, src/picongpu/include/particles/pusher/particlePusherAxel.hpp, src/picongpu/include/plugins/radiation/particles/PushExtension.hpp
- remove math function implementations in Vector.hpp ￼…
- remove `dot()`
- remove `abs()`
- remove `abs2()`
- remove `floor()`
-  fix usage of deleted math functions
This pull requests close #1338
Todo:
=> Topic remove vector math implementations

src/libPMacc/include/pmacc_types.hpp
This is a minor refactoring that unifies the 3 CUDA error printing functions and introduces special macros that do the printing itself.
I use them in a follow-up PR where the return code was already checked and I DO want to throw an exception.
=> Unify cuda error printing

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
This pull request replaces the use of `tanf()` and `atanf()` in picongpu as suggested by @psychocoderHPC in #1462 by `algorithms::math::(a)tan()`.
Since `atan` did not exist in `algorithms::math` before, this pull request adds it as well. 
There are no other trigonometric functions in float format.
**This pull request requires a rebase after:**
=> Replace trigonometric float functions

src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp
fix inverted warning and error message
This bug effects the latest release **but there is no need for a back port**. Only the error message was wrong.
=> fix particle out of mem error/warning

src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless
Adds more in-code references and online documents to the files `speciesAttributes.param/unitless`. Explains the traits that need to be implemented for each species' particle attributes.
Related to #1480
=> `speciesAttributes`: Add In-Code References

src/libPMacc/include/eventSystem/events/CudaEvent.hpp
There is a potential deadlock, when the eventsystem waits for the completion of an event (e.g. after a kernel) but the kernel errors (e.g. invalid memory access, timeout, ...) As in this case `cudaEventQuery` will always return an errorcode the eventsystem will never receive a `cudaSuccess`/`CudaEvent::isFinished` and loops forever.
=> Cuda event fix to avoid deadlock

src/libPMacc/include/dimensions/GridLayout.hpp
Allows usage of  `const GridLayout&` parameters
=> Add missing const for getter in GridLayout

src/libPMacc/include/random/methods/MRG32k3a.hpp, src/libPMacc/include/random/methods/MRG32k3aMin.hpp
This adds another random number generator that can be used to compare those against each other.
Note that this are the only 2 implemented in CUDA that can be used easily. The others require multiple threads calling them in sync with the same state which is very hard in the current design of picongpu/PMacc.
Also added the corresponding Min state generator that cannot directly be used for normal distributions but uses less memory and is much faster (~20% in my local test)
Update: Just tested this on the K20: I see speedups of about 300% when using the Min state. Talking numbers:
- Gridsize=256x256
- Samples per Cell=100.000
- Time CUDA state: 24.4s
- Time Min state: 8.1s
=> Add MRG32k3a RNG generator

src/picongpu/include/plugins/ChargeConservation.tpp
Creates the output file only if the plugin is enabled.
Solves #1419.
=> fix charge conservation plugin

examples/Bunch/cmakeFlags, examples/SingleParticleCurrent/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleRadiationWithLaser/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleTest/include/simulation_defines/unitless/physicalConstants.unitless, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/synchrotronPhotons/PhotonCreator.def, src/picongpu/include/particles/synchrotronPhotons/PhotonCreator.hpp, src/picongpu/include/particles/synchrotronPhotons/SynchrotronFunctions.hpp, src/picongpu/include/particles/synchrotronPhotons/SynchrotronFunctions.tpp, src/picongpu/include/particles/traits/GetPhotonCreator.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/_defaultUnitless.loader, src/picongpu/include/simulation_defines/param/physicalConstants.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/synchrotronPhotons.param, src/picongpu/include/simulation_defines/unitless/physicalConstants.unitless, src/picongpu/include/simulation_defines/unitless/synchrotronPhotons.unitless
Implement synchrotron radiation of photons for electrons. It takes the numerical model from:
> Gonoskov, A., et al. "Extended particle-in-cell schemes for physics in ultrastrong laser fields: Review and developments." Physical Review E 92.2 (2015): 023305.
**Dependencies:**
Photon spectrum:
Zoom:
**legend:**
green: analytical result
blue: simulation result, error bars: statistical error
- ~~photons are created, but they don't move despite of the photon pusher.~~
- ~~ugly compiler warnings.~~
=> Synchrotron photon emission

src/libPMacc/include/random/RNGProvider.tpp
This makes it possible to load states from HDF5 file as init does not need to be called in that case.
=> Register RNGProvider in Ctor

src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
The creation of that file is handled by PMacc so should be the reading.
This also changes the function, so that it returns a vector of checkpoints instead only the last one. This is required, because actually one should only restart from one of those checkpoints even when `--restartStep` is passed. At least one needs to load the last checkpoint before `restartStep`
However the implementation of that change is left to another issue.
=> Move readCheckpointMasterFile to PMacc

src/libPMacc/include/random/RNGProvider.hpp, src/libPMacc/include/random/RNGProvider.tpp
This adds `getStateBuffer` for write access to the internal buffer. This can be used for checkpointing.
In preparation for work by @psychocoderHPC to make it not store any state, there is a added comment that the buffer might be empty.
This required some moving of members to avoid multiple `private`, `public` keywords and also uses only a `HostDeviceBuffer` instead of a `GridBuffer`
=> Add GetStateBuffer to RNGProvider for checkpointing

src/picongpu/include/particles/Particles.kernel
fix wrong calculation of `localCellIdx`
This bug was introduced with #959
=> fix `localCellIdx` in `kernelCloneParticles`

src/picongpu/include/plugins/ChargeConservation.tpp
Fix a segfault in the charge conservation (checker) plugin which is triggered when the plugin is disabled (default) and checkpoints are written.
ccing @Heikman
=> Plugin: Fix ChargeConservation Checkpointing

src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/traits/GetPusher.hpp, src/picongpu/include/simulation_defines/unitless/pusherConfig.unitless
Refactores the access and selection of pushers (in unitless) so our `GetPusher<>` traits can access the implemented method directly.
This avoids `SomeTrait<...>::type::type` accesses which are bad style.
(`pusherConfig.unitless` is not used in examples since it only contains defines)
=> Pusher: Inherit Attributes

src/picongpu/include/algorithms/AssignedTrilinearInterpolation.hpp, src/picongpu/include/algorithms/FieldToParticleInterpolation.hpp, src/picongpu/include/fields/FieldManipulator.hpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp, src/picongpu/include/fields/MaxwellSolver/Lehe/LeheSolver.hpp, src/picongpu/include/fields/MaxwellSolver/None/NoSolver.hpp, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/fields/currentInterpolation/Binomial/Binomial.hpp, src/picongpu/include/fields/currentInterpolation/None/None.hpp, src/picongpu/include/fields/currentInterpolation/NoneDS/NoneDS.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/pusher/particlePusherAxel.hpp, src/picongpu/include/particles/pusher/particlePusherBoris.hpp, src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherPhoton.hpp, src/picongpu/include/particles/pusher/particlePusherReducedLandauLifshitz.hpp, src/picongpu/include/simulation_types.hpp
Add ([openPMD](https://github.com/openPMD/openPMD-standard) compatible) string properties to all essential PIC solvers so we can query them easily in plugins, bindings and I/O.
Ideally, all new parts of the PIC algorithm should now try to implement names properties (see #1507) the same way as we implement margins, etc. to make the code base self-describing.
=> PIC Methods: Add (openPMD) String Properties

src/picongpu/include/plugins/common/stringHelpers.hpp, src/picongpu/stringHelpers.cpp
Add string helper classes to concat an array of strings for the ADIOS library.
This is the same as #1323 has been for libSplash (HDF5)
@psychocoderHPC @PrometheusPi
=> ADIOS: Add String Helper

src/picongpu/include/particles/traits/GetSpeciesFlagName.hpp, src/picongpu/include/plugins/hdf5/WriteSpecies.hpp
Refactors the `GetSpeciesFlagName` trait so it can be used throughout the whole code (and in the upcoming openPMD ADIOS PR).
=> Trait: GetSpeciesFlagName

src/picongpu/include/plugins/adios/ADIOSCountParticles.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteMeta.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp
Implements the openPMD standard including the ED-PIC extension for our ADIOS plugin.
After first visual tests, this works with the latest ADIOS 1.9.0+ release but some string endings are broken if the latest `master` (~ https://github.com/ornladios/ADIOS/commit/b1038dea0145e46474b610163a184c000c371566) of ADIOS is not used (fixed bug).
What is not implemented is the refactoring of `particlePatches` (former `particles_info`) for openPMD (optional and recommended). This can be done in a follow-up PR and also after the next release. For now this does still work and one can generate the particle patch information in post-processing (I have done this successfully on Titan during the last year).
Also, I could not test the [openPMD-validator](https://github.com/openPMD/openPMD-validator) scripts …
=> openPMD: ADIOS

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/simulation_defines/param/fileOutput.param
User interface, `fileOutput.param`: Refactor the previous "sloppy" `density` which always was a `charge density` and add a real `density` option in `FieldTmp` generated, particle-derived fields.
- `DensityOperation`: from charge density to real density
- `ChargeDensityOperation`: new, previously called `DensityOperation`
(namings in the output files have already been fixed in previous PRs such as #1259 in the current dev)
=> IO: Density & Charge Density

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
remove that error is thrown if deselected attribute is not available in a particle
This pull request allow to solve #1496
=> extent deselect on particles

src/picongpu/include/particles/ParticlesInit.kernel
If no zero particles per cell should be created the implementation of `Quiet` started creates a division by zero.
This pull request solves the problem and calculate the position only if we need to create a particle.
=> avoid division by zero

src/picongpu/include/plugins/output/images/Visualisation.hpp
remove shared memory `bool` with `int` variable to allow save atomic operations
The issue with the old implementation is that there is no atomicExch operation for `bool` and if we use a reinterpret cast to `int` we overwrite more than 1byte and create an memory overflow.
=> fix illegal memory access

examples/Bunch/include/simulation_defines/param/speciesInitialization.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesInitialization.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/ThermalTest/include/simulation_defines/param/speciesInitialization.param, examples/WeibelTransverse/include/simulation_defines/param/speciesInitialization.param, src/picongpu/include/particles/InitFunctors.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/manipulators/ProtonTimesWeightingImpl.def, src/picongpu/include/particles/manipulators/ProtonTimesWeightingImpl.hpp, src/picongpu/include/particles/manipulators/RatioWeightingImpl.def, src/picongpu/include/particles/manipulators/RatioWeightingImpl.hpp, src/picongpu/include/simulation_defines/param/speciesInitialization.param
- close #1496 
- rename  `kernelCloneParticles` to `kernelDeriveParticles `
- rename `ManipulateCloneSpecies` to `ManipulateDeriveSpecies`
- rename `CloneSpecies` to `DeriveSpecies`
- deselect `particleId` in `kernelDeriveParticles`
- update documantation
Dependencies:
=> Clone -> Derive(Manipulate) Particles

src/picongpu/include/plugins/adios/ADIOSWriter.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp
Fixes #1506 by allocating and deallocating each field according to the component that is in that moment written.
=> Fix #1506 ADIOS Field Floats

src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example
Adds [GNU Parallel](http://www.gnu.org/software/parallel) as an xargs + array job alternative to the Rhea post-processing environment example.
Example job script:
```bash
#!/usr/bin/env bash
#PBS -N h5ExSlice
#PBS -S /bin/bash
#PBS -q batch
#PBS -A aph101
#PBS -l walltime=48:00:00
#PBS -l nodes=10
#PBS -l gres=atlas2
#PBS -d /lustre/atlas2/myProj/proj-shared/runs/myRun/simOutput
#PBS -o h5_slice/h5_slice.gnup.Qsub.out
#PBS -e h5_slice/h5_slice.gnup.Qsub.err
source $PROJWORK/aph101/pythonOnRhea.profile
source $(which env_parallel.bash)
rm h5_slice/h5_slice.gnup.Qsub.out.{out,err}
f=$(ls simData_*.bp)
ppn=2 #16
nodes=($(cat $PBS_NODEFILE | sort -u))
num_n=${#nodes[@]}
nodes_gnup=$(printf ",$ppn/%s" "${nodes[@]}")
nodes_gnup=${nodes_gnup:1}
nodes_gnupS=$(printf ",%s" "${nodes[@]}") …
```
=> Rhea (ORNL): Update Post-Processing Env

src/picongpu/include/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp
Follow-up to #1520 fixing the restart with ADIOS and openPMD.
While reading the particle attributes again, renaming (`positionOffset` in openPMD is `globalCellIdx` in PIConGPU) needs to take place (as in [HDF5](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1428/files#diff-e85d4780b8b95f839a9a35695b6ad496)).
@psychocoderHPC @PrometheusPi
=> Fix ADIOS Restart

thirdParty/cmake-modules/FindSplash.cmake
Updates the hints how to find libSplash and the usage of an already found path.
- https://github.com/ComputationalRadiationPhysics/cmake-modules/pull/15 (@Flamefire)
Updated via
```
git subtree pull --prefix thirdParty/cmake-modules/ \
git@github.com:ComputationalRadiationPhysics/cmake-modules.git dev --squash
```
=> CMake Modules: Update libSplash Hints

src/picongpu/include/particles/ionization/ionizationMethods.hpp, src/picongpu/include/particles/manipulators/CreateParticlesFromParticleImpl.hpp, src/picongpu/include/particles/synchrotronPhotons/PhotonCreator.hpp
deselect the particle id before a particle is created from another particle
This pull request is needed to support particle ids together with ionization and synchrotron radiation.
=> deselect `particleId`

src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/tools/bin/plot_chargeConservation_overTime.py
HDF5 and ADIOS plugins now create their regular dumps (`notify`) in directories `h5/` and `bp/` inside our `simOutput/`.
This makes reading and working with simulation data way easier, since our "base" directory is not "polluted" any more with many files.
At the same time, the handling of those directories (creation) needed an adjustment, I used that to reduce its complexity.
RT tests (I/O & restarts) with both HDF5 and ADIOS (after ~~#1529~~) have been successful.
@PrometheusPi @psychocoderHPC
=> I/O: Use Own Directories

src/picongpu/include/particles/particleToGrid/derivedAttributes/MomentumComponent.hpp
remove unused variable to avoid compiler warnings
=> remove unused variable

src/picongpu/include/simulationControl/MySimulation.hpp
The random number generator is now initialized only if there exist any photon species.
=> fix RNG initialization location

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/ionization/byField/ADK/ADK.def, src/picongpu/include/particles/ionization/byField/ADK/ADK_Impl.hpp, src/picongpu/include/particles/ionization/byField/ADK/AlgorithmADK.hpp, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.def, src/picongpu/include/particles/ionization/byField/ionizers.def
The ADK model has been updated so that now the user is given the choice between the linear and circular polarization case, according to [Delone, Krainov 1998 Phys.-Usp. 41 469](http://iopscience.iop.org/article/10.1070/PU1998v041n05ABEH000393).
=> Specialize ADK for linear or circular laser polarization

src/picongpu/include/simulationControl/MySimulation.hpp
When allocating the RNG memory only 300 MB were free. Thus if the RNG needed a lot of memory (e.g. more than 250MB) no kernel could start. This is avoided by placing the RNG memory allocation before the particle memory allocation.
cc: @Heikman @Flamefire @ax3l 
@ax3l This affects the latest release. **Please back-port this bug fix.**
=> move RNG memory init before particle memory init

src/libPMacc/include/traits/HasFlag.hpp
The specialization of HasFlag has to define a boost::mpl::bool_<>.
(Not a boost::bool_<>)
=> Fix documentation in HasFlag.hpp

src/picongpu/include/simulationControl/MovingWindow.hpp
- fix that window begin to move one time step too late
- fix sliding for the case delta time is equal delta cell in y
`firstSlideStep` and `firstMoveStep` (in the old implementation) were the steps where the virtual particle has already passed the border and not the time step before it will pass the border. This pull request fix it.
@axel This bug effects the realease candidate. I only see wrong slides with directional splitting. Never the less we should add this fix to the current release branch
[update:] This bug can also happen if the result of the division to calculate `firstSlideStep` and `firstMoveStep` has no fraction.
Test:
@ax3l: this pull request solves a inconsistency with exact bounds of `t == floor(t)` between the first[Move/Slide]Step calculation and the …
=> Fix Sliding Window: Offset for dt * c = dy != Slide

src/picongpu/include/particles/ionization/byField/ADK/ADK_Impl.hpp, src/picongpu/include/particles/ionization/ionizationMethods.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/traits/UsesRNG.hpp
**Important refactoring**
Greatly overdue, the random number generator for the ADK model (and all future rate models for ionization) has been exchanged. 
Before we used an RNG that was creating new states during each time step of the simulation which were unique for each step, particle species, cell and MPI rank.
Now the state is created only once and then saved as well as changed for each cell after each use. This implies the uniqueness of the seed for the aforementioned conditions and reduces workload at the same time.
This now allows for faster testing of all the ionization models and more importantly: **highly increased simulation speed** for more sophisticated ionization models than BSI.
Big kudos to @Flamefire ! :tada: 
This pull request depends on the changes in #1541
=> Make use of faster RNG implementation for ionization

src/picongpu/include/plugins/radiation/particles/PushExtension.hpp
This pull request solves a **~~error~~ compile time failure** when the gamma filter of the radiation plugin is ~~called~~ used. 
Error message:
```
.../src/picongpu/include/plugins/radiation/particles/PushExtension.hpp(53): error: "math" is ambiguous
```
This bug has been introduced with [`e92f735`](https://github.com/ComputationalRadiationPhysics/picongpu/commit/e92f7357a40d1e5371e48cccac5407618fcfaf90) - pull request #1472. 
@ax3l This bug effect the latest release (candidate) - please backport it.
=> fix abs2 calculation in pusher extension radiation

INSTALL.md
- update an outdated boost install line
- update gcc recommendation to 4.9
- C++11 hints
- adios 1.10.0 was released (ships mxml)
=> INSTALL.md: Update Install hints

INSTALL.md, buildsystem/CompileSuite/autoTests/new_commits.sh, src/picongpu/CMakeLists.txt, src/picongpu/include/plugins/adios/writer/ParticleAttribute.hpp, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/picongpu/submit/titan-ornl/picongpu.profile.example, src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example, src/tools/splash2txt/CMakeLists.txt
- we used ADIOS post-1.9.0 `master` already and can now use the latest stable release 1.10.0
- pre ADIOS 1.9.0 we had to avoid zero-writes in GPUs without
particles since ADIOS transforms did otherwise crash.
This has been fixed since ADIOS 1.9.0 on our report and
additionally a test has been added upstream in
[`tests/suite/programs/zerolength.c`](https://github.com/ornladios/ADIOS/blob/v1.9.0/tests/suite/programs/zerolength.c)
=> ADIOS: 1.10.0 Update

src/libPMacc/include/pmacc_types.hpp, src/libPMacc/include/ppFunctions.hpp
close #1563 and close #1553
~~- add type to get a architecture depending useful alignment~~
- change `__optimal_align__` based on discussion #1563
- add pre processor macro `PMACC_ROUND_UP_NEXT_POW2`
Tests:
CC-ing: @Flamefire
=> Data Alignment for Kernel Parameters: 16 Byte

src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
The `TBG_TPLFILE` environment suggestion to use the K20 queue was outdated (all other clusters are correct; see #1137).
This updates it so one can submit a file to K20 via:
```bash
tbg -s -t -c submit/<userInput.cfg> /bigdata/hplsim/...
```
=> Hypnos (HZDR): Default -t File Path Update

src/libPMacc/include/particles/tasks/TaskReceiveParticlesExchange.hpp, src/libPMacc/include/particles/tasks/TaskSendParticlesExchange.hpp
- remove retry message in `TaskReceiveParticlesExchange`
- aggregate retry message in `TaskSendParticlesExchange`
offline request from: @Flamefire
=> particles exchange: avoid message spamming

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
- store pointer as last element inside the struct
- remove old (invalid) comment
```
/* IMPORTANT: store first value with big size to avoid		
*
* that pointer is copied byte by byte because data are not aligned		     	
* in this case sizeof(uint32_t)<=sizeof(pointer)		
*/
```
This changes based on the pull request #762.
- The local mem problem effects **not** CUDA 7.5.
- Local mem problem for CUDA 6.5 & 7.0 is solved with this pull request.
- CUDA <= 6.0 was not tested.
Tests:
CC-ing: @Flamefire
=> avoid local memory usage of `Particle<>`

src/libPMacc/include/nvidia/warp.hpp
This fixes #1583.
The warpBroadcast for 64 bit types was broken. The unsigned call resulted in an infinite loop (for some reason this never resulted in any errors) and the signed call did not use the return values. Also using unions the way they were used before is undefined behaviour. So this was replaced by pointer operations.
=> Fix warpBroadcast

src/libPMacc/CMakeLists.txt, src/libPMacc/test/PMaccFixture.hpp, src/libPMacc/test/main.cpp, src/libPMacc/test/memory/HostBufferIntern/copyFrom.hpp, src/libPMacc/test/memory/HostBufferIntern/reset.hpp, src/libPMacc/test/memory/HostBufferIntern/setValue.hpp, src/libPMacc/test/memory/memoryUT.cu
This fixes some issues with the PMacc test system, so it can be used for more tests.
Core:
- Fix cuda warnings (lots of output)
- One exectuable per testcase and dividing into 2D and 3D tests (singletons make it impossible to test this in one program)
- Move some common code into extra files (MPI-init and PMacc init)
Note: This triggers a CMake bug, that may prevent parallel `make` builds due to wrong dependencies between the test object files. See http://stackoverflow.com/questions/39913202/adding-multiple-cuda-executables-leaks-dependencies
=> Improve PMacc testsystem

src/picongpu/submit/bash/bash_mpiexec.tpl, src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/hypnos-hzdr/fermi_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_vampir_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_wait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k80_profile.tpl
The return code of hypnos-hzdr and bash templates for `tbg` are determined by an additional `killall` cleanup line.
This line creates noise on *successful* runs in case no process was found to be killed. This noise is now suppressed.
=> Hypnos & Bash Tpl: Return Code Cleanup

src/libPMacc/include/algorithms/ForEach.hpp
- use function parameters always as const reference
- fix wrong documenation
- fix warning `host function called from host/device`
close #848
This pull request should be back ported to the current release candidate.
=> ForEach always use const references

src/libPMacc/include/memory/buffers/HostDeviceBuffer.tpp
A HostBuffer can never be casted to a HostDeviceBuffer so that CTor would fail to compile when it is used. Removed the cast.
=> Fix constructor for HDBuffer

src/libPMacc/test/particles/IdProvider.hpp, src/libPMacc/test/particles/particlesUT.cu
This adds test for the IdProvider used in PIConGPU.
- Based on #1589
- Requires #1587 for successful run
=> Add test for IdProvider

INSTALL.md, buildsystem/CompileSuite/autoTests/new_commits.sh, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
This pull request increases the PIConGPU dependency for libSplash to `1.5.0+`.
By that, writes that *only* write particles or *only* fields are fixed as described in #1576.
The problem was introduced due to new openPMD attributes that are always written in the mesh and particle path even if no records are added within. The new release of libSplash handles such situations by creating missing groups automatically, thanks to @psychocoderHPC in https://github.com/ComputationalRadiationPhysics/libSplash/pull/250 .
[Updated](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Maintainer%3A-Dependency-Changes):
- CMake files
- install docs
- cluster example profiles
Planned follow-up PR: allows to remove some [dummy](https://github.com/ComputationalRadiationPhysics/picongpu/blob/3e235d …
=> Fix #1576 Fix libSplash Attribute in Empty Group

src/picongpu/include/plugins/hdf5/WriteSpecies.hpp
Follow-up to #1613: When writing [constant openPMD record components](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#constant-record-components) via attributes in an empty group libSplash supports group-creation without "dummy" data set writes.
This removes previous work-arounds that wrote one dummy data set before writing the actual attributes.
merge after #1613, both successfully tested at RT
=> libSplash 1.5.0+: Remove Dummy Writes

src/libPMacc/include/cuSTL/algorithm/kernel/run-time/Foreach.hpp, src/libPMacc/include/cuSTL/container/assigner/DeviceMemAssigner.hpp
close  #1598
- fix boost 1.62.0 compile error
-> reason:  `gcd_evaluator` is moved out of the namespace `boost::math`
- use `boost::math::gcd()` function
The definition of `gcd_evaluator` is not longer located in the namespace `boost::math`.
There is a definition in `boost::integer` but IMO the more clean solution is to use the function `boost::math::gcd()`.
`boost::math::gcd()` select at compile time the best method to calculate the greatest common divisor.
=> fix boost 1.62  boost greatest common divisor usage 

src/tools/bin/tbg
ignore errors during the cfg and tpl file evaluation
example:
```
x=$(basename !TBG_VARIABLE)
```
This example crashed before this pull request do to the fact that *all* variable definitions (`something=...`) were evaluated and then replaced.
The pull request ignored errors during the evaluation. (IMO not critical)
CC-ing: @PrometheusPi
=> fix tbg evaluation error

src/picongpu/CMakeLists.txt
- disable boost template aliases
- remove that boost variadic templates are disabled for CUDA < 7.5
This pull request removed #1325 and disabled template aliases instead. This allows that Boost is allowed to use variadic templates instead of precompiler magic.
template aliases only disable things like:
```C++11
template< typename T>
using X = typename Trait< T >::type;
```
#1602 is needed to compile CUDA8, but this pull request can merged independently.
=> Boost 1.60+ & CUDA 7/8 Compile

src/picongpu/submit/davinci-rice/picongpu.tpl, src/picongpu/submit/hypnos-hzdr/fermi_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_vampir_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_wait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k80_profile.tpl, src/picongpu/submit/joker-tud/fermi.tpl, src/picongpu/submit/joker-tud/fermi_vampir.tpl, src/picongpu/submit/joker-tud/tesla.tpl, src/picongpu/submit/joker-tud/tesla_vampir.tpl, src/picongpu/submit/judge-fzj/m2050.tpl, src/picongpu/submit/judge-fzj/m2050_profile.tpl, src/picongpu/submit/judge-fzj/m2070.tpl, src/picongpu/submit/judge-fzj/m2070_profile.tpl, src/picongpu/submit/keeneland-gt/parallel.tpl, src/picongpu/submit/lawrencium-lbnl/fermi_profile.tpl, src/picongpu/submit/lawrencium-lbnl/k20_profile.tpl, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/total_profile.tpl, src/picongpu/submit/taurus-tud/k20x_profile.tpl, src/picongpu/submit/taurus-tud/k80_profile.tpl, src/picongpu/submit/titan-ornl/batch_profile.tpl, src/picongpu/submit/titan-ornl/batch_scorep_profile.tpl, src/tools/bin/tbg
close #695
- delete command that removed variable definitions `someThing=...` from the template file
- `*.tpl` files: move batch system commands above (the now still existing) bash commands
**Reason for `*.tpl` change:**
Batch system commands must be defined before any bash command. Before this pull request `tbg` deleted all variable definitions in the template file and therefore fulfilled the batch system restriction. 
Removing variable assignments (and due to that defined variables in `.start`) with `tbg` results in side effects and limited functionality for the template file (since those runtime variables will be missing in the `.start` script).
**Old `*.tpl` files are not compatible to this pull request**
=> fix tbg variable substitution

src/tools/splash2txt/tools_splash_parallel.cpp
Update `splash2txt` to understand the new `unitSI` in openPMD instead of the old `sim_unit`.
=> splash2txt: unitSI openPMD

src/picongpu/CMakeLists.txt
`CUDA_NVCC_FLAG` is defined as CACHE, therefore all assignments before were ignored and not given to `nvcc`.
`CUDA_NVCC_FLAG` needs a list of semicolon separated flags.
- move c++11 enabler after `find_package(CUDA ..)`
- add `-std=c++11` separated by semicolon instead of space
=> fix cmake c++11 enable section

src/libPMacc/include/traits/HasIdentifier.hpp
- add compile time message if `HasIdentifier<>` is used for not specialized
- fix documentation
=> add compile time message to `HasIdentifier<>`

INSTALL.md, buildsystem/CompileSuite/autoTests/new_commits.sh, src/libPMacc/CMakeLists.txt, src/libPMacc/PMaccConfig.cmake, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/picongpu/submit/lawrencium-lbnl/picongpu.profile.example, src/picongpu/submit/taurus-tud/picongpu.profile.example
- ~~Does not need a merge before 0.2.0 release branch is opened!~~
For compatibility between C++98/11 build versions of boost and our build, we increase the dependency to boost 1.57.0+
Refs:
- https://svn.boost.org/trac/boost/ticket/6124
- https://svn.boost.org/trac/boost/ticket/6779
- https://svn.boost.org/trac/boost/ticket/10038
> # 6124, #6779, and #10038 are all the same problem.
> 
> The private library interface has been changed to use a plain-old C++03 enum.
> This is the fix suggested by Andy in 6779.
> The fix was too late for 1.57 beta 1, but should be in the final 1.57 release.
=> Dependency: Boost 1.57.0+

INSTALL.md, buildsystem/CompileSuite/autoTests/new_commits.sh, src/picongpu/CMakeLists.txt, src/picongpu/submit/hypnos-hzdr/picongpu.profile.example, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
Update to libSplash 1.6.0, since 1.5.0 did miss features.
**Tests:**
=> libSplash 1.6.0: Dependency

src/picongpu/include/fields/currentDeposition/Esirkepov/Line.hpp
define a default constructor for `Line<>`
This change is needed for #1582
=> add `Line<>` default constructor

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
Currently you can call the `HasIdentifier` trait also for the Particle type which is very useful in some occasions. This adds the counterparts `HasFlag` and `GetFlagType` so they can be used there as well.
Minor fixes not worth mentioning:
- Move boost includes to other boost includes
- Make the `HasIdentifier` look the same as the new traits (much shorter)
=> Specialize HasFlag and GetFlagType for Particle

src/libPMacc/include/memory/buffers/HostDeviceBuffer.hpp, src/libPMacc/include/memory/buffers/HostDeviceBuffer.tpp
Often getting the individual buffers is required. For that one might need to know the type which are now defined.
No behaviour changes
=> Add typedefs for Host/DeviceBuffer

examples/Bunch/include/simulation_defines/param/gridConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param, examples/LaserWakefield/include/simulation_defines/param/gridConfig.param, examples/SingleParticleCurrent/include/simulation_defines/param/gridConfig.param, examples/SingleParticleCurrent/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/gridConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/unitless/physicalConstants.unitless, examples/SingleParticleTest/include/simulation_defines/unitless/physicalConstants.unitless, examples/ThermalTest/include/simulation_defines/param/gridConfig.param, examples/WeibelTransverse/include/simulation_defines/param/gridConfig.param, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/simulation_defines/param/gridConfig.param, src/picongpu/include/simulation_defines/unitless/gasConfig.unitless, src/picongpu/include/simulation_defines/unitless/gridConfig.unitless, src/picongpu/include/simulation_defines/unitless/physicalConstants.unitless
This changes the way we normalize 2D3V simulations by the following, common way: evaluate dZ (choose something in the same order such as dX and dY).
A 2D3V simulation in a cartesian PIC simulation such as ours only changes the degrees of freedom in motion for (macro) particles and all (field) information in z travels instantaneous, making the 2D3V simulation behave like the interaction of infinite "wire particles" in fields with perfect symmetry in Z.
Quantities such as `CELL_VOLUME` are now _always 3D_.
This replaces #1569, should fix #1575 and #240.
=> 2D3V Unit Normalization: Use dZ

src/picongpu/submit/davinci-rice/picongpu.tpl, src/picongpu/submit/hypnos-hzdr/fermi_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_autoWait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_vampir_profile.tpl, src/picongpu/submit/hypnos-hzdr/k20_wait_profile.tpl, src/picongpu/submit/hypnos-hzdr/k80_profile.tpl, src/picongpu/submit/joker-tud/fermi.tpl, src/picongpu/submit/joker-tud/fermi_vampir.tpl, src/picongpu/submit/joker-tud/tesla.tpl, src/picongpu/submit/joker-tud/tesla_vampir.tpl, src/picongpu/submit/judge-fzj/m2050.tpl, src/picongpu/submit/judge-fzj/m2050_profile.tpl, src/picongpu/submit/judge-fzj/m2070.tpl, src/picongpu/submit/judge-fzj/m2070_profile.tpl, src/picongpu/submit/keeneland-gt/parallel.tpl, src/picongpu/submit/lawrencium-lbnl/fermi_profile.tpl, src/picongpu/submit/lawrencium-lbnl/k20_profile.tpl, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/total_profile.tpl, src/picongpu/submit/taurus-tud/k20x_profile.tpl, src/picongpu/submit/taurus-tud/k80_profile.tpl, src/picongpu/submit/titan-ornl/batch_profile.tpl, src/picongpu/submit/titan-ornl/batch_scorep_profile.tpl, src/tools/bin/tbg
- fix runtime errors introduced with #1609
- revert dirty evaluation from #1611
- fix tbg `-o` parameter
- add new syntax to define variables in the tpl files `.varname=value`
- update all tpl files with new syntax: `.var=value` 
Documentation
============
We define two life times for variables.
-  **tbg-time**: this means a variable is visible during the time `tbg` creates the start file `submit.start` for the batch system. it contains several steps:
1. substitute variables defined with `tbg -o` in the `*.cfg` file (overwrite assignments `varName=value`)
2. evaluate the `*.cfg` file
3. substitute variables defined with `tbg -o` in the `*.tpl` file (overwrite **only** assignments `.varName=value`)
4. catch all variables from the current environment and substitute all `!varName` usages
5. …
=> fix tbg runtime errors and param `-o`

src/libPMacc/test/random/2DDistribution.cu, src/libPMacc/test/random/CMakeLists.txt
This adds simple tests for the RNG generators with which compile tests and manual verification can be done.
Runtimetests can be done with `make run`. Manual execution with `mpiexec -n 1 TestRng <numNumbersPerCell>`
Currently only uniform float distribution is used, but others can be used as well. Good fit for tests by @psychocoderHPC 
Later also automatic verification via Boost.Test shall be added. 
Requires MPI execution with 1 GPU and should run reasonably fast (<10 min)
=> Add tests for all RNG generators

src/picongpu/CMakeLists.txt
Revision to #1617 fixing the C++11 enabler for CUDA. Accidentally had environment vars still set while testing with CUDA 8.0.
=> Fix CPP Enabler: CXX_FLAGS

examples/Bunch/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/SingleParticleCurrent/include/simulation_defines/param/species.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/species.param, examples/SingleParticleTest/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/species.param
ZigZag in our implementation, and probably even in the original publications, is not charge conserving #1128.
Move it in the input files down to "development" solvers so users do not use it.
=> ZigZag: Update input Docs (Do not Use)

src/picongpu/include/simulation_defines/param/fieldSolver.param
Close #1586 by documenting the allowed `CurrentInterpolation` schemes in `fieldSolver.param`.
=> Close #1586 Document CurrentInterpolation

src/libPMacc/include/mappings/simulation/GridController.hpp, src/libPMacc/include/mappings/simulation/SubGrid.hpp, src/picongpu/include/simulationControl/MovingWindow.hpp
This fixes a bug that the offset in the `PMacc::Selection` [globalDomain](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions) returned by `Environment<simDim>::get().SubGrid().getGlobalDomain()` was always set to zero (aka "all 0").
The implementation does not change anything else, since the affected object was only used in a conversion from Domain to a Window which naturally has to remove the `globalDomain.offset` (aka "set it to zero=default") anyway.
Already RT tested in combination with the fix for #1625 with LWFA and moving window (including restarts).
=> SubGrid: Set globalDomain Offset

src/libPMacc/include/particles/Identifier.hpp, src/libPMacc/include/particles/operations/ConcatListOfFrames.hpp, src/libPMacc/include/particles/operations/splitIntoListOfFrames.kernel, src/picongpu/include/fields/background/cellwiseOperation.hpp, src/picongpu/include/plugins/adios/ADIOSCountParticles.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/plugins/adios/restart/LoadSpecies.hpp, src/picongpu/include/plugins/hdf5/HDF5Writer.hpp, src/picongpu/include/plugins/hdf5/WriteSpecies.hpp, src/picongpu/include/plugins/hdf5/restart/LoadSpecies.hpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/PICToOpenPMD.hpp, src/picongpu/include/traits/PICToOpenPMD.tpp
This fixes #1625 by creating the correct `positionOffset` in HDF5 writes+restarts which is a *total cellIdx*.
The methods to create and convert the localCellIdx to a cellIdx respectively to certain domain have been abstracted. The PMacc user can now choose to create an arbitrary new cell idx, e.g., a `globalCellIdx` with respect to the global domain as before or a `totalCellIdx` with respect to an absolute start. For PIConGPU, we nowadays always speak in positions with respect to the total domain for all inputs and outputs which is more useful then a globalCellIdx which is rather arbitrarily choosen to be t*c but might not be that physically useful, especially with respect to tracking. This also reduces a lot of code offset calc complexity.
The ADIOS plugin has not yet been updates, …
=> Fix #1625: HDF5 openPMD positionOffset

src/libPMacc/include/cuSTL/cursor/tools/twistVectorFieldAxes.hpp
Allow different permutation for navigation in space and the accessor to the vector field component.
- add two new function signatures
- permutate navigator and accessor with the same permutation vector
- permute navigator and accessor different
- change template parameter nameing
This pull request is needed for the directional splitting changes
=> extent function `twistVectorFieldAxes<>()`

src/picongpu/include/fields/currentDeposition/EmZ/DepositCurrent.hpp, src/picongpu/include/fields/currentDeposition/EmZ/EmZ.def, src/picongpu/include/fields/currentDeposition/EmZ/EmZ.hpp, src/picongpu/include/fields/currentDeposition/RelayPoint.hpp, src/picongpu/include/fields/currentDeposition/Solver.def, src/picongpu/include/fields/currentDeposition/Solver.hpp
EmZ (Esirkepov meets ZigZag) used the trajectory splitting method from ZigZag
to get a configuration where the number of supporting points is fixed at compile time.
The current of the virtual particles is deposited with the Esirkepov schema.
More information coming  soon.
Tests with KHI electrons/positrons 2d and 3d with all shapes:
=> add EmZ current deposition solver

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp
close #1573  FrameType renaming
- rename
- `ParticleTypeBorder` -> `FrameTypeBorder`
- `ParticleDescriptionBorder` -> `FrameDescriptionBorder`
- `ParticleType` -> `FrameType`
- `ParticleDescriptionDefault` -> `FrameDescription`
- `PtrExtension` -> `LinkedListPointer`
- `ParticleDescriptionWithExtendedAttributes` -> `FrameDescriptionWithManagementAttributes`
- `border_particleList` -> `ParticleAttributeListBorder`
- `full_particleList` -> `ParticleAttributeList`
- `PopPushType` -> `BorderFrameIndex`
- add documentation to all typedef's
- update usage of the new types
=> rename typedef's inside `ParticleBuffer`

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/ChargeDensity.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp, src/picongpu/include/particles/particleToGrid/derivedAttributes/MidCurrentDensityComponent.def, src/picongpu/include/particles/particleToGrid/derivedAttributes/MidCurrentDensityComponent.hpp, src/picongpu/include/simulation_defines/param/fileOutput.param
Calculate a "middle" current density (which is not necessarily the average of the closest current density positions) at the position of the charge. Performed component-wise.
Can be used as an alternative way to verify charge conservation.
To use this, add
``` diff
diff --git a/src/picongpu/include/simulation_defines/param/fileOutput.param b/src/picongpu/include/simulation_defines/param/fileOutput.param
index abbea6b..12938b9 100644
--- a/src/picongpu/include/simulation_defines/param/fileOutput.param
+++ b/src/picongpu/include/simulation_defines/param/fileOutput.param
@@ -59,6 +59,23 @@ namespace picongpu
CreateChargeDensityOperation<bmpl::_1>
>::type ChargeDensity_Seq;
+    /* MidCurrentDensityComponent section define "component" as
+     * 0=X (default), 1=Y or 2=Z
+     */
+    typedef …
```
=> FieldTmp: MidCurrentDensityComponent

src/picongpu/CMakeLists.txt
Installing PIConGPU on a minimal distribution in user mode often includes compiling zlib yourself in a non-default directory. This changes the way we look for zlib to find it properly (first found on an AWS instance with CentOS 6.8 installed).
zlib is ~~not used by PIConGPU directly but~~ *used inside the 2D live visualization plugin (same backend as png) and might* come~~s~~ in with a lot of dependencies that do not declare it properly (which only affects linking), *too*.
`m` is a similar candidate but is usually shipped with the compiler stdlib and also has no find module in CMake afaik.
=> CMake: Find non-default zlib

src/libPMacc/include/Environment.hpp, src/libPMacc/include/eventSystem/Manager.hpp, src/libPMacc/include/eventSystem/Manager.tpp, src/libPMacc/include/eventSystem/events/CudaEvent.def, src/libPMacc/include/eventSystem/events/CudaEvent.hpp, src/libPMacc/include/eventSystem/events/CudaEventHandle.hpp, src/libPMacc/include/eventSystem/events/EventPool.hpp, src/libPMacc/include/eventSystem/streams/EventStream.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.tpp, src/libPMacc/include/eventSystem/tasks/TaskLogicalAnd.hpp
close #1189
- remove `EventPool` from task manager
- add `EventPool` as singleton to `Environment<>`
- `StreamTask`
- rename `getCudaEvent()` to `getCudaEventHandle()`
- rename `setCudaEvent()` to `setCudaEventHandle()`
- `TaskLogicalAnd`: rename attribute `hasCudaEvent` to `hasCudaEventHandle`
- `EventStream`: `waitOn()` is using the new `CudaEventHandle`
- full refactor `EventPool`: dynamic number of used cuda events
- rename `CudaEvent` to `CudaEventHandle`
- add `CudaEvent` (wrapper for a native cuda event)
The bug in #1189 is closed with a new feature of the event pool. The event pool now allocates as much cuda events as needed.
=> dynamic EventPool for cuda events

examples/KelvinHelmholtz/include/simulation_defines/param/particleConfig.param, examples/LaserWakefield/include/simulation_defines/param/particleConfig.param, examples/WeibelTransverse/include/simulation_defines/param/particleConfig.param, src/picongpu/include/simulation_defines/param/particleConfig.param
This pull request fixes a wrong comment in `particleConfig.param` where the quiet start implementation was described as random start.
=> fix wrong comment random->quiet

src/libPMacc/include/assert.hpp, src/libPMacc/include/debug/abortWithError.hpp, src/libPMacc/include/verify.hpp
Many assertion checks inside PMacc and PIConGPU were performed with `assert`. 
If PIConGPU/PMACC is compiled in release mode these checks were disabled.
In the most cases this checks are essential checks to validate the user input parameters and should always be evaluated.
This pull request adds PMacc specific asserts and verification macros to choose if a expression needs to be evaluated only in debug mode or also inside the release binary.
- add function `abortWithError()` to create an exception with useful information
- add macro function
- PMACC_ASSERT
- PMACC_ASSERT_MSG
- PMACC_VERIFY
- PMACC_VERIFY_MSG
**Why we are not using`BOOST_ASSERT, BOOST_VERIFY?`**
The boost assert and verify functions ended up with `std::abort()`. This needs signal handling to implement something like #654. …
=> expression validation/assertion

src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
Module update for Hypnos (HZDR): CUDA 8.0, C++11 compile chain with up-to-date file I/O plugins.
Currently being installed:
=> Profile Examples: CUDA8 @hypnos-hzdr

src/picongpu/include/plugins/adios/ADIOSWriter.hpp
In the lastest version of ADIOS, which we depend on as a minimum, the old `int adios_allocate` call was replaced with a more sophisticated method which can further be controlled in its maximum size of buffers via `void adios_set_max_buffer_size(uint MB)`.
This patch uses the new method and removes a warning caused by the old API.
We can actually get rid of the "estimate how much we will write" now if we want and can choose a value that suits us in terms of host RAM, but that's for an other refactoring time (and will also need checks if it really does not affect write performance).
1.10.0: Manual (4.1.2)
http://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.10.0.pdf
1.9.0:  Manual (4.1.2)
http://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.9.0.pdf
=> ADIOS 1.10.0+: New Allocation Call

src/libPMacc/include/compileTime/AllCombinations.hpp
`AllCombinations` did not compile with icc 15.2
This is the first part to fix #732
There is an issue that boost with icc substitutes the first template of `AssignAnyElementInVector` wrongly.
This pull request solves the issue by defining `AssignAnyElementInVector` inside the class and using the template sequence from the parent class.
=> ICC: AllCombinations

INSTALL.md, src/libPMacc/CMakeLists.txt, src/libPMacc/PMaccConfig.cmake, src/libPMacc/examples/gameOfLife2D/CMakeLists.txt, src/picongpu/CMakeLists.txt
It's time to say goodbye C++98. :facepunch: 
- enable C++11 compile
- require cuda >=7.5
- remove c++98 workarounds
- change documentation
- change minimal cuda version to 7.5
- change minimal g++ to 4.9
=> switch to c++11 only

src/picongpu/include/fields/background/templates/TWTS/BField.tpp, src/picongpu/include/fields/background/templates/TWTS/EField.tpp, src/picongpu/include/fields/background/templates/TWTS/GetInitialTimeDelay_SI.tpp, src/picongpu/include/fields/background/templates/TWTS/RotateField.tpp, src/picongpu/include/particles/synchrotronPhotons/SynchrotronFunctions.tpp, src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp, src/picongpu/include/plugins/radiation/amplitude.hpp, src/picongpu/include/plugins/radiation/particles/PushExtension.hpp
- delete explicit call to `PMacc::algorithms::math`
- use short cut `math::*`
The explicit definition of the namespace is a workaround for #1338 and solved with #1472.
This pull request is a cleanup.
=> remove namespace workaround

src/picongpu/include/plugins/adios/ADIOSWriter.hpp
remove `adios_flag_no` with integer value `2`
The interface of `adios_declare_group` is changed in adios version 1.11.0, see #1650
close #1650
=> fix adios 1.11.0 compile

examples/Bunch/include/simulation_defines/param/radiationConfig.param, examples/KelvinHelmholtz/include/simulation_defines/param/radiationConfig.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/radiationConfig.param, src/picongpu/include/plugins/radiation/radFormFactor.hpp, src/picongpu/include/simulation_defines/param/radiationConfig.param
This pull request adds a radiation form factor for a spherical-symmetric charge distribution to avoid ringing from the CIC based shapes.
=> add radiation form factor for spherical Gaussian charge distribution

src/libPMacc/include/simulationControl/SimulationHelper.hpp, src/picongpu/include/initialization/InitialiserController.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp
Deadlock can be triggered if a mpi rank with unfinished PMacc tasks enters a MPI_Barrier.
- wait for all events before enter `MPI_Barrier`
=> Fix Event System Deadlock on MPI_Barrier

CHANGELOG.md, README.md, REFERENCE.md
Prepares the changelog for the 0.2.1 release.
- **README: Document PIC extensions**: Highlight extensions we already added that are not in the
standard PIC cycle.
- **REFERENCE: Add Format for Markdown**: Avoids scrumbling the text when opening the file directly
on a markdown viewer (online).
- **Release 0.2.1: Changelog**
- #1659
@ComputationalRadiationPhysics/picongpu-maintainers please have a look and comment inline. If everything is ok, please approve.
=> [WIP] Release 0.2.1: Changelog
