ComputationalRadiationPhysics/picongpu

buildsystem/CompileSuite/autoTests/get_work.sh, buildsystem/CompileSuite/autoTests/new_commits.sh
- `adios 1.7.0` (already some month in)
- `mallocMC 2.0.1crp` (today)
- only test a specific commit, cronjob will request new work
=> CompileSuite: Update Modules and Do not Loop

doc/TBG_macros.cfg, src/picongpu/include/plugins/adios/ADIOSWriter.hpp
Adds documentation about compression, aggregators and ost.
Fix Typo in ADIOS Plugin Help
=> TBG_macros: Add More ADIOS Flags

README.md
Marco's first pull request was accepted with #595, wuhu!
Welcome Marco!
=> Developers: Add Marco Garten

src/libPMacc/include/nvidia/rng/RNG.hpp, src/libPMacc/include/nvidia/rng/distributions/Normal_float.hpp, src/libPMacc/include/nvidia/rng/distributions/Uniform_float.hpp, src/libPMacc/include/nvidia/rng/distributions/Uniform_int32.hpp, src/libPMacc/include/nvidia/rng/methods/Xor.hpp
- allow instantiation of RNG on the host side
- allow instantiation with default constructor
**This pull request is a part of the up coming multi-species pull request.**
=> refactor nvidia RNG

src/picongpu/include/plugins/radiation/Radiation.hpp
add namespace splash to used `DataCollector`
=> fix missing namespace

src/libPMacc/include/particles/memory/boxes/HeapDataBox.hpp, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/particles/memory/boxes/RingDataBox.hpp
add default constructor that we can use all types as member of structs
**This pull request is used for multi species**
=> add default constructor

src/picongpu/include/compileTime/conversion/TypeToPointerPair.hpp
add rule for `MakeIdentifier` were input is already an identifier
=> extent MakeIdentifier

src/picongpu/include/plugins/radiation/Radiation.hpp
This pull request adds a check to the **Radiation Plugin** testing if the restart file exists and tus closes #709 (partially).
=> close #709 - check existence of radiation restart file

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/Fields.hpp, src/picongpu/include/fields/Fields.tpp, src/picongpu/include/fields/LaserPhysics.def, src/picongpu/include/fields/LaserPhysics.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
- use forward declarations
- add `LaserProfile.def`
- move include for implementations to MySimulation.hpp
**This pull request is needed for multi species to avoid include dependencies**
=> add forward declarations for fields and laser

src/tools/bin/plotNumericalHeating
This pull request
**fixes**:
- a bug introduced with multi species support in #692 that lead to crashes in case of no energy data files
**adds (as issued in #710):**
- support for only one simulation directory
- support for unfinished simulations
It does **not** yet support different time steps. 
Test have already been performed.
=> improve numerical heating tool

src/picongpu/include/particles/Particles.hpp, src/picongpu/include/simulation_types.hpp, src/picongpu/include/traits/GetDataBoxType.hpp
- add new trait
- Particles.hpp: add `GetDataBoxType` trait
=> add new trait `GetDataBoxType`

src/libPMacc/include/eventSystem/events/kernelEvents.hpp, src/picongpu/include/simulation_classTypes.hpp
replace `cudaThreadSynchronize()` (deprecated since cuda4.0) with `cudaDeviceSynchronize()`
=> replace deprecated cuda calls in libPMacc and PIConGPU

src/libPMacc/include/Environment.hpp
- fix that `setDevice` not detect already used device on "process exclusive" compute mode
- implement save device selection
d56c47a55416cb2a82ed486e6cde7af222fe1a06 tried to fix the device selection in the past but it looks like it not solve the problem
*Long version:*
- since NVIDIA changed something in the driver cudaSetDevice never return an error if another process already use the selected device and the gpu compute mode is set to "process exclusive"
- this is independent of the cuda toolkit version (tested cuda 50,..., cuda7.0rc)
- a bug report is send to NVIDIA via mail, therefore I have no bug number
Tests:
=> fix setDevice on compute mode "process exclusive"

src/tools/bin/uncrustifyMyCode
add small script to format code with uncrustify and our [style file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/doc/picongpu_uncrustify.cfg)
=> uncrustify tool for picongpu/PMacc

src/libPMacc/include/algorithms/math/doubleMath/sqrt.tpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/sqrt.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
MSVC does not support non-standard
- sincos, sincosf
- rsqrt, rsqrtf
=> MSVC compatibility

src/libPMacc/include/memory/dataTypes/Mask.hpp
- change switch case implementation to loop algorithm
- use short if for one dimensional case
=> refactor `Mask::getRelativeDirections`

src/picongpu/include/algorithms/DifferenceToLower.hpp, src/picongpu/include/algorithms/DifferenceToUpper.hpp, src/picongpu/include/fields/MaxwellSolver/Yee/Curl.hpp
- refactore operator
- remove fixed 2D implementation by a generic one
**This pull request does not change that the difference is divided by the cell size (issue #820)**
~~**Please do not merge before #806**~~
=> refactore operator `DifferenceTo*`

src/picongpu/include/plugins/adios/ADIOSWriter.hpp
For large scale file system operations, let's wait a second before we hammer in new "open" requests.
(On Titan's Atlas with 4k to-be-opened files I saw several re-tries before a file was "found" in stderr.)
A portable way would be the pre-C++11 `boost::thread::sleep()` which is *already deprecated* since Boost 1.53.0+, so [sleep_for()](http://www.boost.org/doc/libs/1_50_0/doc/html/thread/thread_management.html#thread.thread_management.this_thread.sleep_for) (Boost 1.50.0+) could be used instead, which includes TWO new
dependency (`boost::thread` `boost::chrono`, BOTH must be compiled) and increases our dependencies from 1.49.0+ to 1.50.0+.
In one sentence: big relevant FS only exist in the UNIX world were this sleep would be even relevant and we can use C++11 …
=> ADIOS: Re-Try Open File 1s sleep on Unix

src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp
add comment for the multiplication with the cell size in the current solver
- Esirkepov
- 3D
- 2D
- Native
- ZigZag
=> add current solver documentation

src/tools/livevis/client/run_client.sh
Close #830 Remove Run Script (useless and outdated).
=> Close #830 Remove Run Script

src/libPMacc/include/math/vector/math_functor/max.hpp
add namespace prefix to max function call
=> add namespace prefix to max function call

src/libPMacc/include/cuSTL/algorithm/mpi/Gather.hpp, src/libPMacc/include/cuSTL/algorithm/mpi/Gather.tpp
2D support for cuSTL::algorithm::mpi::Gather
=> 2D support for cuSTL::algorithm::mpi::Gather

README.md
This pull request adds @stetie to the developer team.
=> add Stefan Tietze to developer team

README.md
Merges a stalled branch from my repo.
Maintainer updates:
- @BenjaminW3 Benjamin Worpitz is a maintainer (since about 1 month)
Solute and cannon shots: :postal_horn: :statue_of_liberty: :fireworks: 
- @f-schmitt-zih Felix Schmitt get's the status of a "grey eminence": his words are pure wisdom and young people like you (yes, you!) shall pay him respect as soon as he enlightens you (he still has the maintainer rights but is not active in the current development since he has a *real life* now. somewhere far, far away... :crying_cat_face: ).
- @c-schumann-zih Conrad Schumann is now in former members - thank you a bunch for your contributions (e.g., xdmf scripts & HDF5)! :)
=> Readme: Maintainer Updates

src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.kernel
- change `float` to `float_X`
- cast floating point scalars to `float_X`
=> clean field solver DS float usage

src/libPMacc/include/mappings/kernel/AreaMapping.hpp, src/libPMacc/include/mappings/kernel/ExchangeMapping.hpp, src/libPMacc/include/mappings/kernel/StrideMapping.hpp
change `DINLINE` to `HDINLINE`
=> add host support for kernel mapper

src/picongpu/CMakeLists.txt
add `find_package(OpenMP)` to `CMakeLists.txt`
=> add `OpenMP` support

src/picongpu/ArgsParser.cpp, src/picongpu/include/ArgsParser.hpp, src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp
=> remove deprecated throw declaration

src/picongpu/include/simulation_defines/param/fileOutput.param, src/picongpu/include/simulation_defines/param/memory.param, src/picongpu/include/simulation_defines/param/particleConfig.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/unitless/checkpoints.unitless, src/picongpu/include/simulation_defines/unitless/fieldSolver.unitless
#917 has been divided for better overview.
=> remove invalid typename from .param and .unitless

src/picongpu/include/plugins/PluginController.hpp
=> Fix spelling error

src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp
- remove complicated min/max construct to calculate the relay
point (paper conform change)
- not split the trajectory for a particle which not leaf the cell (optimization)
- return current deposition for a direction if flux is zero (optimization)
- remove particle splitting in 2D for the z component of the current (optimization)
Test:
**Why it is not implemented as separate solver**
The difference to the paper implementation is very small and a second implementation results in 99% code duplication.
=> optimize current deposition `ZigZag`

src/libPMacc/include/memory/boxes/SharedBox.hpp, src/libPMacc/include/particles/ParticlesBase.hpp, src/picongpu/include/plugins/IntensityPlugin.hpp
A few more spelling mistakes...
=> fix spelling mistakes

src/picongpu/include/plugins/PngPlugin.hpp
This seems to be a copy-paste error.
=> fix wrong debug message

src/picongpu/include/plugins/adios/restart/RestartFieldLoader.hpp
=> Fix spelling mistake

src/picongpu/include/particles/manipulators/RandomPositionImpl.def, src/picongpu/include/particles/manipulators/RandomPositionImpl.hpp, src/picongpu/include/particles/manipulators/manipulators.hpp, src/picongpu/include/simulation_defines/param/particleConfig.param
- add manipulator to change the in cell position of particles
=> add manipulator RandomPositionImpl

src/picongpu/include/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, src/picongpu/include/plugins/adios/restart/RestartFieldLoader.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttribute.hpp, src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, src/picongpu/include/plugins/hdf5/writer/ParticleAttribute.hpp
add `#pragma omp parallel for` to long for loop
~~**Do not merge before #907**~~
=> ADIOS: use OpenMP to speedup for loops

src/picongpu/include/simulation_types.hpp
- remove enum `DataPlace`
- remove enum `ParticleType`
=> remove old unused enum definitions

src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/param/seed.param, src/picongpu/include/simulation_types.hpp
- move rng seed from `simulation_typed.hpp` to `seed.param`
=> Expose Particle Attribute Seed's in `seed.param`

src/picongpu/include/particles/traits/GetDensityRatio.hpp, src/picongpu/include/simulation_defines/param/speciesAttributes.param
- define a new species flag `densityRatio`
- add trait `GetDensityRatio`
=> add species flag `densityRatio`

src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesInit.kernel
- add type of the species to template signature of
- the kernel `kernelFillGridWithParticles`
- the function `calcRealDensity `
- multiply `GAS_DENSITY` by `densityRatio` of the species
~~Do not merge before #955~~
=> multiply `GAS_DENSITY` by `densityRatio`

src/libPMacc/include/traits/GetUniqueTypeId.hpp
add trait that generates a unique id out of a typename/class
=> add trait GetUniqueTypeId

src/libPMacc/include/traits/GetUniqueTypeId.hpp
- remove static attribute uid
- add static method uid
- method `::uid()` checks that id is valid for a given range
- uid result type is selectable
=> refactor GetUniqueTypeId

src/libPMacc/include/identifier/value_identifier.hpp, src/libPMacc/include/particles/operations/SetAttributeToDefault.hpp, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/simulation_defines/unitless/speciesDefinition.unitless
- rename method `getDefaultValue()` to `getValue()`
- add/ change documentation
=> refactor value_identifier

src/libPMacc/include/preprocessor/struct.hpp
- fix wrong implementation of `PMACC_C_VECTOR`
- dimension for vector is undefinded
- type (in this case a vector type) is used instead of
the type of the components
- fix signature of `PMACC_C_STRING` (takes now only two arguments)
- change interface of `PMACC_PP_INIT_VALUE_VARIABLES`
- add parameter emptyStruct
=> Fix Bugs in PP `struct.hpp` (PMACC_C_VECTOR)

examples/LaserWakefield/include/simulation_defines/param/laserConfig.param, examples/SingleParticleCurrent/include/OneParticleSimulation.hpp, examples/SingleParticleCurrent/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleRadiationWithLaser/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/OneParticleSimulation.hpp, examples/SingleParticleTest/include/particles/ParticlesInitOneParticle.hpp, examples/ThermalTest/include/ThermalTestSimulation.hpp
=> remove tab's in examples

src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldManipulator.kernel, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/initialization/InitialiserController.hpp, src/picongpu/include/particles/ParticlesInit.kernel, src/picongpu/include/particles/gasProfiles/GaussianCloudImpl.hpp, src/picongpu/include/particles/gasProfiles/SphereFlanksImpl.hpp, src/picongpu/include/plugins/BinEnergyParticles.hpp, src/picongpu/include/plugins/IntensityPlugin.hpp, src/picongpu/include/plugins/LiveViewPlugin.hpp, src/picongpu/include/plugins/PngPlugin.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/output/header/ColorHeader.hpp, src/picongpu/include/plugins/output/header/MessageHeader.hpp, src/picongpu/include/plugins/output/header/SimHeader.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/traits/AdiosToPIC.tpp, src/picongpu/include/traits/PICToAdios.tpp, src/picongpu/include/traits/PICToSplash.tpp, src/picongpu/include/traits/SplashToPIC.tpp
remove usage of native `float` with `float_32` in all source files
=> remove native `float` usage with `float_32`

src/picongpu/include/plugins/output/GatherSlice.hpp
- change master rank for `GastherSlice` in any instance
This pull request avoids that only mpi rank zero is the master for all reduce steps. 
- reduce the load
- reduce the memory food print
Tests:
=> rotate mpi master rank

src/tools/splash2txt/splash2txt.cpp
Fixed that in tools
See 1k item ;) https://github.com/ComputationalRadiationPhysics/picongpu/pull/1000
=> Remove deprecated throw declarations

src/libPMacc/examples/gameOfLife2D/include/GatherSlice.hpp, src/libPMacc/examples/gameOfLife2D/include/Simulation.hpp
Fixes some documentation issues in the GOL example
=> Gol example docu fix

src/libPMacc/include/nvidia/atomic.hpp, src/libPMacc/include/nvidia/warp.hpp
- add warp function (`getLaneId()`, ~~`getWarpId()`~~, ~~`getNumWarps()`~~
and `warpBroadcast()`
- add atomics (`atomicAllInc()` and `atomicAllExch()`)
To speedup the new atomic functions in warp communication is used.
=> add new warp atomic function

examples/Bunch/include/simulation_defines/param/gasConfig.param, examples/LaserWakefield/include/simulation_defines/param/gasConfig.param, src/picongpu/include/particles/gasProfiles/GaussianCloudImpl.hpp, src/picongpu/include/particles/gasProfiles/GaussianImpl.hpp, src/picongpu/include/particles/gasProfiles/LinearExponentialImpl.hpp, src/picongpu/include/particles/gasProfiles/SphereFlanksImpl.hpp, src/picongpu/include/simulation_defines/param/gasConfig.param
- rename member variables of gas parameters
- use preprocessor struct generator for the generation of gas parameters
Dependencies:
=> use struct generator for gas profiles

src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/Particles.tpp
This pull request fixes typos.
=> Fix 2 typos

src/picongpu/include/plugins/radiation/Radiation.hpp, src/picongpu/include/plugins/radiation/Radiation.kernel, src/picongpu/include/plugins/radiation/calc_amplitude.hpp, src/picongpu/include/plugins/radiation/debug/PIConGPUVerboseLogRadiation.hpp, src/picongpu/include/plugins/radiation/frequencies/radiation_log_freq.hpp, src/picongpu/include/plugins/radiation/nyquist_low_pass.hpp, src/picongpu/include/plugins/radiation/particles/PushExtension.hpp, src/picongpu/include/plugins/radiation/vector.hpp, src/picongpu/include/plugins/radiation/windowFunctions.hpp
This pull request romoves some old typos in the radiation plugin.
=> fix several typos in radiation plugin

README.md
@Flamefire  A warm welcome again and let the PRs for libPMacc come! :sparkles:
=> Developers: Add Alexander Grund

src/libPMacc/include/debug/VerboseLogMakros.hpp, src/libPMacc/include/identifier/alias.hpp, src/libPMacc/include/identifier/identifier.hpp
Fix some missing include and remove outdated ones
Also adds namespace to LogLvl
=> Add missing includes

src/libPMacc/include/Environment.hpp
- move defines out of namespace and add namespace qualifier
- add missing include
=> Add namespace to defines and move them out of the namespace

src/libPMacc/include/mpi/SeedPerRank.hpp
Fix license confusion PIConGPU -> libPMacc
@ax3l
=> Fix license header

src/libPMacc/include/expressions/DoNothing.hpp, src/libPMacc/include/expressions/SetToNull.hpp
- add folder for expressions
- add expression
- `DoNothing`
- `SetToNull`
=> add expressions `DoNothing` and `SetToNull`

src/libPMacc/include/particles/memory/dataTypes/Pointer.hpp
- change template interface (add T_InitMethod)
- define trait `GetEmptyDefaultConstructibleType<>`
=> extent `Pointer` with initialize method

src/libPMacc/include/particles/memory/dataTypes/Pointer.hpp
- removed unused code which is equivalent to #1047
=> remove unused code in `Pointer.hpp`

README.md
Modernization of some sections of our `README.md`. Also adds some more lines as proposed in #1057 regarding user - maintainer contact and mailing list usage.
=> Readme: Modernization, Support

src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/LaserPhysics.hpp, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.kernel, src/picongpu/include/fields/MaxwellSolver/None/NoSolver.hpp, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.hpp, src/picongpu/include/fields/background/cellwiseOperation.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/Line.hpp, src/picongpu/include/fields/tasks/TaskFieldReceiveAndInsert.hpp, src/picongpu/include/fields/tasks/TaskFieldReceiveAndInsertExchange.hpp, src/picongpu/include/fields/tasks/TaskFieldSend.hpp, src/picongpu/include/fields/tasks/TaskFieldSendExchange.hpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/plugins/kernel/CopySpecies.kernel, src/picongpu/include/plugins/output/images/LiveViewClient.hpp, src/picongpu/include/plugins/output/images/PngCreator.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/radiation/calc_amplitude.hpp
Related to #1042 Removes a large selection of warnings from `src/picongpu`
=> PIConGPU: Wshadow Warnings

src/tools/bin/plot_chargeConservation.py
This python tool plots $div(E) - rho/epsilon_0$ for 3D hdf5 data sets from PIConGPU.
It allows to check the charge conservation when implementing/testing new algorithms and to spot errors locally.
=> add python tool to plot charge conservation

doc/INSTALL.md
This pull request is related to issue #1124 and fixes the broken link to the hdf5 source code.
=> Install.md: update link to hdf5 source code

src/libPMacc/include/cuSTL/container/CartBuffer.hpp, src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/particles/tasks/ParticleFactory.hpp, src/libPMacc/include/particles/tasks/ParticleFactory.tpp
This fixes some includes:
- Missing full path
- Missing include
- hpp instead of def
=> cuSTL: fix includes

src/tools/bin/plot_chargeConservation_overTime.py
This pull request closes issue #1105.
It adds a second python tool reading all hdf5 files of a simulation and plotting
- max(abs)
- mean(abs) +/- std
off the difference between normalized density and divergence of the electric field. 
**Update:**
after an offline discussion with @psychocoderHPC we decided a histogram plot, which he suggested in #1105 and which is (still) missing in this pull request, has to be postponed since there is now simple way to plot histograms over time.
=> Close #1105 Tool Charge Conservation over Time

src/picongpu/include/particles/Particles.kernel, src/picongpu/include/particles/pusher/particlePusherAxl.hpp, src/picongpu/include/particles/pusher/particlePusherBoris.hpp, src/picongpu/include/particles/pusher/particlePusherFree.hpp, src/picongpu/include/particles/pusher/particlePusherNone.hpp, src/picongpu/include/particles/pusher/particlePusherPhot.hpp, src/picongpu/include/particles/pusher/particlePusherVay.hpp
This pull request follows #1201. It **only** adds the weighting to the pusher interface.
=> add weighting to interface of pushers

src/libPMacc/include/math/RungeKutta.hpp, src/libPMacc/include/math/RungeKutta/RungeKutta4.hpp
This pull request adds Runge Kutta 4th order to libPMacc.
=> add Runge Kutta algorithm 4th order

src/tools/bin/plot_chargeConservation_overTime.py
This pull requests adds 2D stencils to the charge conservation (over time) tool as requested by @psychocoderHPC.
=> add 2D analysis to charge conservation over time tool

examples/SingleParticleCurrent/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleRadiationWithLaser/include/particles/ParticlesInitOneParticle.hpp, examples/SingleParticleTest/include/particles/ParticlesInitOneParticle.hpp
This pull request makes **all** SingleParticle... examples 2D capable.
=> make SingleParticle... examples 2D capable

src/libPMacc/include/nvidia/reduce/Reduce.hpp
There are some conversion from int to float and back which are not required. Basic integer divides are enough and should be faster especially as in this case they can be implemented by a shift operation.
Also there was an inconsistent use of `l_id` which is `threadIdx.x` (no need to add a variable and possibly a register for that) and the check `threadIdx.x != 0 && l_tid >= active_threads` is unnecessarily complicated as `active_threads` is always >=1
=> Remove unnecessary floating point ops from reduce

src/libPMacc/include/mappings/kernel/BorderMapping.hpp
Improve docu as suggested by @ax3l in https://github.com/ComputationalRadiationPhysics/picongpu/pull/1169#issuecomment-154375396
=> Improve docu for BorderMapping

src/libPMacc/include/particles/traits/FilterByFlag.hpp
Add FilterByFlag to libPMacc/include/traits
=> Add trait FilterByFlag

src/picongpu/include/simulationControl/MySimulation.hpp
set current solver optional for species
This pull request close #1207 (compile time error if current solver is missing)
=> close #1207 set current solver as optional flag

src/libPMacc/include/cuSTL/container/allocator/DeviceMemAllocator.tpp, src/libPMacc/include/cuSTL/container/allocator/HostMemAllocator.tpp, src/libPMacc/include/cuSTL/container/copier/Memcopy.hpp
replace CUDA_CHECK_NO_EXCEP by CUDA_CHECK
solves #1192
=> replace CUDA_CHECK_NO_EXCEP by CUDA_CHECK

src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/particles/traits/GetIonizer.hpp, src/picongpu/include/particles/traits/GetPusher.hpp
- move trait `GetPusher` to namespace traits
- move trait `GetIonizer` to namespace traits
=> add missing namespace traits

src/tools/livevis/client/mainwindow.cpp, src/tools/livevis/client/mainwindow.ui
- change slope slider max value
- change slope slider pitch for better adjustment
=> change slider max values and pitch

src/tools/livevis/client/mainwindow.ui
- change text size from 11 to 14 points
- fix layous to support new text size
=> change text size and gui layout

src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/fields/FieldTmp.tpp
- close #1206
- set alias `interpolation<>` as optional flag for a species
=> set `interpolation<>` optional for species

src/libPMacc/include/algorithms/math.hpp, src/libPMacc/include/algorithms/math/defines/modf.hpp, src/libPMacc/include/algorithms/math/doubleMath/modf.tpp, src/libPMacc/include/algorithms/math/floatMath/modf.tpp
add modf to PMacc::algorithms::math
=> add modf to PMacc::algorithms::math

src/libPMacc/CMakeLists.txt, src/libPMacc/include/memory/buffers/HostBufferIntern.hpp, src/libPMacc/test/UT.cu, src/libPMacc/test/memory/HostBufferIntern/copyFrom.hpp, src/libPMacc/test/memory/HostBufferIntern/reset.hpp, src/libPMacc/test/memory/memoryUT.cu
This is how the test could look like. 
Both test are validated over DIM1, DIM2 and DIM3 and
over several number of elements per dimension.
=> First test cases for HostBufferIntern

src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example
Adds a useful tool required to access h5 files from different processes during post processing to avoid
file corruption,
see
https://pythonhosted.org/lock_file/
And updates ADIOS Version.
=> Rhea: Update Doc Python setup

src/picongpu/include/plugins/output/images/LiveViewClient.hpp, src/picongpu/include/plugins/output/images/PngCreator.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp
- `CMakeLists.txt`: add `thread` to boost requirements (#1251)
- add method `join()` to
- `PngCreator`
- `LiveViewClient`
- `PngCreator.hpp`: use `boos::threads` for asynchronous png creation
=> use boost:::threads for png creation

src/libPMacc/include/cuSTL/container/CartBuffer.tpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp
Add asserts to cuSTL containers checking sizes at assignment.
@Flamefire 
solves #1194
=> Add asserts to cuSTL containers

src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
change needed pngwriter version to 0.5.5
=> update pngwriter in `picongpu.profile.example`

src/libPMacc/include/cuSTL/container/assigner/HostMemAssigner.hpp
replace nested for-loops and pointer arithmetic in `HostMemAssigner` by more sophisticated foreach call.
promised in #1308
=> Simplify HostMemAssigner

src/libPMacc/include/cuSTL/algorithm/kernel/run-time/Foreach.hpp, src/libPMacc/include/cudaSpecs.hpp, src/picongpu/include/plugins/SliceFieldPrinter.tpp
If no BlockDim is given `Foreach` computes it by itself.
Solves #1256
Tested with SliceFieldPrinter plugin.
=> let cuSTL/kernel/runtime/Foreach compute best BlockDim

src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example
Just a record for advanced image operations, e.g., to tiff via [pillow](https://github.com/python-pillow/Pillow) (PIL fork).
Example usage: https://gist.github.com/ax3l/5781ce80b19d7df3f549
=> Rhea: Update Python Modules

src/picongpu/submit/titan-ornl/pythonOnRhea.profile.example
Noticed some minor typos and necessary updates after a re-install of the venv.
=> Rhea: Update Python Framework

src/libPMacc/include/algorithms/math/defines/trigo.hpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
add arcus cosinus to algorithms::math
=> add acos to algorithms::math

src/libPMacc/include/algorithms/math/defines/exp.hpp, src/libPMacc/include/algorithms/math/doubleMath/exp.tpp, src/libPMacc/include/algorithms/math/floatMath/exp.tpp
=> add log10 to algorithms::math

src/libPMacc/include/algorithms/math/defines/trigo.hpp, src/libPMacc/include/algorithms/math/doubleMath/trigo.tpp, src/libPMacc/include/algorithms/math/floatMath/trigo.tpp
=> add asin to algorithms::math.

src/libPMacc/examples/gameOfLife2D/CMakeLists.txt, src/mpiInfo/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
Follow-up to #1390 which fixes the same problem in some sub-projects
=> Fix more CMAKE_PREFIX_PATHs

src/libPMacc/include/pluginSystem/PluginConnector.hpp
add 'getPluginFromType()' method in PluginConnector.
See the discussion in #1376.
=> add 'getPluginFromType()' method in PluginConnector

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
This fixes #1372 by swapping the pointer with the uint32_t member
=> Swap members and adapt comment

src/picongpu/include/simulationControl/MovingWindow.hpp
- re-implements internals of `MovingWindow::getCurrentSlideInfo(...)`
- fix rounding errors in moving window
- close #1330 Moving Window: Too Slow
This pull request solve the same issue than #1336 does but with the different implementation with less rounding magic.
**Documentation:**
**Test:**
=> fix moving window moving speed

src/libPMacc/include/eventSystem/tasks/TaskSetValue.hpp
avoid that `kernelSetValue<>` is called with zero blocks
It is not clear why PIConGPU does not crash if a kernel with zero blocks is called.
=> avoid invalid kernel call

src/libPMacc/include/nvidia/functors/Assign.hpp
Follow-up to #1449, thanks to @BenjaminW3 for spotting my incorrect merge.
=> Reintroduce PMacc Include

src/libPMacc/include/memory/buffers/HostBufferIntern.hpp
=> Fix C&P mistake: Use Host DataBodx

src/picongpu/include/plugins/output/images/PngCreator.hpp
close #1464
- avoid that PNGs are scaled two times if `scale_image` is not one and the cell size in PIConGPU is not quadratic
- remove member method `resizeAndScaleImage()`
=> PNG: avoid double scaling

src/libPMacc/include/math/vector/Vector.tpp
add floor specialization for `PMacc::math::Vector<>`
=> add floor specialization for PMacc vectors

src/picongpu/include/particles/ionization/byField/ADK/AlgorithmADK.hpp
When the ion is fully ionized the trait `GetIonizationEnergies` will not
have a valid target for read access in the vector of ionization energies.
An `if`-condition avoid that access has been added to the ionization model ADK.
(*This change happens according to @psychocoderHPC 's [comment](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1423#discussion-diff-64031848R72)*)
Also equals sign alignment has been removed as it is not part of our
coding style guideline.
=> Fix the invalid read access for fully ionized ions in the ADK implementation

src/libPMacc/include/random/methods/MRG32k3aMin.hpp
As suggested by @ax3l in #1487
=> Make static_asserts class members

src/picongpu/submit/pizdaint-cscs/SLURM_Tutorial.md, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/picongpu.profile.example, src/picongpu/submit/pizdaint-cscs/total_profile.tpl
add batch system changes from 2016/06
- remove `aprun` with `srun`
- add flag `--gres`, `--cpus-per-task`
- change usage of `--ntasks-per-node` (know real tasks per node)
- update SLURM tutorial
- update `picongpu.profile.example`
=> update pizdaint batch system templates

src/libPMacc/include/random/distributions/uniform/Range.hpp, src/libPMacc/include/random/distributions/uniform/Uniform_float.hpp
- add range definition policies
- specialize the generation of uniform floats based on the policy
Tests:
CC-ing: @Heikman, @Flamefire
=> fix rng uniform float results

src/libPMacc/include/traits/GetStringProperties.hpp
- add trait `GetStringProperties<>`
- add function `getStringProperties()`
- add object `StringProperty`
=> add trait `GetStringProperties`

src/libPMacc/include/communication/CommunicatorMPI.hpp, src/libPMacc/include/communication/ICommunicator.hpp
Add an interface to request the axes which are periodic in the MPI communicator.
=> Communicator: Get Periodic Interface

src/libPMacc/include/pmacc_types.hpp
=> PMacc Types: Name Exchanges

src/picongpu/include/fields/FieldManipulator.hpp, src/picongpu/include/fields/MaxwellSolver/Lehe/LeheSolver.def
Fixes typos and some style problems.
=> Arbitrary Typo and Style Fixes

CMakeLists.txt, INSTALL.md, README.md
Move the `INSTALL.md` to our base directory and update links that point to/from it.
=> INSTALL.md: Move and Update

src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp, src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp
- delete separate implementation for host and device
- replace `2.0f` with `float_X(2.0)`
=> cleanup laser profiles

src/libPMacc/include/particles/traits/ResolveAliasFromSpecies.hpp
Fix #1531 by adding the correct license header.
@Heikman pls confirm & merge.
=> Fix #1531 LGPL License Header in Resolve

src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp
Updates the documentation and variable naming after several rebases of the central kernel in `FieldTmp`'s `particleToGrid` methods.
Does not change the implementation in any way.
=> FieldTmp Central Solver: Update Documentation

src/tools/splash2txt/splash2txt.cpp
fix a compile problem reported by Alex on the mailing list.
=> splash2txt: fix compile problem

examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/particles/ionization/byField/Keldysh/AlgorithmKeldysh.hpp, src/picongpu/include/particles/ionization/byField/Keldysh/Keldysh.def, src/picongpu/include/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.def, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.hpp, src/picongpu/include/particles/ionization/byField/ionizers.def, src/picongpu/include/particles/ionization/byField/ionizers.hpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
According to eq. (9) in [D. Bauer and P. Mulser. Exact field ionization rates in the barrier-suppression regime
from numerical time-dependent Schrödinger-equation calculations.](http://journals.aps.org/pra/abstract/10.1103/PhysRevA.59.569)
Wiki entries will follow.
Depends on ~~#1541~~ and ~~#1542~~.
=> Add Keldysh ionization model

src/tools/bin/tbg
fix #699
update tbg variable detection to support multi substitution in one line
=> Fix #699 tbg multi substitution

src/libPMacc/include/particles/memory/dataTypes/Particle.hpp
- add missing `T_ValueTypeSeq` to specialization
- use `ValueTypeSeq` instead of `FrameType` to validate if key exists
- add assert to `Particle<>::operator[]` to avoid access to deselcted key's
It was not possible to call `HasIdentifier<>` to a particle which was created with the `deselect<>()`method (because the parent frame was checked and not the current value sequence after deselect).
=> fix particle `HasIdentifier<>` specialization

src/libPMacc/include/nvidia/atomic.hpp
This is intended for a generic use of the atomicAdd function. There is also a `atomicAddWrapper` in a private namespace but that does only work with float/double and does not return the old value.
This is also ready for the new atomicAdd for doubles in CUDA 8 / CC 6.x
=> Add generic atomicAdd

src/picongpu/include/particles/gasProfiles/FromHDF5Impl.hpp
local variable definition shadows class member variable
=> fix hdf5 gas profile

src/tools/bin/plotNumericalHeating, src/tools/bin/plot_chargeConservation.py, src/tools/bin/plot_chargeConservation_overTime.py
add option `--export`: export plot to file
and remove unneeded white space
=> add file export option

src/libPMacc/include/particles/boostExtension/InheritLinearly.hpp
- move inherit type creation to the namespace detail
- add accessor to the template signature
This pull refactoring is the base to solve the icc issue #1646
=> Refactor `InheritLinearly`

CHANGELOG.md, README.md
Update the `dev` branch with documentation updates from our 0.2.0 release (changelog and acknowledgments; added one further commit to update the current dev with up-to-date devs).
note: the other commits you see in this PR are just cherry-picks from backports which are already included in `dev` - so you won't see them in the "files changed" tab.
=> Update Dev Branch: 0.2.0 Change Log

configure, examples/Bunch/include/simulation_defines/param/precision.param, examples/Bunch/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/precision.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/SingleParticleCurrent/include/simulation_defines/param/species.param, examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/species.param, examples/SingleParticleTest/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/precision.param, src/picongpu/include/simulation_defines/param/species.param
Remove the "needs sm_20 or higher" comments in-code since we dropped support for sm_1X.
=> Doc: Remove sm_20 Comments

src/libPMacc/include/cuSTL/algorithm/kernel/run-time/Foreach.hpp, src/libPMacc/include/cuSTL/container/assigner/DeviceMemAssigner.hpp, src/libPMacc/include/dataManagement/Dataset.hpp, src/libPMacc/include/eventSystem/Manager.tpp, src/libPMacc/include/eventSystem/events/CudaEvent.def, src/libPMacc/include/eventSystem/events/CudaEvent.hpp, src/libPMacc/include/eventSystem/events/CudaEventHandle.hpp, src/libPMacc/include/eventSystem/events/EventTask.tpp, src/libPMacc/include/eventSystem/tasks/ITask.hpp, src/libPMacc/include/eventSystem/tasks/StreamTask.tpp, src/libPMacc/include/eventSystem/transactions/TransactionManager.tpp, src/libPMacc/include/mappings/kernel/BorderMapping.hpp, src/libPMacc/include/mappings/kernel/MappingDescription.hpp, src/libPMacc/include/mappings/simulation/SubGrid.hpp, src/libPMacc/include/memory/buffers/Buffer.hpp, src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp, src/libPMacc/include/memory/buffers/ExchangeIntern.hpp, src/libPMacc/include/memory/buffers/HostBufferIntern.hpp, src/libPMacc/include/memory/buffers/MappedBufferIntern.hpp, src/libPMacc/include/memory/buffers/MultiGridBuffer.hpp, src/libPMacc/include/mpi/MPIReduce.hpp, src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp, src/libPMacc/include/particles/memory/buffers/StackExchangeBuffer.hpp, src/libPMacc/include/particles/operations/Deselect.hpp, src/libPMacc/include/particles/tasks/TaskReceiveParticlesExchange.hpp, src/libPMacc/include/particles/tasks/TaskSendParticlesExchange.hpp, src/libPMacc/test/random/2DDistribution.cu
substitute `assert` with `PMACC_ASSERT` or `PMACC_VERIFY`
Both calls are available since #1578
=> use PMacc assert and verify

src/picongpu/include/initialization/InitialiserController.hpp, src/picongpu/include/initialization/ParserGridDistribution.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/plugins/LiveViewPlugin.hpp, src/picongpu/include/plugins/PhaseSpace/DumpHBufferSplashP.hpp, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/PngPlugin.hpp, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/plugins/adios/WriteSpecies.hpp, src/picongpu/include/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp, src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp, src/picongpu/include/plugins/hdf5/WriteSpecies.hpp, src/picongpu/include/plugins/hdf5/restart/LoadParticleAttributesFromHDF5.hpp, src/picongpu/include/plugins/hdf5/writer/Field.hpp, src/picongpu/include/plugins/hdf5/writer/ParticleAttribute.hpp, src/picongpu/include/plugins/output/compression/ZipConnector.hpp, src/picongpu/include/plugins/output/images/Visualisation.hpp, src/picongpu/include/plugins/radiation/check_consistency.hpp, src/picongpu/include/plugins/radiation/particle.hpp, src/picongpu/include/simulationControl/MySimulation.hpp, src/picongpu/include/simulationControl/SimulationStarter.hpp
use PMacc internal assert and verification macros
Both calls are available since #1578
=> use PMACC_ASSERT and PMACC_VERIFY

src/libPMacc/examples/gameOfLife2D/submit/1gpu.cfg, src/libPMacc/examples/gameOfLife2D/submit/2gpus.cfg, src/libPMacc/examples/gameOfLife2D/submit/4gpus.cfg, src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpiexec.tpl, src/libPMacc/examples/gameOfLife2D/submit/bash/bash_mpirun.tpl, src/picongpu/submit/bash/bash_mpiexec.tpl, src/picongpu/submit/bash/bash_mpirun.tpl, src/picongpu/submit/hypnos-hzdr/k80_profileRestart.tpl, src/picongpu/submit/titan-ornl/picongpu.profile.example, src/tools/bin/smooth.py, src/tools/share/gnuplot/BinEnergyPlot.gnuplot, src/tools/share/python/sliceFieldReader.py
Remove more EOL white spaces in scripts, commited change as generic user again.
```bash
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git commit -S -a
```
=> Scripts: Remove more EOL white spaces

doc/TBG_macros.cfg, examples/Bunch/submit/bunch_0032.cfg, examples/KelvinHelmholtz/submit/0004gpus.cfg, examples/KelvinHelmholtz/submit/0016gpus.cfg, examples/LaserWakefield/submit/0001gpus.cfg, examples/LaserWakefield/submit/0008gpus.cfg, examples/LaserWakefield/submit/0016gpus.cfg, examples/LaserWakefield/submit/0032gpus.cfg, examples/SingleParticleCurrent/submit/0001gpus.cfg, examples/SingleParticleRadiationWithLaser/submit/0008gpus.cfg, examples/SingleParticleTest/submit/0008gpus.cfg, examples/ThermalTest/submit/0001gpu.cfg, examples/ThermalTest/submit/0004gpus.cfg, examples/ThermalTest/submit/0008gpus.cfg, examples/ThermalTest/submit/0032gpus.cfg, examples/ThermalTest/submit/0064gpus.cfg, examples/WeibelTransverse/submit/0004gpus.cfg
Even more files... ahhh.. committed as generic user "tools" as always
one more for #1675
=> .cfg files: Remove EOL white spaces

examples/Bunch/cmakeFlags, examples/KelvinHelmholtz/cmakeFlags, examples/LaserWakefield/cmakeFlags, examples/SingleParticleCurrent/cmakeFlags, examples/SingleParticleRadiationWithLaser/cmakeFlags, examples/SingleParticleTest/cmakeFlags, examples/ThermalTest/cmakeFlags, examples/WeibelTransverse/cmakeFlags, src/mpiInfo/CMakeLists.txt, src/tools/bin/egetopt, src/tools/bin/findAndDo, src/tools/bin/plotIntensity, src/tools/bin/plotRadiation, src/tools/bin/radiationSyntheticDetector, src/tools/bin/transpose, src/tools/bin/uncrustifyMyCode, src/tools/png2gas/CMakeLists.txt, src/tools/share/awk/BinEnergyPlot.awk, src/tools/share/awk/SumEnergyRange.awk, src/tools/splash2txt/CMakeLists.txt
Done via tools commit and sed script in `test/`.
(the old scripts grep was broken...)
=> Style: Fix more EOL

src/picongpu/submit/hypnos-hzdr/k80_profileRestart.tpl
This pull request adds `... | tee -a output` to output in order to get all output from the restart calculation **and** from picongpu for **all** restarted runs together in one `output` file.
=> add amend option for tee in k80 autorestart tpl

test/hasEOLwhiteSpace
The previous grep command was broken, this fixes it.
Also suggest the exact copy-&-paste commands to fix reported issues. Was used for #1695
=> Test: Fix EOL and Suggest Solution

doc/TBG_macros.cfg, examples/ThermalTest/tools/dispersion.py, src/libPMacc/include/algorithms/math/doubleMath/abs.tpp, src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp, src/libPMacc/include/cuSTL/container/HostBuffer.hpp, src/libPMacc/include/random/RNGProvider.tpp, src/picongpu/CMakeLists.txt, src/picongpu/include/plugins/IsaacPlugin.hpp, src/picongpu/include/simulation_defines/param/isaac.param, src/tools/bin/addLicense, src/tools/bin/transpose, src/tools/livevis/server/src/Visualization.cpp, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/include/ITools.hpp, src/tools/splash2txt/include/splash2txt.hpp, src/tools/splash2txt/include/tools_splash_parallel.hpp
Gosh, there have been some in here again! Done via script in #1697 and hopefully the last time...
Committed as generic "tools" user.
=> Style: Replace all Tabs with Spaces

src/libPMacc/CMakeLists.txt, src/libPMacc/PMaccConfig.cmake, src/libPMacc/examples/gameOfLife2D/CMakeLists.txt, src/picongpu/CMakeLists.txt
- PMaccConfig.cmake: search for all dependencies
- CUDA
- Boost
- mallocMC
- MPI
- refactor PMacc test CMake files
- refactor PIConGPU CMake file
- refactor gol CMake file
**Tests**
=> CMake: handle PMacc as separate library

src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
- remove tenary if operator with normal if condition
- change the comparison for the lower bound from `X >= 0 ?` to `X < 0`
- change the comparison for the upper bound from `X < 0` to `X >= 0`
This change had no performance impact (discussed [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1731#pullrequestreview-14902275))
=> change tenary if operator to `if` condition

src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp, src/picongpu/include/simulation_defines/param/speciesDefinition.param
Generalize calorimeter plugin to all particle species.
Depends on:
This solves #1723.
=> Generalize calorimeter plugin

src/libPMacc/test/memory/HostBufferIntern/setValue.hpp, src/libPMacc/test/particles/IdProvider.hpp, src/libPMacc/test/random/2DDistribution.cu, src/picongpu/include/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp
follow up of  #1743
remove `BOOST_AUTO` and `PMACC_AUTO` with native C++11 `auto` keyword
=> remove usage of `BOOST_AUTO` and `PMACC_AUTO`

test/correctBranchPR
I accidentially skipped all tests if the first (sourced) travis branch-test was successful. This fixes it. Introduced in #1732
=> Fix Travis: Tests Disabled

INSTALL.md
Already list the package names in spack in our INSTALL.md
=> INSTALL.md: List Spack Packages

src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/memory/boxes/ParticlesBox.hpp, src/libPMacc/include/particles/memory/dataTypes/SuperCell.hpp
Hook into the fillGaps kernel to later calculate the number and the linked-list of particles per cell in a framelist
=> Hook into the fillGaps kernel

src/tools/bin/tbg
Updates the first doc lines in tbg to be a bit more up-to-date
=> TBG: Outdated Header

INSTALL.md
Updates the hypnos example in our install instructions.
=> INSTALL: Update Hypnos Example

src/picongpu/include/version.hpp
Bump the version to `0.2.3` in its release branch.
=> Bump Version: 0.2.3

CHANGELOG.md
Changelog for the 0.2.3 release :)
Thanks to @ax3l, @psychocoderHPC, @PrometheusPi, @BeyondEspresso, @n01r, @Heikman and @HighIander for spotting the issues and/or providing fixes!
=> Changelog: 0.2.3

CHANGELOG.md, README.md
Update release date to today and update README as as in `dev` (links, badges).
=> 0.2.3: Release Date

src/picongpu/include/algorithms/AssignedTrilinearInterpolation.hpp, src/picongpu/include/fields/FieldE.kernel, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov.def, src/picongpu/include/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp, src/picongpu/include/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.def, src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp, src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.def, src/picongpu/include/plugins/adios/ADIOSWriter.hpp, src/picongpu/include/simulation_defines/param/fieldSolver.param, src/picongpu/include/traits/AdiosToPIC.hpp, src/picongpu/main.cu
Fixes a ton of doxygen warnings in PIConGPU "core".
=> Doxygen: Fix Warnings Core

src/libPMacc/include/compileTime/AllCombinations.hpp, src/libPMacc/include/math/vector/compile-time/Vector.hpp
Fixes a few doxygen warnings in PMacc.
=> Doxygen: Fix Warnings PMacc

src/picongpu/include/plugins/radiation/amplitude.hpp, src/picongpu/include/plugins/radiation/calc_amplitude.hpp, src/picongpu/include/plugins/radiation/nyquist_low_pass.hpp
Fix doxygen warnings about inline formulas inside radiation.
=> Doxygen: Fix Warnings Radiation

src/picongpu/include/plugins/SliceFieldPrinterMulti.hpp
Fix include of a stdlib inside a namespace.
=> Std Include: Never inside Namespaces

examples/SingleParticleTest/include/simulation_defines/param/fileOutput.param, src/picongpu/include/particles/ionization/byField/fieldIonizationCalc.def, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/ResourceLog.hpp, src/picongpu/include/simulation_defines/param/fieldBackground.param, src/picongpu/include/simulation_defines/param/fileOutput.param, src/picongpu/include/simulation_defines/param/pusherConfig.param, src/picongpu/include/simulation_defines/unitless/checkpoints.unitless
fixes a few more floating doxygen doc strings inside core.
=> Doxygen: Fix Floating Docstrings

src/libPMacc/include/particles/traits/FilterByIdentifier.hpp
Implement a filter trait select all types from a sequence those have a certain identifier.
=> add trait `FilterByIdentifier`

examples/Empty/README.rst, examples/LaserWakefield/README.rst
Adds `README.rst` files for the LWFA and the Empty example.
=> Examples: Readme for LWFA & Empty

src/picongpu/include/plugins/hdf5/WriteSpecies.hpp, src/picongpu/include/traits/attribute/GetCharge.hpp
=> Backport 0.2.4: Ionization - Fix Charge of Ionized Ions

docs/source/index.rst, docs/source/plugin.rst, docs/source/python.rst
List of important python tutorials and prepare section for plugins (will be imported from wiki).
=> Docs: Python Tutorials

src/libPMacc/include/preprocessor/struct.hpp
- fix `static const` replacements from older commit
- add example to `PMACC_STRUCT`
- update comments within the examples
=> update documentation `struct.hpp`

examples/Bremsstrahlung/README.rst, examples/Empty/README.rst, examples/KelvinHelmholtz/README.rst, examples/WarmCopper/README.rst
- unify citation style
- unify headline `DirName: Title`
- small style issues
=> Examples: Readme Styles

docs/source/dev/pmacc.rst, docs/source/index.rst, docs/source/particles.rst
- document available particle init and manipulators
- document PMacc `struct` factory #1879
=> Doc: Particles Init & Manipulators

src/picongpu/submit/hypnos-hzdr/k80_profileRestart.tpl
The `k80_profileRestart.tpl` file should be modified to automatically restart from ADIOS output.
Since only the last checkout is used for the automatic restart, the previous one, which maybe quite large, should be deleted in each step to save the disk space.
=> To automatically restart from ADIOS output

examples/Bremsstrahlung/include/simulation_defines/param/gridConfig.param, examples/WarmCopper/include/simulation_defines/param/gridConfig.param
this changes are equal to #1799, but for the new examples
This changes is needed for #1796
=> use constexpr for arrays in `gridConfig.param`

docs/source/index.rst, docs/source/models/ionization.rst, docs/source/models/photons.rst
Start a section on models for the default and especially the extended PIC algorithm in PIConGPU.
This section should document the assumptions, applicable ranges and implementation limits of our models, so users can follow those in order to do meaningful science in validated & verified regimes.
@n01r @Heikman please extend your sections after merge :)
=> Doc: Models

docs/source/dev/sphinx.rst, docs/source/index.rst
Documentation inception!
Documents how to build the docs (locally) and how to contribute.
Taken from PR description in #1843
=> Docs: Document Local Build

docs/source/index.rst, docs/source/models/LL_RR.rst, docs/source/models/photons.rst, docs/source/models/pic.rst, docs/source/postprocessing/openPMD.rst, docs/source/postprocessing/paraview.rst, docs/source/postprocessing/python.rst, docs/source/usage/reference.rst
Creates chapters & sections for further model descriptions and post-processing topics.
=> Docs: Models, PostProcessing

examples/Bunch/include/simulation_defines/param/species.param, examples/Bunch/include/simulation_defines/param/speciesDefinition.param, examples/KelvinHelmholtz/include/simulation_defines/param/species.param, examples/KelvinHelmholtz/include/simulation_defines/param/speciesDefinition.param, examples/LaserWakefield/include/simulation_defines/param/species.param, examples/LaserWakefield/include/simulation_defines/param/speciesDefinition.param, examples/LaserWakefield/include/simulation_defines/param/speciesInitialization.param, examples/SingleParticleTest/include/simulation_defines/param/species.param, examples/SingleParticleTest/include/simulation_defines/param/speciesDefinition.param, examples/WeibelTransverse/include/simulation_defines/param/speciesDefinition.param, src/picongpu/include/simulation_defines/param/species.param, src/picongpu/include/simulation_defines/param/speciesDefinition.param
remove defines `ENABLE_ELECTRONS` and `ENABLE_IONS`
=> remove `ENABLE_ELECTRONS/IONS` 

INSTALL.md
Not necessary this time, isn't it?
=> Fix grammar error in INSTALL.md

.readthedocs.yml
Enable PDF (Latex) & EPUB build on readthedocs
=> RTD: Build PDF & EPUB

src/picongpu/include/simulation_defines/param/ionizationEnergies.param, src/picongpu/include/simulation_defines/param/ionizer.param
In order to contribute to the closing of issue #1982 this pull request adds general file documentation for the `.param` files connected to ionization.
=> Document ionization param files for issue 1982

CHANGELOG.md, docs/propose_changelog.py
Controlled and updated the titles and labels of milestone 0.3.0.
Created the changelog semi-automatically via a script and then curated and grouped accordingly.
There are some small to-do's left after this change log is merged, all documented in https://github.com/ComputationalRadiationPhysics/picongpu/projects/11
=> Draft Changelog for 0.3.0

src/picongpu/include/simulation_defines/param/radiation.param, src/picongpu/include/simulation_defines/param/radiationObserver.param
This pull request closes some aspects of issue #1982 by documenting in detail the parameters of the radiation plugin.
It will **not** update white spaces.
=> add documentation radiation parameters

src/libPMacc/include/traits/GetNumWorkers.hpp
calculate the number of worker threads depending of the accelerator
=> add trait `GetNumWorker`

examples/Bremsstrahlung/include/simulation_defines/param/components.param, examples/Bunch/include/simulation_defines/param/components.param, examples/KelvinHelmholtz/include/simulation_defines/param/components.param, examples/LaserWakefield/include/simulation_defines/param/components.param, examples/SingleParticleTest/include/simulation_defines/param/components.param, examples/ThermalTest/include/simulation_defines/param/components.param, examples/WeibelTransverse/include/simulation_defines/param/components.param, src/picongpu/include/simulation_defines/param/components.param
Add comment on plane wave laser, after user comment, that is Gaussian in time.
=> Laser Plane Wave: Add Comment

docs/source/usage/workflows.rst, docs/source/usage/workflows/laserPeakOnTarget.rst
Explain how to set a laser cutoff in detail for the manual
=> Document Laser Cutoff

src/picongpu/include/simulation_defines/unitless/speciesDefinition.unitless
little follow-up to #1754 adding a missing include that caused compile issues
=> ThomasFermi: fix missing include

docs/source/usage/tbg.rst, src/picongpu/submit/hypnos-hzdr/PBS_Tutorial.rst, src/picongpu/submit/taurus-tud/Slurm_Tutorial.rst
=> PBS Usage Example

src/libPMacc/include/mappings/threads/ThreadCollective.hpp
- use `ForEachIdx` for the implementation
- add support for a arbitrary number of arguments for the `operator()`
=> refactor `ThreadCollective`

src/libPMacc/include/mappings/threads/IdxConfig.hpp
=> `IdxConfig` append documentation

docs/source/prgpatterns/lockstep.rst, src/libPMacc/include/mappings/threads/IdxConfig.hpp
Little typo fixes and clarifications for the lockstep programming model as discussed offline.
=> Lockstep Model: Doc Updates

src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.hpp, src/picongpu/include/fields/MaxwellSolver/Yee/YeeSolver.kernel
=> Yee solver lockstep refactoring

src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldJ.tpp
- remove unused template `AREA`
=> lockstep refactoring of `KernelComputeCurrent`

docs/source/models/field_ionization_comparison_c_ii_ionization.py
This is a follow up to #2033 to fix the missing math mode introduces with this pull request.
=> fix mathmode issue in ionization plot

src/picongpu/submit/pizdaint-cscs/large_profile.tpl, src/picongpu/submit/pizdaint-cscs/normal_profile.tpl, src/picongpu/submit/pizdaint-cscs/picongpu.profile.example
- update profile exmaple
- update tbg templates
- rename `total.tpl` to `large.tpl` (the queue names has changed with the last pizdaint upgrade)
=> update pizdaint data

src/picongpu/include/plugins/EnergyFields.hpp, src/picongpu/include/plugins/EnergyParticles.hpp, src/picongpu/include/plugins/IntensityPlugin.hpp, src/picongpu/include/plugins/LiveViewPlugin.hpp, src/picongpu/include/plugins/PngPlugin.hpp, src/picongpu/include/plugins/PositionsParticles.hpp, src/picongpu/include/plugins/SumCurrents.hpp, src/picongpu/include/plugins/makroParticleCounter/PerSuperCell.hpp, src/picongpu/include/plugins/radiation/Radiation.hpp
This is a follow up pull request to #2034. It changes all other occurrences of `notifyFrequency(s)` to `notifyPeriod`.
=> change notifyFrequency(s) to notifyPeriod

src/picongpu/include/fields/FieldJ.kernel, src/picongpu/include/fields/FieldJ.tpp
rewrite kernel with the lockstep programming model
[Lockstep Programming Model ](http://picongpu.readthedocs.io/en/dev/prgpatterns/lockstep.html) documentation.
=> `FieldJ` bash/insert lockstep refactoring

docs/source/prgpatterns/lockstep.rst
Add a section to the common lockstep programming patterns that shows a typical "master changes a shared data section" workflow
=> Lockstep Docs: Master Pattern

src/picongpu/include/plugins/output/sockets/SocketConnector.hpp
Handle the return code of the [write to a socket](http://kirste.userpage.fu-berlin.de/chemnet/use/info/libc/libc_11.html).
Close #2062
=> Warning in Socket Write

src/libPMacc/include/particles/operations/CountParticles.hpp
=> lockstep refactoring of `KernelCountParticles`

src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesInit.kernel
=> lockstep refactoring of `KernelFillGridWithParticles`

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.kernel
=> lockstep refactoring `KernelFillGapsLastFrame`

src/picongpu/include/particles/ionization/byCollision/ThomasFermi/AlgorithmThomasFermi.hpp, src/picongpu/include/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
Closes #2024.
This pull request fixes Thomas-Fermi ionization to ignore predicted re-combinations which did lead to ionizing the same ion state several times.
This pull request moves
particle[boundElectrons_] = newBoundElectrons;
after the safety check. Now the number of bound electrons correctly changes,
i.e. **only** if the new number is lower than the number before and ionization
happens.
This PR also increases the detail of documentation and fixes a code line
which overwrote a variable. The latter issue had no functional relevance
and did not produce any erroneous behaviour.
Thanks @ax3l, @psychocoderHPC for spotting this one!
=> Fix charge conservation in ThomasFermi

src/picongpu/include/plugins/BinEnergyParticles.hpp
=> lockstep refactoring of `KernelBinEnergyParticles`

CONTRIBUTING.md, docs/source/dev/styleguide.rst, docs/source/index.rst
The new coding style was not yet linked. Updates it and adds a little rationale.
=> Docs: Link New Coding Style

src/tools/bin/newVersion.sh
Adds a tool for maintainer ([see wiki](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Maintainer-Documentation)) to update the version number of PIConGPU on all places during releases.
=> Tool: New Version

src/picongpu/include/fields/FieldJ.hpp, src/picongpu/include/fields/FieldJ.tpp, src/picongpu/include/fields/FieldTmp.hpp, src/picongpu/include/fields/FieldTmp.tpp, src/picongpu/include/particles/Particles.hpp, src/picongpu/include/particles/Particles.tpp, src/picongpu/include/particles/ParticlesFunctors.hpp, src/picongpu/include/simulationControl/MySimulation.hpp
- delete definition and empty implementation of `init()` for
- `FieldJ`
- `FieldTmp`
- `Particles<>`
- remove functor `particles::CallInit`
- MySimulation.hpp: remove usage of `particles::CallInit`
=> remove empty `init()` methods

src/libPMacc/include/particles/ParticlesBase.hpp, src/libPMacc/include/particles/ParticlesBase.kernel
=> lockstep refactoring of `KernelFillGaps`

src/picongpu/include/fields/FieldB.hpp, src/picongpu/include/fields/FieldB.tpp, src/picongpu/include/fields/FieldE.hpp, src/picongpu/include/fields/FieldE.tpp, src/picongpu/include/simulationControl/MySimulation.hpp
- `FieldE`, `FieldB` remove method `init()`
- `FieldE.tpp` instantiate `LaserPhysics` in the method `laserManipulation()`
- `MySimulation.hpp`
- remove init call for FieldE and FieldB
- remove member `laser` and the declaration
=> remove init method in `FieldE` and `FieldB`

src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/ParticlesBase.tpp
rewrite kernel with the lockstep programming model
=> lockstep refactoring of `KernelDeleteParticles`

src/libPMacc/include/particles/ParticlesBase.kernel, src/libPMacc/include/particles/ParticlesBase.tpp
=> lockstep refactoring of `KernelInsertParticles`

docs/TBG_macros.cfg, docs/source/usage/param/plugins.rst, src/picongpu/include/plugins/PluginController.hpp, src/picongpu/include/plugins/particleMerging/ParticleMerger.hpp, src/picongpu/include/plugins/particleMerging/ParticleMerger.kernel, src/picongpu/include/plugins/particleMerging/VoronoiCell.hpp, src/picongpu/include/simulation_defines/_defaultParam.loader, src/picongpu/include/simulation_defines/param/particleMerger.param, src/picongpu/include/simulation_defines/param/particleMerging.param, src/picongpu/include/simulation_defines/param/speciesAttributes.param, src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless, src/picongpu/include/traits/PICToSplash.tpp
add a particle merging algorithm based on:
Luu, P. T., Tückmantel, T., & Pukhov, A. (2016).
Voronoi particle merging algorithm for PIC codes.
Computer Physics Communications, 202, 165-174.
parameter: 
```json
"e_merger": {
"period": 100,
"minParticlesToMerge": 8,
"posSpreadThreshold": 0.2,
"absMomSpreadThreshold": 0.01,
"minMeanEnergy": 0
}
```
=> Feature: particle merging

src/picongpu/include/particles/flylite/types/Superconfig.hpp
Fix the author header in Superconfig.hpp - thx @psychocoderHPC for spotting it!
=> SuperConfig: Header Fix

USAGE.rst
This pull request addresses issues brought up by @wmles in #2092 
- It adds a section describing how to download the PIConGPU source code (otherwise all the `pic-config` etc. used later commands won't work)
- It adds extra information on $SCRATCH for users on their laptop.
=> Docs: Extended $SCRATCH Info

docs/source/usage/param/core.rst, src/libPMacc/include/particles/Identifier.hpp
expand the documentation of PMacc pre-defined species attributes and include it in our manual.
=> multiMask: Refactor Documentation

src/picongpu/submit/submitAction.sh
Fix the offset of 1 for number of modified files in `submitAction.sh`.
Follow-up to #2123, thx for spotting @psychocoderHPC
=> TBG: Fix Input Modifcation Detection

.gitignore, docs/source/dev/doxygen.rst, docs/source/index.rst
Documents how to build the "legacy" Doxygen HTML output. This is still useful and can be of interest.
With ❤️ for @psychocoderHPC
=> Doxygen: How to Build HTML

share/pmacc/examples/gameOfLife2D/include/Evolution.hpp
I formatted the full file to follow our coding style.
=> Game of Life lockstep refactoring

include/picongpu/particles/Particles.kernel, include/picongpu/particles/Particles.tpp
=> lockstep refactoring `KernelManipulateAllParticles`

include/picongpu/particles/pusher/particlePusherAxel.hpp, include/picongpu/particles/pusher/particlePusherBoris.hpp, include/picongpu/particles/pusher/particlePusherFree.hpp, include/picongpu/particles/pusher/particlePusherPhoton.hpp, include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp, include/picongpu/particles/pusher/particlePusherVay.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/radiation/nyquist_low_pass.hpp, include/pmacc/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp, include/pmacc/particles/IdProvider.hpp, include/pmacc/types.hpp
- remove usage of `__device__` and `__host__`
- add define `DEVICEONLY` (equivalent to `__device__`)
- fix the indention's within a few files those was absolutely confuse
=> remove usage of native CUDA function prefix

include/pmacc/cuSTL/container/CartBuffer.hpp, include/pmacc/cuSTL/container/CartBuffer.tpp, include/pmacc/cuSTL/container/DeviceBuffer.hpp, include/pmacc/cuSTL/container/HostBuffer.hpp
use c++11 move semantic in cuSTL
solves #1834
=> use c++11 move semantic in cuSTL

include/pmacc/particles/operations/splitIntoListOfFrames.kernel
=> lockstep kernel refactoring `SplitIntoListOfFrames`

include/picongpu/plugins/EnergyParticles.hpp
- indent everything within namespaces
- remove thread collective iteration over the frame list
To simplify the review please add `?w=1` to the URL (will ignore all white space changes) or follow [this link](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2164/files?w=1)
=> lockstep refactoring `KernelEnergyParticles`

include/pmacc/math/complex/Complex.tpp
This brief pull request adds complex logarithms.
=> Add complex logarithm to math

include/picongpu/particles/manipulators/generic/Free.hpp, include/picongpu/particles/manipulators/generic/FreeRng.hpp, include/picongpu/particles/manipulators/generic/detail/Rng.def, include/picongpu/particles/manipulators/generic/detail/Rng.hpp, include/pmacc/functor/Filtered.hpp, include/pmacc/functor/Interface.hpp
This pull request refactors the new functor interface to allow the usage for the startPosition functors as well. 
- change the visibility of inherited classes
- move the random number initialization to a separate class
=> functor interface refactoring

include/picongpu/particles/flylite/helperFields/LocalDensity.kernel, include/pmacc/nvidia/reduce/Reduce.hpp
- update dependency `flylite/helperFields/LocalDensit.kernel`
**Note:** I have not changed the code style within the old parts of the code.
=> lockstep kernel refactoring `Reduce`

include/picongpu/fields/FieldJ.kernel, include/picongpu/fields/FieldJ.tpp
=> lockstep kernel refactoring `KernelAddCurrentToEMF`

include/picongpu/fields/FieldTmp.kernel, include/picongpu/fields/FieldTmp.tpp
- change the algorithm to move over all frames: each worker has its own frame handle
=> lockstep kernel refactoring `KernelComputeSupercells`

include/picongpu/fields/currentDeposition/RelayPoint.hpp, include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp, include/picongpu/fields/currentDeposition/ZigZag/ZigZag.hpp, include/picongpu/plugins/IsaacPlugin.hpp, include/pmacc/algorithms/math/defines/comparison.hpp, share/picongpu/examples/Bremsstrahlung/include/picongpu/simulation_defines/param/density.param
- add generic `min()` and `max()` implementation (also supports integer types)
- use PMacc min/max within PIConGPU
=> PMacc:: generic `min()` and `max()` implementation

include/picongpu/plugins/hdf5/WriteSpecies.hpp, include/picongpu/plugins/kernel/CopySpecies.kernel
Rewrite kernel with the lockstep programming model.
The algorithm itself is not changed, only code to fulfill the lockstep programming is added.
=> lockstep kernel refactoring `CopySpecies`

docs/source/usage/plugins/adios.rst, docs/source/usage/plugins/countPerSupercell.rst, docs/source/usage/plugins/hdf5.rst, docs/source/usage/plugins/isaac.rst, docs/source/usage/plugins/particleCalorimeter.rst, docs/source/usage/plugins/phaseSpace.rst, docs/source/usage/plugins/png.rst, docs/source/usage/plugins/radiation.rst, docs/source/usage/plugins/resourceLog.rst
Documents external dependencies of plugins in a consistent way.
Also fixes:
- ordering in menu (alphabetically)
- typos and ordering in ISAAC
- reference in phase space
=> Doc Plugins: External Dependencies

pic-configure
- fix a little typo on the optional part in the arch
- add an example to add multiple CMake flags
=> Doc: pic-configure help

include/pmacc/particles/operations/ConcatListOfFrames.hpp
cupla substitute the names `gridDim`, `blockIdx` and `threadIdx`, therefore it is not allowed to use this names as variables in host code.
Internal variable names will be renamed.
- rename `gridDim` to `gridSize`
- rename `blockIdx` to `blockIndex`
- rename `threadIdx` to `particleIdx`
=> rename CUDA index names in `ConcatListOfFrames`

include/picongpu/plugins/PluginController.hpp
This is a follow up of #1735 and removes the forgotten include and usage.
=> remove `InSituVolumeRenderer`

include/picongpu/fields/background/cellwiseOperation.hpp
=> lockstep kernel refactoring `KernelCellwiseOperation`

include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/radiation/Radiation.hpp, include/picongpu/plugins/radiation/Radiation.kernel
- activate Radiation accelerator `omp2b`
=> lockstep kernel refactoring `KernelRadiationParticles`

include/picongpu/simulation_defines/param/isaac.param
Tried to add some useful information for the `isaac.param` as demanded in https://github.com/ComputationalRadiationPhysics/picongpu/issues/1982 .
=> Added doxygen documentation for isaac.param file

src/tools/bin/tbg
EDITED by @PrometheusPi:
Stream error message to stderr and fix minor typos.
=> tbg: Fix existing-folder error message to stderr

README.md
@Heikman Thank you for the year-long work together, the long nights of coding, testing and all the progress we made. From an first prototype to what PIConGPU is today, it was a pleasure and creative gift to work with you! 🐥 
We wish you all the best and all of success with your upcoming endeavors!
=> Docs: Heiko to Former Members

include/pmacc/math/complex/Complex.tpp
This brief pull request adds complex sinus and cosine functions to libPMacc.
=> Add complex sin() and cos() functions.

include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.kernel, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp
- remove cuSTL kernel (equal implementation than teh second kernel in this plugin)
- activate plugin for backend `omp2b`
- use non collective loop to move over all frames
=> lockstep kernel refactoring `ParticleCalorimeter`

share/picongpu/examples/ThermalTest/tools/dispersion.py
fix "E402 module level import not at top of file" of flake8
=> ThermalTest: Flake Dispersion

docs/source/usage/plugins/hdf5.rst
Fix links and lists with proper .rst markup.
=> Docs HDF5 Plugin: Fix Links & Lists

docs/source/postprocessing/openPMD.rst, docs/source/postprocessing/python.rst
Update and add links to openPMD and yt part of the post-processing docs.
=> Docs: Update openPMD Post-Processing

etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example
Use the latest dot release of CUDA on Taurus (default module).
=> Doc: CUDA 8.0.61 on Taurus

docs/source/install/profile.rst
Link the profile for Taurus' (TUD) KNL queue.
=> Docs: Link KNL Profile

docs/source/models/field_ionization_comparison_c_ii_ionization.py, docs/source/models/field_ionization_effective_potentials.py, share/picongpu/examples/FoilLCT/bin/plot_charge_density.py, src/tools/bin/pic2xdmf.py, src/tools/share/python/sliceFieldReader.py
Fix occurring flake8 issues in python 2.7 & 3.5 (upcoming, refactored travis recipe).
=> Docs: Fix Flake8 Errors

docs/source/usage/plugins/phaseSpace.rst, lib/python/picongpu/plugins/phase_space.py
Python reader class for phase space plugin.
Use as follows:
```python
from picongpu.plugins.phase_space import PhaseSpace
phase_space = PhaseSpace('/home/axel/runs/foil_001')
e_ps, e_ps_meta = phase_space.get('e', ps='ypy', iteration=1000)
```
All returned values are in SI.
A full example for plotting phase space data with matplotlib, including unit conversion has been added to the manual.
ccing @codingS3b
=> Python: Phase Space Reader

docs/source/install/profile.rst, thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_traits.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_utils.hpp
Updates mallocMC:
- support for CUDA9 `__ballot_sync` [#144](https://github.com/ComputationalRadiationPhysics/mallocMC/pull/144)
- traits: missing Boost include [#142](https://github.com/ComputationalRadiationPhysics/mallocMC/pull/142)
From
- `mallocMC@dev` (https://github.com/ComputationalRadiationPhysics/mallocMC/commit/977b55f98fe0e6e4545f6e092660b7b4f1b54493) to
- `mallocMC@dev` (https://github.com/ComputationalRadiationPhysics/mallocMC/commit/3531c29c0d2a88be45508a789eab624cb0dd4fc5)
```bash
git subtree pull --prefix thirdParty/mallocMC \
git@github.com:ComputationalRadiationPhysics/mallocMC.git dev --squash
```
=> Update mallocMC to latest dev

include/picongpu/plugins/hdf5/WriteSpecies.hpp
Allow to dump particles that do not have a charge or mass frame attribute in HDF5.
Note: we allow to define particles without such fundamental types in PIConGPU (instead of falling back to zero) since this allows us to differentiate between physical particles (such as photons or neutrals) and unphysical particles (test particles, probes, etc.).
If such a particle species in encountered, we simply do not write the constant openPMD records for charge and mass (instead of writing implicitly a zero value, which would suggest these particles are physical - which they are not).
=> HDF5: Allow Unphysical Particle Dump

docs/source/install/instructions/spack.rst
Update the install instructions via spack to remove complications.
Addresses problems and unclear sections as seen on the user side in #2369
=> Spack Install: Clarify

include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/species.param
Add new docs strings for the new probe pusher.
Follow-up to #2371
=> Docs: Probe Pusher

include/picongpu/particles/filter/All.hpp, include/picongpu/particles/filter/RelativeGlobalDomainPosition.def, include/picongpu/simulation_defines/param/particleFilters.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particle.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/particleFilters.param
- begin name of all current particle filters lower case
=> use lower case begin for filter names

include/pmacc/memory/CtxArray.hpp
Add documentation on the concept of a context array.
A context array allows to propagate a local variable of a virtual worker of subsequent locksteps.
=> Docs: CtxArray

include/picongpu/plugins/PluginController.hpp
Only specialize and compile particle plugins for particle species which are elibible for it, based on the `SpeciesEligibleForSolver` trait.
Silently disables components which are not fulfilled, e.g. for nonphysical particles such as probes. Moves user (input) errors from compile time (which are in this case always very long and unreadable template meta programming errors) to runtime where it is (ideally) easier to spot.
Possible follow-up: For further usability, we can add log messages on high-level debug levels to output which species are ignored on `pluginLoad()`.
Depends on
**CUDA 7.5**
`dev`: 6:03 (real) | 7:38 (user)
`PR`: 6:08m (real) | 7:40m (user)
**CUDA 8.0.44** + ISAAC
`dev`: 6:35m (real) | 7:36m (user)
`PR`: 6:46m (real) | 7:43m (user)
=> PluginController: Eligible Species

.travis.yml, src/tools/bin/plotRadiation, src/tools/bin/radiationSyntheticDetector
Adds a new stage to Travis-CI for static code analysis.
Currently only checks Python code via [pyflakes](https://www.blog.pythonlibrary.org/2012/06/13/pyflakes-the-passive-checker-of-python-programs/), but more such as [clang-tidy](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2303) for C++ can follow.
=> Travis: Static Code Analysis

lib/python/picongpu/input/parameters.py
So far, the constructor of UiParameter and derived classes relied on the constructor of base Parameter class to set the objects value explicitely like this: 
`self.value = value if value is not None else default`
There are two problems with this that are fixed by this PR
1. the dtype is not necessarily respected 
2. in classes derived from UiParameter, the value is obtained by a possible transformation (logarithm or linear scaling) of the slider-value (see `set_value()`) which is so far not respected during initialization. 
Therefore it happened that when sliders were not touched in the UI, the `set_value()` function as a callback was never called and the parameters `self.value` remained on the initial value which is possibly on the wrong scale.
Besides, the `__str__()` method is …
=> Fix initial setting of Parameter values

docs/TBG_macros.cfg, docs/source/usage/plugins/adios.rst, docs/source/usage/plugins/hdf5.rst, include/picongpu/plugins/Checkpoint.hpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/adios/ADIOSWriter.hpp, include/picongpu/plugins/adios/restart/LoadSpecies.hpp, include/picongpu/plugins/hdf5/HDF5Writer.hpp, include/picongpu/plugins/hdf5/restart/LoadSpecies.hpp, include/picongpu/plugins/misc/SpeciesFilter.hpp, include/picongpu/plugins/misc/containsObject.hpp, include/picongpu/plugins/misc/removeSpaces.cpp, include/picongpu/plugins/misc/removeSpaces.hpp, include/picongpu/plugins/misc/splitString.cpp, include/picongpu/plugins/misc/splitString.hpp, include/picongpu/plugins/multi/IHelp.hpp, include/picongpu/plugins/multi/ISlave.hpp, include/picongpu/plugins/multi/Master.hpp, include/picongpu/plugins/multi/Option.hpp, include/picongpu/plugins/multi/multi.hpp, include/picongpu/plugins/output/IIOBackend.hpp
- refactor HDF, ADIOS to allow usage as multi plugin
- refactor interface class and helper for multi plugins
- `IHelp`: is the new factory to create a `ISlave`
- `ISlave`: remove factory method
- `Master`: use `IHelp` fectory method to create a instance of `ISlave`
- `IIOBackend`:
- inherit from `ISlave`
- `expandHelp()` is moved into `IHelp`
- refactor `EnergyParticle` to use new interafces
- add documentation for the new option
- add function to split a string ￼…
- add `splitString` function to `plugins/misc`
- add function `containsObject()` to check if a container holds an object
- add function `removeSpaces()` to remove all spaces within a string
- add collection include file `misc.hpp`
Please review the PR commit wise!
=> IO with filtered particles

docs/source/usage/plugins.rst
Documents [multi-capable](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1288) and [CPU-capable](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2180) plugins in the manual.
=> Doc: Plugins Multi & CPU

docs/TBG_macros.cfg, docs/source/usage/plugins.rst, docs/source/usage/plugins/energyHistogram.rst, include/picongpu/plugins/BinEnergyParticles.hpp, include/picongpu/plugins/PluginController.hpp, share/picongpu/examples/Bremsstrahlung/etc/picongpu/0008gpus.cfg, share/picongpu/examples/Bunch/etc/picongpu/bunch_0032.cfg, share/picongpu/examples/Empty/etc/picongpu/1gpu.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0004gpus.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/0016gpus.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/0004gpus_gui.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1gpu.cfg, share/picongpu/examples/WeibelTransverse/etc/picongpu/0004gpus.cfg
- refactor energy histogram that the usage as multi plugin is possible
- add `--<species>_energyHistogram.filter` (allow to filter particles)
- update documentaion
=> multi plugin energy histogram with filter

docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/phaseSpace.rst
Update the python examples in the manual for the phase space and energy histogram plugin.
=> Docs Plugins: Update PS & Energy Histo

docs/source/usage/plugins/energyHistogram.rst, docs/source/usage/plugins/phaseSpace.rst, lib/python/picongpu/plugins/energy_histogram.py, lib/python/picongpu/plugins/phase_space.py
Add filter awareness to python post-processing tools for phase space and energy histogram.
Follow-up to #2425 and #2424
@codingS3b can you check if these updates work for you? :)
=> Python Tools (PS, Histo): Filter Aware

include/picongpu/particles/functor/functor.def, include/picongpu/particles/functor/functor.hpp
bug was introduced with #2408
Both files are currently not used.
=> fix wrong include path

share/picongpu/examples/Bunch/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/simulation_defines/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/simulation_defines/param/species.param
follow-up to latest changes in `species.param` in #2464
=> Examples: Update species.param

include/picongpu/algorithms/DifferenceToLower.def, include/picongpu/algorithms/DifferenceToLower.hpp, include/picongpu/algorithms/DifferenceToUpper.def, include/picongpu/algorithms/DifferenceToUpper.hpp
- add `*.def` file for `DifferenceToLower` and `DifferenceToUpper`
- update code style (2nd commit)
=> `DifferenceToLower/Upper` forward declaration

README.md
Add @sbastrakov and @codingS3b to the developers list :)
Welcome! :sparkles:
=> New Developers

include/picongpu/fields/MaxwellSolver/Lehe/LeheCurl.hpp, include/picongpu/particles/bremsstrahlung/Bremsstrahlung.tpp, include/picongpu/particles/bremsstrahlung/PhotonEmissionAngle.hpp, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.tpp, include/picongpu/particles/ionization/byField/ADK/AlgorithmADK.hpp, include/picongpu/particles/ionization/byField/Keldysh/AlgorithmKeldysh.hpp, include/picongpu/plugins/output/images/Visualisation.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp, include/picongpu/plugins/radiation/amplitude.hpp, include/picongpu/plugins/radiation/windowFunctions.hpp, include/picongpu/simulation_defines/unitless/synchrotronPhotons.unitless
=> Replace usage of M_PI in picongpu with Pi

include/picongpu/particles/filter/generic/FreeTotalCellOffset.def
Fix the example and small typos in the filter `generic::FreeTotalCellOffset`.
=> Fix Docs: FreeTotalCellOffset Filter

include/picongpu/fields/laserProfiles/laserExpRampWithPrepulse.hpp
follow-up to PR #2352 
resolves issue #2516 
now the envelope looks like this:
(for upramp amplitude 1e-8 -> 1e-5 -> 1e-4)
or like this for upramp 1e-8 -> 4e-7 -> 5e-4:
=> bugfix for laserExpRampWithPrepulse

etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example
Update MPI & HDF5 Modules after today's maintainance.
=> Hypnos (HZDR): New Modules

docs/source/index.rst, docs/source/install/path.rst
Stream-line the intro pages and the install start a little more.
=> Docs: Stream-line Intro

docs/source/usage/plugins/positionsParticles.rst, share/picongpu/examples/Empty/README.rst, share/picongpu/examples/WarmCopper/README.rst
Fix minor rst formatting errors in the manual.
=> Docs: Minor Formatting

docs/source/_static/hide_chapter_titles.css, docs/source/models/pic.rst
Start writing the PIC model section. Introduces our implemented system of equations for the reader.
ccing @ameresj 
Depending on how you like this, we can merge a first draft and you guys can contribute further updates via additional PRs or we improve it already in this PR.
Note: docs on how to build these docs locally: http://picongpu.readthedocs.io/en/latest/dev/sphinx.html
=> Docs: PIC Model

docs/TBG_macros.cfg, docs/source/usage/plugins.rst, docs/source/usage/plugins/particleCalorimeter.rst, include/picongpu/plugins/PluginController.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
- add new plugin option `file` to define the file name
- add multi plugin functionallity
=> multi plugin `ParticleCalorimeter`

docs/TBG_macros.cfg, docs/source/usage/plugins/particleCalorimeter.rst, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.kernel
- add particle filter
- fix member variables are not initialized, broken since #2563
=> add particle filter to `ParticleCalorimeter`

include/picongpu/plugins/output/GatherSlice.hpp, include/picongpu/plugins/output/header/ColorHeader.hpp, include/picongpu/plugins/output/header/DataHeader.hpp, include/picongpu/plugins/output/header/MessageHeader.hpp, include/picongpu/plugins/output/header/NodeHeader.hpp, include/picongpu/plugins/output/header/SimHeader.hpp, include/picongpu/plugins/output/header/WindowHeader.hpp, include/picongpu/plugins/output/images/PngCreator.hpp, include/picongpu/plugins/output/images/PngCreator.tpp
Add at least the basic picongpu namespace.
Later on, needs proper namespace per directory.
Seen as [polluted scope in Doxygen docs](https://computationalradiationphysics.github.io/picongpu/annotated.html).
=> Misc Plugins: Namespace

include/pmacc/RefWrapper.hpp, include/pmacc/eventSystem/tasks/TaskSetCurrentSizeOnDevice.hpp
Add missing namespace to PMacc. Related to #2577
=> PMacc: Add Missing Namespaces

docs/source/usage/plugins/energyFields.rst, docs/source/usage/plugins/energyParticles.rst
Add a note on the expected precision of the currently implemented reduce operations for energy of fields and energy of particles.
Related to discussion in https://github.com/ComputationalRadiationPhysics/picongpu/issues/523#issuecomment-70630415
=> Docs: Note on Energy Reduce

include/pmacc/math/vector/Vector.hpp
Add a member function to calculate the sum of all components.
=> PMacc: Vector sumOfComponents

include/picongpu/fields/FieldJ.tpp
The stride size for `StrideMapping` depends on the supercell size and the stencil margins.
In the case where the lower and upper margin fits into one supercell we need only a stride of 2 instead of the current used default stride 3.
If we use stencils with margins larger than one supercell the default 3 can be to low and will produce data race conditions (therefore this PR is also a fix for big stencil margins).
- calculate optimal stride size (skip only as much supercells as needed to avoid race conditions for cell updates)
=> optimize stride size for update FieldJ

etc/picongpu/hypnos-hzdr/k20_restart.tpl
Add a template for auto-restart on Hypnos' K20 queue.
Derived from `k20.tpl` and `k80_restart.tpl`. Identical to what was posted in https://github.com/ComputationalRadiationPhysics/picongpu/issues/2618#issuecomment-395727160.
=> TBG: Hypnos K20 Restart

docs/TBG_macros.cfg, docs/source/usage/plugins/adios.rst, docs/source/usage/plugins/checkpoint.rst
Add more information on ADIOS metafile handling and skipping.
=> Docs: ADIOS Metafile

include/picongpu/particles/flylite/helperFields/LocalEnergyHistogram.kernel, include/picongpu/plugins/IntensityPlugin.hpp, include/picongpu/plugins/common/stringHelpers.cpp, include/pmacc/fields/operations/AddExchangeToBorder.hpp, include/pmacc/fields/operations/CopyGuardToExchange.hpp, include/pmacc/math/vector/Vector.hpp, include/pmacc/particles/ParticlesBase.kernel
Fix some uncommon spellings. Close #2635
=> Docs: element-wise

include/picongpu/fields/FieldJ.tpp, include/picongpu/fields/FieldTmp.tpp, include/pmacc/particles/ParticlesBase.hpp
Fix #2643 spelling of "guard" in docs.
=> Fix Spelling of Guard

CHANGELOG.md
Add changelog from bugfix releases that are already published.
=> Changelog: Add 0.3.1 & 0.3.2

docs/propose_changelog.py
Sort for new label names. Add Python3 support.
=> Changelog Script: User Input

lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
To change plots on the eupraxia GUI it is also necessary to clear the colorbar. Therefore the function clear_cbar was added.
=> add clear_cbar to phase_space_visualizer.py

include/pmacc/cuSTL/container/HostBuffer.hpp, include/pmacc/memory/buffers/HostBuffer.hpp
Add 1D support to the cuSTL HostBuffer.
Needed in #2588
=> cuSTL: HostBuffer 1D Support

etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example
Upgrade to newer GCC 5.3.0 toolchain.
=> Hypnos Laser Profile: GCC 5.3.0

lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
rescaling of updated imshow data must update vmin, vmax
=> phase space mpl: fix update colorbar

CHANGELOG.md
Draft for the 0.4.0 changelog, up to PR #2679.
- add PRs:
=> Changelog: 0.4.0

README.md, docs/source/index.rst
Changed to
*PIConGPU - particle-in-cell simulations for the exascale era*
Thanks everyone! :)
Close #2250
=> Docs: New Subtitle

docs/source/index.rst, lib/python/picongpu/plugins/__init__.py
Fix module init file and link new docs into main sphinx document.
Follow-up to #2726
=> Python Docs: Fix Paths

INSTALL.rst
=> Docs: Alpaka 0.3.4

LICENSE.md, README.md
Update list of names and responsible people.
=> Update Readme & License: People

include/picongpu/param/pusher.param, include/picongpu/particles/pusher/particlePusherAcceleration.hpp
fix style according to @ax3l's comments in PR #2731.
=> Fix style issues with particlePusherAcceleration

include/picongpu/param/species.param
Fix 1 grammar error and update(?)  example text for particle shape
=> Fix species.param example doc and grammar

include/picongpu/param/species.param, share/picongpu/examples/Bunch/include/picongpu/param/species.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
Follow up to ComputationalRadiationPhysics/picongpu#2793.
=> Fix species.param docu (in all examples too)

CHANGELOG.md
Merge back `master` to have the changelog of 0.4.1 included.
=> Merge 0.4.1 Changelog

etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example
Add a `$proj` variable on Taurus similar to the one in Titan.
Should we also use this for accounting in our `.tpl` script?
=> Taurus Profile: Project

share/picongpu/examples/Bremsstrahlung/etc/picongpu/8.cfg, share/picongpu/examples/Bunch/etc/picongpu/32.cfg, share/picongpu/examples/Empty/etc/picongpu/1.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/4_isaac.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/8.cfg, share/picongpu/examples/FoilLCT/etc/picongpu/8_isaac.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/16.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/1_bench.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4_bench.cfg, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/8_bench.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/1_isaac.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/32.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4_gui.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/4_isaac.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg, share/picongpu/examples/LaserWakefield/etc/picongpu/8_isaac.cfg, share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/1.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/32.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/4.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/64.cfg, share/picongpu/examples/ThermalTest/etc/picongpu/8.cfg, share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg, share/picongpu/examples/WeibelTransverse/etc/picongpu/4.cfg
- FoilLCT: ISAAC improved grouping of variables for external overwrite
- same empty newline spacing between sections
=> Examples: Unify .cfg

INSTALL.rst
Add the documentation on installing c-blosc.
We use it regularly with ADIOS now.
Also adds more detailed section on libpng.
=> Docs: Install Blosc

docs/source/usage/plugins.rst, docs/source/usage/plugins/sliceEmittance.rst, include/picongpu/plugins/Emittance.hpp, include/picongpu/plugins/PluginController.hpp
This pull request adds a plugin that calculates emittance and slice emittance for various time steps in y dimension.
=> Emittance Plugin

lib/python/picongpu/plugins/data/__init__.py, lib/python/picongpu/plugins/data/emittance.py, lib/python/picongpu/plugins/data/energy_histogram.py, lib/python/picongpu/plugins/plot_mpl/__init__.py, lib/python/picongpu/plugins/plot_mpl/emittance_evolution_visualizer.py, lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py, lib/python/picongpu/plugins/plot_mpl/energy_waterfall_visualizer.py, lib/python/picongpu/plugins/plot_mpl/slice_emittance_visualizer.py, lib/python/picongpu/plugins/plot_mpl/slice_emittance_waterfall_visualizer.py
- `emittance_evolution_visualizer`: plots value of transverse emittance for each iteration
- `slice_emittance_visualizer`: plots slice emittance for each slice for one iteration
- `slice_emittance_waterfall_visualizer`: plots slice emittance for each slice for each iteration
- `energy_waterfall_visualizer`: plots energy histogram for each iteration
=> DataReader: Emittance & PlotMPL: Emittance, SliceEmittance, EnergyWaterfall

docs/source/usage/plugins/radiation.rst
This pull request fixes an updated documentation of the picongpu command line flags used for the radiation plugin.
Thanks @ejcjason for finding this error.
=> Radiation Plugin: Update Options in Docs

include/picongpu/param/ionizer.param
=> Fix Typo: Aluminium in ionizer.param

include/pmacc/mappings/threads/ForEachIdx.hpp
Fixes #2877 . Also add tiny improvements to the code in this file.
=> ForEachIdx::operator(): Use Universal Reference

docs/source/install/profile.rst, etc/picongpu/juwels-jsc/batch.tpl, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus.tpl, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
Add new system documentation, profiles and tbg template for the [JUWELS cluster at JSC](http://www.fz-juelich.de/ias/jsc/EN/Expertise/Supercomputers/JUWELS/Configuration/Configuration_node.html).
The software stack seems the same as on JURECA #2869 .
It has 2 queues:
- batch: 2 x 24-core Intel Skylake CPUs per node, max 512 nodes per job
- gpus: 4 x NVidia V100 per node, max 48 nodes per job
TODO:
=> System: JUWELS

thirdParty/cuda_memtest/CMakeLists.txt
Updates cuda_memtest:
- CMake: Honor _ROOT Env Hints [#19](https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/19)
From
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/6d505ea392f51ac69d02eafd866f6d3456cadec7) to
- `cuda_memtest@dev` (https://github.com/ComputationalRadiationPhysics/cuda_memtest/commit/fc69def93e281dd12014061740aa169206c46399)
```bash
git subtree pull --prefix thirdParty/cuda_memtest \
```
=> Update cuda_memtest: CMake CUDA_ROOT Env

CHANGELOG.md, share/picongpu/dockerfiles/README.rst, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile, share/picongpu/dockerfiles/ubuntu-1604/Singularity
Merge back `master` to have the changelog of 0.4.3 included.
```bash
git merge --strategy-option ours mainline/master
```
=> Merge 0.4.3 Changelog

etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/jureca-jsc/batch_picongpu.profile.example, etc/picongpu/jureca-jsc/booster_picongpu.profile.example, etc/picongpu/jureca-jsc/gpus_picongpu.profile.example, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example, etc/picongpu/titan-ornl/cpu_picongpu.profile.example, etc/picongpu/titan-ornl/gpu_picongpu.profile.example
Fix the section title length in our example profiles to stay consistently with 80 chars.
Follow-up to fix style issues introduced in #2903 #2930
=> Profiles: Section Title Length

docs/source/install/profile.rst
=> fix style (underline length) in profile.rst

include/picongpu/plugins/adios/ADIOSWriter.hpp
The ADIOS plugin calles `.c_str()` on temporary strings in several places. Introduce the intermediate string value as a variable to avoid use-after-free errors. The [same issue](https://github.com/openPMD/openPMD-api/pull/421) came up in the openPMD API.
=> ADIOS: Avoid unsafe temporary strings

include/picongpu/main.cpp
The motivation is to make debugging and user experience in case of an exception a little bit nicer.
Can later add exception hierarchies from some libraries we use, or our own if we will have one, for a more detailed reporting.
I've used `EXIT_FAILURE` instead of 1 for the exit error code. Not sure if we rely on it being 1 anywhere.
Also updated the code style in this file.
=> Add a wrapper around main() to catch and report exceptions

include/pmacc/particles/memory/boxes/ParticlesBox.hpp
Const added to getters in ParticleBox.hpp for compatibility with new ISAAC Renderer
=> Add const getters to ParticleBox

README.md
Add a badge that shows the number of commits in `dev` since the latest release.
Nice and informational, especially since we (still) show the stable release-branch `master`.
Also add a link and counter to "good first issue" issues :-)
=> Badge: Commits Since Release & Good First

include/picongpu/fields/FieldB.tpp, include/picongpu/fields/FieldE.tpp, include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp, include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp, include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp, include/picongpu/fields/absorber/ExponentialDamping.hpp, include/picongpu/fields/absorber/ExponentialDamping.kernel, include/picongpu/plugins/adios/WriteMeta.hpp, include/picongpu/plugins/hdf5/WriteMeta.hpp
Also, rename accordingly, remove unnecessary includes of this file, add proper namespaces, add minor style changes.
Motivation: I plan to do a draft of field manipulators kinda like particle manipulators, so to avoid collisions first moved this one out, since the old name did not fit anyways.
=> Move fields/FieldManipulator to fields/absorber/ExponentialDamping

README.md
Add Dr.s ;-)
Got my certificate, @PrometheusPi did you get yours as well? :)
=> Docs: Dr.s

include/picongpu/param/isaac.param, include/picongpu/plugins/IsaacPlugin.hpp
1. IsaacPlugin updated for particle rendering
2. Particle sources can be selected in the isaac.param
=> Isaac Plugin updated for particle rendering with updated Isaac lib

lib/python/picongpu/utils/memory_calculator.py
=> Add an option to account for PML in the memory calculator

include/picongpu/param/fieldSolver.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldSolver.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/fieldSolver.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/fieldSolver.param
This was forgotten when YeePML was added.
=> Add YeePML to comments for field solver selection

docs/source/install/profile.rst, etc/picongpu/aris-grnet/gpu.tpl, etc/picongpu/aris-grnet/gpu_picongpu.profile.example
The profile has been created by @StevE-Ong in #2998.
=> System: ARIS

include/pmacc/particles/ParticlesBase.kernel
I refactored `counterParticles` as suggested by @ax3l and @sbastrakov in #2642.
=> rename "counterParticles" to "numParticles"

.zenodo.json, docs/source/models/pic.rst, docs/source/usage/plugins.rst, docs/source/usage/plugins/adios.rst, docs/source/usage/plugins/hdf5.rst, docs/source/usage/plugins/isaac.rst
Add missing publications to references in docs and zenodo meta data.
=> Docs: Add New References

docs/source/usage/plugins/checkpoint.rst
=> Docs: add missing checkpoint options

docs/source/usage/plugins/radiation.rst, docs/source/usage/plugins/transitionRadiation.rst
Updates the macro-particle form factor documentation for both the radiation and the transition radiation plugin.
@PrometheusPi
=> Update the form factor documentation

etc/picongpu/summit-ornl/gpu_picongpu.profile.example
#3007 has some paths of @ax3l , I assume a leftover.
Thanks @arghyac007 for pointing out.
=> fix optional install instructions in the Summit profile

README.md, docs/source/usage/plugins/adios.rst, thirdParty/cmake-modules/FindADIOS.cmake
This pull request is implanting a change/update in the URL to ADIOS. This change was suggested by @ax3l in a later (after closing) comment in issue #3085.
=> update URL to ADIOS

docs/source/usage/plugins.rst
Someone broke the plugin table markdown. Fixed it.
=> Docs: Fix Plugin Table

docs/source/usage/plugins/phaseSpace.rst
Add required but missing `ps=...` argument in documentation.
Add further options as well.
=> Docs: Fix PS Plugin Matplotlib

docs/source/usage/param.rst
And a short description. I wanted to make clear it's not a core PIConGPU tool, but still potentially useful to quickly make a basic setup (e.g. for new users) and then it's always possible to edit `.param` files manually like one would normally do anyway. @hightower8083 I did not put your name there so far, do you want it?
P.S. Thanks @hightower8083 for coming by to chat! Just a friendly reminder to make an issue for tracking workflows that we were discussing (when you have time for that, ofc).
=> Add a link to PoGit to the docs

etc/picongpu/aris-grnet/gpu_picongpu.profile.example, etc/picongpu/cori-nersc/knl_picongpu.profile.example, etc/picongpu/davide-cineca/gpu_picongpu.profile.example, etc/picongpu/draco-mpcdf/picongpu.profile.example, etc/picongpu/hemera-hzdr/defq_picongpu.profile.example, etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example, etc/picongpu/hemera-hzdr/k20_picongpu.profile.example, etc/picongpu/hemera-hzdr/k80_picongpu.profile.example, etc/picongpu/hydra-hzdr/default_picongpu.profile.example, etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example, etc/picongpu/jureca-jsc/batch_picongpu.profile.example, etc/picongpu/jureca-jsc/booster_picongpu.profile.example, etc/picongpu/jureca-jsc/gpus_picongpu.profile.example, etc/picongpu/juwels-jsc/batch_picongpu.profile.example, etc/picongpu/juwels-jsc/gpus_picongpu.profile.example, etc/picongpu/lawrencium-lbnl/picongpu.profile.example, etc/picongpu/pizdaint-cscs/picongpu.profile.example, etc/picongpu/summit-ornl/gpu_picongpu.profile.example, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/k20x_picongpu.profile.example, etc/picongpu/taurus-tud/k80_picongpu.profile.example, etc/picongpu/taurus-tud/knl_picongpu.profile.example
follow up of #3133, remove duplicated full path to the completion file
=> avoid bash complition file path repetition

docs/source/usage/plugins/radiation.rst
This pull request fixes inconsistencies in the radiation plugin documentation as reported in issue #3095.
=> Fix doc rad plugin units and factors

etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_picongpu.profile.example, etc/picongpu/taurus-tud/V100_restart.tpl
Number of tasks started per node was wrong.
- use node exclusive, else scheduling is wrong
- add function `getNode` and `getDevice`
=> fix taurus profile

include/picongpu/initialization/InitialiserController.hpp
The previous version used `BASE_DENSITY` for all species. Replace it with a proper density of the species.
Thanks @IoannisTazes for drawing our attention towards it and @n01r for [spotting the issue](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3160#issuecomment-584186175).
=> Fix calculation of omega_p for logging

USAGE.rst
This is the first part of [this suggestion](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3167#issuecomment-589388041). A follow-up PR will provide the second, larger, part.
=> Add a brief description of simulation output to basics

CHANGELOG.md
@ComputationalRadiationPhysics/picongpu-maintainers @ComputationalRadiationPhysics/picongpu-developers please check the change log and suggest updates for the short summery of this release.
I created the change-log with our change-log tool (thx @ax3l ) and did some manual corrections.
The contributor list was generated with the following command and was manually adjusted.
```
git log d340812641320d3a61e343a521287fd0720ba55b..HEAD | grep Author | sort | uniq | sed "s/ \+/ /g; s/^ //" | cut -d" " -f2-3
```
=> changelog for 0.5.0

docs/source/install/profile.rst, etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example, share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Backport #3228 and #3225 to the 0.5.0-rc1 to allow that we can test the docker container.
=> backport to 0.5.0-rc1

thirdParty/cupla/example/CUDASamples/blackScholes/src/BlackScholes_gold.cpp, thirdParty/cupla/include/cupla/cudaToCupla/runtime.hpp, thirdParty/cupla/include/cupla/defines.hpp, thirdParty/cupla/include/cupla/device/math/Common.hpp
- update to cupla https://github.com/alpaka-group/cupla/tree/f60a0ac72cb175d4a8a67301882f7a6b1de4c3c3
```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git subtree pull --prefix thirdParty/cupla git@github.com:alpaka-group/cupla.git dev --squash
```
This update pulls the latest cupla math changes, those are required for the next math refactorings in pmacc.
=> update to latest cupla dev

include/picongpu/plugins/ResourceLog.cpp, include/picongpu/plugins/ResourceLog.hpp
=> Fix returning a stringstream by value

README.md, include/mpiInfo/CMakeLists.txt, include/picongpu/CMakeLists.txt, include/pmacc/CMakeLists.txt, include/pmacc/PMaccConfig.cmake, share/pmacc/examples/gameOfLife2D/CMakeLists.txt, src/tools/png2gas/CMakeLists.txt, src/tools/splash2txt/CMakeLists.txt
PIConGPU is now a C++14 code. Updates CMake files and README badge.
Follow-up to #3242
=> Doc: C++14

bin/tbg
Modification of the TBG script which would implement #3189.
=> tbg pathlist

.gitlab-ci.yml
Provide a dummy job for the gitlab CI to be able to merge currently finished pull requests.
The real CI script will be provided with #3283
=> provide gitlab CI yaml

docs/source/usage/param/plugins.rst, docs/source/usage/plugins/transitionRadiation.rst
This pull request fixes some warnings by the the sphinx documentation. 
(There is still the open issue of sphinx+breath+doxygen generated code not showing up.)
=> fix minor issues with the sphinx rst formating

include/picongpu/fields/MaxwellSolver/Lehe/Curl.hpp
=> Fix implementation of Lehe curl for CherenkovFreeDirection_X

src/tools/bin/plotNumericalHeating
The tool should be fixed with #2697 but because of wrong regex the tool
is still broken.
=> fix plotting tool for numerical heating

etc/picongpu/aris-grnet/gpu.tpl, etc/picongpu/bash/mpiexec.tpl, etc/picongpu/bash/mpirun.tpl, etc/picongpu/davide-cineca/gpu.tpl, etc/picongpu/davinci-rice/picongpu.tpl, etc/picongpu/hemera-hzdr/fwkt_v100.tpl, etc/picongpu/hemera-hzdr/gpu.tpl, etc/picongpu/hemera-hzdr/k20.tpl, etc/picongpu/hemera-hzdr/k20_restart.tpl, etc/picongpu/hemera-hzdr/k80.tpl, etc/picongpu/hemera-hzdr/k80_restart.tpl, etc/picongpu/jureca-jsc/gpus.tpl, etc/picongpu/juwels-jsc/gpus.tpl, etc/picongpu/lawrencium-lbnl/fermi.tpl, etc/picongpu/lawrencium-lbnl/k20.tpl, etc/picongpu/pizdaint-cscs/large.tpl, etc/picongpu/pizdaint-cscs/normal.tpl, etc/picongpu/taurus-tud/V100.tpl, etc/picongpu/taurus-tud/V100_restart.tpl, etc/picongpu/taurus-tud/k20x.tpl, etc/picongpu/taurus-tud/k80.tpl
=> Clarify output concerning cuda_memtest not being available

docs/TBG_macros.cfg, docs/source/usage/plugins/radiation.rst, include/picongpu/plugins/radiation/Radiation.hpp, include/picongpu/plugins/radiation/Radiation.kernel
Add runtime option `numTmpResults` to increase independent work on a
device.
If set to one the code will behaves as before this PR.
The default will is two to utilize modern GPU devices with a typicaly configuration.
=> radiation plugin: add new option

include/picongpu/_defaultParam.loader, include/picongpu/fields/currentDeposition/Strategy.def, include/picongpu/particles/Particles.hpp, include/picongpu/particles/ParticlesFunctors.hpp, include/picongpu/simulation/control/MySimulation.hpp, include/pmacc/Environment.hpp, include/pmacc/PMaccConfig.cmake, include/pmacc/algorithms/math/doubleMath/bessel.tpp, include/pmacc/algorithms/math/doubleMath/floatingPoint.tpp, include/pmacc/algorithms/math/doubleMath/modf.tpp, include/pmacc/algorithms/math/floatMath/bessel.tpp, include/pmacc/algorithms/math/floatMath/exp.tpp, include/pmacc/algorithms/math/floatMath/floatingPoint.tpp, include/pmacc/algorithms/math/floatMath/modf.tpp, include/pmacc/math/ConstVector.hpp, include/pmacc/particles/memory/boxes/ParticlesBox.hpp, include/pmacc/random/methods/XorMin.hpp, include/pmacc/static_assert.hpp, include/pmacc/types.hpp
Increase HIP compatibility to PMacc and PIConGPU.
- HIP support for RNG XorMin
- update pre-compiler switches to support HIP
This PR is not fully introduce HIP support. There will be more updates soon.
=> Increase HIP compatibility 

docs/source/dev/styleguide.rst
Fix wrong syntax used for code snipped in `rst` file.
=> fix documentation

share/ci/run_picongpu_tests.sh
For a while, there are environment variables available that give information about the available memory and cores in the CI runner.
This PR calculates the parallelism used to compile tests based on this information.
=> CI: auto adjust parallelism

include/pmacc/nvidia/atomic.hpp, include/pmacc/nvidia/functors/Atomic.hpp
- add optimization for PMacc's atomic functor
- fix documentation of atomic functor
=> Optimize atomic functor for HIP

etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Update used modules for summit ORNL.
=> update summit profile

include/picongpu/plugins/openPMD/WriteSpecies.hpp, include/picongpu/plugins/openPMD/openPMDDimension.hpp, include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp, include/picongpu/plugins/output/ConstSpeciesAttributes.hpp
This is a quick fix for #3383. Feel free to suggest improvement like:
- common code structure
-  avoid magic numbers 
- etc.
=> openPMD plugin: Fix ED-PIC Attributes

thirdParty/cupla/alpaka/.zenodo.json, thirdParty/cupla/alpaka/CHANGELOG.md, thirdParty/cupla/alpaka/README.md, thirdParty/cupla/alpaka/cmake/alpakaCommon.cmake, thirdParty/cupla/alpaka/include/alpaka/dev/cpu/SysInfo.hpp
update to tatest [cupla dev branch](https://github.com/alpaka-group/cupla/tree/f60a0ac72cb175d4a8a67301882f7a6b1de4c3c3) with alpaka 0.6.0 release 
```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git subtree pull --prefix thirdParty/cupla git@github.com:alpaka-group/cupla.git dev --squash
```
=> Topic cupla update

include/pmacc/PMaccConfig.cmake
=> mark CUDA 11.2 as supported version

share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
Pointer in the thermal test is not initialized but deleted in the destructor, this could result in segfaults, e.g. when calling `picongpu --help`
=> fix segfault

src/tools/bin/newVersion.sh
With #3502 we forgot to update the tool `newVersion.sh`
=> fix tool `newVersion.sh`

share/pmacc/examples/gameOfLife2D/main.cpp
This pull request clarifies some error messages in the Game of Li(f)e implementation and adds some comments.
=> Clarify error message and add comments in GameOfLive

include/picongpu/fields/EMFieldBase.tpp, include/picongpu/traits/GetMargin.hpp
Was found during work on #3561.
=> Refactor and update comments of GetMargin

include/picongpu/simulation/stage/CurrentBackground.hpp, include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
Due to compile time variable usage for an early return the compiler is
throwing a warning.
https://gitlab.com/hzdr/crp/picongpu/-/jobs/1143505980#L3971
=> fix warning: unreachable code

docs/source/models/AOFDTD.rst
I added the dispersion relation and stability condition for the aofdtd field solver to the documentation.
=> Updatet documentation of AOFDTD

etc/picongpu/juwels-jsc/booster.tpl, etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Added a profile for the JUWELS booster module.
Since the software configuration is not yet finalized this is a work in progress.
Currently the proposed profile and job script template should allow PIConGPU to run on the booster.
Memory size `TBG_memPerDevice` has not been adjusted and the author variable has been eliminated for convenience.
=> JUWELS booster profile

etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Further, I created a script to install all dependencies which is linked in the profile as well.
I also changed to `getDevice()` function to obtain an interactive shell on a node and not just the job step.
=> Update juwels-booster profile to include all dependencies

docs/source/usage/workflows.rst, docs/source/usage/workflows/boundaryConditions.rst
I am not sure if "workflows" is the best place for it, but in the current structure seemed most fitting,
Resolves #3593.
=> Add brief user documentation for boundary conditions

docs/source/models/AOFDTD.rst
With values of the additional factor appearing in the stability condition
for M=1,..,8 neighbors.
=> Update AOFDTD manual section

include/picongpu/param/grid.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param, share/picongpu/examples/Bremsstrahlung/include/picongpu/param/grid.param, share/picongpu/examples/Bunch/include/picongpu/param/grid.param, share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/grid.param, share/picongpu/examples/FoilLCT/include/picongpu/param/grid.param, share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param, share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param, share/picongpu/examples/SingleParticleTest/include/picongpu/param/grid.param, share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param, share/picongpu/examples/TransitionRadiation/include/picongpu/param/grid.param, share/picongpu/examples/WarmCopper/include/picongpu/param/grid.param, share/picongpu/examples/WeibelTransverse/include/picongpu/param/grid.param, share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/grid.param, share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/grid.param, share/picongpu/tests/XrayScattering/include/picongpu/param/grid.param, share/picongpu/tests/compileFieldSolver/include/picongpu/param/grid.param
Update and add in all `grid.param` files the latest doxygen string for
the file description.
Co-authored-by: @sbastrakov 
Note: I have not added the `input-output` label because this is not a change a user must know about (no breaking change).
=> update grid.param file doxygen string

include/picongpu/fields/incidentField/Solver.hpp
After merging #3592 PIConGPU is no longer compiling.
=> fix broken compile

include/picongpu/plugins/multi/ISlave.hpp, include/picongpu/plugins/multi/Master.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
=> fix processing of outgoing particles by multi plugins

etc/picongpu/spock-ornl/caar.tpl, etc/picongpu/spock-ornl/caar_picongpu.profile.example
=> Profile for spock at ORNL

docs/TBG_macros.cfg
Follow-up to #3635 were we forgot to add it.
=> Add fieldAbsorber runtime parameter to TBG_macros.cfg

include/picongpu/particles/creation/creation.kernel
With #3616 we broke the ionization kernel.
=> Fix particle creation: increase primary thread number

share/ci/compiler_hipcc.yml
=> CI: use HIP 4.2

docs/source/usage/plugins/openPMD.rst
=> Extend docs for the openPMD plugin regarding --openPMD.source

share/picongpu/benchmarks/SPEC/cmakeFlags, share/picongpu/benchmarks/SPEC/etc/picongpu/1_radiation.cfg, share/picongpu/benchmarks/SPEC/include/picongpu/param/radiation.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/radiationObserver.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesDefinition.param
This pull request adds radiation cases for the SPEC benchmarks.
=> add radiation cases to SPEC benchmark

docs/source/install/profile.rst, etc/picongpu/ascent-ornl/gpu_batch.tpl, etc/picongpu/ascent-ornl/gpu_picongpu.profile.example
This pull request adds the setup for the Ascent (test cluster) at ORNL.
=> Ascent (ORNL) setup

docs/source/usage/plugins/openPMD.rst, etc/picongpu/summit-ornl/gpu_batch_pipe.tpl, share/picongpu/examples/KelvinHelmholtz/etc/picongpu/6_pipe.cfg
See section 2 of [this preprint](https://arxiv.org/abs/2107.06108) as well as the added documentation for this PR.
I have tested the template successfully on Summit.
TODO:
=> Summit template and documentation for asynchronous writing via ADIOS2 SST

docs/source/dev/pmacc.rst, docs/source/prgpatterns/lockstep.rst
=> Fix broken includes of doxygen into readthedocs

CONTRIBUTING.md
added the clang-format step to the suggested pipeline for developers
=> clang-format included in suggested contribution pipeline

etc/picongpu/taurus-tud/k80_picongpu.profile.example
Modules had to be updated and an install script for required libraries is provided.
LaserWakefield example compiles, runs, and produces output.
=> Fix taurus-tud k80 profile

docs/source/usage/workflows.rst, docs/source/usage/workflows/addLaser.rst
To be extended for incident field equations in a follow up PR.
=> Add a brief doc page on ways of adding a laser to a simulation

docs/source/models/AOFDTD.rst
The code was fine, the issue was only in documentation. Was found while looking at #3735 .
=> Fix mistakes in documentation of FDTD equations

docs/TBG_macros.cfg, docs/source/usage/plugins/isaac.rst, include/picongpu/param/isaac.param, share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param, share/picongpu/tests/compileCurrentSolver/include/picongpu/param/isaac.param, share/picongpu/tests/compileFieldSolver/include/picongpu/param/isaac.param, share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param
Add suggestions from @PrometheusPi: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3719#pullrequestreview-729674893
=> update ISAAC documentation

docs/source/usage/plugins.rst
=> Further update plugin requirements in readthedocs

INSTALL.rst, thirdParty/mallocMC/.github/workflows/ci.yml, thirdParty/mallocMC/.zenodo.json, thirdParty/mallocMC/CHANGELOG.md, thirdParty/mallocMC/INSTALL.md, thirdParty/mallocMC/README.md, thirdParty/mallocMC/examples/mallocMC_example01.cpp, thirdParty/mallocMC/examples/mallocMC_example03.cpp, thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter.hpp, thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/Noop.hpp, thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp, thirdParty/mallocMC/src/include/mallocMC/mallocMC_utils.hpp, thirdParty/mallocMC/src/include/mallocMC/reservePoolPolicies/AlpakaBuf.hpp, thirdParty/mallocMC/src/include/mallocMC/version.hpp, thirdParty/mallocMC/tests/dimensions.cpp, thirdParty/mallocMC/tests/verify_heap.cpp, thirdParty/mallocMC/tests/verify_heap_config.hpp
- pull mallocMC 2.6.0 dev branch https://github.com/alpaka-group/mallocMC/tree/864f635a86e9bb0a581151e0f6146d0fee3a4d9e
```
git subtree pull --prefix thirdParty/mallocMC \
git@github.com:ComputationalRadiationPhysics/mallocMC.git dev --squash
rm -r thirdParty/mallocMC/alpaka
git commit --amend -a
```
- update `INSTALL.rst`
=> update to malloc mc2.6.0crp-dev

include/picongpu/plugins/IsaacPlugin.hpp
Remove unused variable in the ISAAC plugin.
=> Plugin: ISAAC remove unused variable

include/picongpu/plugins/openPMD/openPMDWriter.hpp
See [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3759#discussion_r702988100)
=> Remove unnecessary parameter in writeField function template of openPMD plugin

include/pmacc/particles/ParticlesBase.hpp, include/pmacc/particles/ParticlesBase.kernel
As discussed [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3770#discussion_r704473988)
I didn't test it yet,  but maybe you can already have a look if that appears reasonable @psychocoderHPC ?
=> Enable KernelShiftParticles to operate in guard area

.gitignore
Added a few macOS specific system generated files to be ignored on commits
=> update gitignore  for macOS system generated files

include/pmacc/simulationControl/SimulationHelper.hpp
It was previously done inside the checkpointing function which was confusing.
I am now working on documenting in general how the PIConGPU computational loop works and can be extended, and so found out this confusing piece.
=> Separate notification of plugins into a separate function in SimulationHelper

include/picongpu/particles/bremsstrahlung/PhotonEmissionAngle.hpp, include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp, include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp, include/picongpu/plugins/ChargeConservation.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Replace with `std::shared_ptr`.
Also remove all includes to `boost/shared_ptr.hpp`.
=> Remove leftover boost::shared_ptr

include/pmacc/kernel/atomic.hpp
=> Fix unused variable warning

include/pmacc/memory/boxes/CachedBox.hpp
This is a similification of the code in CachedBox.hpp
=> Refactor CachedBox

docs/source/dev/extending.rst, include/picongpu/plugins/BinEnergyParticles.hpp, include/picongpu/plugins/Checkpoint.hpp, include/picongpu/plugins/Emittance.hpp, include/picongpu/plugins/EnergyParticles.hpp, include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp, include/picongpu/plugins/multi/IHelp.hpp, include/picongpu/plugins/multi/IInstance.hpp, include/picongpu/plugins/multi/Master.hpp, include/picongpu/plugins/multi/multi.hpp, include/picongpu/plugins/openPMD/openPMDWriter.hpp, include/picongpu/plugins/output/IIOBackend.hpp, include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
It is the most pressing part of #3790.
I will write my considerations for other naming there.
=> Rename instance interface for multiplugins

docs/source/dev/extending.rst
added a small note on when and how often pluginUnload() and pluginLoad() are called, as well for what pluginGetName() is used
=> clarification on pluginUnload

include/picongpu/plugins/BinEnergyParticles.hpp, include/picongpu/plugins/IntensityPlugin.hpp, include/picongpu/plugins/output/GatherSlice.hpp, include/picongpu/plugins/output/WriteSpeciesCommon.hpp, include/picongpu/plugins/output/header/MessageHeader.hpp, include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp, include/pmacc/memory/Delete.hpp, include/pmacc/memory/buffers/MappedBufferIntern.hpp, include/pmacc/particles/memory/buffers/MallocMCBuffer.tpp
Also replace its former users that were host-side C-style arrays in plugins with `std::vector `
=> Remove macro __deleteArray() 

include/picongpu/particles/InitFunctors.hpp
Explain it only applies to coordinate space. Add a more clear separation of physical density vs. macroparticles. Add a general workflow of sampling algorithm.
I decided to put it there as this doxygen is included to readthedocs when describing `speciesInitialization.param`. It partly answers what #3676 (faily imo) pointed out. Some more inside comments are also needed, and probably some renaiming, as `T_PositionFunctor` is actually more of a `T_InCellSamplingFunctor`. However, at least it should answer the user-facing part of #3676.
=> Extent comments of CreateDensity

docs/source/models/collisional_ionization.rst, docs/source/usage/plugins/radiation.rst, docs/source/usage/reference.rst
This pull request implements the reference list as suggested in  #3258.
~~**Please do not merge** since this pull request is still not complete. 
But: feel free to already comment on the pull request: especially on sorting.~~
=> add reference list

docs/source/dev/debugging.rst, docs/source/index.rst
So that we can refer our colleagues and particularly external users to it.
=> Add a readthedocs page on debugging

include/picongpu/fields/incidentField/Solver.hpp
As discovered by Max ~~(student of @steindev , doesn't have a github account)~~ @Enderpigmen there were some inaccuracies in the incident field solver implementation. It was still working, but produced more "noise" and inaccuracies than it should have. It was missed previously as the functors I used for testing were a bit unfortunately chosen and couldn't show it. The two commits are two unrelated fixes.
Draft while waiting for Max to check it on all directions, for now he did with Y (as we originally saw issues there). Thanks to him for running lots of simulations and demonstrating the problem!
=> Fix inaccuracies in incident field solver

docs/source/index.rst, docs/source/models/total_field_scattered_field.rst, docs/source/usage/workflows/addLaser.rst
~~Current state, too early to really review. Not marked as draft, as I would like to see the results rendered in readthedocs.~~ Ready for review.
The idea is to explain it sufficiently enough so that someone else than me could redo the work of #3860 or provide support for that code if needed.
=> Add readthedocs description of TF/SF field generation

include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
As discussed [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3892#discussion_r741089576).
=> Optimize Jz calculation in EmZ 2d

include/picongpu/particles/MoveParticle.hpp
Reduce the read and write operations into global memory for particles
which not leaving the cell.
- remove a unessesary interger multiplication
- update multimask only if value has changed
- read/write local cell index only if particle changed the cell
This PR decreases the pusher register footprint for the SPEC benchmark from 64 to 56 registers.
=> improve performance of MoveParticle

docs/source/usage/workflows/addLaser.rst, include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp, include/picongpu/fields/MaxwellSolver/FDTD/FDTD.def, include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp, include/picongpu/fields/MaxwellSolver/Lehe/Lehe.hpp, include/picongpu/fields/MaxwellSolver/None/None.def, include/picongpu/fields/incidentField/DerivativeCoefficients.hpp, include/picongpu/fields/incidentField/Solver.hpp, include/picongpu/fields/incidentField/Solver.kernel, include/picongpu/traits/GetCurl.hpp
~~This is a very messy so far draft implementation of incident field for arbitrary order FDTD. It doesn't really work yet, but my toy example for 4th order (now commented out inside the kernel) kinda worked.~~
Now the implementation is finished and ready for review.
Readthedocs should be extended with explanation of how to use incident field and how the current implementation works. I expect this to take some time to write, so not part of this PR. The docs update will be made in #3877.
Solves #3735.
=> Arbitrary order incident field solver

include/picongpu/particles/collision/binary/RelativisticBinaryCollision.hpp, include/pmacc/kernel/atomic.hpp
backport
- fix performance issue with HIP 4.3+ #3903
- fix using host function in device code #3911
=> backport to backport 0.6.0-rc1

share/picongpu/dockerfiles/ubuntu-2004/Dockerfile
Fixes to be compatible with the latest spack development branch.
=> fix docker recipe

include/pmacc/fields/SimulationFieldHelper.hpp, include/pmacc/fields/tasks/TaskFieldReceiveAndInsert.hpp, include/pmacc/fields/tasks/TaskFieldSend.hpp, include/pmacc/math/complex/Complex.tpp
PMacc should be independent of any PIConGPU types. Fix using PIConGPU
types.
=> fix that PMacc depends on PIConGPU type definitions

CHANGELOG.md
Here is a draft. I started with a [helper script](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/propose_changelog.py), which is really nice. Then regrouped PRs and fixed their titles in the log where necessary. That took surprisingly long (or unsurprisingly for @psychocoderHPC i guess).
One thing i don't particularly like is that a lot of those lines are not actually relative to the old release as suggested. E.g. there was a bug introduced to `dev` after the release and later fixed in `dev`, so together they make no change relative to old release. But now i think it would be practically impossible to separate.
The first message before the changes is a bit drafty, but content-wise reflects what i think. The "thanks to" list is same as `creators` in #3923, same …
=> Add changelog for release 0.6.0
